prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:yKVL32StUwpmHKrndVW6baB4n4OAHnlK5pw2XMBToTQV7SFxbcrj6q0h7zGLkq6d64TGQtM9gVrElvX98NDWu9jQ0/Pl1XiDK4D/VBQ/fnKDkdMIWLqarHOaRj2PKEoyiYF3uzsuZRib9e8C27p4MHw8HG/SItPDlMAltkSgNOgoXNz1fW2NTcADkhodrAAOs0DYs8vvdLCk+qKK,iv:Wlf2Rc1QBbVs5SW4HLrJYqlbVS0HzksUI2ahZv9CyPg=,tag:b9MHdW9lSxnycOQzTbyBQQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:dFvYQX0nD4tu4FpRgMkTX6IZ3PYONvorF+cvCyrLqid8M8dHWzgQkuHLnkcXwA4YwHghhCEPf6hLOhYqG8wE0Q==,iv:YnABTH2NJE51iKCyZQqowf8Gy9w/N6iU1QqclF3igJ8=,tag:wPBa7Sg9teGrdwRITDmKRg==,type:str]
    password: ENC[AES256_GCM,data:Caw5968VirRPZeMYeTccwKKyAxkB83/uvzdTp97XH8yx51RWNGzjHeldc+T96PDF4NpxPqXBGBtrK23fQydp5Q==,iv:KpiIFz6lOFIKcC/ufCDgQb3L3xwc6Cp2q+6yX/cBjY8=,tag:99soYXdwYgRRnb07kkfw3Q==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:xQ==,iv:rKzX2Yc2R0hLoW58oC53vCKKYoy8Qzl92k+/fqsFmYg=,tag:2pJHiao2L48ONLovCswN7A==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:k1I0WBnXgRDolA==,iv:Hz85Gs8XCkAjK848fKIzufcSBiRkSlyhXu/BiN9MIaA=,tag:rIlV2kOvBx8Nc97vXYUpmw==,type:str]
        orgId: ENC[AES256_GCM,data:wQ==,iv:rYZTVOimmiqOw2HMy1oWuxCYAj0fGdS33jxi7D5CpmI=,tag:NugqwxZCTbEkXEfX9Ht0sQ==,type:int]
        type: ENC[AES256_GCM,data:GNzxpvGJyYZtog==,iv:O/66/AtPu5dW5ir8vt2OwiYfz5MxovnZVTLz16LLkfs=,tag:2bj6qZojOLJBYs0APxcwLw==,type:str]
        url: ENC[AES256_GCM,data:Q7wKEngjWRaPbTt5ouZeCIRpF4j+XFWykUFwDNKx2l8=,iv:QXQIC1NzHmyR7d62fuM9jq9bSwQ7S7lvvpw4OAK/ads=,tag:MQ6UKCNMCo67Wtvi47j7fw==,type:str]
        access: ENC[AES256_GCM,data:5dX3Iz0=,iv:9ioDmp9hui143YiAC3C+MRBYTiwLgIbdYrKI61hemFI=,tag:/tYfoXFJCo2Gk6WP3oeUZg==,type:str]
        isDefault: ENC[AES256_GCM,data:OnPj1Yo=,iv:Jy0hlcnaYtyIqQTk1MXVmuxmfmPvNd4yczXzUP+8o1I=,tag:WthqjgYy9KflM+S4svUumw==,type:bool]
        editable: ENC[AES256_GCM,data:vBO2FRk=,iv:czBWrC1oKofHRrKOtyqGEhgUp023ompwT+YFcUiqbKg=,tag:vQmSXorEBMMYtAwIJrp1Lw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:I6fabg==,iv:tnzObtnJkgnVNQJdwMcKY00/vLCYqiIm3eCEI56dHz0=,tag:0pKTiXqOwMRGFyV27Ck6tA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:QlNy224T1udeFDuY3ceIQDK+5FqDaMSxElOHIo0zncbzIl0SQDmhgDBLgO3FD4iQJK4emNFnMG1GRmQ8WBQfXA==,iv:ssx0iHnCYWRRdjvjpmsa7DIc6TGe9B2P03pj9w6C+ME=,tag:khve2kWJkmOtWCyGQGj/sg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:3rCi/ZRcIziwksFkO1z/1WezOWsPRLl2kA5LkTMJBDxSBRViuzywNeFVfWGihW0RtC9dhR2DVs/T/oIzwpAbzQ==,iv:5SEWnXbT+wpUmwgX581XJHsDuwCfXBZVoCJkC5X/5J8=,tag:FPl0pje+89QhuBp51GUZOA==,type:str]
      - name: ENC[AES256_GCM,data:pgb6EN5IA2IIPWFPAScrbsTIz07UzcEkrQIc3AtyDw==,iv:G2lD2+EJqFSpib/oUR7VHMdxAOwDhO1fhxda9EghAXI=,tag:w2GlPme3CBdC+zsIseqLPw==,type:str]
        type: ENC[AES256_GCM,data:BdHbEnGp9HQidF+qU1WtwOP3RfA2ALx4l6+EZKK7qA==,iv:Vo5qYrs6dR7MGfYKgTpgmfTMkXQ/RMASrC9yDO0qp+c=,tag:hnJAYJ3fS88NjccQD9Ujcg==,type:str]
        isDefault: ENC[AES256_GCM,data:4h4fVmc=,iv:dfDI++y0cvml9LMwhBkEApZZjUQEZ1Naww8lpNfezOA=,tag:YMaPvbFHKmQgEL+Fnmzrww==,type:bool]
        editable: ENC[AES256_GCM,data:1Q3VTA==,iv:4TzZfGqGodYxwQ5cGd4A1snqkDTj41g/dUdRTJVdwek=,tag:LeYgT6rVPw5HonAFA/WSbg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:36LbSciIbDBwTvcUPQ==,iv:EN1ZrQoiNAdWYuXtgZ9e9LrZ/lzX7O33gD1KGUWTLhk=,tag:BwPgZCGvMXIkHwkgsDwInQ==,type:str]
      value: ENC[AES256_GCM,data:lD4ZL+fKXpntFsczPV1S6dhenf8nIQ6CCWupXwj8EX7OrAHYkRZxnfT2tI5iw4cMSPaYjcvtT9UlWt6PMazBJ4zC/XRR64USIme24iqxNvSO6wlC5JzKMWDwao026aStErEmxuQ3aJ5f7CgwJtxbwp7MfQ5tOJHGjhEdldzwC2AecyrGnIvaBqZ8CGv2YKlxfIpanHCXgdlo68Hw2l6aDlA5c4lzKPw3brrOKy+NH+p82w==,iv:HBzNU+hDKHBB+4RQXO4NEaCNbJl45wQYjgxSKEYzgdA=,tag:Sx+q7C4adD4vFDyoldno7A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ViTbDoCnFctZ+0gGJNFkpRq/QgcPXJRP0HjPaE7VNPGvElYX+HpojuzOmesN3RmU8gaBaC7wpXkH+RtJGahPgA==,iv:FBOBQ1K35DS8KH/5bWCaR3HS2UTzPuxQS9fo1yR45m0=,tag:o3T8wC1q9Wg2UwZ6/st56w==,type:str]
        password: ENC[AES256_GCM,data:qTi8cqA5K/kLBdNKpKqYLUDNNBLRqr/JE2pHHhsV/vr4C+ilzk63IeWJqp1kzquQU/KZftjI+Bfhd+r3ukatbw==,iv:8uI0YW8snIHgHPTzku+3E5JzuBqV84+VzbAmMA3edFg=,tag:4jNm/yyikbPTaXlt3T7HgA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hptZ5drzQA0LCXw7RMCMSBYt5KCPL1F45fUm72RGew3kDIIvkEJfIDvUGFFaBYe6: ENC[AES256_GCM,data:32+GmLJfhqHht9CGky/KGfJStYYtGJPjHn4D8NVpK6f0CQa03RcNMmg4lW93+IJwb8iTLeiDrt2xNuvL,iv:k5RcgzldNZnhui7sMc5zUnDY7P8nq1kg/ARWhspeKUM=,tag:pT+M/y8su9QIZxcSlBS34g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:18Z'
    enc: CiUA4OM7eLrOFl5vWH6y3k+nEIgXHx8yvu3+8qeV5psnlvF6MRDxEkkAPHlbmf+d8XTAW+nXtUVGork/lsbEHPGN+NAkZNd6Y70A/zZiZDDO6dYc7UDt6uN5DeeSKOsVtzxU2P5MS8Tiwxo1Gzygb/Zn
  lastmodified: '2026-04-17T08:24:19Z'
  mac: ENC[AES256_GCM,data:Son/9XhGNAJzNOdeEHWShIfptemf0C77cZlfUZ+xYcepcJgtSYtuAtzi7c7nh6E/rla2HAv/xAXxULVi+Ng8mtfkxRlZDmX0CPWA3IsM4swOjcxWJdN8iWg2i0whqDBBSRCi8VkNcRVL9QSvvzuV6WkV4cNTbX85cXaXoT50dAs=,iv:ILkbnx3EWMKH5mXpzxhcecnxzEFfsusDU3f1D8xVXqc=,tag:TRScLw1cGpSstRi8cK3D1Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
