prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:XR4q42Yxndmvl8WqlNdPDvfnh2pmxWRgXtZCduZI1kTa9EVZehLCwB88QdwWGk1hx39Bo8+I7bjplZ5UvUW0Qt0UxNms2m3OcTfAU/16nBDLv3ZrD6nXUg1XfyujtgSzbV8pvG4svAmwKQjH17r9DmThLccorZUzJRBAxq7FvRjk5BmlqrPUlwpvQ7VWMw4aHnWT2A6v27CZTpD9,iv:66BxLrRUmcHmx874lBrLHB5+F6fWSLyoJFi0Uzk+huA=,tag:L6Lqo5quZFIpcP/JPhLF6Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:gRBDwKApMkmDkLM/I/uiCbNEdAJjQzJIbpUFXWpHCMEGfvHwpcry6q2+tPYNUhxc3L1LwEAEwO8YIdcYkHkXkA==,iv:16aAIs3xf+BOKtG1G9c5wOyIlN1cPqGgF30qcqOAjb4=,tag:Ntpjy/6ksGD63A/WcamL8Q==,type:str]
    password: ENC[AES256_GCM,data:EWGuZAMLP/FD6C9OcVPgexeLDQ0hBD4LtTDVAwIu2nBax0oNnVExk+kZqg6mnco1swvJaTYHeq4bXVLclzoYFw==,iv:5TsXu67vEenljjIZMxqjl8Au9xOw9zaprEL01byAm8w=,tag:kTFAgAq/zXJKDpZNeG8BtA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:X5Yhzh8gBiU1a5pqDZIw3rsJzsA=,iv:gdyYAiI9aCCS3GQh1UtszLXA0qxjf71xA4HVv5rcOf0=,tag:R8O0nUd4v55SAmMf9Jy9Lg==,type:str]
      client_secret: ENC[AES256_GCM,data:MiR2duRu+n570arbKJZh5+9D/fxEm+JNC99Pu9kUa4eMJtVyF5bNGA==,iv:dEpd6b3+KmRRq/YK1/nqkgAtU/H2BtdiKCFhL3Pmtlw=,tag:W3rpfhVLfA2RQKffEOoNuQ==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:g1OfJlsmL9RKpiwwJg==,iv:9NppvLz3qgaubih6v4drmYRe2/XYutojVy+utGd5FZA=,tag:0vVsVPQYTT4poFauvTWNow==,type:str]
      value: ENC[AES256_GCM,data:9LlcNvegZSDkNgyqOau3enFujpeWd41CeyCxnzu27waycavEBgPnGLhKDMRJnW60I+5LBzLFVb8OyS6N7sg10EGWPaWNXJ/b1QnHvC5QhQJvgijKwFI4qtgRf4EyY6hX1FeBcb/xWBvJSE598whwoI5TJeG+JSe2PHm92oN6eT2+aXwynDEl6Z6m3fnHwDd9qyHKA/1VgmgsNV+3iP8y/87iioNNcqDxqF+Y0D6FCa4XWg==,iv:nqT891h0EPtpi+sCu4UOfJdRsQvfI4D2EJIHdC+UQLY=,tag:5A5HHLQzouqevoqwtaGhtQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:r+A1Wmst8UJdKFkWCQCZdRNp712nHdte5ofYEDQj1GC9XgWh2v6CQnWsbFi6KgoGQEIQjtiQDaTSggEZFH9uSg==,iv:d+GCh2Z+WHV+yWjxC4+YQ7IaPsa/Ryg6NlbhsBNJFio=,tag:CU1gDKrShOmaYvFJ+NVulw==,type:str]
        password: ENC[AES256_GCM,data:v71TXUj0zmplL30SpfM/TwnOjUxj0wNK2Fihw/G2goIRGnG62pbnumZ2YvLq1kAN419OTgWz45AAG2Tw1KXKtw==,iv:7O9c4M8SuSxu8S3bKvwunAoKzwSsvtML7np6clLqjBM=,tag:fWJByRskBxAXMgiFqLdYSw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hptZ5drzQA0LCXw7RMCMSBYt5KCPL1F45fUm72RGew3kDIIvkEJfIDvUGFFaBYe6: ENC[AES256_GCM,data:1kyBMa2YzoQpC1h36LyQiYxuOv30kaOkR8taj7PCe6i4DCdIhBTjQ5VnA9PsIE9jVVHhvXc/3i5UQi7A,iv:UDNpv1HO3MkOJxJ/PUEeeGTgZztHiBI2QTQQq0dg8KI=,tag:ftcaLdxVT0U5uUy64wxyyg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:54Z'
    enc: CiUA4OM7eEdNpcXCknOKhcysSEK/PtxxY3jOtMwDG7ohbf1H25R8EkkAPHlbmTnsgj4R0g5Pu6Ocjqij2uIESRIR9QkZAYWoh+PP8wvktuyqWkNtq1qTNbDeq7wO94Y4P7S/U8TMJE7hJFB02gJ4GY0Z
  lastmodified: '2026-04-16T19:32:54Z'
  mac: ENC[AES256_GCM,data:OQGGKkDCxgJpoRA2ZnTzCRXSzM0HMTHd3n51COXSZKe3pV8qfPBsUW48qi7UlkZpEuIo3ApBunTuSVJRx/7a+rQfkNrD0QpvgOCTRsLn3SE2r5MHVOMzLeR5RBe3R/4hBP7pUe/etBWKPfNGv5Prbye8m+2eEKUS3kYwbYh9SHM=,iv:BwO6j2xQLTuFHP9Z2xGsgySr12BErmUAWxjixbMecZc=,tag:dT1fXRo9/lMHtMqyAa0/5g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
