prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:g5YXqsafvD2rDwr4fBLsD7AKz+04+KyneONklf/mxleSnbCuKzu/uP6t6Crk8yYmCV926ptwVXuTzpq+HEauQTBMyWmmbbCI4RhaL0GDDiBxWazP42gm5BWUObN5Bu4bMnEOWnUBUiBPbdSNEK/vqkgpR9zfjPKlXmtYSzc5OfxCHFnwAKxYWt4Gmts99PZnZRedDiE5xTfkLMRq,iv:uSLQABhcD6WOLaLH/C5KU/a9WGnV9Q5u6n0HwBe+imQ=,tag:o5IkQVy1kJ/RHMl8hzgPBw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:0MtthfVlokjUE9doi9K4z+3gcZ2WQ5NdAkd3ePXApSsfi1sNF3W2NN/jShoJUvTg7TebseQM3iZVuf/bDP6l2g==,iv:YMviHJ/Y1wBKRAuUUylfiGqO+HxBPQp+jnfKrYcLu8Q=,tag:K+jzc8QJiHah6LWOt/dn8Q==,type:str]
    password: ENC[AES256_GCM,data:v2s/KmB9yq3qXTP8/SXxNS/Be2RPI/rJD1gcp3gxt8RcWbJ4zzcZiEJruMgOVsuHui7zAiBSyp2nBU4RDxsOtg==,iv:g0EmoYPfJdjCId5cB4kyStkx3g1skxsS2cE+H0yAxyQ=,tag:AS9HPfHxTHBJBIcJhCdLPw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:EuEZScjOLJq/lazNsw==,iv:aVGBT3Fuc+Qj+l4rkkCQgYLFqor0x8ZnKEi5cyN/pw8=,tag:vjNHafpL6scJrJo5uLequw==,type:str]
      value: ENC[AES256_GCM,data:bOX/25criq7awBSzgujZEQwmHwP/BxqCUh5opS0Dfd8b9Bo/Fj7LsExjn16Ws+Wvok4NWeFvehekRxB+DpqKOztg4oE5EbOXy+fQiXQtamYs1xGmpUaxY4YsJ72wlVXd+y9mHM+/gwiR0fOIgjzPPqfJtjlDYBJFWUm8YSK9EIE6tkgIct3po4w/5aI0A5nxLAqygZlX2P3l6E/LGQRxLf6N12qIRwN0r5BD3/LxBAIJ7A==,iv:l4PI8fHPtbE1X5GNkojwnGVJjpefqsV0TNf5al7iFPU=,tag:KOldFaouDc5R3QmIMdrR2A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:LQDiz3RE3itVkwr/452IetSukIrGLkhcwXb1gwIqi+aIifgW7YWsoZmbwmVwsVsG4BwrwFtJUXVcQtg18nk+YA==,iv:bHklVxgKleXWztu+t/pTcPGq0e8dqxe94qN7qEtqkOY=,tag:8agTlNtnkGgBRCN2w6xssA==,type:str]
        password: ENC[AES256_GCM,data:s/EuKWaK46w2WyRPOdMvJldMj53jSQdeBu4Yo3EwFxe1/k0zcQWlQty3U/rGFBQVadZFglHasva/m1fyaRBBoQ==,iv:qfAcT//sbQpcXeV6rnofBzAyjrCUoWKJFWvd5bPLuxc=,tag:PXtWuXD6WPu6QrlONucjqA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        cD17A7Pe8kfJqUoXTDrD4aGhcplTA8YHEE1YnhBB0ZtUOnJqWPsL8Q4KrqjTHsZB: ENC[AES256_GCM,data:d01wwk52lW1IMOPwf2YRqeKwYAhZp1ZeREb7ZCvKzdplNeGQq09XKXOYHGVxLgjI+sYXuXe4/Wn9DWu3,iv:pQkXF7XFYLOlrjL4ojxk4ty+WyLNsJOqaGv+cgvaIkg=,tag:VHlXlgyA0MlujrtsxeMurw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:fw==,iv:JFsMJycENHkXauLmU7clWsSfp1UT/NaPyLT9ETBRsqU=,tag:bL67uZcpuh/vOHm+o9DckQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:NMJJA7tvsQdZWA==,iv:aql8GcQGJN8UTsehW+kugaeW9RlxzY5/CdCJ2JhbdFA=,tag:lpJBOBfG5r14QF0rL62Yng==,type:str]
        orgId: ENC[AES256_GCM,data:bQ==,iv:6h4QMjvpCyDB2n7i3xWlrYGm87Jp8xztEb/g2ulCjqk=,tag:SNSUQPVAaYgLoyWd5qynRQ==,type:int]
        type: ENC[AES256_GCM,data:5z79YOazAizo4A==,iv:bIMBkztZklrUSJ19p29041f8/BgWctuy7rqOCi7T3YQ=,tag:DQrl43FhdXuME8VaBu6AmQ==,type:str]
        url: ENC[AES256_GCM,data:0WzY6Pa6VSebSiM+EgLL7rZyKwJ01nhWTqLz+tTSqE4=,iv:EuJtEc8oK/yrRk59LjhAM2dZYSkdbeeXEEvwuP0crXo=,tag:pzQd2NkBrAAWf0vQWifXLw==,type:str]
        access: ENC[AES256_GCM,data:1sTgUuo=,iv:Gkui6okqho3R+6t6ZIwcQ/1zD89biJhHQtcCNG1lauk=,tag:tbKQgYh68tsEgoY67Wsrlg==,type:str]
        isDefault: ENC[AES256_GCM,data:kJj0/8w=,iv:6DCLlla8iheCowMhUiK9SLJoM8dUPWNZ0NfkQoVrNY8=,tag:OJwjQLigxzLha3yMjX3WZA==,type:bool]
        editable: ENC[AES256_GCM,data:rqaq/+E=,iv:OB4lZiYroz1R44DyzumaZAkVaG7Ja40FOKZ+c2XBX/g=,tag:kWcRrqFV4kVsaWgeL3+/8w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:6be0vQ==,iv:XZQce1UG0fbffCXH3gROwCvr2GnlzyLeJdiU7TftK9w=,tag:nQciR6C1Ph3dmgeiXt6smg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:XJYUdxVoJtVz7oiDnRlZRYXhQIrwnoFVQSkhPm6nxCccBLOwwoFRXoMbOrJGW1e3AoIe+IugoKdmdkllXza/vw==,iv:OyT2CtyVsfHykDo+O0qdxVEMZ3Psw2UKOeEgg9CJz+4=,tag:odDJ7wqCGC1YgQ7wpS5wkw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:XGVDWS8acQILEA3EbWEvcjmsCa7W16LMkpVAC6IXIuFUK9NKsJTy/y4/CYt0PA1sHSiKIu7z2IfvS0Vl28F1/w==,iv:hxZuDh1InJLuKGwixB+Qf7BsVhC3hHW2mKbxgMWE+Kw=,tag:ac1G1XrK3mNovtWgBlPlNA==,type:str]
      - name: ENC[AES256_GCM,data:LurcubeH/7DhJS5O9ryXGzV2gHvE9ZdCkS/HJoGtfA==,iv:aCaHH8X2FxXXZil5OI/vbpeSKjSfp+fbfSpt8JVxZbA=,tag:k9fzOcrZNY9kWm8SDJccbw==,type:str]
        type: ENC[AES256_GCM,data:dQh5sSATDB3GuSxmKfW5lwyyMHy+m4ncxStUw+Albw==,iv:eAuG49nhz+p8q/ijCtRO0TT22Oxc57laCOG3zVhWKj0=,tag:AUetAZX44K7gvxyGaf/SJA==,type:str]
        isDefault: ENC[AES256_GCM,data:dBQsvnU=,iv:0cBfmbY6XHWTVThWyYrTrmGsBnAPlsVIA0hpIHMIacA=,tag:YUEe08iv60WX9Fdf+eGvtQ==,type:bool]
        editable: ENC[AES256_GCM,data:SpqOTA==,iv:+vC0skWpuVgLWPVEG+ou0+PN/WrcoSanka5IC+y5bK0=,tag:VeFqQt3NFDcxUy88H8uMjg==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:24Z'
    enc: CiUA4OM7eDYWD7JpYPKiX7bbaZ/ia/2tjGo05oWYjzcTALNqv/IfEkkAPHlbmTQ7woJUAFvqX7SoTBeJKGFIVBYPl0LanAROgJg1NMG1z6edgw/xEBy2VrpFMON75ZsbqVlgESJR9iKbIUNZxMeJMm8j
  lastmodified: '2026-04-17T08:25:25Z'
  mac: ENC[AES256_GCM,data:5l/bRDWvYjl5Ttu/IikWE8EK5krDeIsMk/j2daVkFyH0h6GP04jpA8F29fIlrMQSdARc+YAQw1pb3B6JWBOCqfKHEQsqHB7ZOxIBpY84Ls19cIejJaYo4Rd6AVq/W1dCv8/BjB7obMB2RYyQcshzTebRIbs6zonHGeMkZd1jSmg=,iv:5DoOfl/qkT6EIaAdCXnRKgNIKHtxgWaM3y+91FRQu5Q=,tag:0Qu9zXjNAUixNJNYho2dxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
