prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:ryczX9VKB+WMQD4ukRi/MAf6h/NVVyItc+ytXs/AsOXMWEPnPKvsfngDCpq3koASOH/Lq2I5IQninMvGO9aeZ0orA/LOowL9wcmw1WRTZGNK+tIgmr+cvYzbgkzosW2CxZ2Q8wsKgY/cFEUBrioo6bVHIEEmdsqccXasV3AWg0zSeuWQmiJMnxPiw8vbPgMpeeZHEV/30xR35r1I,iv:hWW8qSar0EHWquXgqhEZ4qy7QKF8wInGsWcs6jAUvWw=,tag:WM/tX5efvE6c7wPY+hL1pA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:EAmJTlFSOOhgMG+s3Gv1lGxufT99LtYcm4JjDJuIx0nu+DGzad93hHiMyWey+BRtbV6jf1v/G/tKLWKgAf47eg==,iv:4jAs5U0VXnVyt9OXZ+Vbl3PhjD/MwYZAQr7OUPX3sG8=,tag:rR7n34u52d3I9wKAwrwj7g==,type:str]
    password: ENC[AES256_GCM,data:xUzBoVOS31/nqZjg9rUaBoe09LQbxvXbx+3uft8BVfVBBZzrGL8fVGMG//KyS4DT1ze9viS/DWt+JzC1d8SiHA==,iv:9PQRDGlmBnS192Go8BRoZRx8GxkEQUTqqZDizHeGOwM=,tag:Pj0dfqnsWp4kMdFKAbcljg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:6jerRc7x8iV1PZutwQ==,iv:fh/iCA0CeAsTHPBRrRD3uekuMRt2GhRl6F6AQjFU0GY=,tag:kquJLqsrlyM92mwMH1HsWw==,type:str]
      value: ENC[AES256_GCM,data:zOLf6VR32VqJ67of5MBTUsstorVwDenmxxLJk2gLVqGfC2n56tmLvd9QH5pWMYWNedqbVmZcf/dngAKb51LtT/VyuFK0FkBt6wa1XZ99kCcRWEY9bbrEpC2HmfGA2IiorssYB2QYxvJ1n3+QAORxDZDCejersGscPz7sJcfc8WYkAX9xJDWz1OJmZPCX4iNxgbLPCMFK51JKg/IAOOqmRl4oGsmYa1CJpA4Wr8wZiijRHQ==,iv:qlqvSEa8+QvvbBGlIbm/PzV1Nq6xWl34vdxIQvDneN4=,tag:iRjfO6E5i++XayHcZQ8swA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:lIH5rNQepsaa5yvZo5QZ3K4qCQz0hnJ7M4p8IHspwsosJ++5SbOMiU87lTi0Ff1vo8eCwiMAmaxRl1ZQJvlnxQ==,iv:djz7BBEGsBbT/we6kg9pj6lA6Nb8GLDFIQ/J+PzJBEw=,tag:UYUBMBMSANw6t8Rh+ksCUA==,type:str]
        password: ENC[AES256_GCM,data:9fwiMaPBQP+R5Kws4fz8gMFGi3fwWJS1hYF/FYH4Rn9qs2Qt8nM7dStiWvG6KUl0gTORDtSU62xVbrR+J/NMtA==,iv:qzt+K0WYU+gUtUFx9Q7S2hqY4AaCFAdvCqh/ltGTWzM=,tag:214++HOFaJUiWb2LjDdoOw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        cD17A7Pe8kfJqUoXTDrD4aGhcplTA8YHEE1YnhBB0ZtUOnJqWPsL8Q4KrqjTHsZB: ENC[AES256_GCM,data:O/wh5zm7Z7Uf5PTs40zXxrIxHF8WsGXI7ay6iqKvlVSJ/LmzspHVFwx+IMXn4RYragBZs0bYTaI+BYK8,iv:voTHstrKg7qMgeJbZcIMI4tLZHZnQhZQLhGleZ/qRW0=,tag:yUyk/SRvaZz7RJ9tICcDQw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T06:50:53Z'
    enc: CiUA4OM7eNmBYnjq7gtfsuctVDF6IPGrOkJOYiaXHF5c2C8Nvk0YEkkAPHlbmX0loJ7HA8mwK4LF/nkTDftKMVdD3pp+dqudnQOm9acf4Pc3dme68elbVVREAdOp9lj+EXfzt/1LM64addYXExWgS6VT
  lastmodified: '2026-04-17T06:50:54Z'
  mac: ENC[AES256_GCM,data:c1Qip84/U7bAyFU5llbGCCLSwWEvmGEwYDCnASAyjskdD/diZ+ZHNDxLRXXEC8pKrC0EI4VIopYTQT5z/6O6tSJjDtO8+pfD9FqRsKODdcXuh4KCRp/oDI2i0mK9Xt3xs3oP2v2Jnr8J7FnewMZMvSPQ3KjEb+1/VpiSEQil5o8=,iv:gH10wBqT490ltTeNcPXgBgidDmyHL0WXri10ISMRsJI=,tag:EwLsaNVukCXl2+TaOXHsRw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
