prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:pp7Skvl8bZSKgBdKzVLNTAi9st935FEIK86kH1izrmvwcrnswFw2SeUoQhiML9ZcCfwGjIC6OhWEHdTEH5NK6vOSIKG6saODI862Ix4n/ayg2EdCnxCBLmz0zzVauK32GhVrH58omxSLj9+SNNxusFG2hJ4Z9kzvDRmlBkVen1H2GoxrYLny1ExGK7q3qZx8y6vosMCYXS1bqEgY,iv:jkSFgZz1/5LGqiX4ZCWywYKWUog/fuibvJ9xUZhyAR4=,tag:qyzUtJ7K1ZUG20ouyX+miA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:70i6oP+auQ1J0rAf9e+G6BJp1mq5vTfKJnqnJQelIeeGRNsBTDfSZGKZD3beTK2+qjKC9q5a48uo49VCy1XFFg==,iv:dUwm08VemMSWBKK9zSwpWP/bB5oiy76VAUlAGfH/EPY=,tag:tqZYThB5oHZ27P8/VlE84w==,type:str]
    password: ENC[AES256_GCM,data:qKPlLWspNB0JJGEpGBwnv8kVKha7ieE7qom0wtp0MRSQtZ7PMIiEbLGKKvZj9Gwc6aLk7D1HnlQyTKmHnycLag==,iv:B2RtHPzSk0zYUsZ+p3n/0+Xvti6eQNt+DTGm+EBE01I=,tag:dvsJSA5/WzvXO73oXY64+A==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:ZpRQ+oVEiDB+uFKtng==,iv:uQu54IXwJiMXnjYI0rtjzR5IJgMRFYHzFBozawHe0wg=,tag:zarkIFvP9OpF0KY1+bGr4Q==,type:str]
      value: ENC[AES256_GCM,data:YPc1HywzW5WLBoKnkynLHH1HPCJ4heIvGshwC0jnShwmehq8lMejCRQ+CaewSItgVDS3Rl6nToXy9lyiAuInvoLyv1yxeT5fVv3H79XslmvwXQSKJraJfR3kMQ8qHPBV32zFQKy9Y+ep12WwBUfHBG+V16w1PE+lKuSVYMpg82zwrsFlVMltKOjd875AZxh2I1gYbtroD7Bmkh+ea/I3IYyGDPivZMtQwp9xmhO0LFIJQQ==,iv:munYEOkF6h7nJecP/6jXk1GEWFAnmHSMW9ehE7hFxdY=,tag:MYbXNp+Q0iHi1cGAuAUFJw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:PoL2SaBNODfnD+U/bkYdGTfvFrrMFFH21ZuMKyY60FDB1a1WKkBz9hyQI4ZOEUzxZviABY8EvxnWxLaEIuvPdQ==,iv:+NyNpXpPOoxkupzC6CJdvErpOI+NkTXYqeNHJsTVJes=,tag:WRi+rCS9/2P5jdXsSgoDkA==,type:str]
        password: ENC[AES256_GCM,data:+OGxQ5FFUeLt9zFrbRpPr5XhwfeAZI6d9GunaTlf4mo8YAjPDuAE6jjMJD5u627d8rq+0Au+PbWqbQWZRttCPg==,iv:rQC2w/ktiT4wwFOFbJrVtffLDW+5Lzj1FIfDFFFbxzY=,tag:6xBd7pb/cBlDa90qgiQOUw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        LHaB791vqQdCtiBB6jwx0KB4LA5zgeryfRV6ZEgqwEk3Kz7tv0aMjobp3G9ZYY2S: ENC[AES256_GCM,data:PczHBb6YeCb4U7DZH1lAvTDqZ+qJ9XfDoucMHdSIYnFZu8Z/gcdHxYQJ6Q+wqwqkFvRG3bm+E9jZeZcJ,iv:uel6otoFSQ8fFME35qEcYxXClCH/S2//9FX2mbL74LU=,tag:41P7eynnBRiWU+zkhUIsOw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:lw==,iv:9zUoaXFz/LHsToAwq1qzGdmn6In0VV2iXsSsLZXhFWw=,tag:D1wbC+x6ZNwyaXZ+oxuh/Q==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:WuEAZMIDzBsMxg==,iv:z84hRcOy7fjSSTYER7fnn+2jPBL1RtQ1SK6Azxh6xbY=,tag:HgI3t8lNoPmGDSAtOlIhcA==,type:str]
        orgId: ENC[AES256_GCM,data:Cg==,iv:hIeHDt5Bgf9+IPgdMgVIv/oZDXls6mCwgP5l1mIFM1M=,tag:ZDYm3TjDJB/9q+MefDzoag==,type:int]
        type: ENC[AES256_GCM,data:PQBOnKoNMFuC3w==,iv:kmwhJRq+tZ9Ug9YGmf1RDre8A0xBAr14ip8oupFVGvQ=,tag:JegASopkTM/8FpZ7YM944Q==,type:str]
        url: ENC[AES256_GCM,data:sRd1swnwJsVYVynWMOJJZDaf7Q5gHYqow+V2EJZ1GF0=,iv:/nntR8FSvo/Dsq0nJB3F9S8ptDdqyB8CqdkdT2Rn4aU=,tag:SqVWR1lZZQ5c9rFXqZOInQ==,type:str]
        access: ENC[AES256_GCM,data:4o8Q0OE=,iv:LsaS8dv2NdAyrb15+7VaKPKupLLrI85Ku/5xgSV4WSk=,tag:HywoJotwunm3eV5NfVn7ng==,type:str]
        isDefault: ENC[AES256_GCM,data:uY/pAHg=,iv:vfNhHPIMf5LwZbgS7F2PoV2Ww3umU7wME5/CqDzcEXk=,tag:jY2Rv1jLYlOyeuz1rlsohA==,type:bool]
        editable: ENC[AES256_GCM,data:iiJMJqk=,iv:b7ombeVzEr+dGFyXfnsv5ZlX7Y8oQRJVLtTDmCdKtJA=,tag:zMBFyJjqu8h+a3rzRPtsrg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:jmXIuw==,iv:NwsVJBMZIuuIDgU5Ffl2Q3hMLTuoEKcHbIymXZHh/60=,tag:yWfiwbxDKElzkwPEdLiZsQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:oHyWdT/Mfg7FD5yjf8qamKSpt8heF5Wq8kvaed/OL1Jc5BBXHdcuzLBOrmG2G/SkhQSJceJ9TpXTgiygyrT4Gg==,iv:WbqL8K/MqyZ7lRKBjQdOymIxS2fl5cEbL51VsKN0Pmg=,tag:KW00D/kXB/gLp8XDHDLEVw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:09S1Ngzjz8c4qZc22y+U0Bt8OwbCrvOMKZRsHub4y/vDqExLo5dxVFNl83FU0WXx6LdP+6BEUF8qI4F4DTotAA==,iv:k57eogw+aWitVc7PWGcu3d0MW7YZu3zKEJxAF1wup6E=,tag:VFfpp6L2fsdFJ7CxI45QAw==,type:str]
      - name: ENC[AES256_GCM,data:sNU2z8qfe20xDEZ/SFQYcUVwuydS3DnSMigkpB/jbw==,iv:RpRI4bxKXgmSojrAl//NOfDuQwbobwbtEKcuyZ6ShVg=,tag:KLfQ65vpQ2dMBC3ydosppQ==,type:str]
        type: ENC[AES256_GCM,data:kB3x22e4Ho8wREoXri/OwdbWQ4Pid3NNbLCEG07Mwg==,iv:1IeMcM0s2ZkAE/ZxZkK8dVWroHO/CZGoIeqck0h+s1I=,tag:R6elrl8t0JYE+VL2jxZhzQ==,type:str]
        isDefault: ENC[AES256_GCM,data:h7t9utU=,iv:EBxD8is+REMsUveCzNVzZOnK/K4ood80aLNATa+rA1Q=,tag:EHaLXD3X1wsAE9McoMHxnA==,type:bool]
        editable: ENC[AES256_GCM,data:K+7VmQ==,iv:3Ots3GrSk25JN+9Rjv0dA4i0BB5BQBMGub99KjrvOLc=,tag:qHiz6t9OkEmrUpvP/E5bLA==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:05Z'
    enc: CiUA4OM7eIg8//nJNZJ7UjQ9JgUoiC0K6YR8n/F4XUgl8RpGUvZpEkkAPHlbmWmJC7xyyn9TAxlavYUt8nGYR/4jIyMJTo3bo7ud0B+89UFUA/LMI6eLk9WZU5s4RXN7vrbmu7oyEFBLeSeIRlj+Xm2L
  lastmodified: '2026-04-17T08:25:06Z'
  mac: ENC[AES256_GCM,data:ORvP6GYRK/AsdMOl2RhHhjy+kJgJpyFMPJhBl/T3ShiimydOpp9REpZRNc/O6fXHZQDGRXfPkjoJq8atvebI2K/uWUi9CrkwDT57MM3gFGwOX7ME4JzzuwrV+GBddqXRPfx0q7AKh0SrNyOcHXnmy7/LgePOdz+fvJfOgixPdWc=,iv:KrEma0YHqpVGkd/LEwWSsDPyyOgUO7fKAjO692YxHOI=,tag:WtpJAwWNLeLadrKtLEKPfA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
