prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:CeaHNK8INNKgfqJbRspcGl33nTqm+VCtCzWOmFsmg1SqCRKlOMsh5IxFGf1J6N9efy0Jplay1txp83Hv/IOZoE8TR9A5MI1N8o0iCr9SxqjUhPfnC86lwf81HZEoqdanO85Dwte7eJzctoxz+hbqYCCbR8Cdkc1UPej6etdXvO0xapCe9Mg3FH0xATTYvxUlItSB9fiJei7A3A8X,iv:FTHSfT6Be+4rFjpRWYxH3PEpw9IfWn2yKqcefK/iVQY=,tag:QffYcTA3dIlKyRD+adtb+g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:rzDq7NyoMdUuEYurR903+6AtzybPInUBtY1F6gl8wIPn7f20sPK9LF9vBe0o2zHR9kLe1VGv4PwU4pTtZf+ApA==,iv:RiJF3v64jnVTLU8gWypw9vn10s0g7IfKWvmkB6pIwZU=,tag:hlHI6ruO4N4JUyoZQ592yw==,type:str]
    password: ENC[AES256_GCM,data:MegBe+t6+aWXDvYoMSGMF0KNqq9C4P4MLlsw96gQfKYa9WTJTZdo7rGmWh3XRm+luC2jOE0eXlSdJDKZtqtSJA==,iv:Fj51rF36CWzsWlwHNRojKwqLgtx/W0sBVLF6R4kKIig=,tag:MWGXDT7hOUZps1SsIdg5lg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:blb3q8RrzWYrDAw6eg==,iv:O9zmoT7kuRzHhMLdUTJ9jnrqn3PsRtncgSdZg/sjKgE=,tag:tuCM1nXi9FqtOjgqW0lftQ==,type:str]
      value: ENC[AES256_GCM,data:+IskkdFaWUY8MZgVMSF0uV9GKeEYouu5qFIXc6mrYu1MwDbFXL5dLpeP0n3T1OZ2Fg9rOvREa4jxJCRHuSoFbz/57PUlJAIZ9WEgpG5mGDUEAkSrE9kF/b44kO/YFYe6y+dv6frsTsT+bMfoEFDrD2gtlbE8haQNizdk3Rk0P7Bdf1LPbTLqHFTIgDEPnYPGfo3PV4qb2dG7BGQTMhXj1Fzow+7UjF1eAD8y/AqF6mnCuA==,iv:B3BFngWICACir22qEGjUA2/T0ypnF28ugmEZBU+OpSA=,tag:GwxZbQ19de+R9rclXI8pNQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:OwirExKq3YfqDQ+JKOUFJWkmqB4ETLLBbrEvlsHLPNO4ecXFq89D3wj1Dp7Opqu4b9xmnz25hO40brbxTHVWZg==,iv:OrFFbyQIDW7QEAu079MjorZNcBNS9T6YfVMOz4+IaAA=,tag:rddfZ5jkYcdmd57KCos0Rw==,type:str]
        password: ENC[AES256_GCM,data:17wesxyDe4kFgSmLrYBpZGS2Cj6KBNgqoqNYWpDqaXpBV/huR4PA+oTTGGmlU/UlPNoSLBEdZEUmlUiphRQsbw==,iv:fWvHIuY2u+gXFnl/x4sYGTkdqeOQFYvsCvJZRRSaCis=,tag:ANtLn6idACwaUiWBgcFclQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        LHaB791vqQdCtiBB6jwx0KB4LA5zgeryfRV6ZEgqwEk3Kz7tv0aMjobp3G9ZYY2S: ENC[AES256_GCM,data:nL3fTeXzL4RTK6kMaqLbSNLOZGrJVG6nFtAABPNcuPFVpCxh5Qy5W6ST1GfH0+ha/lkT4h7p4aWNx/GT,iv:n/MCSYf8zyLwia9hokkpYOnq9tojDe7e7p261Cb9v+c=,tag:mEFd6kALEDJSVjeY33IGJA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:42Z'
    enc: CiUA4OM7eIVu6eJR0kYnyPmulSu8W73dwyKeWpK7yt2bX663F90PEkkAPHlbmSfCu/0uso1ImicR8UPn9N1vKEFTOspov1UD4hexD69e2koYGUgZzqQrSx0HdjLWGRo8QGmIWbvfTyifYA6AzOAhbDmP
  lastmodified: '2026-04-16T19:33:42Z'
  mac: ENC[AES256_GCM,data:l9Gfh0vLF61ED9Ve230ETKHWNKnh9koE2be2PSculvPGg9QlKJuVO689L1x4zwlBveQOfBowEBf3X9/o+2vvNWm0AOQ+DWu+o3QUJiShZr17QnzxfbPTHFTHFvs+A4eJn1j2pd4cvCxCMHIzxYzd8S64E22IS800yMUEoRdGVoA=,iv:lFxC2N2G7m8dt6fxg9JMwCPQipGdcwrVCOsgEXVdMBE=,tag:awqsTh0FkcmfarLdNM2eJg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
