prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:uIXJtRMvTyd+hsIKgA4O29O/ZtAbbkAd4vs++PcQXngtez6bhij02Pk+HbzE1YQp0SXzDSFuMJwZaLlW4JQOvN5v7mDE0JikvL0e62R0w8pq8w1+shIRjE2Rof/O8vT+t4+dCUl3DAgq8+Ox8nEHoyhadcJhfdOJr0vmSF8k2zmTHMJZYnghvc6b9mq3EUDGeDV3AkEvYua0a2jM,iv:4/0uuDHwGMh+gTImMtIAJ39NxLCjaerBhvjn3KUv/uQ=,tag:MByL5oWdNytDM62swfGPwQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:V3k29SqfbHzcbuSVjnlD/+kmXBNTkrx08pehSTSEjwV6ghpe8K/ndeqRtegzSPLnBYBy4wbQMaG3zxbTm3M+JQ==,iv:7y+FBeqERLbWQND+TNbwOfZyitGOjKerk/VUUXFNxWU=,tag:iDHiKmJVg/rnBB5Aq3pf0A==,type:str]
    password: ENC[AES256_GCM,data:AsCZRuJnzVBiOjGeSgvTUqQW73uzfX7o0M/uM9IWmMXswtBL75hkR7puRS1PpdFhH3n0VM/17wgwHzpkEJ9Btw==,iv:5eaP8zwJ2wOkdxGiNa2sdHnS037w12d/i0uENPKTVAI=,tag:kfl6prloxB9m/PCyjoxeDw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:xP2FSDxWGCZXLqRpvA==,iv:H2LjTizHfNh9JxG8L8skg97Ds0/Wp9EF1So7NWmMW5Y=,tag:MUWenq5aJpENL6/QQKPKXQ==,type:str]
      value: ENC[AES256_GCM,data:EqcZ17G8VEE9fJO2KlE4PmsbVOeOflBSbpFL9ogE1NPgbEQFnor3YCBhKwatyK3XU2vEgdOekN9yA/FGe+PeYS45Im35q1JRElnM0S1YsA0oP7DebhGyxFB5jcN/Ly8C9nI6ghJJfnMO0aNdZl88MjNhsyWlNPDPwuUnUtSwqnEto3QFRL3dYXepNQO9n7VXkCmlHTskAez4eKO0PI7mwwMVT/mCNGe8Ws6uq2Hm51Bcdw==,iv:K8E8YtfNR12ZiCTKPtgEhIEeQGCZFcBebLl09R/p1gA=,tag:LtKP61O1bCrXErOTy8tvig==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:g4aqH3C02u2ODEAjoESAOG+RVeB74Wd4kILWPV/X1B4hoHasXzvUVZ17S0NRERmweOPd7/1/Sc29b+EedwwnTg==,iv:48Mx0rr2Z8byax7du9F9oprvMKXuDyScSBEs5jS/uYU=,tag:gelTr56WS0b4DqdPRyX/4A==,type:str]
        password: ENC[AES256_GCM,data:0YxLzPf9jppwsaiJMKqDzlAeCl9iqUvdP0JAU/42Fu5XF41G9c0f91kRhq7oFGuyNYZQwJAVMiD+YM+xqSpaLw==,iv:crYAb8yhNqBwFlAv0YKIs5+0ZOvU8cFm2UONijQDHHk=,tag:6OX14FrV1V5f3JAkDSqBpw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        haZKNVqTzKp0rZcfR2U65WeIWc9dJWmWkN1R4EyH1B6wzJTSG830chWOsFQdmgwZ: ENC[AES256_GCM,data:v+HIy6pDD6bl/a6dbpVZmHNTqT5xhQr+jlsbEEWCI/uSW8plUR5ygTbJvGocmZuMltBd6pteG5QBi7cK,iv:bngE66PRrVhYj7kSxOSyHW/yWQSd8rMWzzRShHVvDOg=,tag:QKbBOqfn8xya2zl5lRXEJg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:ZQ==,iv:LB9U31eqJTwaoJb5FzNHROBDzXw6XvJdLzkK9PUmTmI=,tag:9VOMNcVfut5BNj11b9fuHg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:GmcoZeYUvIcSjw==,iv:mx/BgwgFPG+SlEqUZrzrfTrqVyOHaNLQCWmB07QuL8A=,tag:g2cHAFqtC9G6gg8oFzlI8w==,type:str]
        orgId: ENC[AES256_GCM,data:JQ==,iv:5GN5TRxfMBm/WzHnYWASyNlwJf7yR0BFsflTiZP3rxE=,tag:SnmF+PjsCK181uP3te4Mvg==,type:int]
        type: ENC[AES256_GCM,data:P0b5PnsheBt7mg==,iv:smP9pJXNUJy+tLrE+6WqWVsz0dYsDl0cvevneL8sJK0=,tag:lJkE7iwIuhXlOxd6vRf59g==,type:str]
        url: ENC[AES256_GCM,data:npR7UWbghcZhyIdK/99YdCYIY7chJHqgplscs3icVr8=,iv:3h+G90CUlTFIeC+nyrK9cXonOBAWGg5ecVtHcKju8Nk=,tag:RE5sAfo0WLrlySgj/nX1+g==,type:str]
        access: ENC[AES256_GCM,data:qhFaCPs=,iv:ZVi0FNZER6mD2Knj2ocyPZRJEoQmvjs4D4BijQ9U2KY=,tag:e6b8lI/oW7bjwfhZ/2pK9A==,type:str]
        isDefault: ENC[AES256_GCM,data:6IyObnE=,iv:sdWD2Oe7lLnuTDTa9m0PoKxd7rG2xkiYg5DIxBamYck=,tag:b6xtLB7Km1GT6E6zDdqtfA==,type:bool]
        editable: ENC[AES256_GCM,data:x2IhGyY=,iv:uamobuSAQnhdjDjJUFibaehM8h3a1KWgW7CbTmO5sPs=,tag:Ac4TfD8f/Yhdl0+kctCQAQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:EOTl6g==,iv:GhPXqluP37+uqCl+7L4v2dFA184hx2UyS3c9HJRyLJ4=,tag:6r8GE6t39ZGfvlo4fi21+g==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:os5yPSgWmPwRwrxlyPPxmgBXulrNtjD5rbHTMlU5+UeAecu7IVwtK2iybNJBBUZgMbLH1ZfgdefXnMIT5cqBKQ==,iv:r5ANS4gVCymeV5QtNmIdopjp1jJ5EkVuT31Ma1hciNw=,tag:oXfC3IolTs8HdYzOvo9Bsg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Hu4f9aP9D0GUeF9AUpvvgS+9cCeEnjHifgYytY+kFBBbVqMWG1/fzvLiL1B8eTZbMAgU6unmBcb1lg6192SnqA==,iv:4P0idNMRGeKlMSVG2dIneEwgYU2kKqInNCJZEJ3qtp8=,tag:q3BBWIaUsu46Ht5P43pI5g==,type:str]
      - name: ENC[AES256_GCM,data:GbmLZYBP1hVUEOT6RzyoOsozWwpM+iqoycChb561BQ==,iv:i+Wrr0SETNgg03o1BkiXB47L9r3WdgbOkg2FRUgWkY8=,tag:jSuJLnu1VxMZG0nP6Xm8xQ==,type:str]
        type: ENC[AES256_GCM,data:v6i9H6lW+rwHmUxt4DFcDtaERd8ezHtKIWUl25w40Q==,iv:t5fHAdbY8eHlDSNi7B/mIvYDe1bdEhcU2HRjw8hi8vM=,tag:gElpXk9e4QnUQh/P/LU+6g==,type:str]
        isDefault: ENC[AES256_GCM,data:OBBteGY=,iv:nd9VOpwO1jkzLe3DaAVLoOR5NHUuu5YALvO+cgzI/wY=,tag:lw/aUQf1gLNwO03KbVdK6A==,type:bool]
        editable: ENC[AES256_GCM,data:Rs31KA==,iv:LdnvwGKYjaK7kQ0g7qLbbMOgt4oV+Zw7U8jTVQUEHvE=,tag:DTMonwhq/lBLGmjbIf5I8A==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:15Z'
    enc: CiUA4OM7eAjfi/n13+N4q6g4XHHinX5jDUyPOlrdzHxxoukroPmGEkkAPHlbmYU/vHOGWunA3Io903OObr01JGwpAlLBwuLkXWt+dAQ95mFtPnm8P9MJJEoqitXTwhDDVShpUy2bvG/bGk4O/aCFm56K
  lastmodified: '2026-04-17T08:25:15Z'
  mac: ENC[AES256_GCM,data:V9buWouS10nkWHAl//n9VA/qDkuY9RFOspwwqezK8wvMGdSDPRm/vW38QUIIIp3R3yQb31+DS72Thb3luLf7AbWaInhsL/TBO2/9hEDaeW86bq5ptkW7YCNlrkRFb/uemeCiA7AaiDdWETG4wxETQqPZCzxut01a84S5euEAiOw=,iv:DxbKre5W/yXIPWhTG0japMIbBzmgrHUlfXL8p2BFZgQ=,tag:svVg/KWfQq0EVHgE2pNPYA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
