prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:o1KcKEYx0plinyL0Osh35bokcJRg28VrfarnH1bX5lVRSJ2gGsBDHiD1mgkxYbXPZW6BY7+gTsTC98+u0uoutXIpPU/dIf+iEGOU0lk/YsJZPxB6d3DEIcrtP3ASllLFurMRfBIMB0ZCjL2rjMWE1wIrGJzivz7rrgM3LdZci/FPntxVG1n/x5gAGETZDazMPNnE4r8r6rALm0Xk,iv:ncKVyueCb+G+ImfmppxlQw5nE5IpU7l7JyUk9lxHaLw=,tag:isQuMdokL46ZUr/h55IiWw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Di/XUMnacjRdZhzRih5pWIxrsdwSM2UWgGeFwzotatr0g43zkyCOyPXhK6WWBFhOCXxP4Vrv9Sd7zVf5g+bBrQ==,iv:Gi2B4pi2QxagCICBNc06oqIvcoj8R+7Uqu8dQ8c10cU=,tag:8UzOvo3lAptpolw7RZBwwA==,type:str]
    password: ENC[AES256_GCM,data:u77OQpkArOFpArBL59j1u+JKpS2OPdIBO4NeP8mdlaALKz394xO3OEMScOualACEf+9Lw6vRE/t0dZrNjiLcsw==,iv:5/Aq32ECYzGq5Q+/g7qKnnNqqYTxAYb/DYROZeh3la0=,tag:rEc6uRnfubpw98fmzUrjmA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:1I5ecmc06+ogow34PA==,iv:y9NsnlzyOAyP6w5qp53i+cAvXQ+r865+I7pOFwpgQ/A=,tag:i4OYSvH2ZtgHDEKjxBBeMw==,type:str]
      value: ENC[AES256_GCM,data:mEca+oRhjN15Ljff7x9EvzPaZJmrCzVl1C7LaOjzR9oG1MikljZ/TP4aW81vhFNWi3+t0BhjWtiT9786C+Bxr0Wm4VojvBdC5ZAuGTxYxrQN9JYpP+A4nQ84ysHCeb6tj6z5FHLcYAFgCgryXfx4cg+ikC9RYjQ2qUO2LiSIpq/v13P79QTAY/Unct65UWLDSRDxztAaWgpFNVczukNI6m2YSf1D7Mqx0ZE/xGPsB6mqpQ==,iv:qOYWUCJN5mumgkw50fm7yH6vDjXPuwRckMuQ1HhdmYY=,tag:k2HWNBvjRFTIQoScRGTeVg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:t9Cxp9ZlF/aFLBD6puObY/VTESTVnIp53Cbjt9HrelxwWt/liExZ0JSdn19uIV75mZhajItq882J7WKGjXxOrg==,iv:Ob1BWE0fz/AMZdx3kCU+r4CaOC2P0BPUwTGPDhpGNjE=,tag:CXNmbqccnGBFqBqVPWDmiA==,type:str]
        password: ENC[AES256_GCM,data:k8nK5KmPOPtfkSpQNxYlYm9uVD++kgTxtBTGUl5LMCm9yKt7tRKixmT1i/zHoViImMajGMVR3i3AtiQbAJCBUQ==,iv:K3pxIOtUTULIhsKVP8w6m6Xrol4Fk7S0jPCPaI89OwY=,tag:S1d4iO2BX3K1shZv3Rs04A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        haZKNVqTzKp0rZcfR2U65WeIWc9dJWmWkN1R4EyH1B6wzJTSG830chWOsFQdmgwZ: ENC[AES256_GCM,data:k2N6lgV0gNFKlIDPf1e54DDy9KPGcRsy7floPqcpmZ1cma5O5FZGBu2qOHTat9Lwk/ZTmE3UkKpsxbe6,iv:QC04nxxZlNhEdEg+hzxZWIolIlIQZs+NgvVw81XtRCA=,tag:yz2302ZfBNFOrUvTphim4g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:51Z'
    enc: CiUA4OM7eK5Htp6Ntw7QO8kL11idtZIJwjpUDdNfjYJLomSfd5rGEkkAPHlbmYi6+OTFDTyS3gkbmOGrpqh/7yNcfPksK/vu+8gESw3/eQjjpl6iBTX3Yx0Z8c8lxNPsyuLbjmrSCpkYhhUoXE7iBn1N
  lastmodified: '2026-04-16T19:33:52Z'
  mac: ENC[AES256_GCM,data:RAAujOAATfSV2znOQJiWPOkr02YSZfQ6jwvDVOk/awytLf4eTzcFpDMuCgtIq7TLE4aX1N73UMoNgQloevqGZL10CN7DOBQlNq68aI423xM8tq4SMU+Wc581xGRRLuBBEYC6RnBAw4ibKqvXKfyyIqO1VaA0Z57ax1GpzZakfOQ=,iv:/lc8ZRF8Duw8pHIZ9fndICMgrkc2jtMtUmBX+Bkvv5I=,tag:mFvF73KuTQGXwe8ZisiH6Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
