prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:yoBKgjW+Ev/OoqZdqnVHQvfI41cs+qxvNTAApullxtKs4JwDf8ohhz/tE2Tn7OWGq2yIJa0mSdqqLXYd8VacxK2oKA/zthb6lR1ITJgm/ZAWKM5ac4v9aLh/EBSG3DFJLal6v8hfTn//z5QqjQjrN1FzgT3n7jJHMzYy0Fvu90sRhZRN4fEEL9MRvx+dS1nErFls3kVhyh+lSiHe,iv:v6eLx+fJ4ED9c3FMm20elI3Dx96tSF2QELqCXd9YOeQ=,tag:XG+8AL84CIJE5V00q5ajNw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:zQS+6dfAoZb1WC2WUdzKrdWojJ91Hf76RffzPuIMnshklWAA16BOKfKXKoUPshrQcI6NhQieJgRCs6mi9BJ3kA==,iv:W339mB0J2KLAU0jN6jYoVmW+5YOXwVG50zJTk6na/cs=,tag:Bf58CRb4wsg05Q4rS6k2Ow==,type:str]
    password: ENC[AES256_GCM,data:FRncFpNVJPTxTJViowbA7XIrcQYe4Rc20PSRWLFba2BzQQqqlLPrvPgjYVvcB3r0ee9rq2P+mCxpSdllrRK3MA==,iv:Xgg3pyuZh9D8KrdQ+79J2F8yBq5OK9ynEcHvus0hfCk=,tag:X8bRgmq14D1tsT56LIQ9bw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:lk7l1SEPI8pIiyt5v5dLYmymUU8=,iv:TvYGllsySbfPU7fqaKSCOf/JlQRxwpvSVOrkH8rrVOk=,tag:Oo/g3q5VtNIcZmflVUPK4g==,type:str]
      client_secret: ENC[AES256_GCM,data:LUM0GoeT0jI5h9gwhA3fi48/DXm7+Slb0yMGvaMFFlTMbS9UvHQ/Ng==,iv:pYbouoZzxD7DOxXd/ZnLUTUD+MrPaqSnidScY1cTogs=,tag:LBfY9FuYsugSQ064qhkvWA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:FyC8secRwo2fHi1Duw==,iv:V030grvWwOEEuCr7ReuDFQ+EzjmVYf/K1d48I6DOVwg=,tag:GSkGI7k+em2SLx/AsmYfzg==,type:str]
      value: ENC[AES256_GCM,data:EW8FRdHqEnF+XKXLAIJl1jKTL4si6LVZD4u+tRHBKkeCRgdqn0DJotQhywZFlEKM7z3N1Do5Nsv6PSE8smN3fnHUUrcfQjcmUaSpCwqqFLVIlSmx3lpBP18cL2fe6yZmbWlnG3966bK5ClT4knR69BsQC3GLaIEqFaMBnQDa5Zy3+G+K3pZSWvJzEjBylh6jtU+8PJ1ABTAswLXMud8Bv0VOb9in9OhPmNajTLRtjZx5lA==,iv:xWicqgGGQR8nJm/CL09phNHfgNkrFTbOnvG8IW3JtcI=,tag:VM/7Ht2AIxX5dhmecay6kw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:beRT2Xre/JqYBnALPacAatFLfY1MAjyyibbY+FWVrq/XX4FD+wOX91QzI6lU+eEPqnPehY37QhoS5VKLISrrmQ==,iv:0I1xeXqEnHVz1iNrgZQQmnpu3/T0mON0rM9GOejKgM0=,tag:KIoEzBa1MwDfzP2DQqItdw==,type:str]
        password: ENC[AES256_GCM,data:MqcY9Uo5ZmL749aioA/oDqXix0/+IbXp5daJnV6Ch1NI/p0pn55hsymcEABufNSdgtz1ipVWzAlmbiQMqUDFJQ==,iv:GL+jANZD3PA4oIFaMBnhm7UBjFN3tu1lBg71PoCPT5o=,tag:mhiT2qesNIUiH6va78ZV0w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        toshiphuuVah0rahMae5bahD6Pee0teiPh1ohlie8elool6shookaishahShohCi: ENC[AES256_GCM,data:OisaQ82E+JZ99g0NSzxL1X84/V5DAlu1BjkITfYTTAhcz0iQh5mK0WNpMEiuOM1k76Rk2goUJMc/WqR2,iv:WeIAqhCHlWBVbhKj8AjAioORJjhQv8i7oSC5hsQENSo=,tag:+tONHNHDekzO3S3tF70REA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:17Z'
    enc: CiUA4OM7ePSSraB2PEAnbxiKvGog2va7JBlzkylwGcFz0LPkL3eUEkkAPHlbmVgNrxgsjoVtF5TYHPaotpY319xDBcQRYfs2iN6aO9bYaL1HYr/NzUlUF5Y75V3TkUueUcE7tUjgyGbtfOSGV/8uuJjN
  lastmodified: '2026-04-16T19:33:18Z'
  mac: ENC[AES256_GCM,data:34nK8b9FIFsRV55rSiUhUB+Y1FZiMI0qbIqDjHd0nOlK7opQoczhn0JBjI8V36f7lLG0yJANLEtW/icsMpjsarT5A8r/2q35LLeEttwZKtD3a6hYhrMafq6oH5ElmNBaJAsTEqMJFpLkiaknLIDMFRN+46//o9kU9Fqs/zKvHR4=,iv:za20bK7q3vn+eGPGv+vIgHZGrb+DqxYgU3jJgCzdfLc=,tag:qvwdtZl2d8FHeAQoXu7i2Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
