prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:vEQa8qWnd1RggBftaeuzroAOC3FMw/dfBvU+QCgEOiYRvWAdpUzSXZgwRqLHHKDgDmJ4/D0+n1m8wOzSjKiil4VRFQIEr3V/vFvV38KbnguH/pcSqY6r7YhUFTWItR3rpVykF8awBJJHONva/o+rnnY8NpMAnf7i8lxP4arJZnfB65HqQKyNrFK7ou/BEuBSxl8LpHZjKhB11HdO,iv:USR/L8F3FpnbgCmvIshaHVIrqpQ6Cu4xejrTrD90IF4=,tag:ZWw6oNLWmDtBSPjWpetL9Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:jSbM0dw7qFqLJhebZ9My804UGtIq0bc6/xyaFnBbJkHe5zdNEQkvhb4fBpwplb1M0TycLNRfmoaA9O4L5nNqug==,iv:sSxvtJRQnswrmqQN93oLzn6SRVGG5D0S6wFTkPRS/xU=,tag:TAEdQ2vWk+A6mSWZ602ZYg==,type:str]
    password: ENC[AES256_GCM,data:fvZzCIRhz9/of7BUe+oqjU3KkJFgNhjBSRpv7RpD7hEonjMAEdBrIE4qkxPe08fDiG/Vn9J65XeJj4ceCUZ13Q==,iv:MlSTuVDcyRvqzWVVqTOXt5yIb+FPSRhbKwAREqMmC60=,tag:lwi+Fhu1c2hXo6ZySEIwFA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Fg==,iv:2eyD8KGF+jGcbzXbXsMHuQCvMP1XDqPGsnaw6vKmfD4=,tag:Gt99ibsVupIuIGJaL5xdxw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:gIM6pIdj+IB72w==,iv:yXP+dPT7/70igcpOmi/WcD9remATTQYSm9IfL9mUMIY=,tag:nvToPZWG9pnvswM4twVeKw==,type:str]
        orgId: ENC[AES256_GCM,data:PQ==,iv:xi07suxlVedVJ2NbwD87P8otXbFmo7whHnZEimpyctE=,tag:bM04P4hYLe22ipFJe8UHgA==,type:int]
        type: ENC[AES256_GCM,data:hVgTFvtdOlGWRQ==,iv:iPVgQdHB6qWeUonJw/AipHrgL2Osee4FQDCdHD5Kg48=,tag:jL06hVpW8OepsWzBQoD9sQ==,type:str]
        url: ENC[AES256_GCM,data:4lC8cd7bKoS+CkMy5ZuODPoquIk2DKYohKb/uLwu7Vw=,iv:Pbfrm/jCwNS9Uak2yR+JE9cqoJAIYgR3bljl4HM5dBI=,tag:GN+zgyPyw0FeYq+RBszagA==,type:str]
        access: ENC[AES256_GCM,data:qrqKed4=,iv:bgaJrNpvqC+yB9pmTHpwmdROtS0c8ins33vKv4k5Ny8=,tag:1RoGlNwoV7ELYL+WrjbnCA==,type:str]
        isDefault: ENC[AES256_GCM,data:ZtxfwdM=,iv:4ganVgWOrc9Wt6ax7WxoUKCWL8hYoJusN7mLtxnsX3E=,tag:eEtAbizKEY4R+b4J7bkRtg==,type:bool]
        editable: ENC[AES256_GCM,data:CtKlgsU=,iv:/KMVzxVl0P1CY65rofs026tCetLGPtTMdEsmOf+o40M=,tag:8FFV93Cwr/scdzSTU9xe+A==,type:bool]
        basicAuth: ENC[AES256_GCM,data:qbIYqA==,iv:KSlbXuK4IlBxdg3JpCo1MdxtvStAxAElb2kQyhqieC4=,tag:e82EB4+4Kdp5XceV6olISg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:aMMxVlNbWQ0CFo69Z4aHoQ5u4SqhqNf1lsyO8kBG0DDJ1ryAt4H07oEFcU4Ap4BvKtb0QiIGQFwjad4/TBIBaQ==,iv:eLcKQdykh0DIhueGdQFayJeCeOelVDQ/ngq7VVtBCAA=,tag:oRlD9AF4riGKk1VXOczQ+Q==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:Klx8QKV6NxDeFsO1ZZ02NQ+xeFTv3log8LYfOoqEtwZ1B6XJjGEDwIZr41xEYrbS70B9wE4nO8SNrAX5hlFQpA==,iv:bPOd9GD+rQPdawZAlHdR/W4iV4qt+avW5l67LRpEs4U=,tag:8b+XBUivZaABRokoWho74w==,type:str]
      - name: ENC[AES256_GCM,data:lDG53LAfJyMCZ+I6kPfyszls9hVnKQTapA4DC2AFLQ==,iv:nAlN+ZaY59/Rb5mdgQvkNV+GXQ1H1/Fe2c6hrlKF9pY=,tag:p+TlUzl2kKZJvIBAdI89ng==,type:str]
        type: ENC[AES256_GCM,data:bcY4tQjXgX9lEKpdqt343KTx6JjqtmO8sGKRwlW0HA==,iv:GsLB3nqPbwUVdcj/xKNgTxRrJS/xbzg/1gzwpuJGYf8=,tag:j7/phkgNMs7XV3pbOMuGYQ==,type:str]
        isDefault: ENC[AES256_GCM,data:XVMsrPE=,iv:KgcRfoYfSJQdh+m6YejfeqqxArnbWFQOJs9PsEr0nqs=,tag:GKOzyKGaT34CTlZzjAuPdQ==,type:bool]
        editable: ENC[AES256_GCM,data:1BkxBQ==,iv:MiasShf6ClOsKJ5u16Kt9rWKDHphDx0zETbap7RqZTo=,tag:MeIw2TRqdUAMGKPK78CfLQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:loBMXYjeSovGMmy25Q==,iv:e1hRF3giTPXApLRqOGkVibodjkp/3nuCQ1ooUk0Zb1A=,tag:dSUJ7AEJ+Vu/kXcDhig0yA==,type:str]
      value: ENC[AES256_GCM,data:TzZGNKGadc8Oli/o4tYwhtd5VNaFeWyUcfCKUjVC5Nt0Y5q1Pt4Q2jDS3RfsWmIuoPE3C2LDrvm9fWbayJksIOT+r633Xkr0oK4N3JiXuqJ+QHpGqG1tjbRfaIU3ie7iJb/8mdB39z8Kig/tsUmd4PYwlijhJAfZQyHILN0r1U6qKeSyZvzvjtm4G2J5+knNGYRCmigZbLcg7sctnFerC+u1mPNFvVDx/DR6twQdsOMCYg==,iv:SZjFQMuUg3tGAxgt8JqZ5kuLke6Zuxq92sE7Yst5YpU=,tag:tOUyFRS4EhqYjgULlmBY5g==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Z90+hTgw4lprH4W3KsDX2Bbf1B1ijALZRSfTdZnhztMr0DoqS+X7TIwDHs5iG9tuzD1kd1sMi34DljBO12Chpw==,iv:gWZA9I7OzC/gJ2NALwdYBi6kb+GpOkAB0fJF5qSTuOs=,tag:Djp+ml0x9yKhQ5lFUTklaQ==,type:str]
        password: ENC[AES256_GCM,data:KPTweSygE5CtMx2w4aHN5cEj3TGyc0mvQteG5nWsSa3fanRUsGk5Hndc59K+BcX0mVn7Ql+PxrHanzZaFgl+kA==,iv:fcdluVaEd0NWUV+nsvW9ixVOfaZvXkiFqMu21jKul+w=,tag:ywGRZH/ajyV8i7NPmLvqIQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        toshiphuuVah0rahMae5bahD6Pee0teiPh1ohlie8elool6shookaishahShohCi: ENC[AES256_GCM,data:UqVD0NeMatpIpBIZtGpTDI2P5Y2WXZxiKFqiXCTGNM8CvpJTKbNJLktRCtUEG2uAYvift6vzpsbXkpUc,iv:kokv0m3pfgctVLbw6pmLfMI2buayyvxQ1lm+mbGivuM=,tag:L0DYCyLzFWdrmnRJNVMT6w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:41Z'
    enc: CiUA4OM7eOLw4pFIAvXDn3w0IVmR10WUM3iX1NbxnobKFpV0tV5NEkkAPHlbmcC5BF8N9P+60yNXzWRHE00js/C8FH6pp3WSLEUybBYAo28IEe0v6Zoaza7vMq0ewYbeBefz4Y/JLA3I30KLF4ZFpUPD
  lastmodified: '2026-04-17T08:24:42Z'
  mac: ENC[AES256_GCM,data:YhqTxFeD/D8cpBNQyxKjKbNBIDCog37pL4XYkYXZSpJwHwTKGkkKmOUcHphToPqNnw4RL+br5Hrw4XrLq5LAoWdHy1ujve/mPKJTloE+CxSh8n0WuvobycB2UnNBwn190oot9X4nLdYX9Or2RHByaXxxhHdJMtNrftdcMuwmFbc=,iv:XTi1C2CECnh5zHJYpNNPUgaM2JPfffDrejfdZn5wLu8=,tag:t6FQibGVgQdVylNy3iAGYg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
