prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:MHjl2VEZ+yLFpfsawpen8esflBRzaoQsLV4GeQcZBPg4kGwItCT/sVO3v4B1BsdrjfZ3wV/hr0ISaJxQCdwaxt3f6SuULbDKnMJFDZHr5ubWE0xHYIpIJYSA9BZiKzRg2wPLnMvvyAa1wVZOEE0IIPIzk8nkD2v74ZjmcLPMaMMMS1zHlktxI5wSXYWazHtp/sp14/9aF1vx7chF,iv:NvJiVgUxr5FAWDCKTeZVI0E/S95fRRVA5okWpj7O86E=,tag:n6TXwMBCcREfhrtC56LwWQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:/Hbsi7b8BSEPLwFj6EFssEYfyyCT6c4INBwNKhA6BFI8ZTfvz/j+1LIXjJlFl7WPQALlDZ6YhKhwlA2NsDeN0w==,iv:DGDryACsNRd1RQjd164n9HvTBhFSm9OJXk/ot/8Iu08=,tag:snzteYdTK/QHDIf7BOQFOQ==,type:str]
    password: ENC[AES256_GCM,data:gN3wWUIA74jqlSDnBylosZSHONJ7Dw3MH5NbE/1xFSPYmEUjKsQg7RuLP8FvtrCjHX/95FyGKawsY18v4p8pRQ==,iv:r33TsiY1m/zfe5aq2xI2Dye4ws27hfswvAUp2PZbCaQ=,tag:wOQCE8n5tCnxgWsee1PYIg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Cg==,iv:lgf5f0TOFADZXDl8iTs1IO9zoSNPVaBFqnnH1bYdo9o=,tag:nmWxLlWuFJw1wbCELVewhg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:bdeobx7uJ6SSfA==,iv:ivwlyVRPETjk1RxHNRmxAmTP0coK+jHbEQvyB/7zU+o=,tag:MUEx+0S0ftSm+TUSDKRaPQ==,type:str]
        orgId: ENC[AES256_GCM,data:nQ==,iv:WgfuMekUGMDe9X90TNzf9nfW0Abwz6JhWmywzJCzCnA=,tag:MsFz1HceV0TTY3ukaTpPfw==,type:int]
        type: ENC[AES256_GCM,data:RygI/jlUl86lPQ==,iv:Nkca++mFQqEXGeiFGHGtNA7zGPXkdq0aoszU+0Bi7RI=,tag:dEyXssYbQCVS2nicOu0mKg==,type:str]
        url: ENC[AES256_GCM,data:HOZoZLKjAzysZk69rOesoX1awmOIX69RnkdCA4lYMz0=,iv:oucdVCOG+MRjd+AiGvH8DgMEBL/d+HyC38UFj52uq7M=,tag:NcMyYcDHeldlK+vfKaFXXA==,type:str]
        access: ENC[AES256_GCM,data:+dkCemI=,iv:RPD67YrXVjSu+qjTcCvcSLPTJbqXsyjF4JielffAw70=,tag:9gfnWWo/6mtMDKrXGbLE2w==,type:str]
        isDefault: ENC[AES256_GCM,data:EbUUz88=,iv:abwuZTit0uRU2FiRcMfUFh/47EMKosuX/+SACexSQVw=,tag:fbW4tIGpkCLz9Mrzm7sl0Q==,type:bool]
        editable: ENC[AES256_GCM,data:tFLCgYw=,iv:K9BbZWuoHUbRgYIRdsqKYuD54m1SJkvj9swIehQwd3Q=,tag:PC85xvZg+QQGJ3VBiHgbRA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:bQIgFQ==,iv:tS22cEQzr5zeTE7Q/a2HTkliw/lQxrfuKfW/zpbxP4g=,tag:CPdZqdygu/h167P7C0cC1Q==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:IPp2nrTsb713rRDDSSy7WR1q6HnQypwcCnS9QO18fw5XuQ3ikDPCL3vMlpEwdffx7omsyTfCGD3XAFFW5T75bA==,iv:k4jqwV93CjXZOkc+2mwycV0sR094nCuj1HotsuSdLHU=,tag:Phk7QaREiHFon+zkJUtAXw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:quN3mF/N1yooKyGmCRkUsEWC+TLUUhWe8I2D3Lbuc3vFooqQHW4Ly7p3Nfbt0k3r4eEuICy7QvgnnuO16nhw6g==,iv:Qiuj9PhWXBeVOVGaxP2o9X9H7eGyTClSIcWtoS8e1SE=,tag:GsbEA6UMs7K+tX/K4xcNmg==,type:str]
      - name: ENC[AES256_GCM,data:o6WEWCEUedFjMamyEQ5hzB33ngGD39Q1uzvysLGB0w==,iv:a2lW+UotlKjQjRxgAphWb2HjqRmUkG0aJW1dpSSYB7c=,tag:quFpsBoK9Mr3pk16rCcNhg==,type:str]
        type: ENC[AES256_GCM,data:wGG5it4ysYxrcKi+/hgYM93lhcon3N5TNCz0mP6FrA==,iv:ALVFqR4dlUG8o0fo8xiuc8Ah9YjUYMMyQDrnfF+weAg=,tag:ap9Bdr/xlB6X4e1JVLAacw==,type:str]
        isDefault: ENC[AES256_GCM,data:Xc45qD8=,iv:6M1+OkbDMLvGhH2YH+F96OB/jl7rpWlikN+Jc0s8plc=,tag:WN5IJbpttedtgiPTBSacHg==,type:bool]
        editable: ENC[AES256_GCM,data:7M6CeA==,iv:ETi8cQb5wz673Uho+ZFnvwre/TLoIqpT/qrw4pRu3ms=,tag:wsRbjpOPH+3GpFDTNE+TdA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:HSYwpPoev+dAOabH/A==,iv:DV1RO1kBdq16IrFvNnphZNx8JwM82CV2sURs3yD/0G0=,tag:NhVJfdI9aEpvC484j9rUbg==,type:str]
      value: ENC[AES256_GCM,data:d6jgKwPUT+1JmKCgyxwo0cTtCVqug+ZQ1bXP6ya63Rz0uSCzqdm/61EwJAim14gObPFnoTAQpgNuQ5GZ5VhnWnFAJdAhWCUyMMHSNiBgkB1RazgjEqhpJdU39GFDUJUaC1vCqq+fQHbI8ks8i2EHEH7wPfRF+ukcpW5iEng1yO7CM0qeFEZFDmDqTa4ACg7kTx5TGZQu5I7pXJPC1vjWi+JL6dhdnx7HKVgJKPcC+2amjQ==,iv:U2EZcmSfT9ZK/sXCbblzsN5+7OSSA0qiu7iSFcUcXPc=,tag:5ykwKH7evCTfbvcUwjmizA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:6jSBWeIvK/EjDBlbyfgUz3z8LiIaLNZpKNEIWVj1UgelAa1MymOf8sRDag60y4MZdZXVaDZ8NzIq+HFFmvUB0Q==,iv:7vd69pbOpYdA63pztYDirmEZR7KLIKpfFMAhnLfn/So=,tag:byPcTSd5S31xV4f7dyglhw==,type:str]
        password: ENC[AES256_GCM,data:iPx8sIwRLdxEJ5q+kIh8y2BmJIRBdOI2UVl5BEGvAhACwZ9YEDRj1FxFwiC/IV/Lu/l2PyKlnLkiItN9iyR2LQ==,iv:R6jbej9RsfHqxwVxoKX39Khk2PiG9/S3/Mn/Sj9w06w=,tag:0lc41Se+wFC9MvJ696tsYQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        fXVdxJmr0ZKsp6urCavA8lDFtB4fPjxhO9V1frHwenDLtMYmaIdY49ahNk9jLPiI: ENC[AES256_GCM,data:IYiHz32gfVWvZZ4BRfjeTuOq7ftXXXyXRbWUzfSRgk/pNz3B5RtZuq6I+rIplUW5/q+KwwqY+5wWpp3G,iv:e1JRXU+yi8jggtOmMV60Zmqmje60431o1yA2eXFbkPQ=,tag:CVVa4eRyXxgJxvVYONEIxg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:44Z'
    enc: CiUA4OM7eIMjm27+enOQ1jINIU6w4o3/7QcC9Xht6NW9sEjFpsIJEkkAPHlbmT75cK/D8HkKXlELHkSntwvRO/Xpd2tUaLXu03OA04+uYznzHcXvEt5zU20zyEliqsKzvOxD7BG79o6I9e1RgGf1k5z4
  lastmodified: '2026-04-17T08:24:44Z'
  mac: ENC[AES256_GCM,data:fY0kJCQFLM5C1BSyFtzta+0KZzoqmoCjtxeS5cFLYBMqp7j9d5Wzlk4GAE4UyEFehVlWlpxTeH+IPRpMD8K92oLLw8tztoD2TO75M6cpkYsij6Vmv9f8fMVSRN7wuDtlwNgZybW9x6ReRViqdKolPONfdZtK/yJgdnrpHqs3UqM=,iv:888ig3FUJhrJjbLjVvhp4vrJSoCfp0POipF0LscHYE4=,tag:eZKu2ndNZdUCaCygs5mtUw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
