prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:ttrbTvesDC2x9MVrIIjv39JFuPOjDxlQNuiFGHdmSLBB0pTKfFadjDnStgaanG8oPwCYR3K0m0KLJLy4BEZFztWuc8FJoXsR/psCDYzD5CA1SyWGtMWl+fDacLtnzN3x0JeINbYpKjpyY+8TLOuNAXDCx2gY5lqsCdeGi6Rcy6cE/hyH8cDl7LvJkTWZAil/1lx8F9cMLMP5rAIL,iv:cPskPZRCdYEMPwWEZcRtZShtkmUfjiUUzDdttfU8NkY=,tag:NU5+ViseDYt1+4bHsU7J1w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:SLptSTWdVNL6gBrevXc2GSJ2+Y0mpSf+6qz9yFTuVkHyeUPPgvIturPjKNbyQhdopcqBJol+Wc/q9dHARCPdbQ==,iv:ms7OmgVd9r9vRfrSrZ13vj3YrYKlP2RpN8pgrwxr498=,tag:myYFmAy3/ZsyC3omxzwsmQ==,type:str]
    password: ENC[AES256_GCM,data:Njv4ZnP9IqEyoZ54dfZm2H/5xorpDnBBaV3sWMVAMVF0iFxY63mvGybWOiQ5KCrG4PitDK0I4P7Tb+YhIjoFFQ==,iv:x7gNSzfS5BeV1L7COozlsWLcB/o4IvbqTz0p2ekv37s=,tag:zRbGHqhf+PvGqMo/QVyQXw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:F+GyBEcYuufBFaurpBq89qSDI8I=,iv:VuynEIAdrElQUNHoeCtYJQiij6NdChUesc/k37THvlk=,tag:3shrTJAebFjsY8X/WQqttw==,type:str]
      client_secret: ENC[AES256_GCM,data:y7xjV35P2xEaOboUr4vP9Tihp8WmJIxWHGkPzZZcnyaEzjCLjMHzgA==,iv:wYBvvxmcVsnpmFKYHKUQt7VoYdKzF81PpOV1sPF6Vq0=,tag:71A3ulDfJHy8WTbg+Izpbg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:FTndcfi2N0cljrmXCA==,iv:jEMlh7F2T0XlVWOBiHRzHoCNxN3LKsr8+CIcHUYlwH8=,tag:dbH+DXVvv9JCR+X3MgjOfA==,type:str]
      value: ENC[AES256_GCM,data:F17z4YW0ku65g5LphwUcgc1G9/th4W+fQ2ff2faYAcFzXMEst+asXaq5l6fPnJFNGZ5WFzxQrvM8hCuamXArqXDH+DNoj1w3e/+yG1N4uQ+CtZepqMIjRmGw6xD4HuQda8dbN4lwIez2g4fn51cvDx7AICwStYcbLCQkq7y6p7WceRISpS3zOTsVcmTyyj/3rLvJAX9UrIdk+/ou7ABcGpLMVmVkWk5teyiY4zXnE40ejg==,iv:2tyxF/wF61RRpmPD9h1MF5NIERILcRGaHN7fW1/DB4s=,tag:p7a6bZgDNsOTNKdWi3azgA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:WRRJrJQf5pYMr/798+SZ+gcq3jvBKe9p6kfitXde1y4CmcT3b5aqz5qxtvDC/FGY5qeCd3DFtLw3y1mPkK1npQ==,iv:K7MbOkXcSBwmtDN0Y4DfkxZunIS4WRj3Uxhenm3Gg7o=,tag:18c1b+9SscWr3mtp/zwEKQ==,type:str]
        password: ENC[AES256_GCM,data:8zZHRCI17h20MryQup3od5QYGWuNOrAe3D7vXrw3XQ+l6bh5/VeLBSqTY3PmGcZWbZynFo9zHax2JnKNQg2L7g==,iv:l/fILRIHPUM9f8dptCCWAjY43dNRqoIgcwL0ADiWZmg=,tag:bI+iYfWRkoGpTqnE+GQeHg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        fXVdxJmr0ZKsp6urCavA8lDFtB4fPjxhO9V1frHwenDLtMYmaIdY49ahNk9jLPiI: ENC[AES256_GCM,data:mSYRCaKNg3sMZBESMrjc2+pQYJ5y7eOihC4o86lEQIHs4aM5apYAxbid0Mfjra3JsUq3j1pLPM01+I9A,iv:3BK7r28P7KpdoxPglUHmj2rsaPGPS5pWqkRD7hBQWu4=,tag:nZHmDftqOgyVmMNHncI4Qg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:20Z'
    enc: CiUA4OM7eLIG5+b1h43CirrPv9S4oo/vkdRygrNmZbAWlogquNTcEkkAPHlbmXNHI/TE+B7JcZZL/ZV6yV+Y4Vu9DeEKBKCm5UBFZM3YoM6Q1XgKmGCbp9rwObekh1SEtUqJFLTmuU8C7LSmm0OEMdgy
  lastmodified: '2026-04-16T19:33:21Z'
  mac: ENC[AES256_GCM,data:be572msDB01kXq/QuV3nPm/I5U9BdrI6+IHl2kseCj9sYJd4Rpd/TWAa8YpS5goGWygQh1kGlT+K9yalluVdJCDljXttU9+sgPz858cSe4w8UjIuobgffxwBfRqi7ACsxMSeie61y+E8LjfPmc5rXG0JmKNhDDbh/jbFTeNCeS4=,iv:u80X3CyGcrLRURTf2bVCadA6+6W0l16EfLvJ6hZ0HyY=,tag:IN4NRBKXNpa/UrGwPuD1zw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
