prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:XVxtW7UMTj3Be6nI4O5U2eJVWz+EmNvlrk6+TeABrxpsJTre35/ubAsX08HERSWygILjHb1R7iApCHDEIUb90eAGX9i+Q82jZDoe1AV1cTR8+yYds+V8xWI1hCNbZa/iFwKjAcHfvyC3XBnYxFFe2GlY+GGWWmb3L2udprAwKgIRFlELe63Oxe31ji6c11e7+7oor2l2rB0A2ldh,iv:6gGnyBazucPE8UuSt2WALHPNiUzoyrSmn3+Kh+wsZ94=,tag:B9zUJHSWPtkamMf3v1lPew==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:tK2JX1yxDwkbGK5/fuRNSZ0yb8haeelOanMyafj/5CmDckstjn36KnfR0boqiECnVhXA1RyyKkMBwdn0LPxEvQ==,iv:VVaHeTfSxdI+RJc0zgXetAgt2SFB8txAMQqlZdeiFj0=,tag:ko6kTsy584sotAibqg+Ibg==,type:str]
    password: ENC[AES256_GCM,data:Sq5gjDqzVmsraSnS8YMuqSodco2RIW4MlgQ6AQZg943LazlE05bLXNpTQ/ZiAJwayv0GdHYCD/UarbvNc33ZLw==,iv:+e/i+WE7hKVyn35A43zy5pdxLZXjpCng5IY27zsRUIM=,tag:6ECIIsKXHN98xRlX1KiReA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:oY4txt1j2E2u5tiqqA==,iv:9f4MRfYbBUdOi31wWEB4BIqddeuQ3caFelZcYG3GNwA=,tag:xpw3WdFVsjqQShOO5wGPHg==,type:str]
      value: ENC[AES256_GCM,data:5UmRGgIpnBjjHsLGjP9Mi3IZRau+gOWJs1865qpAA/w+4yzOAV7CJVxouH8msi2Bm03GwvHoQLEIj8RvkL8VYP+6L5hgDTbnIx9V/E9pnSQMgk+0hL5zx7Od7PcV4jreFUzDwSbQUMxmQSvQX4wua+Qh1T6rTvm+7nrh165S7SM8xMS0aHDZ6ahv0uAkSiUiS8BZyIpJDAF5Ry7rM5/oAZChZdZ9vcxixaLCqfmo2hWftw==,iv:RLIpn6EG3LDEFIJ+p/JJ59SFD4x68Ciax4n6jgxleEk=,tag:02ntiuuzULqMfPsDGmFj2A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:IYTOqwj1ppGqENH1h3mO/R/aQex3Uw73U4QXu0Q6M19pxCcBLwHWUxtrV2D6lVcnpWxufvBITBekXWEH5NGVqw==,iv:j5eniBiBO1nMldLNbEx81rAj1gSA0IDBwxqKHyEGDZQ=,tag:Ryv84wNYRBBaSIVe0ilS2Q==,type:str]
        password: ENC[AES256_GCM,data:AdcTL4ZtPC7Svk9aCLwOUcjkQrMekAT7xZBWIJpX3blmGjXwl1R2WHehvsbcq3loBjbjwyIjGuGlAZg0pbeoXg==,iv:QiZTHHgYXTFQyTBl8PjH9jc8a8/WmCCi3/1ItLC24is=,tag:jnDffvSdIeDXi2fNgK6Azw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Mo212kziLwQFZyjyGPGj76j9OEzgjXmVoAOZNQ7ckVOJy0ujANhbICirTTpWNBk5: ENC[AES256_GCM,data:bqT4kvPEf+hIMia7T/Z47cnXC24bbyAtvsgp2BpIMGp6Cknn4JhLDlNKNa1DE1chjLAsYlvexn33PRpm,iv:bTfctVu2OKh6TOdpQQ18UReJ2C6ydehpfgfcLBsTK74=,tag:E3xLayd/dlD/JRZYyZCvkw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:IA==,iv:smHrChmyXbHhU41MaKaLFdPEit1wd8+MHdlcL/nJ+KA=,tag:my4Nldf8P53VVKL7WR7UFw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:C823eLzV5wfV5A==,iv:vmFKqLAjzych5nEEFODv68UD7h1073fvo06JQbW7C/Y=,tag:CZkcPZ2MY2vKRbz/Sy1FUg==,type:str]
        orgId: ENC[AES256_GCM,data:RQ==,iv:/CZgtXgmpyxtvRk+lBW59ae1XIBDpVmS9NstLss9YCg=,tag:Lh2wyDW9p/4/dswpQJKoxg==,type:int]
        type: ENC[AES256_GCM,data:I6HU6x7hv1SZ3w==,iv:KfbxMZQmmsEFRRFB6q9or8lKCxjTdU6jH1eUUwuX3VQ=,tag:TGHKyDsD9I0svyX+vnWniQ==,type:str]
        url: ENC[AES256_GCM,data:fFQxdIfR969Lgb8pFCxgPcXxUZHj0xFh3mPh9rbtxo0=,iv:ykbWtAiTNZ6iLrdEnDWaQ8ngYdIrumdjgBaENnOOxwc=,tag:l8kMhFg2DN2anzwxW0/wEA==,type:str]
        access: ENC[AES256_GCM,data:I3iubTM=,iv:6hz08bQtZIRvEkfqF2tGahgNbO8xdSTAvAuM0oLna78=,tag:8ZtOXhwUshYxGwC81KoikQ==,type:str]
        isDefault: ENC[AES256_GCM,data:C9dKs1I=,iv:yJaZtSU+2DA+j1rnHgvRhFZQ30q8Mcsj88UE8Y4LosM=,tag:T9V4Sg/9+djFpASbb3OXMA==,type:bool]
        editable: ENC[AES256_GCM,data:AnzPgmM=,iv:kdcumYpJSXJsFCDnbpphPA5WIfNFBY2Im124AcC/v0w=,tag:qN1lJwwq8P14PkXUT8U/Eg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:GX/4Tw==,iv:crQyrr4bF4c+0R0grIzHktYGgSGXG15UqXbRnITbOGc=,tag:8nAWvY3jLBhFC8BynaO92g==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:VsdEsVPZ69y1fB/D/IheneXE1DWZU0hinxHPWpli7ALAhDm9Zr1NNFRjopJD8VWh/WJFjIeADWvni3a+G++d4g==,iv:BuRoR1dcUFIHJ5dUFEsCowIrvEsbaeMN0CONSzCnnI8=,tag:yLwQWwxzHL1k2vYT1VqMKw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:3XEQuhtYBw5zXVOq8cGqpjID9lb6t4R8uKNau3e7B868rkRQwk9KhrjJrewyNEvfrNQPxbP38WeFHLdmInxeFw==,iv:pi+f4G/l9qCwi2OzRMB88VDHMXss61uN7XUZ/svFzd4=,tag:P8Jv7ZQp42cDRbW8HWR/JA==,type:str]
      - name: ENC[AES256_GCM,data:hAu3Rhpd8fjDtua6WJuUj1yn3Tjamfu+t/ru20jbIw==,iv:dlXhW7SIAXLc3o7OQZGf4AVPUrto058rU7+w9dQ2J+w=,tag:dfL65zW/8nkSjZJ5tStGZg==,type:str]
        type: ENC[AES256_GCM,data:7BNamGAFHQnj1ZT8pAe0nwh4JcrC4LSn1Zqh096Q5A==,iv:6XuuDcTJUQP3n8zFZDGsL0TEbj6Et1Q0GQzHPVhuJTs=,tag:xi1fTctKApX/BRpKn+kcSg==,type:str]
        isDefault: ENC[AES256_GCM,data:8xgUixA=,iv:GlOid4H7P9cCDErvpsoIcIi4TTrTjESCuSgYW9tqNR8=,tag:o7HhJ0vNLAcfhn69K2ha4Q==,type:bool]
        editable: ENC[AES256_GCM,data:vrVArg==,iv:BaPUuDtBz9XjmjbfmTtoRzogitjqdba7al5p0nLhz7c=,tag:hk68yDSw9tfF6l1qa4Uhlg==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:27Z'
    enc: CiUA4OM7eDMcBfqDDZw3it/qYoGKuryxTq5tGQNjRmkzkab357FPEkkAPHlbme/bpU8uLSE0PedbevC0D3DsChOZTeWZIRzFn4lOPaKzT3u0xt0DvIiozygVRzLnyiFXfv8RPy6L015s1Zfpfx+mz8ql
  lastmodified: '2026-04-17T08:24:28Z'
  mac: ENC[AES256_GCM,data:RXfBUyCyT3hmXbRwPN8Mw9Js/BKfYgyA2MuS2V4+slL8nO0Z6V1+vD1Bt/LHtX/Hiy4iBrJqvMk+xiShbhzLMPo0qQ11dFu6m7NWti+ZsmF7I+xtrPeTaXnS/462+YSOUw0W8mUCjJrOnHP7ITy3Gt8nQ/AuKh6MmHdXfj2g8pg=,iv:7/v7bKQLdBTJaXi7wvaMpFk+QFkqIA+PDjpm0AJLjeU=,tag:Rojt8K7F6BCLsBgBp0IKLg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
