prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:08K9Hg1xTkI+rxESOX7gMVoWD9blYPZg7Cw12eG7Xy2SzPzpDjO8S3whxOvtqT6JJKqwyWTPI1SRuKRp6SVKK5itN6YaICdC9VnqZ4CX6nUfUGTnxLpDcqUO8qakEZVcvk25tIB2EiP8c4felFGP97/81CN0OR6oDKySJfoLmiSjzfOaziNxeKLHWz1OdpNSRDXfFNps5RKH5krv,iv:nCCSHDgnZrznkgiBHog3JzQRGIzmOoxI5Oh+2vE2P6k=,tag:oDuo/Vn1FduCGG90KII7qg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:jHYHO6CR9i02/jXPfsakfy65gsDQLeAsXfTqIdBEDZurUBXnNhXo01enL0CajQJNq65Mu8+sP3p+xqcgGX+h1w==,iv:e2sYPlqTfqFb+6GWSW31IiXXe78nGQsfDpLBydkE5Kg=,tag:msxvPdz3tSNBymrirNdeVg==,type:str]
    password: ENC[AES256_GCM,data:JlXfGpG4+bbsSESUuAebsMRg1mST3wAZbqe5TrQgrHI7NUIlWa+uDHNtWa7u6Niid4jIKBPLpQIvWH+DNJJ3bQ==,iv:hFBbKSsvPkzGuTFJOuXwMhGAAhZUSGgqde930++Xwrs=,tag:IX28SrDUQ3Jc+5Xiw3bOPw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:/dfHdxkWBDZpP8+TZw==,iv:5gx/sRd3nOC2ODZmL0V12X1O0ssC863Q7HPfQgbaTcM=,tag:PAiizc13WA3XVA20bZi3NA==,type:str]
      value: ENC[AES256_GCM,data:/WoQoUuvSYv4rdZWU1RQyJinsh+Qt01bga5vqzqGCncOWp8RGbAAIwB+sy0SL3by2VuYeBd0QxLOx+hNkBhaWUSfvpbyGTfhZ+SIkel1qFOWFGr5JRhagdHKEo81JXSE4srhTRZGwy0u9KLZdCNYkkKrD8QVdpimVkMbB0XEcxGcNWO71gYK21efTBuIzI4STE4j/tGVkudRiNXTSCcXyd7IC7iQVsCd5GeG15+nZ7ZJ9A==,iv:XxpeY0YZr8f8ZmM3pghieQ90UjpZ3HsJlGtneLFta38=,tag:hRrBPyl5JhobphalysNlbQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:/tUBGO03EFrGXu9ePZt7W75YrhzqxY1o+2XsDzK6yWkbV5h2lFZ946SFyYEL4vk8NNdD7nybAYIEkTO45MdyUA==,iv:FeZhcrJpel+VY1F4zJOXQKNvKetokb3A0IUXDb82AYo=,tag:OEJm5/jlc3+O7udWsLZWVA==,type:str]
        password: ENC[AES256_GCM,data:ErReWeMb6el5EdnJNleij7k0Yz9kah3aorxZbDwt9tLF8k2Q2c7dBDLJemmuScZRLOIRKwpTbKJMvnd5nGZM6w==,iv:UUo5VRP7AMR8le42iUjs0oyVTihrHKn2VC+bPyCGtr8=,tag:Mevt6frk5cWVbRpv+eRriA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Mo212kziLwQFZyjyGPGj76j9OEzgjXmVoAOZNQ7ckVOJy0ujANhbICirTTpWNBk5: ENC[AES256_GCM,data:JX9u1fhvMmUDB+qJCGDB/aC2gi95NCxy4YOcwnf0hKx5TBpTIQmNekewQNTK9xOVpXpZ+/x5ltDklb6Z,iv:2OcEmR+8smVFdDL4LKbeBFl41dCBw7QAlHmoVcUUwag=,tag:wh7kMfEdpADUFdzFNLm7lw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:03Z'
    enc: CiUA4OM7eEiwTcp2E/dOm0qub2dcj2XtVt4Qo17e7zIGnKNNw0i0EkkAPHlbmTbd0mNPG6rDsMwMoSN4pKF/ClgTb/YvZ4fwC0u3iKlpbXNmQ1R8NDPMzaYFw8SyoYWEjywSKs9u2JqH6v6WeN7MZ9eM
  lastmodified: '2026-04-16T19:33:04Z'
  mac: ENC[AES256_GCM,data:tRw2EoPbhOfzYx0V+69x4DJHejUw5oeuIqAtB5HxWEy0lFxb7hqvdyxKaWk6gys9uYc8c7QsHbqQ6lbb7bgn4ghZP54hfERDn5M3NWTlH3b7DvcPFSZiwZEIQ3sJxmK91D4py61EtfFu2SOHIZp7g6phG2PKCwxuJYXWmxLmsj8=,iv:0RWcJ2ot06za6qJZ5eOOix5loeQluilaaNXDJlDdymU=,tag:jJ+nqRYqb45AnkXSnEpvkw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
