prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:OZthje3dnOAwIszHcH1EpRxXZYT1jd+Sp8aEWZgsMxCdEVSuyS3mTFq6F4+pv0kUx47fvNTQqzSfFZ+HfwqRP2fJafry5rKY8PJ/v1L+UeEtMRH92vshczMozutJuz9hptY24KjuSAU11RNMSNllSJ4OeAcs9Pdbz2yDQL8vHaQL9iYcI7tQ/zFVf7jX3uBC8I5Z2tFjqAqgMtY4,iv:osoSD9IBgLT/8SzowrJRBBNAblQD/29dz8mtTIcqU+8=,tag:+hg0iLx5uq22aevNTtg7GA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:TtZuxq1Mm9sUfX0Ssjyx8C+5eIs1uivAOaYaOAl3YDEy3NbJXme/Vhvq8gktRAwa8x6YIRpf81eYnpUVBXWu0w==,iv:meHsA16I9ilsiAnawC4tcQa2XmbDbNBsdaxG2em+kyg=,tag:8YU0kJHu/UciBengp6+y4w==,type:str]
    password: ENC[AES256_GCM,data:PCauic+eoQunYrFUn1qAC2jTvly51XyJQSsVF6d69mK38f6Hpsj+cEPl4zBce5zaiSlviGTtDBrYKW4+uqtweg==,iv:D4phwbnZqSBrEr7wTxJW9XbH4C6oXtbW4s2tSQIWV0w=,tag:riIeRXVv0fTn5/sDEbMO0w==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:N6KKbM/QuEdJ8Z6Uy+j+VLtJJxw=,iv:oPhcp1eHiIW2HlV3iUNXzxqaVmkDa0Uln67IpJNzTHU=,tag:r02tfy28txjJuCO5k5bvBQ==,type:str]
      client_secret: ENC[AES256_GCM,data:pZjaLO48SblanrMS3eJOjM2xpIzgWAJW9Lgjfn4LVNBBAl9JoPoguQ==,iv:XwmBX3YCBPeMMPsgavFRM5kCSnxEIrJt47rxNOxM9W0=,tag:mPVBdSAUg6jwTJ3cjM0dTw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:DVznsLqFvQIJms/ZtA==,iv:Bq5qet9sR3/GoiIYEsLGLMLZ/KtpNY+aD5QwfOrPfmc=,tag:16ng+BnayebuS6n4+ciEAg==,type:str]
      value: ENC[AES256_GCM,data:qo8BjyfexAutK36Q5iwT8i0sK2DIs8j71pKLTNpDbaN3V10cI+tNC+C0P98cY/BCukuXHCIYnZYfNOTejA9OiYfclLuoJt4dyZtsAuMG4uSq/pCNhbUmvDGM5kH7VI8p99wnc3y6N6foEDklKbXVE/DjLL1jJ7g5pETmHzf3MFkNibs3on7cS5NY3lG087gQLosfMdNRpUc04S1jZ9nHqmX2TYGbCDkIOis47LnS/fFvmA==,iv:IVSSHkeFpF1tsA5uV6qVjntApz/1Cnv3yJbtaNKJsdI=,tag:kcq9s4qPt260JFeZRo1Nag==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:YnF5ALgeirOvWzS1s3HdQOUgv5U7nehdZVaBY5S5ioTVfL1McGEllGMkaOPankcf2LYaJahgLkqc9n1FRE5VoA==,iv:vfrFxRRrffZsrR9fUmNWotHkvGy+vjr7eZJL0VNBYmE=,tag:0vhmc2F2SeNLVMnwUI+qrQ==,type:str]
        password: ENC[AES256_GCM,data:goiHYBHYEyBea6dEcbMVB7RXbnsIqJf7CqDOTilmfOA7rUZfzyLXWQPQjFa90USPs+JmJXD009zJW7INFzgEww==,iv:XqfgaXTXFaWCVLa8l/m+J7wdOj8qYFKsu2O0Vdi/yvE=,tag:wH7renq8cGaLbGeNR8Fk1A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        weegoh1uewojiJ1ei6ahxooh7iz8Paegaivohsh9tai7uu0che8wo9aiPiZ0BiMi: ENC[AES256_GCM,data:jvYr8VfxVhB6AvzqUSuOmy2jqCabP/6gnBgOrVu1QsQBe0FtoRgchcSGgWAvkZeYOFT9XVlJUBl27sQf,iv:vDDegt2TDChfNY5P6N7GfUSmbIpSPOhhxkwRsBC3k2I=,tag:FR2kXJSfbKwZM7Egn80rWw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:50Z'
    enc: CiUA4OM7eAkryAD0vhlUE+DJYRDl5c/BzARUAC+9C7fZVNqNSg0uEkkAPHlbmZczo1zfhVBNMWqI2qSkjeUNpy95RXxTNzqOA34NKfvyGiIBwiUymcNKzJTAvkKasVY6b/DwkienKypSoxa/gRbST3Ti
  lastmodified: '2026-04-16T19:32:50Z'
  mac: ENC[AES256_GCM,data:+hmT2G7LuvNHjr85y3dIC1Fqy026MvNW7JFLTKYojxL9aYecPwwAmCcYmWfwNR0CpnByTgs6wZNpRcoRgQQAKo3yBkUBIQ07etB4NxeO92K8zx+uKqctdKD/0U6iWcj29SD8UAItzEajKdNWEMtwGvzSpbMMoqKPsbovgHZBi2c=,iv:mLhjmYJPL1V8wrjrGQ9Ql0idAmj2OvyZG9bgpw9PM1w=,tag:5clslUVZtxYuvrlXVMHquw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
