basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:uVZv2H2CloGvG8uYHyZLQOCvlrs=,iv:yGwZ9EDY2fNbZCayKFrKQAOSR3EwcVF02TQvvI9j9Pc=,tag:zT/z2H+Ua392vwT+ESAYoA==,type:str]
          client_secret: ENC[AES256_GCM,data:66uPXfbrBzVlk6vc2hDhn1+zydmEeSNpc77gH1yrKmcxj1WnJ4Wxyg==,iv:rObky/zC+qrVxxYpceobWSox3kG6PdQcWox9opUiMT8=,tag:S58X6Biyq6bOJZdIN23UCw==,type:str]
      services:
        usage-quota:
          environment:
            JUPYTERHUB_USAGE_QUOTAS_SESSION_SECRET_KEY: ENC[AES256_GCM,data:8B7CazROB/oLEq+QkxlruNevXF30UFSgyb9IngG1KF1fT1QORj4aP177yCGjFT96peDPiwWOuWys6+CWvj6dMw==,iv:Hp9tCn7YH257SubetpM6SrFp8NHCU+N1ErVxgxWZw64=,tag:pSRTB5kJEXBTyeO+rdn6OA==,type:str]
            JUPYTERHUB_USAGE_QUOTAS_PROMETHEUS_USERNAME: ENC[AES256_GCM,data:6StSea1CENzRHYP97sYdaR91iRWJLfT1siigK/GUj3VPD1H9C51wnVcwd2vZsNf9TUBpVs9X/WlsmaWH9crBDQ==,iv:UBOymV2g/OO4dUKi2mqHcMoHneMiQegRxoK+8bo+9Tk=,tag:3fJqVIJlESCrr5FBn4SsHw==,type:str]
            JUPYTERHUB_USAGE_QUOTAS_PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:TloJ9S3qgm0xFAIs+nZ48/ap4HQ/ltzR85BqgNdoxrciZGieCRCcbRRojigXIG1TorwKz3UjMpARlwdjl3eJ0Q==,iv:AZHu/vXSNHDS2OipVjNvQ5hZoTmovd7aHyCovS04TeQ=,tag:YRIEGCFKoZaUmumrvb3BXw==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-04-23T10:26:42Z"
      enc: CiUA4OM7eBMtdeVmSe8dX8fZyWpKuEQ0SBlJbbNIc5ix/P/PYR5/EkkAPHlbmZ4kIyJwmILorg1iJwmv1FZSCGwQGXQweldertAIp5xmPZyLqzCUKn0sbKtGU6MIEjhOYfYSFABNJCKqxHUJ+OB3wA+S
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-04-23T10:26:43Z"
  mac: ENC[AES256_GCM,data:Iy6eLlZYgpO4M/FauyCW8EHrJ3ILNCO6UjXUD7cnm/r07R9W+V39Dv8FlpMYDN1U+FGW/OcyQuNVD9gDpzVGi1Thqqx4KVxd+vpIuK0HzRLm8PQKe6+1aTQC11uSNxyGC5W0mgdcSitCa+LWyZfhHtA1fGUirBcaqmpiDloBtog=,iv:AgTIBQxx+TR3m8P7B8omo9ShAzwDmRNTR+5NtdxQqVc=,tag:Y2p/C5NIKTGiSMConfOH1Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
