basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:aRm3zmd+jye27BXbpUBZzmJa0Q0=,iv:TrAoXo+0LGMg0+T6QGO22nYO7RrhjHUzSKMqEX5tjUg=,tag:4ue3k6h/ZnTjyDwzXPxRMw==,type:str]
          client_secret: ENC[AES256_GCM,data:Hv76c9oyDkEp5H51X3kVjq6sGPiGV8xHhCnbonS1UnVrPWN20IRd+Q==,iv:EuYDQhu77/I+xil+srb2RLX12Z/lK3fz1gbQA7fns4k=,tag:YYqiahmoZyBcvtsOhVRI9Q==,type:str]
      services:
        usage-quota:
          environment:
            JUPYTERHUB_USAGE_QUOTAS_SESSION_SECRET_KEY: ENC[AES256_GCM,data:cF3Zyz5tmVn0gLmJ/tVQeA5++2gxetMBEKOhSoQMFiLbTZhaid0BgmfNo0nZtcDWdnso/SCqM4j3DW+cr+ZLAw==,iv:O6vJgNgYZDj/mYwIWz9j576g7sQgitxPYSzv7k+cQW4=,tag:LTpt7ITrH6ymsLox94EAtg==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2026-04-16T06:53:49Z"
      enc: CiUA4OM7eN32H1AebM3ff8QBDateAcJR7mVxfh1ZqRiq30U7OYsGEkkAPHlbme3rW651l4dv7VgnFVspURZjh/xd6KmunvywG77Zw8g/tSO21AHPrhfez4MHSW//qrlmZGi2pKomEaLOM3zFfv28gObQ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-04-16T06:53:50Z"
  mac: ENC[AES256_GCM,data:4I2az84vIMqzqd+Qei4kRSMb8dAXikFD7dIjgzKHe0tKQJvABcdn0h1EijppZtnKweclHD1WDDamSkE6xKwMuy78otv7KzoG68mQDcJFHWDOAxt8Gj5Mvo+LFm5GZpVNFNK1rh8HSKTn5bAGoU/cR0yNi7MgUVisZFIkpjifn9A=,iv:Yw5CCBQ5g2BqbC0wm19L6NpAVkINYC8N18dcTYEpeuw=,tag:5A7CRu0SAk1sEfSaYo7rsQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
