prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:KSGyytjxI0IyhD4dnCPtmdTxLluO3p0w1gpCuiRllEkqRf4tpizQ4FDy9u5R4n3B8gexE1i+jy4ikmbva6dbYOvC0fB8x5GtM5LpMuk7cGkwxgymEr8jQK/7fQJQ+JHWo/T1Xb9FQrwKeu+P7Z2cMpNmQTZMU5/3vm3X9ijFsnlw50wQbFlv3gdKv9JyNX5EF9j50BZm2OSn665q,iv:d7ZVabO2t3BG7Adc/CiqCcfbkQbnzD09gVav2VpPbbQ=,tag:422tfk8xLBQ6AVMlZNtx1A==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:k7c9G74jWSQdgCXyWSrW76leTak1oIjhTri4m5Kcpv0ANvJ1H/elHfVE+GdeiS/Kq9VtWf8p2wnv35j0vM3raA==,iv:R4jSthJsEYRNjZQVOhA5UTr2IqM/RjxJeLGTUgBx+/o=,tag:A0bXv+kBPL8XLK/e9G7a6Q==,type:str]
    password: ENC[AES256_GCM,data:HtKAx5a6iw6f1s/zPa0otaT8NTWXloJqcOV1hQQswNT1dr54jZOHDVvETZRSPf6n/JIr8rCyWyPIZepbXzVfWQ==,iv:NGOxh1egJueGKwgHj+yAL20BFYgS1sRR4T5kbOn3zM4=,tag:Xud5eVBnC7ZzcpgqcZDgCg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Gg==,iv:gEXAEqfpgz+VCiaHJaCJRPFDrp8C94UhmHJWJm+m+os=,tag:zsLYcGkrtpI3J9uRuiOqFQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:ZWeoA7IlFmLuFQ==,iv:n1vQALNy3vlJ4YPwWsMI4KsMEJCX8+C07VGL0skt/0Q=,tag:YEsaRCvI0mVMpJGlRoXBcg==,type:str]
        orgId: ENC[AES256_GCM,data:eA==,iv:aleGV2DbxtFAHCoAl8OYKj+Ruj/HoP1+jtRMI2v/9OU=,tag:76n8QKLGHqQxmMnNpxTCeA==,type:int]
        type: ENC[AES256_GCM,data:/MBnm91ttfq9ag==,iv:h9fxi1gn4l15VEJM22Lh8J+UDuLjb80ZYjJX9wdisAw=,tag:7Eu9ldpMCIMlXmfkSD8lcg==,type:str]
        url: ENC[AES256_GCM,data:GeIc2qeapGhrPkavFW/DIm5vWLd6VKkHR/ZojD/3fRc=,iv:bPo3c0KO3YgauhZ+R8PLFuFnAUfZNSZX56xzsUv8k+w=,tag:n5YQNwXYjZPx7/x2MFinKA==,type:str]
        access: ENC[AES256_GCM,data:onNDNrs=,iv:G0ePSpz3w75tYaoZjAvAkChork0Rk6teTqHCIG61hGU=,tag:UnxDV7+BDAq4jZ3Ay/WFXw==,type:str]
        isDefault: ENC[AES256_GCM,data:9s9ArkA=,iv:82mprEgrpD8dSzETR4peSLCx8P9K5D8u2KX0nxoClC8=,tag:lj7VRh2BXEC/3XBELotqYQ==,type:bool]
        editable: ENC[AES256_GCM,data:LaC+uKs=,iv:J9fNahzmj671A1P8oC/k5SeDkzkkAp+eVDke7V2SKRA=,tag:KFcRyYHhetsZJnMweHcfpg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:uaSEBg==,iv:CNU+UCL4lRcCTfZm9DpSaDeWv5XZXmewzZSz5ZMur9U=,tag:Fj/SfTdGygc94HzCRjQYMg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:ongBkJDizp5cMmj5Flv7LE303I3BdtQ8oZNdmTxE1fEaLqCbPmpwkD8QE0CyQYYGIQSchYm9WL4rQNjXaEdvkA==,iv:UUgteZS0bJkTvGVQAlA3NrpPjTU9xmxTCeT6xcHlzZ4=,tag:my1/hcNa9SZaowl4bYS7Og==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:BTh+j21Jv6TrH5P3wHhIWaAX5T3a25Q3A5ESwBsQuoFRsvJbGfKjPW56yg/1rt+g+JjQ2dCOfS+LVn+qM4KgSQ==,iv:7+yL6tdq8E7Hw52lKur+i80nuwUSrhTlnFJK55jaPLA=,tag:uFOBod5UL0In2oTIr3FB1Q==,type:str]
      - name: ENC[AES256_GCM,data:JxnQuPFeFHIhH9br0dAyjuqMQKIevct5NJino27TWw==,iv:+sJU1uAMY/KWXPAHDtSgAuD0DZokqRqCUle7Lm9FcsE=,tag:eJaNT0+YhNIOlCVRFhHtqQ==,type:str]
        type: ENC[AES256_GCM,data:T5LgmvfxkgWdQxYLyh/EnU6yGjnFPlwTyB/Aw9gBlg==,iv:mhy4YI6rbhDztKhYOZSY//yPv3d7jPL/YeRjLlOgQN0=,tag:Z0R8YjRyLV6hyp6sh3Xlqw==,type:str]
        isDefault: ENC[AES256_GCM,data:HyERLCg=,iv:rc/xxqY+pNI9APKdyb/uqmIHYEGAHk+cxmYC+zI6QDk=,tag:qvj+0/rngTYl+atFBQ+oWw==,type:bool]
        editable: ENC[AES256_GCM,data:qE3P+A==,iv:n9QM+dK6OJYF4nSVFZao+q3UElyCqgn6cTN6qwS1J38=,tag:0axrH4PBp/bYYusoVZi9ig==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:pBJo+oinCM2bcSHKCg==,iv:xuZf4psUG8NeXjySKuR36Uy7QAPOtizJ3guD9RFUQOU=,tag:QiYgNzGbx7wOul1Zs5ivWg==,type:str]
      value: ENC[AES256_GCM,data:Ni3KN7zvF9yjLEYB49G6BwXuBLrAWVQhxbZx99GGpHA5uXB4s35vqu1d0j1G+HkMBA1Bmx6zWJyNi7H5WbQN7JXYSZdRCopKtyfiZyFin2fjOyjvpMmn6Tli4UBmcF70+qylYzFphdEsQWGyMhIRLQx1oBxEFHO05N0V+EzDHk8ZzQifVlApKHs1PqwxtYD/gYQu3YOw7TVfSkgn5996efQooDlrd64CW/iMvPTzMwxtwA==,iv:uTSPZO1cEwc1BP5HBPRQw3uZ2IETCUNjgmITovjj/iY=,tag:QZLrh7LawYWhSWPaTWtKmQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:hsw01mFcd+vPjROrJI30+rFVT/ku8TBgsdSO8tnmgnrAtrDaboJUVln4OKIhed6IcPUpwODkSrEyR5lM3Rvv+Q==,iv:9xplnzDBzXAa2qqRmLAdI3RiUz2RfY95AGT6h6youso=,tag:lqlUZjX/BB2RoMqrGdf2jA==,type:str]
        password: ENC[AES256_GCM,data:8/o5ilnGDk58tD2bIgs1edtqhtRjKzVx77d55FcQEgpUidYV+iegEytSVNy9KkzNjuzdclYgK6MVm8zIZJDEEQ==,iv:2XCnwQH9w/GtFuqei1djzRmyV+wlJENoPwqYlRmuwkA=,tag:6nDMUqMGydISZNF0EHjz1w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        weegoh1uewojiJ1ei6ahxooh7iz8Paegaivohsh9tai7uu0che8wo9aiPiZ0BiMi: ENC[AES256_GCM,data:VWjQOAmNyMGinaOOmyqwtlppj5HllvyvwJDIJt+NIpYLn4D9mz54PeMpMKegryKKK1dPjc+girx89Pgz,iv:DI5dV+1VNgty4vsY1w54Za7Rmew6Uf7FOQ7RI7OzlgQ=,tag:8bS7KQUkFcYPnnFwJX9Hxg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:15Z'
    enc: CiUA4OM7eOs7uJGvCB/9qMKNYFf2CbK84/Z4NJaIAN4qqmKaajsXEkkAPHlbmftJpHAvBiW7PH1U6YNPpkEAUNYVo0IJGgty7eW5iBnr7n2BL1kUw5wcN7zE/S33+ERN2ZhvaKckI/x8VoM3TCDVeZhS
  lastmodified: '2026-04-17T08:24:16Z'
  mac: ENC[AES256_GCM,data:B5GZC4vOl5+2/alWCV8N+fLcWwi8iRwVSx+HtW67ETlgJ7ZKpIsbXvsSbdwm6KHMM1caC2kmpdHJllPbuwayxgo7hTB3x9e9NEjFDIzZUF8zyJhNtKBsE5xlyNHTtsD0Kqaulb0zgfHczraBWvUkyjBIC/+4jwKRCMUYvZPL7MY=,iv:eNZwZf35LSrn+rizzWUwzVIMmMKujhV0fKWdHiToCU4=,tag:hMvvTsyNDSqm/QSqSDFhMg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
