basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:356pubL0yPKU7+621CPTwtCKSI0=,iv:zYlU12dvHgaRNjzJcXddMKPXsSxoBzI1DOGXPcay8LU=,tag:krRqRPorImnLhD+KqYMQNw==,type:str]
          client_secret: ENC[AES256_GCM,data:CIvoxBk7pLqXTu4toLmtOubPFl4IGjEQTj/yyyvzXuuKwE8iZILnog==,iv:WwdCqcglze0biAcwM4tbXGh7NyUD6wDuh9Y44VZRpxw=,tag:Il2OniVdiFevcpaQW5xbgQ==,type:str]
        UsageConfig:
          prometheus_auth:
            username: ENC[AES256_GCM,data:a2d+xWlOMgXzWmQsFLLSd4K3ROirf0BxjHqf34ZEbwTPadUo3kLvHfJ4mmB00ckLQcfeNZZZs/LcBAK+SuL+Iw==,iv:lUU2tNFE/ueSKbVlQZ3KHlJPFpCmyChoGOiMM6X3l3k=,tag:sX7Y9QwADYcQXUdOaqwrgA==,type:str]
            password: ENC[AES256_GCM,data:BUdEnGVfxJVMA3PYsDnIVfZbbfGequXD2thfTqR4Z7mMndjI/EWMB2tPZTNNBgibsjiVhKTM+WQ0uPvP3L9MYA==,iv:kutibzqK+h0fLNlfKnpTTq44eo02dPleu+C+JcRtxhg=,tag:m+//x797wluhugPY3wC0Dg==,type:str]
      services:
        usage-quota:
          environment:
            JUPYTERHUB_USAGE_QUOTAS_SESSION_SECRET_KEY: ENC[AES256_GCM,data:23FkTxsp5buQ0Ib2xrYWAwnBzyFFDx8mcTr/nqjo/z+5DZGDruZeAmwvHtlPOrPucHqk1Z8WU0gFWBlewTj02Q==,iv:4cuBxMs47SsCwBgfmA0UUi7R/POH7PiPUnxeXkmM4dM=,tag:O/8G0aAEvvbGjHBkJFIXxw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-23T08:24:48Z'
    enc: CiUA4OM7eJtNGwfGpmPzbPkMLaHxMVJBQmfCZQLJm8/qFd0QgbagEkkAPHlbmdKTfDIetYUMUe1OdhUyt6C6VGJi8uoqXqt2OtiW9tYSUai/Z5LX7517wCQN8XfJKPIEZkXYGgm7i5Kj9EXrwa+Gonhf
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-04-23T08:24:49Z'
  mac: ENC[AES256_GCM,data:fHSv4yC1fTVtza8secLJnOGeoXyUpPtw9lL+yDyiu9zLoTOAckRHy/EnvqcYYsqYP1J8eu2txSuHuAfwlMhB/ACWnyzioZvpz4HGAcQYnqNybdp/swVDgGlDGhI8+6LsmvuwrMOxIz+H1WM0XqTbysULdO1gpREhaD5rcULouFU=,iv:6q69zIREnu4tM5YUS/ryT9r4zWhkISm0NRfeLG5ewtg=,tag:lUjfSzoWRBqwFiVqL5dweQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
