prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:R7L3RiIfeQz9mjyHRwct6RSgAF1yGX9MHo4udfLFX+MKN+x/Zm0PpH7h7fuEIw3XacXTZ+AFltg/zHwxNX7jm1soisduqsJFzu4kwTo9g7y9ECrb0ua1U7AHNR0HHqsl57C0m5aBKhiFcFYI/VvX7wK8Z82buf/5GFhDZI9UDlXagxgrvTxvsoH46eq1ggS7ZuIRd/GZ3Vv77F0g,iv:11KN69a7GV3yQiVyS8ftWarKQ15mZvOB48qqGgzSoW0=,tag:sDeKnO2BfXFxVmG0eD4kZg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Tiza8IpcSmM2/BtWwjv/joijpZgEsD57QmozEskbJVrrL0x2ZRq2Z54pQ8/BRbmFGU32f6nM+cF6axX9Q55V4w==,iv:O2FIjRTbQKzcPUsF22ydTWbkn5ex6rhDk8H7keWSHYM=,tag:pfOG2NapYFi3t4jylDbuYw==,type:str]
    password: ENC[AES256_GCM,data:CM/aTOMniPUfURkeFpTcfu/E4eIJXjVLLckiBZATVJPE5CL8pPGYM7/wuDcU+H2dLlz4dtKA+JaG+BLfqxuB+w==,iv:ntP3ht3Dkw1ni50n3l+xIoAaKRFiOOvgUomNd4ZKsaQ=,tag:zr7Hg7emyo3lVyMXLiHT5g==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:wA==,iv:wsXZoo1Cpn341jEopJy89wAcbxlIHT1bj3JKHTMf0Po=,tag:7Ci/NSJhSnSJQ7ZDmDnpeQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:UvK9Uo8sbEbcmw==,iv:DbF/N2Ft+t75swxFx5Xj1AYAvZos/NwRf6Q9Srxyubc=,tag:SIdBNBHuWPRUYYJXs2/toA==,type:str]
        orgId: ENC[AES256_GCM,data:yQ==,iv:F2+ALR8/uq4kmpvrCf8UqgibpFSCOatIAqC+MjBTiv8=,tag:PVMe/II/EQQIJP5dPGRhUg==,type:int]
        type: ENC[AES256_GCM,data:Clik7UerQI0UGA==,iv:pvfE3n2SlmUUyZXY7rBxEcgavZo2ktH6QJfrXY+roEI=,tag:novCIZ+AzxcaPcQAbo3vmA==,type:str]
        url: ENC[AES256_GCM,data:zJeEWKi2myOGqjawfUQTGPHyd4cR5fKr0giqT0wuEo0=,iv:9vgDwwHHF+9WoDc7tGPaYZdL8QoUZsU/KhzMPok6GOg=,tag:pZbx7vUS/MQfwj5aFbCmsg==,type:str]
        access: ENC[AES256_GCM,data:XC4n/ZM=,iv:rJi3gVup5rDhm8nwSH1SkBlc/mNO8eOgmEGx0zpTBbE=,tag:rPgIVeynDB8cuc7iM2Tz+g==,type:str]
        isDefault: ENC[AES256_GCM,data:x9nGRzg=,iv:VrQO5LjH5I2rup6547yPcWoLo8cNQW9hbW/hMGuLrdE=,tag:M/ps2BFo25EvQikmwfMqBQ==,type:bool]
        editable: ENC[AES256_GCM,data:9HR9Zyk=,iv:RW6yQIi0PtXAh7STuE6uCbe+8WamaMciKmviFqpY+ww=,tag:gcnaTuusmV2ucn6FRqMBwg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:4O9Wug==,iv:j7s90CBCxjW/nscg8oyk4MqZL83ky01MsF2iiSG04f8=,tag:eWZQE3eNz41N5CRWugzZHQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:40LrYn/IpBmS665lFnNfzrgPfolBBr/oHscxITQbOWPEdrGXLA868EHjRgNFP1yjN2xzLIF/vr2kA9ynVUMZEQ==,iv:6aQ57pr/U84KVP3inyozRAvvPOt2AY9mdTXJ2upUTs4=,tag:aN0JddLWg98M19JCa3drOA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:EUyYci9gLgJ6mwnaGOzNt0ADjHNvVgDcKMOFwjYVQBiZLA/Cy7qio0H65HUTKxpqcqlAPCDcq0YmVjzcARsfKQ==,iv:i1gYfZuizI7Y2A3OUGg6i/uvU5nVvjl1k5Y7NcikVfQ=,tag:d7WzCIqjYNP2+2QDOvNpWw==,type:str]
      - name: ENC[AES256_GCM,data:YJVRE1QpR4QxgoApiB0h2tczAwQubSuMQtACnOs4PA==,iv:1o8QBSgI0gmsGVfc4IxO40rrNsThRQY3xai7Y2+zxX0=,tag:rceiXJUOZquBJZit05rAeA==,type:str]
        type: ENC[AES256_GCM,data:Kppd4E/bO505vKELVsuxlu6mPh7SipQPtIbpecNxQw==,iv:jHxvjVdKPWdaDdQ5c+VAntbBV+fzhlZZVMfbOhLyiok=,tag:+TZpmT5hlbGneQg5W/D8Aw==,type:str]
        isDefault: ENC[AES256_GCM,data:ojtr9mo=,iv:LSjQGcqhIQ+5AXqTRrcewOZENGG8rPpbTW+OXUCZwZk=,tag:E1cT4/WI0X3z7ES9wdqEnQ==,type:bool]
        editable: ENC[AES256_GCM,data:USHj2w==,iv:odxLT0tiUKeP9uC5RkXhVa6SpExnar/IxZqxZ5rOaHA=,tag:eQl5vamNYiyn7bgFt6tnxQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:WSQIbRSQXnMAYSEdBg==,iv:3225h+vuXafz3Fz5CDoy+UMp2/Krgb8N9efoPxvbA/E=,tag:NaMbTyKKI9iVPz9EEfCMdw==,type:str]
      value: ENC[AES256_GCM,data:ewJ7yYb33pSr02tXQT/6f55Shcjo65fVcPIDTdry3831RZrTLIbLsOjWHQa5QZ1c04TYD5WmR3azmAOMeNLGnU70s6BLCdkpkqVQGX9TPiY+HVw+L1+Dol6r2DVpttKkPdib/1Z0Qzs+wuYmX9qQKrv7riLe40gunnW2LqKH+eruwpVpZ+I7wsU8nMMaMm6Vtqi67m0exQkZuzCPbZ/bYbd0MFhtfLK0dt6EiGHvR/AMNw==,iv:7Ie3U85GCiSQT9y0YEBV4Rrq39QC/yytN34RSphXmuM=,tag:pp9LS0lzheSryirjF8lKvg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:8QwUGRKuaMrNTx1Hvyq0c6nX+c3IbLDLIXcq4gP8UpKo7oLJCCgZ+15xicIxjha1vxluUDr5ELJ3YRYcUbAjGA==,iv:3wqx8wfJstMVb4sO6dtjAaXTrhOZhXr7164OMSuXHFI=,tag:Cku5sV2066jJLEJUf078Tw==,type:str]
        password: ENC[AES256_GCM,data:14Zpir+NBIVHaCyIGxmsK5K5euqeKMc+K8iktAasCeEDuuj5xFo1lW1klNl/IviEo+sWrp9/8Sz69n5FYAAIQg==,iv:uy3ebEG7n5YWs1Yc0SrfE9G4pRabWFU4tIQYtvaEl4A=,tag:NmxNjp/hlneO9Bi3R8viVA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        zaepio2aingap5eehohneiLoo8ooHaht8kiezieTh2oneiRaitovoLeenemah6ti: ENC[AES256_GCM,data:AgWbQ7KF9IHX9HrwcHK+Th5LYpKsKUOz4D/QaKO2+8hcBPPVpa7RZHXvgTz4pHSPyDYh5GXnhaDSFLxF,iv:vzgmqq0u+u3DyPOk8oBeu3eqUoz5os5zMgP2BEwG7j4=,tag:oIsn09nSdZre8frNoFH3zw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:12Z'
    enc: CiUA4OM7eBSTlbr3i2LCgsJv2vDptdcIVWdVFaGwVhGMP0RHd/7UEkkAPHlbmTzNbA9SJMno0FF2TmUJ50mzjLzipzwpZBfZ8+41C7ADhq5r8bCASdnmfq8DralTz9LtsNfvIROUg2P7DpnDiXaklFCM
  lastmodified: '2026-04-17T08:25:12Z'
  mac: ENC[AES256_GCM,data:Pn5mcQaJhwfEwRyQv3obOP3uu8M8B1VcuBgb9wdnOu0aSX6XYTyXCSAIZ/ek/VhQCm1sQi2RM+vbf3/e15IT9u+XgjhCeyOdyypjrY6VNyAY3JAyWz1dYhkKTP0X8AGkp+qarsP5GXRYjImbpx2DihketFAtK3UNFVJ4dPn0BLA=,iv:KF4z/jDWA6vBiJkWmQg1bkbMi2pL6xzOY/NmLMLh1qM=,tag:6edhsEsneO24Igh9pZPExQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
