prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:mxVIl/3qBMPj6wEsjXWC6zTwSSB49M6XzEujo5qTCNEEdAwPFUBDn56hIpdIVYUv1DwfWJ3OHP/wEFRZmVPEc/tI+TZtrrAUh2txD9AoMHa8ddPqsISinDexGUUPq55uNey242sjrsq1jBpWfBrlDY5LsMt5wD6IlnJVJo06JCvcmm21Lz7rXioUWdbenfDbbc4LPOyiLACK4enw,iv:gTwEu2xKjIZOTVDupe1711BxldsYo3hkv8X+G8ZvFSk=,tag:1rtD0RSONphfjTFh8wdz8w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:ylJd9vG2XpQOGVJ0Xo9w8mZxBsLemEu7oO7hCmyaGXWcKyvLEVheLZwxi9pySLT8m5ckjE/jtDpeXchSiphAiA==,iv:d7ihgVuZkXbZiULF4cl1w+zlIcd/odRzFqR5TpQLN7U=,tag:ri6VSXXOQXsLGdTWKFOm3w==,type:str]
    password: ENC[AES256_GCM,data:wUgkO5MJWkhDRffbBYGe9zAq3BXrj2iC2NubfPEOuchku5UEGfPOcMPHwiKPgJsZwfs/A73IvCbbxUXYid+x+g==,iv:P4S19KDjMcYE+hfPsnBxheXrf4E37wHccpn/hfm8TYU=,tag:hTZkJJObriQ/dYI7Cmh3VA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:lL+Qwik7OTFs8xZRezh7g276Jf8=,iv:eWC0tBsPttnX0/Ob3EHsofrEscN6q/KD6zrpAaA1SuA=,tag:RxTMPnt28qYLBAg4Q01kAg==,type:str]
      client_secret: ENC[AES256_GCM,data:nrCsiVZssbI9PmKnarKzC3Qp9SWAHfy+hOiLBnpvHvhS0YkJnEfy+w==,iv:kw5IHgN8ZhoYAwaDguwpzS7wl2ldMdFtKU8ULAFHnzU=,tag:cLxaVcbTJ6xakPjgZvYCHw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:I/uAyQC4CqYkziPQxg==,iv:r2CUTunzvmEDFhTcl4myDrLwQ825epMOJWSFijThhyQ=,tag:W8ENhQKsBog0teRWPbUGTQ==,type:str]
      value: ENC[AES256_GCM,data:6r9TSbY781rFDLgVp/lZmj3L/lEnkYYO4s5sZ4k9iq8KIP9eWsbUZdGBO0UOdmstzq4eqMSZsvPRCgD8qowvZF9NTsnV/oiFeVA6bPCfLpqybE8rCkGgeAzdqejsUNdvu7Lu51yFyjDOYSnrMjhJiyYF0cC60i8F3yM5Kavoac7VlYvMlolqw6VcGVeOg/vc9u9sAfH0CbObSJD/nqaJ1uAM9rv2GpUEG5lnPfJE+QMAbA==,iv:j0vSkXEcPnYn0QU0qWkQe0dmVVGTIrj10O7HKwGSqZ8=,tag:NBsA7XEtdbHixlL455DqLA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:jR1knOmj1c/8FzYDEPVThrg1XrFeZf/MB1IGMUXE4OWw4x1BJ3NRi2a+EL63KFY/afO5W+EAtT+0PXANUjTzgg==,iv:HM6V3JM02EcAykKA3uCoatKfDTkxsBlqHk3rJC2Pnlo=,tag:OyAsDBHezpPln/TpVYD+zQ==,type:str]
        password: ENC[AES256_GCM,data:fSstQYpAof0Bd3YX9G7oGK6+L+jg6LcA04XsL3Eoz8de417up7Uh9S3WWJ2Ngs2Yuq529s2apXQp7eddEO5MJg==,iv:9QJrtQvZ2bhiNopOGQVfnvx6D6/H7m676UeiekJmKmY=,tag:VeVO/JkPaOE9+afH9cb/JQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        zaepio2aingap5eehohneiLoo8ooHaht8kiezieTh2oneiRaitovoLeenemah6ti: ENC[AES256_GCM,data:Wf3gWE37zXh6hp3TDbHkzeakkHrgmeXKBeYVGvXIzUBgtY+tMyTQgftwEoNjOU1X98ygkjLgNXPGxAN5,iv:TPk77g4dkj2FcYP8Gqq6O8VRGFqsu61VbSoI/5k7J5U=,tag:1SHZnbWNIuzhLmS5tqr+nQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:48Z'
    enc: CiUA4OM7eOZkPdvPfvuX7FNInHLH6yG4S9Q/6Pe24yJbsT40K3hHEkkAPHlbmXrarZ6XGRfuiouBUyh3HPlGavdMoYg5nSE+xOzG87jxsI0xhtNLibEAiC0dUXzyEo0YmqoOzJea2TW8OdLE8W+kk9GT
  lastmodified: '2026-04-16T19:33:49Z'
  mac: ENC[AES256_GCM,data:+LJBRtYgA7zaNJij5BknkKzAPz9e46wl3Qmaj+eYKxg/kD9f9ahvgQuHW8bavWaP68KP2Kk7ylWGeDtWC0BYRrpDU98kXmc7X0mBwIIHU2BqB7867zJ6SyJlcSI3KiMvAqo9InzQKbLB/FRRgGXAa83Yfd96Q9Ji+zZarwbFnZ4=,iv:PK8XoH0WaQhY9lUUEG8wks1vszo1S+jXMFhJyNu8D2A=,tag:OTpY7eUtHaDqQGfm19GOEQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
