prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:dsF5VeQpCGuWiZ3pHWn7BIkkA0w85TXsBEWtirVX2Vs2qDxikICZugpDU4hOqnCWgsR3PAJOqloz7BCdbvUzIeRMHtlxJMt36V0cD723s45awAmuIX3Wvbqh04UmexyXVkUWYindKmC4XCMJ/15iIZeuCXwdp9as7rNyuELg8RnGS8RvgbzscsbyOnkiA3iwqRfLClY9Z/UzRRlb,iv:KJ6Im1iuvZ1GKfdcvrcT5+hFz/G38nUFEAYh9UAaNkk=,tag:MxLkrJqxgnHSjVwQbGVhrA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:HDYwiZ4qcEKY3m6LGUlsIJTX+ZBpce3wyF5DAHL97YMpudyYgrcdeInBQEEVA9/afZ0Bw5krDuEr9N44Xx9+0w==,iv:S3JyJOXfyfwoCKGT2LmwHVsFYxF8KYC+GfzXXjrPbbk=,tag:vdeAazfcQTQbNGuQrFLqDQ==,type:str]
    password: ENC[AES256_GCM,data:9wm5H1zpcaapaGzOtALp9MhZ4QlmFAoRH7n8qER3BUhJ+cfkFSCzLsdpNeJSYjCRImaYSEAVV6G9kg64iTl3ag==,iv:iXKsUOC4o+6Y8b27jdctgU0wJGVm0zltJJT2bCMtl9c=,tag:AP+VeAEnFMnMjG+cMNHX1w==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:QxPK3lOURuiHVFYIZw==,iv:tKdI37sy5RmawhFjkJYqQC5tV0T+r6I1VHbG9GJjAJQ=,tag:zlnRDQmygAuLvgUXMHdoxA==,type:str]
      value: ENC[AES256_GCM,data:8n9ycRoZC3pTmml93WmlNAsqeJ3dp6hZuN1CAcejgQSUST/cbd3tLT8xQ+0CHls2RZq5sli84y6JpFg/NsIPKOafLUgNkMOCc4vrelk4CqxaZ1Rnr97VUHiNjP2NuYMom8V4i9YaoaUnjpyQ0ePHPzxzbbegbl5TsQMOO4ESbcAHR8Ehd0hSq4Y9/yI185NJV3MuqKZLjTDyYpFdv+KrAPALshijeH5/BdW6+SV2rHApTA==,iv:SZ5EkJ1TKf0bLgSiE2sgiARIp0parnblPc7RMmaWuII=,tag:yxytdjVnb9wNwC8Nm9n9Jw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:DPgjitDznOLjsQ2Yw4Nq2eJPt0eR6v1FT1U1341BogwOHQi0G0ltgFVFhts4pV7ldxYIn0mVD8g0Pv1VrrWa+A==,iv:B5hAGkA67W8h7VxjTtetTDeh53RSxgykKeWdyHsJ9VU=,tag:2wRD1YDtIErGmR1Zhs+UXQ==,type:str]
        password: ENC[AES256_GCM,data:XkegVsJATOQNkwqtZxFlputKWiCEss5jaBxQutD4u2hXTBWixo3VrdZ44/qzpq3hFw/ie+B5444uWKxD4QvOzA==,iv:GZ6StLiakuhu+73V6cwbdvUhfqjaqkMIPpR9EUurFDc=,tag:Cj7eea9dLP+JzBijo5J/hA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iIDrjTmdNs4PwqkW4EIvGVI451pyAuMXdEeIrViqEupoQkLtmOwZb4EMUyZQJoLf: ENC[AES256_GCM,data:Knhxy15EfBEWgi/XeoXwfsY1O/9y0+WgOm10NbZXuMQFjydfvcJrYkNN6sOZsj2taVl9m7+FPtq9lJXU,iv:9qosjjbonZ+gqpWOp79LUcabyQwSON/ZLHhbtL2gMqc=,tag:6gd8LgWOYo54eFFpHQ13OQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Ww==,iv:tdIV3uyg8JsSY9UFswjnOpIqZfhow7pWb4aVbsZ/GTg=,tag:UjUFergNL2KcWuXmsLkWmQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:PXI6if2QvNJxew==,iv:RUTeU3HwrE5uV2afvCbgM8+uf4soWnoWezKLoR9og+4=,tag:F/DJPU4vGkiJZbUDc/oU1g==,type:str]
        orgId: ENC[AES256_GCM,data:QQ==,iv:chUWWa3deEm7dnxJLNkXwCqn2p1XSDCQRs6d3A339+s=,tag:kVpggn4QDOfuNL8xUXZbqA==,type:int]
        type: ENC[AES256_GCM,data:554R5A2PYUGKIg==,iv:/+ZbDNZ+Izl/g7D3EzCBilfJEnmhWduaNxTMXXAkHho=,tag:PPHnKTQbx7ZAtYpXVZOV/g==,type:str]
        url: ENC[AES256_GCM,data:rD3piU0wIsPNUGxNMz6UjoYSSxKX2Ubwl7CBGbk/VaY=,iv:jNuROiu8ot7gOhHvQ6QyCrArMaSCzhXVnhMOeyRuu1w=,tag:MoHRfvAehvnpDV9a50fFyg==,type:str]
        access: ENC[AES256_GCM,data:HC19ll8=,iv:CmXutESdwWnz0tKEjNb+qNFdmmEtalQFogZZSoyBAGs=,tag:V8NPPzIlbcj4/MuQFNhOZQ==,type:str]
        isDefault: ENC[AES256_GCM,data:TDbERUI=,iv:nucuuYuHxrTjbEPge+Z8BOSElnev0a5KxrtjNQSSAmA=,tag:pOzXTXLd5rCQ44iKUiGsMg==,type:bool]
        editable: ENC[AES256_GCM,data:pIZ5tWs=,iv:RN+fCdObrgHSf634g4n3by1grLFQ1JhXg96XR8NgKgo=,tag:1N9TNtqdiWDDkuvsQjlTXw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:ViRLHQ==,iv:nFaSx11NlcV+VQLynpeqHRSsa0z/ch7TNBoFXKrePDc=,tag:g5P+5qoE+z6qjRFS089gTw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:yeWTblcYkRBWupk429Sz5ULkZb7eFPl2Vh4GqMAy0urH/43ALL3dRNlVBXH1TzvHh7lH6gI/b1WuV/MQqTylFQ==,iv:c003zc/AreVBSFruv7ef3/Bn8+lLoYIBy6LXDIx6NkE=,tag:WZ6BOPu0Mx8Kc5rnIJ4XOA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:3+MSJGPE7kC77KyddgCMyw8lvAaX7poX0Pk6Lq+opfikKLzdooERJhHdszJlizqMhgqSfbZy8XySfBng60B/Gg==,iv:yQLTBaYl6R+eHS3r7HayX3I0c7Y1L/GH71b2qfjgA88=,tag:StHHlAGywzlT3ShM3ow0wg==,type:str]
      - name: ENC[AES256_GCM,data:OTpEb4UpWYHHHLG7Y1gWG8B2nYv/4UHQocWhoeGTpw==,iv:5XrBbLHpbdDjOVOH73umdLx/DUyj/0t/f5gszgxaA8o=,tag:0tWH3qCH0UxvOuSYE2Pdyw==,type:str]
        type: ENC[AES256_GCM,data:ZYZ7tXUAQaVgZWTBxQ+6/j+0FsXMTqRvyHoblDwn5w==,iv:w4dfWI4ryX6tYk67ZcEgFTQ81q+oSTBJvTNX9K6iYj8=,tag:oLo4z69XNgyHmXvVGDkelw==,type:str]
        isDefault: ENC[AES256_GCM,data:XOUxRIc=,iv:o01ATUO3N6crgBEEBhaZ3o0dlu0AjzJhX4Ctc/OopBk=,tag:ILYmIf9wYKQgZb73WZR3uQ==,type:bool]
        editable: ENC[AES256_GCM,data:H/wwnw==,iv:3rr8I7GjKV++MQCfKKLZ77w2zbJATcsnWCyAAIUgSN4=,tag:pPa9QhteaP6rRDBR2w1DJQ==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:50Z'
    enc: CiUA4OM7eL5KbW+VC5iqnqGoq2/iSFFh+WqlQCUjQwZPL4mTMH/yEkkAPHlbma96Q1JOwx/f8qdUmk1v1FwJTlaqQGtHK68cvSmHb1HAPFW1XCYn6RbNECw5MPgegmP4yGaQpcz1MprTViCVXaA9zGCX
  lastmodified: '2026-04-17T08:24:50Z'
  mac: ENC[AES256_GCM,data:bxifYR0i9y3gANd84S4HqkWjlgqf9g2Miu7XSlNeArfCyw7Of6yAnLT2GtpF1ZgG/E0U1XHCjSLszw7qsOrBEki54aM1ZQIeISgqnwixMcQReMBNIcU1ieEhH4T5V5Poso1AoAvlAwyzelsY1xQIvpXBRhjUuz1mDTPXkb7xlK0=,iv:RTj5yPSlOo6O4HVNYpFb3JiNpsC5JdHOflnUwQg//bo=,tag:7/vvaMCW8tbCvuxjcPwEFQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
