prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:YdG4PpP1u8c0UaPi8qzV8ufSTq5vCAj1oJXUuuVsa9oielcKk2oJxuyUgg76CFAQf13GTUC5KtSKvHMTpd0TGMTmfZbUmqjHhah90aW0lnoW+t5wZJXHYCacRSM3769PO3toaS+Lt4wVRSDG5+lplE5sy9i7m4Eaz+v4+Nl3FOcqMcj5dADSB50fob3yRCMiaCOHAiNuebQMzmma,iv:uEoEPuckynNibtXB7w5aLb+zYpVsnux1CgcCyF2xEGo=,tag:iQk+RUJph4U8pYI7+PcB1g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:bNsG0coa/JS/iI0Ki0JE+gN+q2hkDj78ShBtbTkI+TU1wR/kHd5DpyPmgcP3dzK47YT0NHAyJVwR5eLkTBZAww==,iv:tb4Bp8eV64dpGW8rECTOqHtAkhuVPaU7wwlO3+WDfBg=,tag:pcBUFhk+UFV3mVPloOXmXg==,type:str]
    password: ENC[AES256_GCM,data:CGHtFdTsrrnXQZ1W6S6KcxafV7IY12m7Slk879DGZl02299EiY+u90YB4rsWprAOdKVKcYrS7qPI/r3ADNAXrg==,iv:0fkB4BfQpuNTs36S6ves1FTcGxwFPxBTGSQOgNE45QY=,tag:yIqS28jlTaGM7mj9AtCKSA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:01WfjYCLQaSyvoQ36g==,iv:6cbNF0I4hU+KPl8UJ3IXgvScWZKeO4W8yyESTRiDomo=,tag:AQaAvnJLU5rBrN8nTaq0gg==,type:str]
      value: ENC[AES256_GCM,data:qspKCbhi3hTlDlLAk4qnGhOyuhugWAJWNG3itZ0K9f5xTFSGX/c8g2oMaoI/qpogSbeVzF7KSiZKRxGLKkm0WLrJMmN8HH0VUaqQGBNmRP7P4DuJL0EHOA06fW3KIUQIr6B03w4gPaDg6VB0DLT/S99GHsst+Sc8qOA+XaTOD2s5xRLjB0TOdh0aYn/OxHy1ZUerGtE2x9ur5Fbd0BiBxyxxeIV3Ag+J7N3Lu9bqPP+xww==,iv:Jslr3VsQrDIUJEFAmawHdm5vCoYyR4rFzjwzdH/u72c=,tag:451XDrSVzZxobBFDpUH91w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:36hw/o9gVZ6noLsHWJqkqoAI7RZ/tO2DiKkJezRaWCJmiHhJtpTKpSGj0RXxiEXdAqVe4abMk0LBEdKwCSoT3g==,iv:USwy1kriSxEpDon54PKM+41c9zQrXkPig3WJk6O/DHE=,tag:yHLy2jUes/dzMn7fBSl8mA==,type:str]
        password: ENC[AES256_GCM,data:cnUAa6sbgZX4zVUamW16ACfU3VUmTCyK95lpw//7T6T5UXcXBECTnvm3C305GcCDtWNdSq8jJdh0BJJ6tzz36Q==,iv:AneVcI6fhtuFlA0ooR3bHXu9bc4e30tbe2dlINS1zds=,tag:eMIgX+7/erLjJf+7EeAtug==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        iIDrjTmdNs4PwqkW4EIvGVI451pyAuMXdEeIrViqEupoQkLtmOwZb4EMUyZQJoLf: ENC[AES256_GCM,data:fQL4yuiDUhWVrewYPlOYtoig/Gnq9maliyf8au+vhZOh863s2xrqOmosGK2BXnMj9r8Ygo0KlE7wnf65,iv:1qPHEkoSUQXWZ8YJ/NjsYMZ66fC2YPkL9+IeBLx/vDw=,tag:7OUOA2UGPeY+ouSo9wWuZg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:25Z'
    enc: CiUA4OM7eL/Tq7Kgq0OqEysNSMvdL8hbX92pol6WxV2r3Y19GnBtEkkAPHlbmUJBpegdGBJn8B8ZjXLP+CFqvyi2BAFVDZV5NqDg12AFwYA7Rt7itajbQTXQQmjmc94fEb52E/iXX6skWBcMNQtTiACb
  lastmodified: '2026-04-16T19:33:26Z'
  mac: ENC[AES256_GCM,data:IIzh7zql/J0UEIVFpIGI3xnIHA7jweddwWmmFt3ca8z8LdP5n7SyeN8wjJymRuGTDtq6/W4Wtvsy1X2az3Wotv5BUU6axtreS2QT0f2/KKS2QRZlMwXYATvZStnFMD1TKGxUo/UmP1sS9V59sSLmvhXG8UG9zSK5EfaVjLN5AqE=,iv:I+ZKHVcIqxW0m9hUYj+hAwfyJB7UOxcQ+pCBz6tJmm8=,tag:ms0xEVfYfHT36q1ppzj5Ow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
