prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:MMpqzF3IW582gfTxDA==,iv:9olv3JodGeRrIpjDEMS71Fc+PTztMllPKTcLXLYlIpk=,tag:iU0UZEPfBFgpAX+T4E94EQ==,type:str]
      value: ENC[AES256_GCM,data:UjTjYVqkMW466U6jA950CF0EQAISfZ7v8uT77Uvnm+0HZ5IDJmvxt0poRnOrf7w6dm27GUcugW06fM1fsb2omrZfY3VH6mnEaCBBGsogTdxSeRWDIa/LXh1/8cHDWWE7+z3Izecmp9GnjfgJlFZ7PJRDIDU/516tKapUu+xVJ9JwmFmUgYHovhpFIw9vp5enZFAzwkzGDCVVaOiC8WNPS7rUwYAYhUe7JGwvJwdcxKplog==,iv:yAmw7ixfVavhwQOyatqkbRBssx2AU386Bh8eyRsH9U4=,tag:zKw3fg5aODDQfKzum3lc/w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:CZk/Zd685PhOQ0Id4zjGZOLSob/ue8FGjtThJk1kYqitRau91pUB/NygvtvZ3tBox+taiLN2rnbpJSvB2ioR6Q==,iv:GbBxJWQNS3OsW2skTWUiVB5JfqIMhCv2saeWsZ2i9bw=,tag:x3V10RI7FtkZAIGP10VO7Q==,type:str]
        password: ENC[AES256_GCM,data:VSFQAcEVs5LIynejwuqrJGSyLbfaAWOS64D24R6jnv8k2WkLksmNmnPCnt4pr+PhqhchTJnsSu3eycIVlDqvvw==,iv:w9uZqttu/p+9BPcAg9wCSV6UFB6Ae/1R34IB71i8kgE=,tag:fZlvHjkXS3emP6c4EJI7iQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HL4J2oLIovCYWRg0oPemzW6GEslQ6ZeccbGwscEojHkevGhcleU9bIpXHJkthKWu: ENC[AES256_GCM,data:b1CXQ8wK5WY1pjJkO5tSvtmQZXcS9oHmSybMAod6jxHyH2NjRel2d74OMJAu9YRlv1+M8JiOwSu9o1uS,iv:bJ/x8+3vZg+TOcXrxCnNt4tfGaFH4zupCMSxyBw/xBg=,tag:/vHlsUcraBnWFl8863b0ag==,type:str]
prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:jGd99/mCF2XXLSJBp7EbIFYgMXtkTImU4yn7TsCmW/R+xlRVq/PuZEg3aXdE2gOZvWYlDozhkE6tbVZUBZMCELvJJ1GJnj0JQnMNqvpBk/k3E0BItf/bvW5Nm1VTiSiFsxpyPKfRJHrUpS7WRJM6dHbvWwvXQBCMn+cAsOD38wwyGUCBvKYp/7RIaGy0AeayP4tTr/tV4zYgd7zR,iv:DbIQmO2p2UTYhgGARH95luql0YsTaTyy3aScsfmNe7s=,tag:H4EPsDMxEZftOHJe+N22WA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Zl4buHJ0dziTV83EldaU9oyGajvQyKUfDrefERq/xUKqrA2D7XZ1fZ1RzkbA3sL1WTQgDgZXGX1o2viN4Zqmqw==,iv:V8IBvuFfZ1wDCdZ6IkrETij0d2F+ZnV2Qj3oG/jQQno=,tag:WmzpGAgvK/CVYa6IWkRQ/A==,type:str]
    password: ENC[AES256_GCM,data:AZ6hsRBCCkmaGPWDrSseAd4xOqh2QygRE1U2G2BJRDd6Tg8i2+6iyUS/7QRiIJ3Tr66Z7uVo8NOJFakDGOsy3Q==,iv:m0oV/iFrQuXJAhAr/kCrVJUu4lZUSLTh7IXe+rmxMtI=,tag:U2AYVr8j8NB2GM8tMRzW/Q==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:07Z'
    enc: CiUA4OM7eDNHlLejRn8K6AIw8j0xUYIOOBQmPNXc5oBPaX/6BLJCEkgAZoeZpvWT0idzKVdTACfmACMGtOWVTFCwwi80awWFFU6Yy1+/XdGiNEgTnnyG7TVyL7WCwkYx9LxpcQktdsVgkz1hjfVkwfU=
  lastmodified: '2026-04-16T12:02:41Z'
  mac: ENC[AES256_GCM,data:/0seyZshQs/IFdQg8yAVZNPhX7UnzbQMmmtgTin0KHsaFMfEWVgYJSrBBDKj4lRUQOnRCOKeX7I3CrBFLacDnuklyXcd61w1XDahAjwXA12dRH37M1XknaYqW5g88p6dOu7M4NsXCAyr3dK+gdMBgWPtVyvwCmZumWEu4TBK7iU=,iv:eMcgAzGtZ+isoaADAEg4CMZExYmvjJHtIoeiuV4ktQY=,tag:Grym2Yt3b8am+z2Q8ywpZw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
