prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:V42EXP75+2nxaUA5Ng==,iv:Jdzi66/BfneIH7j4TDDYvuSaOhgHSX2Z+Qyg+Sy6VOo=,tag:rXKQA0UmT1D7TXgtrTG9/Q==,type:str]
      value: ENC[AES256_GCM,data:NWG2xzTH5CAOHLHPPK4Els+lgtcR+u+vH0yj7rIx89QL+69nAvaUh0lozZI9gXGviGtmiPb+sDk6QR3HgFA4AxxRV9EK7IGxhdebw+IxzYSOyWMwvJfB8y4Q7mKlqmBjpi93wsw2aoS6hYzcVX/BsSsYQfnzrUcyne6Qrk4gXWsmjAn+G8Iy8pzTqJQhbsNfY48uOOJZDlLn8HXv/KiyixxjGD7vWgy9Dv4yvVtn4sAzGw==,iv:yeKlDeBHt9j3lzkM8YjpKVcqaE+niWRZ7nY7kBGmQ9s=,tag:Bse7aVRuqZISZQxnE+FyTA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:GwxDcDCM8cJpOA4GKfjX4HceMWBQv4CpBiljDN2485ENLbRr0MAOEj75J3jrAq9O81W9lf4rjvxJgCBanJD2+g==,iv:ltx6eqMiUnGuYYWauY/gaLhlTlKybkpgarYE38WhDmc=,tag:eZ4wSrlzEjrZtLw9z1RKeg==,type:str]
        password: ENC[AES256_GCM,data:M+uBFs4CJ+Qhe2/jheyaIGVrAvqxeztkpUnYJSEtANS0w6CKCg6bZM1I2o8X/Bub89VrgUO1UO6t/asyQbNElw==,iv:fEj9nIC6g5sVmaefIB2YvRHGYCgmlUZZSQLt88xu96M=,tag:MnhPCjnx3gV0/+klVpMwTQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HL4J2oLIovCYWRg0oPemzW6GEslQ6ZeccbGwscEojHkevGhcleU9bIpXHJkthKWu: ENC[AES256_GCM,data:C7QXV9f3fS7/QdAfiDMo5X9SmO8tLaSu0zv2cCI4oBnXQOO/iU2DhLQW6mc9hRxpOvb98ZBY8ZtTjeCu,iv:xiSCLArXuUshryufLE3np1ZVILmY8ZariNeF76f1P74=,tag:Hq1aEh8SMfOLxSRRdQvqbg==,type:str]
prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:+adYPA6Kc3KrhFGcS6ny094A6VwHSNmxPI79SXJeOgIqIm0dGxkyOQFPeRyniWCIaIV9lB1xaou8UXI5T6vqtd6nwb74nNmhqjtYLqCQ+08cowExrDtqzUOU7rc3NCs74N98MFg5Syp0neEkd+9oPzl7uYKCJQDKhdmxkAYGF/4cLpRFi5JfVCU8l4IhyrlxTYHlq9+TN60lTiQU,iv:Hj09wED6C9bfTS/B34Znu9to4kbyWECEMdr+aWeYRNU=,tag:Y1vvCHO9OyY6xesjpHhUew==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:ji9vS7PrvlR+Gui1Zj3fYgcw3PQ3y3VjEzm7S9Xodf63iKwhI+OETiwKbs2lOHBjma2HKq45DozeRRkl22O51Q==,iv:L+HxayYMBiqLjp+0qzsIxD0dbKuIn+3Gdhn7FtxSzx0=,tag:YSQIOtd40F3j/WlzlGvxRg==,type:str]
    password: ENC[AES256_GCM,data:o+U/RQPeomLQGeLW22qapa2QVqzgql2A4Y9UgWl5cm5dZh2DNGH0/7n7ADd5Im3nntn7aiGV+c2JJMpNC8JQKg==,iv:ItjXG8ncOkrwAazPFsJoAbPxRkklc2qvgwvcp1Nb5wA=,tag:Dn9z/B5JCPlFc1hMnlLNAw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:1A==,iv:0EywFUQ1E8ns03BicWAGKweySUmh+xCMW9aSspy6whw=,tag:nDU8QgEzoZZ06altSLqexg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:RKB+Ob4QJbIXAA==,iv:Izmn5cuBdboDIAMJ1XbIRFr3QLN3uccL1bORV/MBM18=,tag:ybUWQe4JliABjoBgQjpBbw==,type:str]
        orgId: ENC[AES256_GCM,data:Zg==,iv:j9bdmgQz7MiB/r1+DsKgcF3qRnA6HWHv5bXCxQm+aXg=,tag:StQhwUh/Ylue1ygN2jtWyw==,type:int]
        type: ENC[AES256_GCM,data:Q47+vBxrX9819g==,iv:nas7jL3wSZWSFzhs1nzNxJJ0ikPUsvT6vSk2pTzYnE8=,tag:L+CvE5XG9r4CHWxSjxxJFQ==,type:str]
        url: ENC[AES256_GCM,data:VE+svxc3OHq6F4JUziTtTl+AFNV1gHmcbrJqfJ8jzhI=,iv:wbLCK0lchBsbHz42g6qaG6Xg0dbr4tJGIIShIa9eUFc=,tag:aYIQ+RKMzBcA1VOFnCZL7w==,type:str]
        access: ENC[AES256_GCM,data:/P8Ap90=,iv:deCloGRvnespKV3C3A7g5rOaIdggQIB9XsEKl0wQyXg=,tag:G6EvCoTWdBXCfnTSL96U8Q==,type:str]
        isDefault: ENC[AES256_GCM,data:Zhb8BMQ=,iv:Wty3ltaG8T55e09QuVl3yMT8X5LkVfM/Dbt5qqSJP0M=,tag:pj7kTznZgFbsu7XnaX90cQ==,type:bool]
        editable: ENC[AES256_GCM,data:P9irxIQ=,iv:ehVBcveM1dxFMa5t673wM2tf8bZ67lvD600My62AcC8=,tag:TBKFp4piC6n8bcJ8YMEm+Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:hVpL8w==,iv:vKzy1jBg3jPI4r6YJkjQX8mGvD5yMrhdMwv4wH+VgVQ=,tag:rkJ8He+uHQHvc387Kqec0g==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:s+lCxOPHO5mXjZujj2qBVhCnUrniILtd70iWizxmuVeZnz46SkqMW4qJRV5EnsRcB/p12ej657fnTekk/K1ANw==,iv:VwRJ93KWhfgWsm+nFnpteozU0guf+fq/OjsTIJof+rU=,tag:b8U9VFNixkt+KiVNuYGSxA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:jVIpjKXpFFdhS2MqXLOsbWsZ9Xfc5dB+pg4teG83pABxy3rEn32ya8VRYdvuT3UBnxO6GPYCGmIw2CV25HvnlQ==,iv:y8aCCZcm6uryg4l7f82ezTcuKAiKgWLy48MliuTnJSQ=,tag:u4MJWsOiDW7Xk57TWe/PhQ==,type:str]
      - name: ENC[AES256_GCM,data:zPOpIy6rHrZ4xDJ9223OZSVwLjut7BN0hl9lLcFyIw==,iv:cArQbzJ21ME3pRRQjnAOiwHj2q4tALOSPPcaQ8zLz/0=,tag:8Ev2ATmSobFN/nmDiTY6Ww==,type:str]
        type: ENC[AES256_GCM,data:MQ5Bwpx/zrI7WdCR7/CMfL64hrOiUB+b4pGDFDteQQ==,iv:kSm5028Tr62qxtXMETpmJdkYWsLtndXnfHlbnxusbrA=,tag:Es+fKsFQVXKsVsCXaf827g==,type:str]
        isDefault: ENC[AES256_GCM,data:RJrnu6o=,iv:IP7DT+eTumXexq7wrspZg4kDX7nhGlQGQkldokrrSdg=,tag:H4FxVH6TXYLCiLYCn9hO5g==,type:bool]
        editable: ENC[AES256_GCM,data:lrcerQ==,iv:LTzVswAiGnB+KCB7vD3qhscjRXNoSoINHeK2Qgm1JiY=,tag:ChNLMIDiaEtw8IJa7FC/Uw==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:21Z'
    enc: CiUA4OM7ePS/neBoYmuyd+080wOvzJC1jsah65PKwZaUBK9SPYizEkkAPHlbmabOVOk7s/k2Jk5heFYuUJIZRAnySsIC/qawsCP4MS40DCqREjmds9iYzMQ956HWgTBiLm3bCr/0BpOt7K64EfDFKs4V
  lastmodified: '2026-04-17T08:24:22Z'
  mac: ENC[AES256_GCM,data:cR0z47STIJ/12sSdyl6PHPilWStgE/iDQJDJ2APEWpG7iw3Iy2NEJdqV1SWtvQBPHHPYvc0mpK64v0w00Xc/YLdcWAJ2wv6C46xr0ouxkIuIgG0Q3YYED15Ib1I7CnIjjYtbrfMIQz+yQLIBF4jTvzeNTj4IrN/jSdIctmdxXVk=,iv:XqkFjtV02ffagbNRr8qsqevf2y6eNlr8V4f04CyH9Vk=,tag:gKCnQA01K3ViHnmXh1D+fw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
