prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:KZ2hE8dWCOO8OSWvuw==,iv:wGEvMDEe9uhN/ipK7GEWtQ+SjdLBwu4MRZFUmd0KpyE=,tag:cnb4eN/Ed/cCEVuOeB5GzA==,type:str]
      value: ENC[AES256_GCM,data:YDqVTNDo0m4eJcjEiYAemqAlZzBllCmPVyiuy914GvZYFnFMKfjxKrzwVACNuPYvn9sj8DK+5tMNS/yFWQQm55isX10uCZGz9jw+ZSiWys6M+KEIjNlStTQvXKH5e3/HgNtK/s4/9JMFNXOVIa8LB7h/ARaapISrspEHbkpkxRyuSfr0Zv8EkKivvYB3M2rb/+g2pqltwnZ3ojqJf6W8UsVrUofJViXtkdn/gtIZFTKTWw==,iv:vccm+YDAEzMlTK2EK5kC+AP3AFdDX8KsSiz0mx9LRyc=,tag:o7SpTdqDisnuUZ5wKnNOYg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:RN0thIl13t0Wh5N8wM8fAHcXw1dskkAZRzgVyp5X8QVtkOBwckdtdM6NHFYRi1ww8H08BljtDFHgnmY9DwyEZg==,iv:QPJWh1zaGSRF5Dxy1TTyR3s6ljsYYsqXCRUWWj/NsL8=,tag:+Wz6XDWZ9LdHD4cgBSB1Xg==,type:str]
        password: ENC[AES256_GCM,data:/imAyEUOb4wpYld1nsDXleOdfcTFRP7PUKywoqHw1UhWyj902RLjkdkhRea1jp3DyxyYDTObPnmLjyq1x+TE8Q==,iv:FM11ANHQlwMoWUP7IgUn3uDQynb8eVZBaRMg4GRSSRY=,tag:w+3fQFCMFBBCQ1t06b4p2A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HL4J2oLIovCYWRg0oPemzW6GEslQ6ZeccbGwscEojHkevGhcleU9bIpXHJkthKWu: ENC[AES256_GCM,data:JJ0iRDW7XO8Fju/LfesQdmaYvq0l+PUZBkMvxo/zel5TGPP65a9f/IgUiytLSMhiwqNtTV+ZKzy+dK8I,iv:a69bpA8uaFvFxYPOwZ2y4erFA3LasrTYgq7DJzihVKA=,tag:VQPMjfBdrNLBVo7gSatkMg==,type:str]
prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:3ibOHGQ2rql3z1Uel3M1ge/NM13sMDeaEzNbZ5eRJ6X3hHxDfEGM5ppKfTTRxoLzeE+QwYkocO1NBQ857CPKrCWoquo8iVpw3DKFFWxdvGxnEkMzPEJA3MAL8MCZM0+40kdSogtolU4CvkPRA2ggZ16Amklj0OSz8qZj9ptuLs3IsdXRGDdargLRPY+CH6beLxIGCoWwiEEkjF2J,iv:8T1AmjlGkFLcOeRINTuVAu46Tf0Y+yIhVmcX+A4KWtc=,tag:6Bmx02VkGLe8YvP06gxBqg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:y0q7Uy0/67OGfpzloU5NqHJynRK0UXXuXA8yig3nFAbt6Lw1wYjFfgNwdTst1QN+R4QzGG2QiXBWWbPoiW3VTg==,iv:btT6qIxRPRFGB2uFGKjPy0jXNcVp/YHrhkEp5l+ndOk=,tag:TzVoqgO+0AK+WxkwKBIwJA==,type:str]
    password: ENC[AES256_GCM,data:SqVFAllfMhw9HB+9ojF6Pf5I3s2u/RWS/5ReIjEvxj4MxUwWG5hfmoskFXhACbT7p8UMQAsFTuwqPQbpE76+gQ==,iv:kQVFf+IXnm+Tyl1QjlfO0e2ulk/EztzXo1GpA774un0=,tag:zT3k1ff0vGViXhY/DLZBgA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:57Z'
    enc: CiUA4OM7eGEZRplafPXJDi1j3W4utz4vKTbH6SXa7S0R79Ve6I5DEkkAPHlbmYBz1fjrgCv6VumlyagoI4ChLxh+UHggmABQPjG+eo9AkMJiHENKr63opEcq7Owg3ES+s2w5ZFJYIRBqEuSLZiBrqPfz
  lastmodified: '2026-04-16T19:32:57Z'
  mac: ENC[AES256_GCM,data:YKyT6p15ZkKgqjGMsQa+GCbD8UZw/lbGmo7f/+x5KbQReBCHiHutU6eG6HJ3PjN6jiaG8Rr6Mt4POyygbZPZYkl7z4HYzweQHrlebCXoA16HU1jwhI+pd/hmZruMlse718gYE39GnB3wsbt+rfQN1yYIik/EGpREWvN2ju1glAU=,iv:OWc6mf0v1oL7fUKTPDTGKo54yGooRIrvf3dLwJTZR+0=,tag:SB/IQiKt9kjLkE5Vdeh/Kg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
