prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:RI5FpzCymSf9afx2uPINkGSxSUy6YJty/2Hnnfe5M/dNN9MWMpc03h8OE2DAjWQTzXlxwj5m5PtoefXRTBA5GiHbcy14wMv2efA1VmcAXOhsqewVCnYlyyWoabLQRG1DeraWM/cyDiDq/S+YF5YhEvzlV1VtZvdThgZsveJYk3BwNCNyiujeyFVe42Iv3qY3bbnUuAOGaWFu1l93,iv:VLc8rJDh7OqFOq1I65xG6aNjiXW0H9Y7LjuPZlrXdwo=,tag:/DBDF1urMUeo0URd/1VNXA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:mJC8dHbRzULAEaure3MOcIikdSUHj08Lmua3kvNnXN12jBdOcdSBLQDckHxmBK4C0/G245dkt+bU8Q9LwxuOuw==,iv:xWBVfP+je9kylg5cjAp1LOit/zk5+R96tIh1KsMjudg=,tag:5Me+jBAkDkoZ2/z323JABw==,type:str]
    password: ENC[AES256_GCM,data:uwbBh7k49bexh9/RykdoQJ+Vcn3DDPk/3yUkS3KNey7HZiQXqIatdUjpLfM10GBiDfJk3FWiK6ikRpQFuhJgOg==,iv:9lreooMECBcBrvQ854gWFGBn+sWxCX3QQXrgeH7xvPg=,tag:UUEuNxgcBn7WKEHqa8Tdxg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:x2VZmJq1k4xdHdst3gMIEhPvlwc=,iv:xu8kHUb/ZXcoD7Q5slMoDdRME37DhR4Ffgy8IBZHhB0=,tag:0VP6KYvi1cjNfnN0Uox32Q==,type:str]
      client_secret: ENC[AES256_GCM,data:+2eJHV9lkwanCFaStpip+gdEQ88GtdwOXJu3XcPx3rQj5JHjbs60Lg==,iv:STBEvogVgEZpalcGlJ9+TTduFrMNXOQa9lPPAzzBFs0=,tag:eia1YJS+uqHHgAQdnZgaeg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:vNfOnnHKOkq24e5ECg==,iv:CGnr8SxISU1R8bA7jk4OrFUHgysJR1Cj2qN8AGS4LQE=,tag:wqz01M0QhiCPsNggD26sGg==,type:str]
      value: ENC[AES256_GCM,data:PQYkl8hImwCdU8SpHUTKKFtZVKCdd+K1dz5xAqmiUTlcO0eb0mXcRodX+39yJ0kzEy5uIZhXLPqXkEaH2ZR7DFXfY1p0hxjeINCihBTVRJmhSSHcFtwGAzZTRvYVIXIAZEWv9RgWh6QJSvXZY4BaBWw2nPgdbPCpJxOlYDxK6D9c2yYEZ3mGmztHSFHpaIUdK6EDG0uJPsQEfronh0hwRbSmMBQYCqXAIgp54k6JyfZVZw==,iv:mCSe9appYM0+eznthwDhfQv2WDorz2mgVmjrn3WaRaE=,tag:s491MFtkyyJZxaz+6aG72w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:MXz0wi1uShXdLZRgL3O9ie0NjA4n86RmaF/nw4gnDvNT7S0VIA0rMio4AsiVop/iTDVeZnpKzEyg1q0mIWSGoA==,iv:dR+qkv0OLm2T+tdb/ECv2xjUpSem63lnGNwrTJQB5+w=,tag:jjDK2f8V7Qk1r/50q/CxrA==,type:str]
        password: ENC[AES256_GCM,data:dFdhvXrd89OdIlebNROks3+KZC5UpA0qmpkM8wlQXBbZU6Wqrrkvnhv5HbhquX6//Es7icFMAMMff9iAZXrEzQ==,iv:RhtvUjyLpPW0HTEVoWCOUHJZLc/dTtBm606qK5F31wc=,tag:v54xpbVWa1Y6jSEiencBCw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HJK2ImmQhgclS5musEdi9AsP4ISIAjn0vkpKAcpW4FELIc4pfmcv2SjP27L1eLQV: ENC[AES256_GCM,data:ApETDRMnXtk6QYdiBtqKNt2SVWuDs3Su5ezOk27GRLR1RIodzzU8oo3XYMjYiPqdAMMMAxLQVz/akzLC,iv:ZOs44rfpVkaskXmj1+LkJnNWEHQGr/a9iQngNlsjc3Y=,tag:Xz8Nnd6qRjA4y8LklU/iJg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:41Z'
    enc: CiUA4OM7eOiFItl6iRyCxarptOnqWg8OZ66lFZ5SfSLkAwEP4nEoEkkAPHlbmWz0IFziWE3i2Fd3q49J/gNOfj+EsWQHbK+5PsCuJnkufPgTs9l3R6x96hkDgY0LCQW7pN4gw/3f1m/6mRWYSULoe9U9
  lastmodified: '2026-04-16T19:32:42Z'
  mac: ENC[AES256_GCM,data:T44I12zreLAmUZ74Obm61k7pLZWxk0fqVTzuLJBM25g7ojYYVfzkz2WABUmEDuGLmDtuSfDH32sSuSrg4+jWOEE2Re1i9tKkTDsVzvOYpXS32Tu97A/BbI3VsUOsiUzlDlFygDEIeaCWYA7swRzpecFXtBvCNNJTLfT5IeZNHwo=,iv:qhLlsCIa6b9yEd8vihbSakIt21RSkmPBY1TV2t6tO+0=,tag:ub71I4pjNxZeB93uoPHVZw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
