prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:aLHu5JN9F9qFbblkd/rySa4TtlPeseTyhK95y+lP7ArKTn35yAEdvO0+QkcV9OSa5qe/l4lEWQqoeIcKyrG13KWWsItDdR/4ce4p3lezjzyXkreB1y4w/ubMW3h0hVkujAbIzzWh8kGGjZaCdfFZGwGza4M1Qsxe80hqPFC6NY3TQ4A2K+P/TjuI8eKc5UttUOlmp1zc88oy9MHH,iv:40PWEVbbfmTcqh8O57sSzrY8LPTOX449xMx0YO9OY5Q=,tag:lNiL4EeSHHv2+4x2ZNT+VA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:19HbPitH2kXYc2ydyyVrtKbTpUjlY8VYenScYSoD/iIB3UDYKGYncIBLEhCulkx8frq84hXn4on01cwyzJ1sLA==,iv:J4kcAide1ftNVVsPcuUdMDpyav1qkbU4JHAu21FMlBY=,tag:29LXwlsaufbQ7odPPzc4Ig==,type:str]
    password: ENC[AES256_GCM,data:Axks8Nz+WOEBJK7hQ9jZdJbSFZoebO8XJmAId7xJHceG2jevUgmEk8yj0Hs3FfHXykd9BhR8WrhVNu19Aa7Bmw==,iv:4ujJ5qU//nTPrUZcSk/Xp6f6efvWOvSVz6dRo6x/DBA=,tag:u4lRBkU0G0DtgjROlX8A8A==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Yw==,iv:Wt36fAt5gY2iKv1N96ys7XwFwthTzxG8hvhO96v7fYA=,tag:4ED0SWDkF1WzQzgwc6Jnig==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:sSpEv8Rpn7XVZQ==,iv:1PGdiB+5r2bvy6HW2HsNo350cTg8gy0BoiC528dPpPQ=,tag:m7N3aIb7IGbtHERQotnaSA==,type:str]
        orgId: ENC[AES256_GCM,data:LA==,iv:ESB9P560zRsYvB3DZQWyhTHrZNKEXNEUZAhyic8eJhY=,tag:xpySQ4cYyk1/IjK/Tk8dwA==,type:int]
        type: ENC[AES256_GCM,data:LDk/ur9ImNuhEA==,iv:XehLgb423E/g9EydRrDjnmM4An6VWAOERyPzMnlAHx0=,tag:O1S8MP6RtUywy5SZEyZ4nA==,type:str]
        url: ENC[AES256_GCM,data:tzGSSahbMYF2VCFkPqkxs1/NHHF2Cva/dIE+2RjgsmQ=,iv:KhdASE4VKa2N/kNinQoyoLtPtz3q69lsqlZ15Dte8cs=,tag:ffSeunYfDTMRjhbMBavm+A==,type:str]
        access: ENC[AES256_GCM,data:iumCFtI=,iv:X/fCWKOkMX0hth4uzhXqRjKYoTYWQc4Y8MkM5PHmFAs=,tag:j0eXOK9+8BtOoQVDRz1xzw==,type:str]
        isDefault: ENC[AES256_GCM,data:uQQho9A=,iv:mQd4qrRTSP3QlgpemQOwYsoAotGm5fpBRebiHfKWRqk=,tag:1T/zt6x/ty5q1KFT0jPABQ==,type:bool]
        editable: ENC[AES256_GCM,data:5wD5NqE=,iv:V3ArkI3phZXW9zcal0kJFy2STRVE9Fna1lscoNR+l1Q=,tag:hn6IFB3bBFRkAtiGJeCEYw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:l/GPBA==,iv:IEw5mCDGjHVwNqr6YrXNqRDM5US7mXVxtsqeGhckiyQ=,tag:EoxPcy3pJfR27Rb5l6Rzkg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:xnpfYwoH+EuQ1pOZoc30Cem/Pwp9g4bRaWUtGN1VO5LYsxZdZYlnhyIRT3vnO+EJgNFnSB7MGtZVD7GLk2f4ag==,iv:JTuszIsDwDvHWoq1VcZSLOQgU5SELvLWdjhF560wRV4=,tag:rBFnJ3+EqTRLKJFXOq6/zg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:DDG2pyqMOFCG8/vNvw5yIpXd1UkNfs1IQaDY3+BzMqZ/zHLm+dSVf5aTZa/LBP0Vtgh/T6V+dvfzg9dxu74u3w==,iv:6N4/TWBEc0kK94uELyHLaaI/7WUqJuGwhWZr2tZ2k2Y=,tag:IHnSGJtrdfBOZpEDydo0Xw==,type:str]
      - name: ENC[AES256_GCM,data:F0BvnFNesvlhLQZrqC5/dJm66RSS2ij7jov4lkvlHg==,iv:VxdY7sNsjwdJnQAOxylElFAT7OFk4SuolyBdMCAGf1Q=,tag:6xzI0n0M8ngp83dx+Laqfg==,type:str]
        type: ENC[AES256_GCM,data:AbbSYFn3CDCpC0kxHRz8t4+2vuFwUO6GbDB/81QJXw==,iv:8+JWtN3GS0EvvUB4ICnHBG3b+nyWSJoqZ6FbbZqmAoI=,tag:uvF1w/TcU5VzFpNpb6R2KA==,type:str]
        isDefault: ENC[AES256_GCM,data:vapkdR4=,iv:aM8zWdsd96PNqzjAhIu1vwH/wILeLf07lW2zXo4oRdU=,tag:fRS+sNcUT2hhsg8PvYpSRg==,type:bool]
        editable: ENC[AES256_GCM,data:rEMEeg==,iv:okqafDsq1+yt/gY+c/wJyoQ3ypX+zPSxOUe4zBU88Gs=,tag:9iqF8jJcuHBeJXOvii8ysg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:Pd44p2ArwIgzLIP0hQ==,iv:hJQunuX8LDoYr2MbY7feJ+bldWb9hAYzS9ag+xi3OnM=,tag:HsF5qlA8yF1B6aYAH6ZEvw==,type:str]
      value: ENC[AES256_GCM,data:Vvifr7gfqCqZNzzJYjAus59ERFFWQE4GfslRIA4AYXqo/XWc/XfqkPuiKGObsU6kA4Tqq4XmJmNQc9JK4K7mqZNd7sxDNi+rvCK7Cld44TQuHDwW1rlb3VtyS0VNEsE5jP7GgodyOubriJvSi68ZVgKymcHBizx4VpSS+Smp0biv8y1DKHWPq/G5ZSBIdY7VbVFJH0WIjTdcZ9P+tK6Z03E+fhXVZ0O6uMa0PxswQsNPNw==,iv:Uy0QMNWZJ7bBKEcg1NB9x9fJAzuoSR4W2MEm5js98rY=,tag:W1b/Daw7gn4G5vvQ0FA2Kw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:audO6+GQVyINUOt90vzN9Kh4ryFZAr4kNgCxgmuAvZ5c2p+MeBi55+6Wrx0ffjXYgYz6Rh1+1ONZZMcj+wSlkA==,iv:wKwAvxMXnLKxBl4xOnjsyLwEulGQmv3s0Ct29LfkmCE=,tag:06BFFCWbI6DajkfHPU5fQg==,type:str]
        password: ENC[AES256_GCM,data:aLgHNfodcClnAOpDzORgAJ3AfebSi0GB4NkmpY+eSbxT1e/6v5HYNsS0GdfozHjA0Ar3aPa9YzrXpvwDHDZTNg==,iv:JQQnYOZ4E5xm0yol7YIZxgtNGDDu14IgHMTCONPutOE=,tag:8/VvCmVtmANytHViGRTprg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HJK2ImmQhgclS5musEdi9AsP4ISIAjn0vkpKAcpW4FELIc4pfmcv2SjP27L1eLQV: ENC[AES256_GCM,data:u8QuaM68VSaYpshv7/eKe40QASMhiWFVpNxdZzf/+3cuXz76LbC5A2jKw2/U9aLtUls2Ut2raZzsrs83,iv:pOg39rks0cGIF29g+Py2ef5TpcYfqFj3BiW6t5Ak8oY=,tag:bgvF68O5CLSlhKmbFFif7Q==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:09Z'
    enc: CiUA4OM7eOEB4NGIrfGPWFXH/K3AeHstYuXDMZmwTm/wKicmXFZWEkkAPHlbmf3Eo/+4FHPFWemYRx9wiPqbMqJ4MNT3+zzw9ZZSfYtaUCpy5IgAAjW+HhGWXUeXS1Bcblg9EyjM/FEcSVbFeWNquWRS
  lastmodified: '2026-04-17T08:24:10Z'
  mac: ENC[AES256_GCM,data:rTI6tAKAbnJ6j1z1HRYyDZrAy9ih4GCCNUZDjMGJxWqFd7cnS26f3+S7rZkfPFor3FicXqrkaJtTqhc/KBXuikuZpvVRpY0aG8jRlNcV9vbsAqVFW9i5qq2f8dGqM+3CyVF59yIaGDNTqCjNW0uYpv1Dci2eryoIDNHEMY3Fqxs=,iv:rbmR+NExw+A9OehymxM46RSFrI9vn83O+GjbT6KshsM=,tag:gKEKCqlP3SAD5GSN+MsERQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
