prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:Qe2xafuaormeUQOfaFXcfyOznClAlG6cVXsUK87aH+SdDpD0fqsw+Gsrn30pGSE9Pr+gPjJPLYavfXPIIGNPisSRW1n13WmaSu5e1BCV6SarreRCOkO6hA6VQOmd4tFWADaXbKEA5Xp8DaMMbtVQmT3kRhAaaAxF2bVKjfzUDcoBzVfvKvtZAy/vAYpaR104ZZxd+0BB2RUvFKnW,iv:xOSyitU6v7cb4bnPpA6fo/1fLay3NkuIDOhXuPlhPHU=,tag:o8C1CGEt6XIWpiN1SATktQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:I9UJC1vZ0GB3SZehHxtTtIcpMB2KtYEi7f73tdy2WHHwB9p34PxbFQBoYlII0ioWZgf+l+wFOj4BO+YIcYIXKA==,iv:bAB2XIqg1MQYG3B0keWhkSCg/oPFkqB3gy0uMx4dg4M=,tag:/rK/UIZ/0icxB+ccHSNNzg==,type:str]
    password: ENC[AES256_GCM,data:eQ2EOChyjRDN0sdkE7iMxqeYaXyBe0T1wL50SZcc2P4OJ/VeRzthp9QDaag46tos5Eh1HBrvKYIjw1egulQv3w==,iv:f/TaviVKaQl9Wrkwi9dgxjVx9hCN6zfQJSxp8Y1CTzs=,tag:ez55fpYcGVPqXdasGBtdnw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:a1nVWsEnPXi8in5z8w==,iv:8WYAgN73qyIOyXjbQplIYiPA9jOnXeA/ww6gCcHYwwQ=,tag:K+nqboNz9lk85YnJ0ZztPQ==,type:str]
      value: ENC[AES256_GCM,data:TDI+rlfclslWaUOPoLGAWZEW9mG5Gtc0exwXyV+6Syk9Z/mSOqZZOnSnUpv35jS/bbE3rSkykXcB7IJaU2oY15VKLCs943cMwnLuIkZBbLSWqDuv7PN/VMqD1axUr2CD2Ym17kjZ3sbpclP9m1z6N4TUCB36IrmLYcGTti0fmGCTxa5XPWebQtZQWtGQmlrmxnLohqShkILGHVh289LWWG675ZTMkzKYQj4IqLVvRYjcbA==,iv:ifr7Lff4cNu6NCNyBZV1HYnn3YZFiq2xgMhWiFYAd3w=,tag:jPbQDz2d98niZwC1qk/Ypg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ssDFCpEQKWY+alrehIjFfPFl06qImSanWHXB6FllElZNmQhiGywJfE29Ts9hf0QFt1rscfHCof2iwiQh876/Fw==,iv:4+GgeAyEEKc7ua/ILeylzheSSbDCGKb8t1wYYXTbD90=,tag:6zogIVHeV6W0QAesLkrOAg==,type:str]
        password: ENC[AES256_GCM,data:5Wm/q5jNsuVjMmMz4h6L32fQvRk1sS/OVnuO6kMJTjevysy3omW8I2h6R4X59nLTiqcF7Qnee+q5uto7Z41bvA==,iv:8zJmdmQ8FEVlYFgs6+CSGW3TWFV0if5VHw18hVi506w=,tag:2PBllqpgkArNqSZency1DA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Appmkqf1qmz3w3rb7eKagIu5mSRcB7MiSBE9rY1wnqcZfw1fhBqbg8A5qmAEkubd: ENC[AES256_GCM,data:wfpBPreuLWqUQCLXbm/HvFCezQ4gFhDFyL6WVu62M15nGvmpFIbQj/r1OmUWjWObgcUIZ4cjwBJkveMJ,iv:H40dOihqT4eQRzYV5qwqYSGyupcti2AMpiBV9d3w0iI=,tag:/0Kr8gPXJsIikdmu6Nf8Fg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:34:05Z'
    enc: CiUA4OM7eOYAnmBurQDan1VrUMhE0xog0nILjtLLTiDFqMd3cAQHEkkAPHlbmUANONNmHN+QyxWWznHM/RvREdIacFP9p4+Bmc1NJ7sKi1m6Ik+zTgBW3AkxGlvMN2n3FSbtavUlj+Y2UwN/k5IhxX3g
  lastmodified: '2026-04-16T19:34:06Z'
  mac: ENC[AES256_GCM,data:ol7WXOgGl7QHprquff3Q6Tc094MURdNcOApc3oh1+tz8peHaiVIQRk9gqlxJjs/rhSGDWfI1qqK4mkwQUfqVrvJeOu4bB1jPGjW7yX6jDmIgMX2Ve90Jh/V4KRCRnsaEDY4YsBx8opS9XWI7lLIUqh4pDiWymy0L7z3DPIw0+H4=,iv:ptY9sni2AhEZtPU/5vEmF5Mpm8LNFOkpu1y61mwXpM0=,tag:gpq2dQ4+UIV8rjIW+ef4UA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
