prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:mm42A2M8BHLMuh95215aARoEY1T12IpMWUU4oxX2I5/c/woq0oUf4O1f9LgN7uQWXPHD/PAEzOejDpPn7wnjV9caB2kJm8fSJeZd7YYlfVe3fzjhVjaBAbB+DUdgBdGwN6/yxtvaLC5cY3ed/MCjik+lVm+AmzMGoN0ElfXya2K1QcYGe/3PMO0hJ6nosFUjqAXzdd1Md3qH39JC,iv:7St9sCTmLJEMCkiGfXRV6Oy5kcWFNQ4d25AHkmOmsAg=,tag:6zhQeNWBEivFx0ov5VmuGA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:gE0K6RSzePdGAIihUm0MmlGWRnbv/33pgRaVB6CD7W+M+cKnRsYEkVY1PvZayk1gPlI+noxCeYhDGHmLBbxEDQ==,iv:+zOguhsWPVQ9wYZ9FGrrCSD7dEfYW+nfWF2Xw76Tbkk=,tag:0qYLpRI/9TLkNp3i8t837A==,type:str]
    password: ENC[AES256_GCM,data:YNrw6kIwi1k2CqBH4iVkBHzqKPx4+MRMauPBUmpkFsEH/JbArN96PsZVZsXc9+CJjK3gsOgT3a+Sv7UnyvdA3w==,iv:nayd6pz/W3XmtKjlhDD9LHfzWfoAhLfRuK1iaXArUhE=,tag:RbWRiL4Vjhvm7nyC/v+aEw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:m3kHkA9tXMYHk6Dm6A==,iv:faFHfG6SAXzm2kkfvEaZZlWvIsuSHx8J7eH49UMYS7Y=,tag:utvQSKireXHfCdtZtyC1iA==,type:str]
      value: ENC[AES256_GCM,data:KxDZbTyMk+ONowzM5BYn8SM93ebuLZqxMO6JBnYs0AYIVQMVBrY5nX8cp8RFcgM6j1VxLUFB3sxesPz0QucRjd27/d3ysWdgF74N2yrBd1ufuL5odxsdI5FdGptTJr82Z+SqPhCdFX0XXKKQCSOHrY0OFJUhkAX4LehVTkVYf4RJBo42DtqWacfCvUdIYQ7guje9alteBNAiup10p0O6umA4y2QqbzwUbWFYogBg5Q95qw==,iv:LvSc9ALpuLVmW4jOMWbB/MIV3qQC3/hZ/439Wh7rgvk=,tag:jt3pBOkwwVJu/UKrIOUCTw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:I2KhOPHlSjgcvAlycOayb1y3VK7cNRKxUXfr6Q+Mi8bAGGNCY334YhsPbJuqgeKah8aM9ZHoyavWWLao2hJlag==,iv:+dDhpFJT/+bDrr3bnGzYmV5ilHCfdJNUZskoc9CCY8w=,tag:yKwhb1aR3ETDNVvjzKGjuQ==,type:str]
        password: ENC[AES256_GCM,data:rTptTpSmzdPm21Xw4mK8kX7ZDLlsmi8jEOERJOM5Lat77v6m6DMDQBrrM/yhGlFA59nKyJlCY99glHxjFuDsgA==,iv:6XrOBmEJgUH6ajjDVktrwfP7uYgBncXzhIU+st3KUpY=,tag:xGzq0Nf+QzaexzyjwrdxWQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Appmkqf1qmz3w3rb7eKagIu5mSRcB7MiSBE9rY1wnqcZfw1fhBqbg8A5qmAEkubd: ENC[AES256_GCM,data:dbARf39ruj6tnbHz/e43BwDDF8jQSllpY3f9JguhJ7tIR1BPXO53HlLBTzqmjBXyOlg337+y0/26Ev4E,iv:8V81hwcnL7ZiaY0diDOb5rbz4F6yk3f2sajZY/EbvhM=,tag:78ZvcMeH8BYDndUjpgLmgw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:OA==,iv:AMgEeMG1FhCsiTK/dtMNDsWaLNcuT5sJTJNrvMWDoD8=,tag:iX2ZxAdq2LK4EqRwPwAppA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:ofBTTXIwOfLYqg==,iv:E+tOfy6mTkuYkIoQayFARZuGL5qKY4PJcyr2DLmsyew=,tag:bUhhbw9xGD8ZyZ9X7e1vgA==,type:str]
        orgId: ENC[AES256_GCM,data:8Q==,iv:/qg9nETi73xKKunOdi3aeG9jnDKWd+Iq8D6HJemAa3k=,tag:MD8KUZX43Y6ak9Bcz22Rsw==,type:int]
        type: ENC[AES256_GCM,data:2wRdWyAkx97F0Q==,iv:Q3gi4CCE6KiHpSrv1OrcWMXFpUQmZvus/u2615TBeXA=,tag:E1z1+H+8OslY6PBcYP7NrQ==,type:str]
        url: ENC[AES256_GCM,data:UJMfjlHwhdc/C7jOXGr4qpUAzWKr9CPwr6YtFLyEEuw=,iv:snQEemuzDVKJlUtyTRQMgcQYsninsST30jdrO/HPOe0=,tag:D8JK50it/BJidzCx/RP/QA==,type:str]
        access: ENC[AES256_GCM,data:eNErb3A=,iv:Jg1vVvZQTQzJXB8lbC5+jSQ6BrGBfzdC+XYyg79rGpc=,tag:THvLTyVrGkodHQsqI3bB+A==,type:str]
        isDefault: ENC[AES256_GCM,data:l/cgBuo=,iv:/D1rY1KJWYR3C/+jv0hPXCe7z5gBhqIf/zUfFHADQ9w=,tag:IGlr1ECdy2PFvKhMGm+FYQ==,type:bool]
        editable: ENC[AES256_GCM,data:Bdp7T4Q=,iv:R+9d1N3nh1bXsvADXl277JGmZEJglDy6AVs5Q4Ce16E=,tag:nHNL73+4rylVxdDeTU5Y6Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:YGi1Hw==,iv:QxQc1P+b89afduO0RV+/xLL5wR4JGa2cchlR6eDLOGo=,tag:okqU/sUptPdaI4YI3SPFvA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:BZwmXV7kJfIXAsKZUSiY2Ejzq1HzI6wlKOfkLc9UD+pw/YZxyyL94a3dRRKi/b82zfAIZjmXwfY+OVQgV8wmgQ==,iv:3KGGLeUGjjLjVZGdBNUgBL267zQ0tFbC1VFgCY/cric=,tag:mAqX2u+wk9NCVQRQbSbYnA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:g6c2euu4Di1WjZpmIhaLdT7gbIJYwqYkm3lv1GTWF+Fputc/PMO+YOtV2iPf4OFKl7zAbj6CmMcbeZy5u08p8Q==,iv:iWV2as8oDoX3rG1YQJM1EnhgXac4hJdzgrJwAcG3rvI=,tag:to+i9hEadIZtzSPDm3jOYw==,type:str]
      - name: ENC[AES256_GCM,data:F2AqUFsmG5Nvhxcmx+pb7J4/1dUcxWbHf9ikUbFmyA==,iv:w5XwsRyDcNRCUvNcQhm+1nk2GyoB8EIW1ElPk3dga98=,tag:8Xez5jJA8BqceZQcHhi7WA==,type:str]
        type: ENC[AES256_GCM,data:/X30cZrQOEbyGvDVn5lghwd9r4fYXtt7SRoZXAdhnQ==,iv:toERX0GKhjW5xodcwYsZgMe2xxQv6GO7c7Ueb0nLKi4=,tag:1uBUkF+QbqZssz/FC1fZLg==,type:str]
        isDefault: ENC[AES256_GCM,data:IimObjI=,iv:UjiqIS9OEQh383anaC0nsWUxIundKlm4EW2bl9N2Qk4=,tag:ODoGxNwEqa5k+OCfhy3hlA==,type:bool]
        editable: ENC[AES256_GCM,data:LLQtHQ==,iv:JcLM/FUeqQ9fRl1wmUGEMO9+6qEvvB0Mk7/5QNkfefI=,tag:u5n3ychzzws6IS0LcTG1KA==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:29Z'
    enc: CiUA4OM7eBRmzX/2hii62hxDXQbD2xaZr2hpDH8DDznbQi1uAs4DEkkAPHlbmc2/jpFBTpz4ZCDjP9u+pOIZJwZiaxMr0o3dDH0rAwoA4wFbop9pduzruh6hfOIYVm8Mro7F/tiMO3ht8w/L+43novI7
  lastmodified: '2026-04-17T08:25:30Z'
  mac: ENC[AES256_GCM,data:CAdd4RlWX8hRRLO+BE3eIZ9r/2qiNZI5x391xYDl3f8zSDCh6xrltS4yGbtk08N4YzRcv1kdQjl1/M3kfCi8MTfVTo3D+vMmGca+yka1HPjCLDa6pw6QyIeiYNA4jX5wOuEk2MGMm1jhC+0EsTa7Eq5bdWZ2a1GA+kV4NsReshg=,iv:gsh+Zt6InBdmac2QPly2T+pr6Vd4RvnlYgzcHDb83Qg=,tag:VkvBSBBeO8sSX+rAWk9cvQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
