prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:nRbwnm3oYej/CAjEOg1Ntnpkg1MoNsJhTwV9GDb3IyL92HD99GqlNs0i7droHzZqZPpELUDlcvEJQRyINw5/zAyRgcmwJPMKn6t8489SG0iDOKaY4Hs0z0UXgF8QkYkk3pFddd+1G5cRmiCA84N4WqshBxWTwR0jRRY3FDDA+bQYtndEqoZTD+q9X+9iG46M1vQPyCCVIKgtDDyW,iv:WH/y2FEglp+DD4A6bdoEjDAVSSvMJLPWIbpPhEiM8PI=,tag:8pukXkf+XcdzkOvxZShGNg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:vL54X1jU3H3aub0eqVheGrfSDBWmNMfy9C9VlvPaqCXzsaN1DGFjL5MZL29AIQAp43p7+UXvS2NS9wvPWMK0lA==,iv:5UQjP6xhRLtnpI6gv8SRyLPrAyZ8KtFentFOOTrLRnk=,tag:HGX0Ai0xyvVnJndDuFMdzg==,type:str]
    password: ENC[AES256_GCM,data:Etw1rhGdelfLV2NkVtRZeyouKbRzvv7j8F5pjOQMZVdx+HAJJZ3KlVOlUPBCIw1UvS78e1MKuLtZjSKodt6/NA==,iv:4Ty6mfNH8gHuJ9rz3LoPgY2lHmH2ck+9JmNYRy/oPzg=,tag:xiPfzInSCobeibAsPV/+hQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:XtOCsZufONHdzBxNcByEtrsWdJs=,iv:Yd/gORrq/lacqUO4zLaB0n0MSv9DTzSbH5Ly0tzo4h0=,tag:dF2saEMBTgD3k+8LCx1Mmg==,type:str]
      client_secret: ENC[AES256_GCM,data:McmJK5MSrbcksner/tOvWPmfrdz6ZvN7U4fQIs5IS166yfRKBwCqUw==,iv:OlaA4ihdjp4Peyp/mGHi0Ow4k3h5Q0UDHKVk656t9Y4=,tag:EDWGm7d3uJw0qKHFKcdknw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:vMipFJ4RncVWY2k2+w==,iv:rqPWaqA6WiC8Aj/AckD1J7+dGNa8j+uA5JB/Zj9G3Tk=,tag:/Ye1cYB51VSqgsm4MlwjgA==,type:str]
      value: ENC[AES256_GCM,data:fXCbJUgpRmiWYmlEnOVCcCSI2zQvDLFfAB0ZG45TNZMCucLmBKqmJSdzHKfVVE3293mdGjgamhYYM0g8FsqO/cTjtFXBH54dxWnWFEQETU1FOL7P9gO6QZpQbod+yUFj2AR4EFAvrNwyNTJqRn0phYZguLO5bMh2OtDbotehad+Mj5y8HflQVAZ9y8lwxbP2qhw91yc5V7a0LxxCf2E/gl6mdi854l6nCIUphvyHJXmzLQ==,iv:fRqXiTej8+N6FnLkxtjOkCucM8IGpoNIgOQyLa0Lgoc=,tag:tP6dHsoQ5TF0HiJjElYlcw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:6pkT3wRLjLkoNhoFRrorgF8/NRzH3k509SLgwLg9Ijrt+uKfQg7JRnj9WtMjz+FEJH/UCy162EC/fyTnBKzsPQ==,iv:wNv9ZKy8XzksoNG4kLgU8IKv7ZjD9Gq8P9tshVRpbWM=,tag:dgDHwQf4nDnaEo6WDClOZw==,type:str]
        password: ENC[AES256_GCM,data:h+yDFeXBqmpEdwQkPnT9Y7TH54lw1/rHP45YY+olDNfhziLLqnTVDTxXtjMjkpMXuQY0uGGsZ1uMDuqCNOpr7A==,iv:ns5bmh2OYuJxz3YpJ8LOisgyKxpxjL7re/9CYFcN+9M=,tag:dkpyTes0RZIphV50InExog==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        KVCDzuJIVYDpLEMDrBsYDGWB9qF3mv60XcPALIjOCX5gyhox0gxaAgy6JcsTb8yb: ENC[AES256_GCM,data:+4pmqMMROXz8els2noEYPZjqauKWvwZfL23ISUiJyePYHPC8WSK0o0iimp/nK2B8kHtPRAQUyIngxOhi,iv:Y3zM2X6VkQTKElLEIgGfcXtkMhR7Tjpbv2gR8XPX9a0=,tag:PGcFiBok/ywHKuObSEsYag==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:33Z'
    enc: CiUA4OM7eEgNEPxlK2bwBzAd8NoJbD6YjA3jFyKkp53Txw+HBDBNEkkAPHlbmXxhBg0pFPnrYClEDTyEmmcnUSYYvYvdNLCq5+Q819Cgvu0LUdib/i9e8bBZc4285jAc5QGJ/jaJPkXHuH58/yi6LJBg
  lastmodified: '2026-04-16T19:33:33Z'
  mac: ENC[AES256_GCM,data:X7h83zgN56sTN1q8eKkPN9XdNoGphuXv5qKUIFr699aCOmzWZ5kxwmgTDvQUmsfSL84Dn7MVD9WBJoC7VtUx6cUmwfBPWLnFB3Y9ocUmO3JEgTiboLDvrbktp3mf9ay6+mqmSwTeKJWX1rWWquXv5cNW5bYru/9rVDV1Bis/U/Q=,iv:TUOjm2uRisEC1uBpVikbNPwqouNPo2X9LIiktI8RjzE=,tag:9ggXUy6D29HKt8R06GVflg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
