prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:lDzt5Og3807hStIce4PYpLkLlGdPf6XQevIPSi+WLaVXIMnUkNdmpYirOaVc5RtqDt9D5uTIUgC+rZAwGhvi5WwQqEPw3ZAPmqiIQAwRpWnW/BoXP3TZ8/1Manrs28f9q2hg4eEy3oAEp8C25PUpt93tnQkEDUd/J/LxtQe1Q5RQ1f7sps9RfA69ayFW/z7Xo6WVTLecW/pI83IF,iv:AjTicYzXVIBc6ouyxLWvpYClMKgL4dpHrsIifZzC8Go=,tag:Kbi5bLDBjlCktqoNIQjPlw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:VW605ShHZV8jwy96xD7AYXJvu+Ia7wTpYfDJqA0QC1zGvPAFiFnPEOqo19HL8N0kvpaBCnc3jLHL/kowyDIJTw==,iv:wI7EIXyUrtES1+cDOSO6tZAFX31qFQMVJ1CXXkjRMno=,tag:9UBfcszPJZZwkPiRgJT4mQ==,type:str]
    password: ENC[AES256_GCM,data:H4xSMaiCuhfq2cRpq/FTs/p5E/vP1pejz3p4Auk4dErla4Jie2O531VO6wqVx2tDLvZwP7gxe1DaagffNRM9pw==,iv:rBhm7xMrMP0XTvVACMKOd+RTOSniVQWdghNu9Ila49o=,tag:whXbmlZNEgLyL63V9bblmg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:0Q==,iv:WaNZWYGa2HpbfxNrIpbBqlP/B/guewi77hFVwIRQjMc=,tag:pQqVjBLLpzdW07H22zpC9Q==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:C2O7BAFrPIHI+w==,iv:U7XiOFjuPR+bCqZKJ1ITxVuruQjGjWLAnLGkX3qOkP0=,tag:oB6WpTFmubV9jciuXse3yA==,type:str]
        orgId: ENC[AES256_GCM,data:nQ==,iv:QVfo4LlAmaQFKOUI7q36b8RgBuMwof/NAmLakOZoy9Q=,tag:itQQqxrZL3hCOZRjgcVCNA==,type:int]
        type: ENC[AES256_GCM,data:YIxFMAtb6tRnEg==,iv:XvQWLXN1xHGsD36cFUfJCHU0GyXy+UtFZR8VkUG3IjU=,tag:H8P5b99cOBZALXL3V+kowg==,type:str]
        url: ENC[AES256_GCM,data:6FmFwtPpgdDh+qLgpiOCcJGjLwWQUGarP/P8mRCZ5b0=,iv:apB6TZ3HotRwBaWuf9RQMqB2FoLQHgKyI+2nb1akrvw=,tag:KISY4wahGBBS7erOd4afOw==,type:str]
        access: ENC[AES256_GCM,data:UscwhQE=,iv:HXGU52mrA0hoejMIQfxio1Wnmgx46lQktrIzb8O+ue4=,tag:0XtCuo7A1DKO1q9G+YXBxw==,type:str]
        isDefault: ENC[AES256_GCM,data:u8u9HcM=,iv:AmJ/CC8mPi3xtp/Mq3jUx2oMiIcTPwnHaJHyIJIiwW4=,tag:Yk03vUJImmMrLg/R/4jXJg==,type:bool]
        editable: ENC[AES256_GCM,data:54GzC/k=,iv:QeQskd12LP7Kqnru5qjcsHkGdwyCod+ZOOmLBIdtDTs=,tag:QlV95vvyIKeiweOEeuMHPA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:brmWvw==,iv:siNEo61W4kEnKbVIb6dkERJJeNaoilo+StKZaSyNZGM=,tag:FWizJv5gKGSMqcL8Q6EOcg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:UP7oUhnP7RfzRG9zGj8wOxHtGs0vbaEvc8Qdqw8K6czbODHSI4ZxbawgT6Bt6DMbdxK7on7Z1p/t8P2Fpsv7+w==,iv:WAurtturPxYdS+/WK8UqqHeeBmDMXz++0/bKzc4oECs=,tag:I5EIJh00mOjvb9+YtGyhhQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:vIZ2O+uWcEDlhbkfV734WrciE2DZ6YMufSmGQVw4qVeqmkBb7ICbcF0xiJ4TIOqO3nj91XoAcz1mU2G6ErYTTg==,iv:VVdK6sqWJig/dMJr7IAraCcwEia3ObV6cQVStSd7sYY=,tag:Q+ltNk5nB/EpDRe4MDNZ3Q==,type:str]
      - name: ENC[AES256_GCM,data:hF8G1QAi/oGP55OFKpZuKAEImNFiechSaGqHIYHqOw==,iv:SRrmI/iDFkwWEsGcDf8w4zLMzoJdOPmAijkTFKO+Hps=,tag:UUxSG85ZF/RKd7hqCipOog==,type:str]
        type: ENC[AES256_GCM,data:s9ajVvksXyvwWkLo3ITfOX/EGWUsle7DuLCmz7F2vA==,iv:JWYQZnsgMXIzWSHNLjDoZmDNwbOeXk8AG5zDNGWjFf8=,tag:Rm3zWWvARtagwRyTxWj2iw==,type:str]
        isDefault: ENC[AES256_GCM,data:F03kK1c=,iv:wwkP9RJpjrYqr3TOMT2fF5sqbB402gXiIcHEG+1PKLk=,tag:/JOEW36+RH3VLPsl20obxQ==,type:bool]
        editable: ENC[AES256_GCM,data:/ABoYg==,iv:ul8YmUKd9V/RPFA5PxyBv25aVG2xokIDr16oNQCgUZI=,tag:a6KUykeHmDyjZpxtaFu3/Q==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:vPwbIGqQdbAGONNMuQ==,iv:WlSkAVe/oow3sD+mBKzvc80BDLLX822xes8WSsyCjTM=,tag:ClS9xUqF9ofdaWtT5vGH3g==,type:str]
      value: ENC[AES256_GCM,data:q0XsGi5OqoBvejB1CU7rvgtHv3a1BDN1UbgcxvH+D7pc2g3bvPKi0FRUaTbDQmNj+z/sAiaFvQbY+XjGguIk2l1u2c96rIMQU+uigFxgjbJuqfmKBSP1E6rpOkaLp4zQMumY6ifibnCAecQ2JT4DpWzy+j5N+NFLsOPmMoWVJ09uSlzGTIWp+BAPQFphCs6Ix9kHQY1Xm24rtWmcUlb8p8EX50CoejVcHQ5GfePfLgiA7Q==,iv:UnTTlztVJoNzgBKF5rgE5ydbhhdsyWKLgUGXUkNsXeI=,tag:HbKJ/BQ6elDlnUgUNNmuIg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:/iPwtnBMQu/w25zizSjPsAZWHpGsGEmdvm6meBox3UCnoZmsabN9DeWYAWnpfjocdDdBCCdGBJ6z/YpIBg+L0g==,iv:nOve7ynqevvVcLuUgQqeR831eGSwHSwoV8wgJPvpPJE=,tag:YGo4frHSp2shrjZmIRMvRA==,type:str]
        password: ENC[AES256_GCM,data:4qibPzD8isQc4Zwr4j33mXg3KrMksbQvASg1Y0iJ/1eBicT1WFfDModS+KSK665zeO+VwSNrc7HSPT4y92AvlQ==,iv:sh+/XTUn/nYAmSW6Yrpjogjh1+EzAAgFXsq0Ds/cjcI=,tag:Yc78jAdw2smTwXhXnfvuIQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        KVCDzuJIVYDpLEMDrBsYDGWB9qF3mv60XcPALIjOCX5gyhox0gxaAgy6JcsTb8yb: ENC[AES256_GCM,data:/ktdNBx8fBMxR5KlfedWOWFvys1AQ3BgoPcI2ESxZx1/Agq4m+iZkwxyrNcvLZTJHp86+3e6GK3z495T,iv:q+NlUQvhNNOZYstpEFOleB2hkldisR08ho47NK7XExg=,tag:alKl4lXOtKXcT1T+DlRzKA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:56Z'
    enc: CiUA4OM7eNxOSOsr9Q7pu1A0wFQnex6RDKpo/sZxIzCfgjRTPV43EkkAPHlbmZzoFU2J/5isLbwXPIiHdfuoTchO8mIKpundz5qx9WQY0OaynbbcSJ4j3xj96340dnPbU1ANIoVEE7QWx6ZmgX9ZICu8
  lastmodified: '2026-04-17T08:24:57Z'
  mac: ENC[AES256_GCM,data:jGbDlPgMx8m6lOX/zkIvoWB9PHWo3Hn2PcCNZOmNOprG+WeEv9tnY03odiOlshvdElZPjlE61fq1/2TCw9/kBeGrjCXbJ43v2b36B6lY4Vj2Jvm0El9qDtnI2PaRh4ES42WaMlc4pO6qcgE8eP6ym6vJgXf3iPvXGMiVc0qFJO4=,iv:tj0S/4Z+AbmlKcvwev0oPstNIVOv8paEqQqHy8BIrWI=,tag:FcL9nhF3g0WF1AKVD6nzFQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
