prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:HU2ACIpjgsNxw1gz5rZkkRCem8gzd4y4F3yEzHyv9B8A9R6//aTjm6TWBcznGC8oxt6hBhGVoQAbLhWLExPoghkxePiHlH2OdB4itXgb9jCDX0d8P1qULt2M2j5rvnEIdAF7Zzzqlz2AKFZ5+gWXASdJoNvZviBgixmP9bWxBp5WrEPG5KfZ98q8ETpA02jDBzFYCAM78mEpHNDp,iv:vNdVk8HL+caIQU9Y4bDArB0MJcSA8Vbz95FwUVsI+fA=,tag:pQTaptY/DVvElqxrHXTXJA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:oRqvAT8PJeiZkF1LGhabhzodJDEtUSs1bxf99ALPa2DLwDoiLYIb0V4OPTVCYBJdPCmRKnXiqkOCWi6n/JoqKg==,iv:KlCr6iyVNmDvZA7rh4ZxKiGX5H8jglsJdkMRBfklDIk=,tag:5FaAQL1NB+1K4Hv1hwkiNw==,type:str]
    password: ENC[AES256_GCM,data:VEPZhgxAW41KthCALqFDCuqKp+8TzqFteaL+zsIb4RcAPd4qietcEbLThhn6C/paJRoGt9WvCTpJ9HprXjBu4A==,iv:7DUMDgkAwDPH7e8gUTZYqfGehWfp9ylTnmPHfjvDvtI=,tag:OZaAd0Ckl5UzH0bxhFCDRg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Bw==,iv:VPNw8MAYWaeupC5TlGsRLmW0B3moMbT/E96K/FmC8yk=,tag:nbO2JB7kvGsjdDfjKe24Ag==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:2OTpaLh8lYHl+A==,iv:IbUfVs1GEbLJ2GEgQLPA1yzzzIUJRqlBq+FwGiHErXo=,tag:oxo9yGZgGrpwnx+Z9VOFAQ==,type:str]
        orgId: ENC[AES256_GCM,data:Dw==,iv:mnu6qZxpDPn3VNfVD6vWknIVvRepfiywgvXFcxrwYYU=,tag:Kzbu5ypkwUs0rPtDF3NCXA==,type:int]
        type: ENC[AES256_GCM,data:pFBBzXmmF9SYuQ==,iv:4Xb+Sw5mJ4lIlQMyDmamoW6eb+iy6A026/MdODe5gOs=,tag:xA0yBQGgxZB42ztvV9LK7A==,type:str]
        url: ENC[AES256_GCM,data:fficZS6HpyA9so0M+eV1CxfBZg6A3uaeOp8encmvPkE=,iv:WFwbb0yMNc6sBvh10NnVSb/4JPovt4P2NIeE5P1O+/Y=,tag:WjD66oK2+FzFumgyxwQWCg==,type:str]
        access: ENC[AES256_GCM,data:2jc+nH4=,iv:GPAzRml60Luw07SlaBtSXWUVuuoRPfNvHTgQ1t7uaz8=,tag:K6+TAeSRe80K4USyDVNkPw==,type:str]
        isDefault: ENC[AES256_GCM,data:eEpWNac=,iv:BgDGBhyS/X4LcoQ3MKN8LxuQOPu/nH0xTNfPRcq0fXs=,tag:aQ5UcC9FBZd9JJqqD5Thjw==,type:bool]
        editable: ENC[AES256_GCM,data:2vRyINQ=,iv:ueno2YHhXcHsrbkxa4ZA/MhauIWrvxXQ2NrNMVKGcBk=,tag:lhy9S/RIECQ/EwL6dTDoDg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:DP2Kpw==,iv:Z6udJNSFuUuFsSZrn43QUbEqO9I7NfJnBjqrqMGK/IY=,tag:wQ3hQnjNuQCmxFwNmv8x9w==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:5gEuZHo+Y58qBhKYh3WFeklo9sjmN3KteEnalhudVeXJwUs/XUjJ6ORo8MURtf/ZDh3DPuVAzn/6cnqvd6CmDg==,iv:kPQjrt7Jc4a/34PbDSpXw8EQ6aHmIMIcXwEVFAAnX+E=,tag:3aw9cP9vCfosXBXKBi0yrQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:l/vM9Ac0YjrvKmd7AduNfp/GLs+V/Ap+1Vsd+KMxQtC0mK2LCRI3M/g8bVVZDHfDNU0SNBoR42qGoMyR5d2v3A==,iv:dQ8Hlt7NFPhdqdL9dmyBqLhw2Pi7uYKXpOJauXbFCog=,tag:rStWATbU6L8bUbhALoiCow==,type:str]
      - name: ENC[AES256_GCM,data:f2IV8eapR2T6ghPF2A1o6QCeUzYcwqvr6apbLPA3Qg==,iv:e45300bvnnd4SBUfgEai/M2RUL3WZTYR85jNmrpNJBA=,tag:LEIyQtdFmJA1VRdEMFDZyg==,type:str]
        type: ENC[AES256_GCM,data:1tSRerdrUqS9x/qzH+rt6wI1wMY0HaYoDsOKarzCew==,iv:WdzSAM9GVAa+ARQaPLgQcjm/00faKJh6WRcj2UvDZbY=,tag:Mk2jEP5c9E3KzTGx9X1xOw==,type:str]
        isDefault: ENC[AES256_GCM,data:et8DC0k=,iv:9VdRwyr3CYQWKl9TeCB7BYvc//DYpKbmixzvZQ79qH8=,tag:GO9SDmLUHRaZopFjMcOCcw==,type:bool]
        editable: ENC[AES256_GCM,data:rfxhAQ==,iv:ulHr1xMZgXVD6NT9BqUhLki8X/KYk4sHJpJ66cljuwc=,tag:tjqAOcrNNdmrm6IMUyVZUA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:S93n3KVa+ICWU2SgOQ==,iv:7fXErTyUgGejs2RsGi03B3jaiOUVkUjSoNr3hfF+k6s=,tag:gMCwqGGmP6KL87ttxZOcUw==,type:str]
      value: ENC[AES256_GCM,data:SW/YO65PrnNhiztYAIsMYWhJtUE5mjdYrODWYrIoMpOgcD4QWtgcvfACIYCxS8T6PwTGVe6rRBEEcA8R+7n7+crLPogGCL633UBX+wVFK9sNvjONe0nb5XYAQFEFXhY4YsdbXfzcKLmC1IWZJGXp64G1bRBp/1oLN3+IhBHeQWGwdNdlI0Kc9J3YUNt/6wnWqKnhnl8qHDZZGKIoZnc4QaKoQ9XH4peSiunCHOWO/z41qQ==,iv:xoKLNG9Y1QkoGgqcmuKoQuR7rCrbR3I7NqPtrJmD6Ss=,tag:iPKrRmREb/Y7IfFyXpqMTg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:FwLEDGVxmGxAHMUXbFfn8GOdTB0nvU6likmlImDMXGbKSfSqBF6aJ/y2DbLHsDG53aR1JmR45WBTyAKAu5z7hw==,iv:Kq/qWk8m0QrSZj2k0nzB2/1/KTgndtszt3WYMENsLHw=,tag:fl8tNL3PaOEHGednOkodHQ==,type:str]
        password: ENC[AES256_GCM,data:UBo/NF4qj5/N+emkBo3iw2RiRKUFZ3QjfC8mpYwSMLQIRGcYix4xQfnw8x/XgRCDfOx185EAKiACyim1pFhU2Q==,iv:YdB418lb58rt5mlNMGy0JuQzNaMrxBuC4aqSLBA1Nz4=,tag:S0hZW64IEeioAfNdRv9UVA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hhCMzo991IiqZmhKUwVmJHh5XKEU1hFc5HMf9JAS7Y6YZXHaNzrzxyc7gUSWWibn: ENC[AES256_GCM,data:iZ+kfiHqgC0JaDS9e6tZtMQqr75HMIwgrJtI2jnpxksHqlKL6qUbBDkDalTiR0HO/oDytw2Nj4L8xrfd,iv:Zk1w4r7nxXj1YIoSx7JZtPNJna6OPI9vTLjns11boxQ=,tag:3NprSoSvkUkX011q8wQQOQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:24Z'
    enc: CiUA4OM7eG8ZNi7v4Lt3mFTTCd2AYjQcw2xVq+5YkSTjVZAwgBi8EkkAPHlbmQ2ySxCkp2kQ8xUDESrbGCazobnQXvyLNBTEjtCKdjmpzJezsLB2KDFgrzJoEl9cWWscSwn24YAT6xwEHkWHTDMMYfmm
  lastmodified: '2026-04-17T08:24:25Z'
  mac: ENC[AES256_GCM,data:ZCjdSPf2vaDf9dchLYHd68pvA9v7u5UB6wzSDeJus2iNjIAc5sfKvgvoea0PmhycSesYIiISd5zV/ql2Zpe9g8NYtu55HLmwK8mAthMxC7Y4bYf5leZsYAzhMvGej3f0ZcaFJu3aldgDAKRN5bK7l7Db4uxLZc9VINO86SVJR2s=,iv:MfrR+xUpenj4aY6Mvxq0BiuZVasnsiYr0gQ1eEOYr6A=,tag:cUODaa94B3HhksXWola4dQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
