prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:g1ZdtTONGbrNC7r/bLv0ed/JPybOUSi0WCUZbyJdU8fg7USvtq1nTfRmBGUZ5+oBU5R/0bIQrmGAu3cSnbP3A/I+50pLBXpgstyNDHgrAmmlSneBRh0J81sA1M4SE+MkDLzfM78EuNgDsoWuKIUDheAhONDCRWsyuvP3SZp3K6HuOziS704CQcSaHxI/X8jkovI5IKt+72nTwtil,iv:U39OI8pHS2SF2V05FSdEKQmppttfNTN7Ct+IJ4ZRKoQ=,tag:vQeOx6IXr6wDxkFhTMa30g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:KdW1lFOvSzofgDxViCrKWkwNmHtocZhIlcF/3gnRTTj+wOun/VHsPez0/EprW82OnwrKk/MXlbFrWhFMJDSZ6A==,iv:pYSlSrK5QXLdj6es3RgaLDcLxW0AK4Y4Ru/PWXmdq2E=,tag:cg5F/7kNOVicf3+GpmYutA==,type:str]
    password: ENC[AES256_GCM,data:/7QZu3NGlIXu8OmFBTWHRqwsBHhx6C4508nCWT1HGd0me4urFEYJ0LvNYIkEkA+0n4LvJ1nh35t2AwmzmLtKjw==,iv:TaD3FRhqFbC2qIxqxY+wqUdV8+8UlZFT8qFo0HzdPnQ=,tag:K+2zUOL0N+KD/DAQcJdV+Q==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:neQKCdvTxcFlsPoIN2XzRQbAook=,iv:6jF+5AiI0gewhdpFfaQGgAEZn2xdEpLiKpvxksVndx4=,tag:gbnDivvEHkLgKLUDH7QGDQ==,type:str]
      client_secret: ENC[AES256_GCM,data:YPBWDPTTaHT1O74tkSfDkL4jgD4OX4IDT+u1xICJxY1ROnL9/yplIQ==,iv:/I048ZEo5OSsV7CjtWQp8wHuCO17WKBn7pELFv2YItY=,tag:DT9IUyvrj41Hj6AzFw7mJA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:QWKcoSwcQzY/ueY7NA==,iv:YWIRowPlCbg2ZEnYW1DM3NgMj5zP3pdeq13qQym7PFo=,tag:biAfL75F3GUgYXjHdSCOFw==,type:str]
      value: ENC[AES256_GCM,data:ceyIVdcr/LU7Bbo+WdyLB5SZkYnBNAszgSbaqkKkDOUEytHFzE/1hLN0mZT3TrZfn2LSJAluavP0P+mzXHpSa+No4Fq9DlnzwF1n8phbwS5JFq6Q1oBPLdbbIXIPxHTxRFlBOXarr9xXqitDWWI8IxiDjxJ63emzhdMfbQySs0RY3V277akO7fuxDpxqcp7DVC7AiBeKSHHbL0PKgzo9PlqdYM5v0tXpIf3423BoiGAcBw==,iv:/vbtBGWDPAGCsbAKVEpkHgv6qu+JKH97tgwqMn7U9As=,tag:XSV6ZoGdv+EhQBunrKW3jw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:uEakmB2MyQKuAJUyiqsXKRMj1k8SZ+jsw0LHd/uL5Tts4Yz5FYcibLuf0z/Z7JHb0kfN/COpAXVsGpuvw4K4SQ==,iv:BGmft4UtFG5RsLrNOCaXPsnr0VTFLY+EstpfjgRRZ2g=,tag:qcIna7vT37oDCetj+m85Cg==,type:str]
        password: ENC[AES256_GCM,data:jXsjflOohXRD1ZCthn8h2w5jvDgbjjNUeZHmEXJmxsR58bUCcNzS4lfjAPVUOa24YH1GGUYvIJGqNcv3g8oM1A==,iv:Uuox5jN+jGLsGiKuBNykZ7k9G0tv+syzKhZyp95PE28=,tag:AF/k9oWttcK4vjzQua3ErQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hhCMzo991IiqZmhKUwVmJHh5XKEU1hFc5HMf9JAS7Y6YZXHaNzrzxyc7gUSWWibn: ENC[AES256_GCM,data:MPN1R4mByJt5s29kXuJ21nJu+WCtaQ/WODOn3UY7Q36BjWTB1yHQ7nHjiLvl85nEalyeHOzBvFgLXEDZ,iv:wME7g1dbpLpPQnxPJJou1gCgpuQ9RTuRxzDE7S1q0VM=,tag:poE4j7zMIStYMQvv9HEqsw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:00Z'
    enc: CiUA4OM7eCtVpQ1GKKINgevMkDmOAqKbWWLSJ2gDAbZiKLG3/CBtEkkAPHlbma6XhD0sIsuQUlYu9WDtAL4nH4GMJkwmbgjO0KMzdxLpeQZlXJJWOKV3Ye5dklR7aAeEgQD3VtzN4wuchObTXDytGO/z
  lastmodified: '2026-04-16T19:33:00Z'
  mac: ENC[AES256_GCM,data:FXxJJgaZEQmXrXb+LuvNIdIEMbZBPqlBCVo3Vp7kgb04TkH1F6Oc4CesJchS/fLt/jhXIAuvIC22QEbf6PxxFpDgjjBbtxS32C4GfTpSMebP9jx9CBLnXSN1Mf2yzTK7no5Ukh6NOCctiIyRbxV5g1Hpu5dT4RoZQ0m1zbNMs+8=,iv:insh3THyJpmt/H7mc+ha7k4hUJGz9jGTsuWkhzl5UHE=,tag:d6vmKG7toQJ66zY0Mbye9A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
