prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:KUVKrtCRj1ctK4g8QeSIPYCpDguwTJBuHzDLnMd4DcbJoEaXjQAMRlXzl6Wr+5kv4Y79E37JOI1CPRNU1u8F/O0kH8A/qm0Wv5GX81VqUfYRcmmybXDnH86gZ3RE9wrvtJYxDArJNqArwAwWSiJtnS7WHw3iDIaU+/FnHs+hRZa0D4wDnAirrcCpVSLkUNBRr58YmFwVFzdbwenB,iv:7FDXUIwW3tdzDNLadZH8WujLvwB1Vn1wHjbNEaYZU6E=,tag:MYjAwUuj2oJgEiA3egswlw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:YtT/dIKpiEXWI/xv9w9sppk4ZLbqbQilEZIrWckQtQBatM1VCZuTIZdFvIIQ5LhxcRA5f697E97r8bPx3xbr2Q==,iv:PXK40uV6sgFLetf58BoS4sdQUQy0/D3kQGcTw1wGWSc=,tag:9mOdPQCVUSCH7gp61QkboA==,type:str]
    password: ENC[AES256_GCM,data:0o5m9Y2Z8HI+t0/Tq3SD683bKz0oSlJD1Xlq6OVKpv64nudcRiBLOMwixRnSHWn+Ej/7Hennz7qLm+EckPZadQ==,iv:IQ32VYrXHOWPWK5q6UVJjtvHi3EYHee1UpTNfX9yxfw=,tag:44nbU/1sH+hUDaYRqwaUhw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:2LRQd7NjFpLzFtYFqg==,iv:LZLdq10JqzJWCWKfk13yoQHgXGrDk8kKb3nK299YKRA=,tag:/x9L1GeA0Yn1KfimSjAlNA==,type:str]
      value: ENC[AES256_GCM,data:G+c3wev7dxIrA0jQ0jdJca+8Y/LsUUoLgpWlSs6qsOvKOJ/TQo3KKjjgE+ZGZBhqtxY7InIIwDKx0cbMf8JvhVFNW1yldT3jzrhLRdlglGECa/BKmFTYKrbaor3iN2++vKrLEdACnM8mti8wh4W6OAFz1ap+bvLdPAXPWVEV6A3/ozFgkzK4prH3BbaKLLDVIB75Pm8mNmTe59eVW7FPGAiROzWu8Dg7cebYNsbgYarn0g==,iv:qSqERrjEihirtYwZfL3cmi3252Oy13yEqAE84KxWpyQ=,tag:Fx9l75G2zYOiRlORHCgbXw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Z2VVZkPImRGhtF34A7Wvs1KWxzAFyM7zcUsAHQdERI4A+2XF546HTg8ICwrZtCEnYWd+C1TFVnJwEZgEy47H6A==,iv:TVk2WhUi/aRCrQrjrp9zPVprs7frq5k268wxKcRo2HU=,tag:ZDtv0AX4hhaG9gncCKIHTw==,type:str]
        password: ENC[AES256_GCM,data:vVw0dxw9fiIsuTrCAZNLo3mNQWZHDs/CJuicc3/Q7Rprhlpn7dOHEMEWYUsuZ3iDw3npwjKtKwO4y0lM01Tzig==,iv:+xUWdTVw01KpWcwVnhWF23MWCWmLrUvODQDs3T+E7pw=,tag:lxjyIiQlRGnfSBdZCave+Q==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TveoCKkfQGCm06D6RE3ZDWc22O4cH4SBtpwODvbXg3EqgGRJsPyOpigl5Yhj6iIq: ENC[AES256_GCM,data:vDsUnbhJXVyVXawfWWEhK3mk6nOjjvOy0BK7Bqm9xWoUhc5SS5L5xST7m61V1d+pJ2LjI7Y5NQx8tjfz,iv:WR3huYjToX682A9JSo7xhoHWyZ/jWuo7pBrnwPYm7mA=,tag:tdl/kTTsfZ4Sqn3UTvR+Hw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:mg==,iv:f1z6WwfvQ6vIybkYcYW6w644K/ZEFGr68pMgXSJ1ceI=,tag:AQBZIYcbphFUYQkAefz6Kg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:n2MPMpIHJLxNuQ==,iv:AK2aS3898kUe6leoV7f+l0dbXMhLakW9CpixEupKi+Y=,tag:+Y07PyOKat72pyZtTs1myQ==,type:str]
        orgId: ENC[AES256_GCM,data:hw==,iv:oDYQ0NkOyvxRR3dNHZdOimtYulrPRRLEsVtXK4gxcp4=,tag:TYpp1lvD++a50GZjB9zGVw==,type:int]
        type: ENC[AES256_GCM,data:lGjyQFlHHYr3kQ==,iv:p7h9vbb2A/F0b6pDua24RX7Juia8XZgD2BHeZpfiMNg=,tag:UlKkKkYS2LjNcyKMz/37tQ==,type:str]
        url: ENC[AES256_GCM,data:4WykZJs7+sAHhYnPWbxVsnYPjQ4KnLZnJiUCV5SRe6I=,iv:yIM/sfjdy5WpHIvmuZrADvD67yfBL7l6BI9jl1MU4Io=,tag:NKJHUZhnaeUwbEcaBLV+6A==,type:str]
        access: ENC[AES256_GCM,data:rCDDKyQ=,iv:1XzRIw3rkq57T1KxKko5O8bIa4cGdbGN8cwUpSTUuBA=,tag:Uq8p+ZJyQZiBa35AB+5rvw==,type:str]
        isDefault: ENC[AES256_GCM,data:hTnjeAM=,iv:LuBrMj60eLJLkM8NyO1HMQh8E9bydgN4UM+F7IPN8xE=,tag:vsmmG/ttSnvANdPA7rG7Vg==,type:bool]
        editable: ENC[AES256_GCM,data:7UJAl8c=,iv:NJn2S9RbnXHe4n16FdN53c6jMs49bWp/0BGG7rHGaWM=,tag:2dxEzJgfWd1W4TwU+XTUUw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:jx7jJQ==,iv:InTbmYm6t68QkVFGYbRWEtXmoZMWs0e9PNw1mlOYCbs=,tag:cAKwvPU2rvVOQ2WNmHa84w==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:+0ju1ZifCXepajJ/h+iKTmnlzwQThJi8vr/cf+hfV0xj5VAU3X09KW1yie2Cbf0Er8elR12gBqO7nkETYhix6A==,iv:ktv4S4J9Ru6eBtFFLyZVXz82HOYLE0vTNTk4kYzDC4U=,tag:9P13dUS+NCSBoUgtYTCQ9w==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:forId/brOMC/NUhZf2hyLFm+TkWC88JeSsfoWe2Fywq4LCzFVVbHxj++gsEZNh5XeWaKkjR3vDvSjxJoeEItFQ==,iv:Lfe0TDmA9gZNIxupuGfPYGgpPcClghK83Lo44CqrUpo=,tag:6zGwPse+h8pb1JsshCXXtg==,type:str]
      - name: ENC[AES256_GCM,data:ycMvZzuCGkvKOPMJu64VCQlCXWp1SZV1QttiFw9KUg==,iv:TmJqcu+XGB4RICshX4m9i3cfHIhBWnrOgxpSAitMHHY=,tag:ppiBovQ7uMOnOOtvU0rIGA==,type:str]
        type: ENC[AES256_GCM,data:qJJGqn/V2Z5iLx0MpWe7y77GIVDp7WB2h1QT0QqvWA==,iv:MNnm770eCNCx/VEnPn1mi4t9uae0sK690H6V7WO4FEQ=,tag:bG2h9yfQCSIh3uQbDPQSOg==,type:str]
        isDefault: ENC[AES256_GCM,data:DbFHN50=,iv:OxBrrYj8489/lQB6ybekeqjv/cG+SlyV9+RyaQSRSIo=,tag:m3ul1c68VYFCrxnaEsgkZA==,type:bool]
        editable: ENC[AES256_GCM,data:+AibuQ==,iv:OuRDIMSkPZ0REfbnnLWIkIdD+RDEK0/F/IxaPsA3aIo=,tag:Doc9GcN9e5pyxDp66v+fCw==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:30Z'
    enc: CiUA4OM7ePO/uHmfVMdGJTms9tN461/TkCHoZWqVqvrL1KCR4B7YEkkAPHlbmY64xk/rlPXlWjbzzQHASbjkLah+r9QPylo9rUvR494TwxEIwWA/wUusJMe1vVy7m1u1j5JC5l/FEboZYsj/jT7+kmY/
  lastmodified: '2026-04-17T08:24:31Z'
  mac: ENC[AES256_GCM,data:Y4SfTB1gWhwqg/q8RTt0zt3hgvdbsjdYFpxYOZS6rZIZDS1NHTi79F/KhDtOlWz42MadbN1g3FB2TxY707fXWUYlhsft/kD4Xdjg2/FoW9aLKloERmELblcGHTZcTp/wDapTG7zW8BTrGjxpL5F4dIPRbbqIBbDCll090gNwWwY=,iv:yu4K9J6XX5dEHFUZ3TB1Gxi+XRNGD8ibu8U67ob+N7I=,tag:eBhWuZPaIy81y23zmEJirg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
