prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:gGfi+cfSF5Qk+Lk8BhmDCVVxtSTdE/PVfuNaNlPG6lc7zXZR8xoEPaBGc1yBYBYTwPOPU9aMtMcPcqCbjiXP2iC0M95+aLXFsOr6nThn2iBTLBCBB9dZQ3Cymb8QcB+4fQ+1fo9OIdotAQ7C7rr2kIJ/aUiTdg1rNMxgc5kix5n9saTh/J/shZBmeyw6UyZnERzqAhrcyoX4nB2V,iv:HkPQTY4saComuVi8p/xIMkyei9k+So/xic5M94GgC94=,tag:gruQ0Z9029RWXhaYTUR72g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:mebgZXzuT4lpUgwfplnMicJLBo28JXQ0O0M1DNyCV1SUExIHDVTFa3mggBVdsC+hcrVUORNpCUwnauVcrVsbwg==,iv:DlBkIwvUyDAXJNGmZSDTBeog2beTgYfHe8imd7uei/k=,tag:JljDkz8Cxx8IaTxzTM4y9Q==,type:str]
    password: ENC[AES256_GCM,data:jMhrUH7EH5lN2ykrwIkj0jzetGXiAFrVTm7+QdYFERAt/gq6vSoOBmA1Gcrv5RbkE8tjldShzGRvJuIcJNHI9g==,iv:EHqj2xgwqSrevZqvqT2+cooUWQX8pGwaeeCMliMhQ1c=,tag:xUKT9C31PXEzEnxJnRHPtg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:XJ2RopKP44mEf23XXw==,iv:2eE3EB0Y05layEighf53/z3KrBu+DO7UWMYsH2BFMiM=,tag:IN3hyMSGX4Cz56f4mHtF1Q==,type:str]
      value: ENC[AES256_GCM,data:iIoDrHVsgFrRL6MklTy+ubZqydkE3ximkNmiMw26WVzh/ii5FPpxGGGS7ywlvTC43psLhdHY3KAQJJaBR7Hnw6Pw5Gb21NUm4J7n0e/VIZzHKGQicHxKWa2Q14KBj8pWnZPWveDBKkx1i6+YCV98we+KxvOaTWgV5CnOGZxZFfVr9A+N08JT46Ae6cxyDJ9+kv2iaFXDoOBU4uSsfj8sYPKbBdtnReQqb8NceQ3SlLodYg==,iv:Pgv0h5b22udpAWE4rf8dI+55h1FLmquma+s7NxmgA1E=,tag:pvJHaowZ3HA3tAvzkzWqiw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:SFBxkMZ3W/MW/JkQifWkSQ/0PB122mYfAaKrKYCGdhGdBQz5/JgdETDMxw5t3xzh5S5HgLWS+We3hVZ0kzHdKQ==,iv:MyhlO3NrSTHU8hLxdp5496OQtIPoWc+1OictUdXWwGA=,tag:DpQapscic2+mcauLedlrEg==,type:str]
        password: ENC[AES256_GCM,data:Yb4DLeKT11eFc49HiqgmaW09aK7S7zg4kRUos0fPftx98Cz4AD/SZwDEXX/mK/FWg3Zq4iwM3VtWMNFmfwo2/A==,iv:Hywul/NRkCkn7HC4jpvET/uS5to6h2at8eWdIAzi7AE=,tag:MyWddTlpMqZfu8RcMR+jQg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TveoCKkfQGCm06D6RE3ZDWc22O4cH4SBtpwODvbXg3EqgGRJsPyOpigl5Yhj6iIq: ENC[AES256_GCM,data:GA+GMaJLnWhJ9GyRqPloWtR36DpsFBe2eKE/n4EcL6ZRhSl2WwtPnwOo2YDLwnK/BsVbDCfJjeL5gVj5,iv:IbVeFd88pAc70p76w5OCl15ZUvPYMsSfh79N3bZAJqE=,tag:UM0NeBHXUo1AscYbpHI2Hg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:06Z'
    enc: CiUA4OM7eIQOomC60KekGZ6Ng+LMH2wI0frqW7V50aRaX/nriYI/EkkAPHlbmWcNngHF+dbC8GlZcS0GsvPNMcecjNF2cGyhFzrEqfsGzqlHZKCAvnftgXmVN/+jlZcDYeg6THBmxT9MFiWlYMe41Stw
  lastmodified: '2026-04-16T19:33:07Z'
  mac: ENC[AES256_GCM,data:qEx9MhT+piCDKwhq4NK+RDC0RGloIZRXU+jboU7TlFrN5qjSuo5hfkwfUvFHcrDINn4w9v8P3BBY+iJzjL0dDkAwjq/j9pOWIRpvl73Fpl0HB320Ypgl2JMUjeE4DDBwWTy9SHQz6jN5Ab2tGsW5ZmS+viXzURaRh1ViDGYvQTc=,iv:InIpVV738liBOlYB5Zm7F5ppdw5qetjrg55lcclocfc=,tag:8iWUOIwpiAAbhsBRgfBFLQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
