prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:QydHF0wC7E3Hf9pa+OxznU4FPwKAkY4E2+Bt44726l9kZykZSxN3S9xjnhNjUVaSxX27MHV3hSyDjSrflglOJ/5u16wFpXRrjar9Dq7j89yXKG+ON0Aaxv4J/8tok1io9Z8JP5imXNHuA23jWBlePNfu6KME+cZE35jASl/JtNmx+wgNmZnjAfxxA9S643Jv7utKIKmQROvcWoU1,iv:DBIhK1oujR8ZUzOSzeMVHwNRKfvQa/eVZSSJ5EHiEA8=,tag:qmf/4Tjca/E4o/2jeoGVUw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:R0IhtAV+SYxXWQu34Z33MEB7AZIu/rgoUMTAqlOxJnP6KB84cJxYgYApm3isRH51S5D8/vyDJ4V+Fclstnp5oA==,iv:ojITeC0TDCrwPboQ1yXeVGcu7nq5+5N6ETA+V0SMq78=,tag:PqLexJOUC/uU+AqF6tt4Kg==,type:str]
    password: ENC[AES256_GCM,data:ri0BN+UhmLanruWXVlIJVPwDQQUy+1o1feGix/WHckZD1sRmx3kbOr49t4Z2+VCHCBd9UfGG8YwGmfzd/0w1UA==,iv:TsGBUy+iPf/2vUXXpThFQgjrEfrhn243+oEtNItaDmo=,tag:QTzeuTrfCfS0zsvM0G1jkg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Fg==,iv:N3gewEWd6TxLL1rLJrrvxICC5m4Nnj6VnTu9AxFdfS8=,tag:FCg7F7LCYhXylFcAQFTxiw==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:xqqTkh7XVTGT6g==,iv:/QGUSDFhmCpd8APU8yK7vInX+W6m3eL5rpOKK1JaVO4=,tag:CeJpkwFVUxsJtj15gkKsag==,type:str]
        orgId: ENC[AES256_GCM,data:NA==,iv:xbT14096R56/iHYzYvM/q/IapM/VHa9mff4mNzqy+48=,tag:tI0PnkBZpD+CZ4wUWxcnqw==,type:int]
        type: ENC[AES256_GCM,data:eJQWyuq/cs3Dhg==,iv:ViOpDsnTwk3GOGla4yNUp+97NfbFZ+/3KBkRmMRsKhQ=,tag:x2xr+B4oHT3E3wQqyZvC2A==,type:str]
        url: ENC[AES256_GCM,data:Vu0PjRm/19m3xvf+utfPtHkeOxB8U3PJ+1FW9v/Cris=,iv:At4BxjCnIwMY9HSCnmLJXoeITuIFgR8NsCbsbg+1DIw=,tag:8pvVS0/CpURCa18f+aJCtg==,type:str]
        access: ENC[AES256_GCM,data:bqwtebo=,iv:svqxsQ2qQDURdfE6IcaCoP6HePtNEJaZc/8nGYxP53c=,tag:fuI1mxgVOrZk7bKJR7vCzw==,type:str]
        isDefault: ENC[AES256_GCM,data:JKJ2RI8=,iv:oBSn40567V6Gr4753QGisAaZQpofaPZmqfQmKktf34s=,tag:AJFqCTtjdVC2FlyclhUXBQ==,type:bool]
        editable: ENC[AES256_GCM,data:gnrgEIE=,iv:hlCYL4BY75yKFUZVHBelBxfQS/FXhIHSHNqp95uU/wg=,tag:5/ttnioVYkZv0mLwWfaxfg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:KYJRpw==,iv:Ke/1rLjgl+B8JYM0I4C4bbaMZIhiGpL9uMj0HXYb0ic=,tag:IeC8dvdjtQZ3wGEiq2th/Q==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:mnFQVx5qFTWEHt4zFj9AiocRnAuGs3V0vNZbJzehbuAkWFgG8IRxJ68Tr2xQyBLh5NSIe7bxTbWYQjV3VBCD+g==,iv:yvO7ui2fobLXmBJSAn3bGUx7GkJLxR75Hh+PtOHp7hw=,tag:nZP8wvdn0jYBvIGyIBYMNQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:+LgUOiLIS/hc6xJav5tVRMSaOoAPm2ZKT1OyVZVoxlkKPqGZiPZZlyQSdsomGFWKt8dmf05EHNq9vDeDRw9FNw==,iv:bBWgxltxwgPGsgU+kx4YgXIihK8690qqE5Pte0ONM1s=,tag:onCwjVPY/GyFE7GLWX0kAQ==,type:str]
      - name: ENC[AES256_GCM,data:d5bcS1BqL8QEpaRio1fDuqh12JgaVOyLydNDYEBg9g==,iv:nRCui/RMrpHW3fLVq5io6hAVXjjFGwKsb13W9T/nCHc=,tag:oXK0TZUciqbtTZM4Q8aGUA==,type:str]
        type: ENC[AES256_GCM,data:od+zw4DlAPcruYhYxkExtyXIOiqbHb0WU+J5hsxQpg==,iv:9dwPTYoBmh38O7b0lwMZZ+BgHMO3wltdaFylBi6iTg0=,tag:9WAbGJoeYI4RRazlXNfQog==,type:str]
        isDefault: ENC[AES256_GCM,data:8BDcHXQ=,iv:khJc9rL7zdbQRtrm6uj9rVTkJHch0r5FYosrd1MOg1Y=,tag:uAIDuOuFINJEcJ25vFuzZw==,type:bool]
        editable: ENC[AES256_GCM,data:UF1zkA==,iv:37cuaPZHq300mn5Sd8gb6KMK0pzd7Dp7YFvs443UOmw=,tag:RNLN2gbZf2IT60dLcDbYGQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:FefqxRHQShp6txJ2NQ==,iv:pMW+ArNtrCb7CV1DgiHMEtBXAnQDWt+mASBjf58v6lA=,tag:lgCDmNghvFYHeZRTK7IZBQ==,type:str]
      value: ENC[AES256_GCM,data:94cV24k6AwjHFUnElZF8CH+LJ5iJUL7OSkjW5GjZpNv8Pv9ezW7HtAI8Kv7iqidnx2f2wZfiOsDY+f+HXKp5kwLPymEX2HpFxKlo/zyN8M9wcHT49mOrhurdF+JxguSo9Yvbtjf0qT3nP+Vlqc49hMzXsAxeMvQfS5bXQytH18cs6kqM9mNuOivUWzYYJJ4g32ZSiLAOCW9we10x2cGElD9l691UXfpWrJYq/p4NzTGwCg==,iv:Q7dRD4X7i6g931xDjaSE24VOhdgRkIHZP6rsk5Cbh10=,tag:56JX2MdbEWl27kaYLG1zgw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:tV4ANGzIDUnzePEW6EGa5bvQfO4dtRX4S8rMhPMq419syeArooYVYIbegfHlnJKP4bZkc86t7T21Yu0nHSZm+Q==,iv:CisKhrFzMbzh+qX6521BICA43+Wf2fyeYFUwS1xLXtc=,tag:oWt3kUJbPJoPzj0ySgxYrw==,type:str]
        password: ENC[AES256_GCM,data:mK5ZDam2qi80xCuWdD6JxZHB7u3UM9e2FsroLnS8dtx2pt/eFMsaJPlmHA4oI4X3/mlmqla2fapekOw2X1g12g==,iv:7RrWPuyE98d08MfRFVvySny4zv4huLYqzVSsl2z3r94=,tag:rrzmIx0ChNGjqvWTTV1dhw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        aewahche8niw3Ier0shaiwieMaim4phixa1Yalu0sieFohdie6Ii2TaecohJo2ti: ENC[AES256_GCM,data:n02YUmsxLykn8knW9QiXK3h7wIuMGKXcXEutksod+adbBD+hPLlbYnD3VeOyyPUnCV9k6ts/p8QZ+Ull,iv:bhKBNIvbl2ZyXf80vjdlwT99IAWW+s0QT64b4y48bpw=,tag:Q0qnuJcuxe50IEKOJIIiKw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:46Z'
    enc: CiUA4OM7eFDVlMgjzL2DmfgQ58LzWtkZNcYCy8+FRm0FFdEhj16eEkkAPHlbmaoS6dKQgb8mHmAUvCzaZHAiJC4t1ND/1IaNmLW1EXRGCqzt+nuoX+qLQo+rizVk1CfK1RPFdWFOc1Gs+2btvWWU0Aeq
  lastmodified: '2026-04-17T08:24:46Z'
  mac: ENC[AES256_GCM,data:CXH3yTL+oATGsLQaIevPw1wwEjrBh/jNZCZKBk1W9ma/AaWgLwzcBwrRp4a1yn12C9JSH3S6QZwK4LFqGyCci/6N/MM0MRcfw5zGIImnqe4YT+gRJh7Z668scLLNXedbp8kHBgrEshZPAAcmDMKVRX/bISw9Q8tU813jVKxxaPM=,iv:ZQyWXPKWoeUnsvs+ffUweT7fzctqeJGNXfS9tKJLdrg=,tag:aCxVd4FeMZ0PSRW/S93TMQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
