prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:ataOo0Zw3Ahmqw6mDqsVp7+nSO8jItdH8MCZ30Nqq3CfVfWVQfpG1gmQ4BmLT5+2V91SgGJeshFiJh1CAashPnMOiSGz+dpSbrv/wwr0sWhqWpqwY8qkcg5csJ21I5HfGu2l4HUSJt73y/JLrSL4zVGJNuof0dEigh4htm2iUxubVhgjkKDek8za4rcSP0vbgA4wbhzMg9xa5T+F,iv:vQCIFYV4Vuzy9viuXF/xpfBOqmrWPjy1/TnfL5LiP9M=,tag:RStHo7Kx9ov40KaT5pEptg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:tEOW2VWuBJkufpdWQRidhavmESeLu+KUQ+ub4WBij5zGKgzMmIy7yQc8//x5JuuYfv0rY4oVFWyJPTVEXk6ETg==,iv:9fl4egRzdEeEsE9QpYIwA/SJHBnyxyyQrY7gyoerfuE=,tag:UYHmyHejnoR+EORVoCmeQA==,type:str]
    password: ENC[AES256_GCM,data:e+dNfKr/+e28ozIt5+vuGWbmif++iRdqWI0JjsrHaijWi9BKIvRVSHF0ZnSJgjED4bSTJilCllLrrVf9GyPR+g==,iv:obyv37VgTFusbtJDpiMherIXbURdKcg/Vl9jYEReczM=,tag:AD5utSn403c2JdlsW6PKLw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:xoLGApJ1HHdMgJuBSAhBZAJnTMM=,iv:u1uejFbi7D4Dx7DAr1STH9hYUCDK0Q8urGW78i1EQRQ=,tag:9vqFxSBBEbKlRingoCnHMA==,type:str]
      client_secret: ENC[AES256_GCM,data:CRf+WiNoQS3jPsGvgOYXTlgqkuhKvxsuQryDl7/BQeGqGywGkBkzlQ==,iv:wCcpnJBdYOdz7m6XU6E10OyHdoyN5+L0aCHZHF3/NG8=,tag:RHbKCYfUU7RcfxpiZXaZgA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:4s1BhWcnbCNEUebvBg==,iv:2YefrsFW7Y05Fi7GuD1VYy4zIET1ohsTpY+ojcqH1EU=,tag:UOmbAoG/R0klSk1SbxhHjw==,type:str]
      value: ENC[AES256_GCM,data:yqEy68nBOhu+vwGMjMCd9GI3950EBJKRhz1FP3JV8CxuvdSVkNdHGLLx+jvQlT6+6CpXRYLUBh8PxP7gEl+HLfq9Jo7lBB2Dn80wei/46+v7l//K2HDrF4Q5JmXoiRF59K9idJraP6tVq2SgKEzp/5vC3Czetn9UlgAe3nWPXjvD8+zRfP2lkDPjK0JN/LtR4I5Dlt/EE/zWP3gKR3UMGr5gF0nTraE/nZEm9R1KP0RtuA==,iv:on+9ehQHzIUm4pez6Y33//ixoR7YyGIf09f/ivWk6J0=,tag:sb8l9THbTkqUzvDUK6z3ug==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:LtTlbH51LGyFc42mBxsRio3NA3jxeVwbcH5tDGhLmNfPI9md7HqpibLYUTAxCVNDiqZEsHJgEmYL7ybrCi5m1A==,iv:P25Jyb8kkz4tHGde5BjtjWl+oRnPdkXDQznh8mIK+jo=,tag:iVTgnXmCHOD9edegSGttFA==,type:str]
        password: ENC[AES256_GCM,data:n+RpFrh8Otj7hv/15UjPBmD7IzsKNxkqP0U54bjLMycLgp+VIknNaZrAswZdPH9bSFn9oqmjTYMk73BMjh2pkw==,iv:h3naLmOWTuoBPrTE44ugG4rdF3ymGBS2+4BWvs5FMB0=,tag:ujQIp+LvNvEUmwxhoanrEw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        aewahche8niw3Ier0shaiwieMaim4phixa1Yalu0sieFohdie6Ii2TaecohJo2ti: ENC[AES256_GCM,data:YxiFY/meqNzI/5oqClXJuVPVVl5s1lDADHOQG2+dHbCRcOWiBNdicxK6w/VWWWXPuI+D6Seud6lfLSa5,iv:I8ChNz0gN2b+Iwuf4Xpq2P1LUkDVAHdnlimk3O7/gKo=,tag:5yO1rsvEBYdLueIFq94XdQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:22Z'
    enc: CiUA4OM7ePJDUsSY94WhUSO+SLCp4G6XxiC56HWep3pzl2Ikpk7+EkkAPHlbmfAWEdHa3KBE6D/OlhxOCT3Tx7mekf9hrMCDirIxHSQKaH2WhZpAi4fLjtxrU4thkxOz4QE/vpqf/rPIjJCxabsGxK78
  lastmodified: '2026-04-16T19:33:22Z'
  mac: ENC[AES256_GCM,data:R1W5S2nEKOrwC8ilXV4tQUPrSTIQRiHEld1POFA6vcBibIp2GQrhcoglgwjtqdXcFOSqHXB/GqtaqPQJc19nzfxSu42dwsez1Dlwv0VDXbLSourSK9B6p1Dbum40toQXqyI6SOl6l/au6BigOxmGo0VUOan+dSfrfPljpDRdTm8=,iv:fHsrh+bysRY77T/Jev2BcLB27914X3GsfRgwUdcL0MY=,tag:Nk0twhH7RDjbPZc3mb7wLw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
