prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:wJCy0QKqgHZSDYCJbiFz1clnlJuCPezFM+tZAUpCuh8GQ+wtpim60tsOy72wjPziOdXLL3uSF8vv/896tTEhA8mz6Fkwm7YC4AHeiEWikV9zyVLYmlxebXhq8ic/qXwH6kF3YcEjY2otufjOsd2GDA8ZSoIvkE0CKbNqOa3dBlTphNk8qV3ZLDmDLI6/mFiCCoLZheIPOwPIiVAq,iv:XKQU54T5gs6mHsXz5+++LU9kd9sINeW1Vp3bDM8lyFY=,tag:cf4J0L9GbjOj3LuVG50lqw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:UUBZndas/mF7pPrZBcyJiicslAX31SSvtBFZCuoS52hIYjsoiw0qj+JEaKETzVwueuhkgay2ZDR05MXSPQcZWQ==,iv:pfF3fbF1QoZbWmFrCFz/0Vfs5E5D+2KTqV3aWEkq4RA=,tag:uNRo/2ScgiftszGoASdtHQ==,type:str]
    password: ENC[AES256_GCM,data:zPj7pNC1pvm/gHteYhE6NhmfJaSgGTyFpGNkae07cPDHtfhiZc1HSA40nPeiMwdr0BxSG3oihtiWZD9m6QDAVg==,iv:aosFcVHZn7qMAv+JBKhI7HcruxGYfy3oDf065mefQYE=,tag:b1+esJay9SjsQBaSmRmc5g==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:qaeYh9Dmk8cjD5wt6w==,iv:Z8Lc3ukiqbh286O1741Q57r7XJK9X1j8WYr4UYaP/eM=,tag:LTEqm2TsufununrY0XRTUw==,type:str]
      value: ENC[AES256_GCM,data:QsaOllTvfOKpS4CDgVOVecJdYnTGqPDwcKtxdwblWttsipx+jbP7nn00uLD2M3OcBWMnIZwGkZ/Eg/huVcFRekTNxRVl3jXLkZOeqP4OsOAKOdbeoZv30vGCdnQCpgNXWmrPhhwDBy8SZ59Fj2kk7qV29PXm8XOkMVmdFNFaAR5sqA5fRYwhOs2JLX4JCKsQfQpvyBTNnecHiynZBlIEwdFMxafSbnDp2uXb/2zFqSJxRg==,iv:qC+9LyRW9mS1xyIDpsPc2BpJkNrfdT7chNRf5CRsD2U=,tag:X6Xsivtd2UiMXnbc7B7giA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:VEf8/kwOHVsc2WEzpMet2rP/CUgAN640uol8qvrehLTVBG462Vz/sI9jXe6XIZ8cDeOvFpPfaP99MfV26po3Rw==,iv:8qxZtk6URQa7STgEuS8ei41mm5tuL6XCQcWFNjceoBM=,tag:1r1DlpwnwEK2x1kfKVbJ7w==,type:str]
        password: ENC[AES256_GCM,data:LP+QKoZp8Pmi2XlI1eAvnuiBkrt06YoJQRMdTdn9hKNIRjuqj0gQTbfaPdzh60dnIQGAzKU2MJE67LSj4V2O0w==,iv:QZY60OBKh1WpxYKec86pfLkypKoqdjWNI334ErWAr4Q=,tag:q3xiZAQ6iDhITpAs/iOxbw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TRZdTFOy4K4FSxvLNImzO5NCzsXcYAHBQbAzSDZl9nG0EpE1dLUQKYQqxaKqiSjy: ENC[AES256_GCM,data:tvHdVEj/wPy29VaaC0qyWpX98kVy5cCywlkXeYFbp4sCJNPfF9IMtPsTBGS/sqZVmFokcrqdCJ83jX8y,iv:QB4rv0ij6wBlbo+ZT4GPk75fF20Mpp80kRwIwFrWtnw=,tag:yWQnm8s4FE33wnZiLpzOeg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:45Z'
    enc: CiUA4OM7eJwkfjPejiNqgcBgXeU/BTYXRjlrpQnHxFcuJRiboGiVEkkAPHlbmQfPksMFMM6W53RyKpVWZbdlR5Pc0iMFX/fwSrDiSLEds1vjEMx4uLSGvcWcLMIhV0NKqyDFe01TeN8c6Ejn/z84nAWj
  lastmodified: '2026-04-16T19:32:46Z'
  mac: ENC[AES256_GCM,data:xTr0j+/u2vXqjQaotz4g+Xw+curlwr46Fs8W0eLv+MQjVHJEeTBsirxPrI9IeiIf0RGbEkugSc2gbh+NSI571fDLfXjAdpnC4kTn+YCkY9CyLSgLy+cHKMXLjPKDIC8yiyYS6HcMx4oAUhAMS55TaAldCV9aRt1tQlPaCh4ALcM=,iv:RJNdTkNXge0ek8L23FwLp3aV8KYit4J3ZyEAP1mfPJQ=,tag:gnNzCLBXl0RwhTAEF3shPw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
