prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:Yom+Dv4lcBNN17e88dbC9Zd9Tvm5TzTu8ntD96puMwYEykgBW3UZymr1bIKKF4MXy76LTL4AhSg2fqlDP6NHJOZXyaXYMTmQLxCr57U0XRJPH2gWR6LNSik4Ql89KOFyqmyUV/3HuZ+2lgI5GEEgiCrIyuQgrHxiMtRFF5H1iYCku9Gt3iPWLuMIQprFGJkkIg0RsLNnyVlLyPQw,iv:r4V1BXcMxoG+xxKYA6C2ZvtROYrxzFsnH3FMn48j2TY=,tag:YfwAaWtVzTwLSJ0JVJmUUg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:8AVQNuPNal9QxORxdY6V78MFU5tBIiXb+DEwlDZTR/XrBVYKq21o5kcumhwZ4V9Uy2cjMU6MBNmPnKzBT2lwmg==,iv:qXhmb8ZXFLcLBUbmSwqfqFV0pokHoIJePkD5z0dyvbQ=,tag:oxKhG8rI0tKWny2KM7fqeQ==,type:str]
    password: ENC[AES256_GCM,data:pZSZOZEwZ+nsC8b6/pM0oRXthPcOGFyloWz27JsxJomRq0sIB/fJRCPaAg3ltxeDp7LnBAJidQZJu4hbVC4OyA==,iv:KJM9dQROBFurTQoFijN1yt8RTjljBmalMm/65IKNjKQ=,tag:Z1gVamluj4S7XdMGyT8xlA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:i1+3vAibZ1ctvY0eAg==,iv:0V4f+JnxE9xNFCtUv+iGsYRgle1I0xJKGOEnKY3vJHY=,tag:641Dc6rcEC0ECLPxSAGuuQ==,type:str]
      value: ENC[AES256_GCM,data:bUX744JSH5Zned3FuxjCp75E8iHqJ75VVL6QZj3gY90U9zWVMlWwib3PKkkVlmwQ9OCBs9JhLkHY2TqQ1lkbBI+qDLgNfa5wYYn5Q2i4H5Kccr0qektaWOByNayen0uQyAD01w18n4Y2yAAqbxLUpuwMsndHRVKs2+gO6woBQnNzOhDNVTiITmi2lXr++cVWhZXELicK/uxlPtfgmQ4y9XDuGEAGEnk9fWZ94RX7U47uNQ==,iv:RhbthXpyYrfTHIHIQZyjbzDmfm832OTI9tY0IZ3YymQ=,tag:RnVDHNwbLrVqim6wVmeVVQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:ceFaHMiZWZm5qFBunBFl8uBgc9cbW6IWe0ECWkFP8cMn1/puzNEdieKXQHzrWGWwej6t2wjVjQlunv5z4+wggw==,iv:pkmPQW3BlZdLPwKKqnp7gMocbRAIPgtfW1Mzi0Vv9w0=,tag:fHlyps93Hvvm1SnncsdisA==,type:str]
        password: ENC[AES256_GCM,data:n90Xzt5pHR1PVUoxevjt5Zdp1sR5x1N1ysR+Cdg6509ssgNtZMHBojrBOZJsEr6k5Apl/FymRm35TF2j/aF9aA==,iv:sKpXf0T6l+4qZbKo+0/TkrI6PQLeRskGBFQs2BI2Y1I=,tag:7qgFoVOoMbg4rxD/1qAoZQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        TRZdTFOy4K4FSxvLNImzO5NCzsXcYAHBQbAzSDZl9nG0EpE1dLUQKYQqxaKqiSjy: ENC[AES256_GCM,data:wdqyeFyrTbPcj8DSRfU+mP/+Fb13YccsiweiYzi5AWPPBpYoLb0rjcd/ynrVl3Q8rSzjVtUcRyUH2SNA,iv:VBQvtJ0jCtIGw0D8cs2UssEgNpbpNAo6DCn3dnYNBGk=,tag:dNyTcljKlJ4r9dyImVQz8w==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:8A==,iv:W80geh6C5zuXxQZ/mrc8AAJ2OtsBheKFZtQDM+sJXDs=,tag:tvbgXhl1VHeVnJPYCRExXA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:zbsp+txT1MzaeA==,iv:ZnDW9VsLcUO3aeiWTyd1ckPvGFpKkN6rXGkZRgTHUKs=,tag:lvlKHSCnyfk9tfOg5PG4WQ==,type:str]
        orgId: ENC[AES256_GCM,data:8g==,iv:2ZbDgeQR1oLAUweJ1jo/VvQZxDgmBxH+99kkKdQyY9Y=,tag:y5SzOaV/r45Yzs86XIfpiw==,type:int]
        type: ENC[AES256_GCM,data:/O7w9w7bvu9YwQ==,iv:4h1mhaPVpjqaezoKAdrw51h6PAlaeG+IGr/aEmjpFQY=,tag:0xqPrDy9rFP86PZvQXQ4Rg==,type:str]
        url: ENC[AES256_GCM,data:GzIdWiHqcVA26WLve1xYCQFZqglEygMoSB0YGug8MGE=,iv:Ogp41qi1kglLFktuVhOa52i90fiTDhTpUbtmhzfeNq8=,tag:+2D8+U/rcdH4rSyfAl89bA==,type:str]
        access: ENC[AES256_GCM,data:WHlLfDk=,iv:CgAGMkhIO7DLOvujg7a1TjFXqxsp5/hxQzT3ECLSFsU=,tag:VyrDHfBmMChRu4pVEMXjxg==,type:str]
        isDefault: ENC[AES256_GCM,data:2mZoZJI=,iv:wIkKiV+mOKo4IAEFzPYbKH4w3WOPUtpW0M86bKiHr88=,tag:kZezBAHoEekbfO3zXzCAFA==,type:bool]
        editable: ENC[AES256_GCM,data:aiMTKw4=,iv:lMfH1G61zFaMMDcyxiFNlosTblyzFR90x75vpdJOkMY=,tag:HVwnANWoI1+X5+Ik3d0w3A==,type:bool]
        basicAuth: ENC[AES256_GCM,data:U9snKQ==,iv:Yrat0BxdMqgidS7m7gRnETv+SVtmmRmyS596XwSQ3Jc=,tag:paJCLQyGjOgzXK/oh80m7Q==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:J2R+j6Ft4W2vybzVuAWtRuuvV78DIdlje4SkZZOIHUi0Fwwa9KEPaT5A88nrzY6TeWm7h4RVEgD9Fp+obqYNPg==,iv:UiKNR8fpbBI6yXJQtFjR2YxTftHBeWSnxLMmFVkn0Us=,tag:6q1/AzEOS95ghhBJP20G+g==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:GIWoUXajWLiRc5ajx6pghppWeyN6mnhzHA1KkrajvrR5HUgzLJtWPT71gHWG2eqNipPfj3qmb5KS57WGSR3Img==,iv:0ucY4MAmBo+9t7q4zolvxoNARWdivRx/rt9mBnWF/NQ=,tag:7xIFKtAUuAApZiPJtsBlnQ==,type:str]
      - name: ENC[AES256_GCM,data:ueBKl65forVYaPFkfDSmjw6i1uJg7nuScU3tf/tMsQ==,iv:jwAIQbnG8yXFkhqy5t+X5Gljk/QPzh1l62zFsJpHqlc=,tag:I9YV6A8vvtggjUM4TxfRDA==,type:str]
        type: ENC[AES256_GCM,data:lpXI491x3WFxIOoOQHz3OoF0BA7Jwj5fqxtsQYYdAQ==,iv:tjUbxmDmkkdIuqt4SFst1zdDBrME/lg1eCBAqyiT/zE=,tag:7cUsF9XtPY0Z0ltrISRX1A==,type:str]
        isDefault: ENC[AES256_GCM,data:DWHT9Jc=,iv:zBjEgoX0cQ7CIbqNtHaO8d/mNDiTGQ8JQABItsHhyrs=,tag:MWggJl6D8Zq/TdI2wh/+nw==,type:bool]
        editable: ENC[AES256_GCM,data:aWksRw==,iv:Wcpv22G8c4Xa36iI4LnRAqs+WxH8geWxYUY5QtfnLmE=,tag:kbeTK2WPA8AaQBvFlGZKKQ==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:12Z'
    enc: CiUA4OM7eI5knne4v9mW2+5G6w2BBIpXfIVgfkPyEYZoZV7N67HgEkkAPHlbmVml77gv4Of/o81kRPadB6C2Sd8dhIBJRfWq5y3ShR+YRd3IcbXxirEb3mT/VGhMNrxODZuV93D6gSCOpynIMwd9F2vm
  lastmodified: '2026-04-17T08:24:13Z'
  mac: ENC[AES256_GCM,data:JqQYCj1VaOTYHuDl5bO6ZBFII+PMtISWXJXd4pFQjl2xK1zvs8asbqaRB6gsNBr+l31z4DZlROn7dMze1iI0geD9k2S2VcoqAvw2BAb/rwelF/+rYA4NMJk69RSiuxm8wTcwGZ3EnM8ZXbKuof6xXg4SRwERlPUNZirLoBk+hbw=,iv:EVJDPWhEzU3rqMOf09+S+J6jrHTlBDtMoe0FgspB1nw=,tag:beMJdHLAiCBbUrAdNb1N8w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
