prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:yMfBGezjbWlIP7Li0UF4q+6hto+PgHHzR9nQkI7vt+ovknc8qicIXAPVYlZyMVJZAXMJcrVfzUUhCQyazZMO9smRKrlgjswj9FCwKLPZfIPcVuBF3oyvNRdFSDez3uD2LeoCUFodqY7dYe2WtLadDhBGkpYqy5XKK650TDkEMb+IAKLhw6TkCTrY8LHAsc0aWWEZcQqG5wJKqmoU,iv:s5jrdh+2P5hb4q6hL24WxVnciiaJvgsAtXon1ipdEjM=,tag:iv6jBjVMxGiTMMYb5Pzl6Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:yaTwFkbph3zKgYo9Jte6XVbbbMtB5cocC2XwmJFoAyxb2erhjsBLoPDirQU0nO0n+O3z3XSKqzFSgodVYaxd3A==,iv:DWmcvIL5NwyDnnGgV4kkff7ARP2BS8avmol2Nw3IDp4=,tag:oHIDg7fCfq1HuGiP7AdLLw==,type:str]
    password: ENC[AES256_GCM,data:sGAvDuUwqp9e/V7zJJwVVl2VZWC6qvpenMewY+ky4t8ctvfu4mbW9/467XreteAYP3zIM/WRrGGPjVeYNhzniA==,iv:UHXpHiCmwGgzP6qMVAWEqqVCTQ1h6s36iPx+tkmXRu0=,tag:McpR1adgnyZLpiJbVwhrZA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:lxxpJpk504grD/9DWA==,iv:JBB/zpLk8n5p/N6VweXHCPt1En2PFkRz4/WvbfMsP1Q=,tag:2DySlVcSejmA/wmuTb5r+g==,type:str]
      value: ENC[AES256_GCM,data:F/8xQHXkK2toE4sRj1RBHXmY0av7xa26Sx2zAcRuH/K6CJr0VQKTBMdh90UrLJ8d8XzpRaQRjoxSBOdEF0SJ1M2yAfAx0WCO+UmTggLk8uvqRjNdPnnOLiSwfLPRgiS6IPPDar70f/WDw2ZNKS31y3dvTJD0lVchrSQ2jibnCCUQV2usmAkwUUkCUYTJOc7uI96zu1lpbSR0DDXCm1Awm1BQKR4pb5XaUUzn7/XKj/sFhQ==,iv:VgJHj5KPKZa/kShBg/uWliZX0twxZTxSLJyY+O8eZ3I=,tag:WPowUTVtHy4GjArbvEbe6A==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:XA4ncAUr+mD5TCqsXSliGF9NV/YYtxrhrNd/9XzYunnuA/B000GiH0dEAPcTEfbXb8BQQ1rAPW40kfp86D/sqQ==,iv:d2G1Jb+4nZFTUJnNwJGDYl4+X/EtZFMTVcdtJvBaIV0=,tag:CgRcoKQ+CSdXRPS/sz0nBg==,type:str]
        password: ENC[AES256_GCM,data:PCJAXFUW9SN7R0xLmVaGvdSxMpCjY9Fb1ygV0WRHkMDpKqxfZaUaFnJpsn1hC9kzrwLUlE6weVKOzHHyHDagyg==,iv:jPeSeCWtraquA/nhnjOLRNOXRM97RHQTm/iZv6kOld8=,tag:ZealKFwAgUhYguszmsT8Cw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Gm2pjLMUB9cj15epxYJQqLKI8oobQzLLTpSf9yAEyKxzvRNu91C95lE9dtLXd92m: ENC[AES256_GCM,data:0zi3J6CPF4mJa3DoBP9hg2kA8dmq7nxChdvM9H1tO39uRXpZALzpNzo4bL0+NQofs7sLiF1l/6vTOtnK,iv:udMZ9oDXjXTbDI0IgjHRI8XhIRwnJ/DMckccT27m5hM=,tag:Jt2h0hyYk1F0xJ1HXrZdXw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Wg==,iv:rwriuV8IDujyUoVwJKe5DxtjVUhJ7iM2ZidBFxEJZMA=,tag:c5CYhEeclAPIEhXt5vwg1g==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:3fwtr3aDr1XQwg==,iv:iRP2H2tT8EaEWj8hgKsETImMV9VZjAZcgUNzoQNqvvU=,tag:AzUv2X9xw6r+NQpkcGCVNw==,type:str]
        orgId: ENC[AES256_GCM,data:0Q==,iv:UGjt74Ok4RIvZnwoq3fy26/22vQU40wvkcJ/8GxTXrY=,tag:XdEkKbl8EKoS1P773AyCJg==,type:int]
        type: ENC[AES256_GCM,data:23lCjIYWQRXzOA==,iv:zj+OxzqZ1M/HnFkq0SZy5PBhO7nN/6wxYxdRmrtI0cM=,tag:LWToRc/lO2dDh3QCEh3RIg==,type:str]
        url: ENC[AES256_GCM,data:PGEe3feFjK9QEZWbtEJeaHIgjSRbOobMGDk/ltWkvMo=,iv:hky4fEbzNDkcjr2lrtW1nGC3W1kkCHsgYeBDI5gNQE8=,tag:12BtzDDyPSUjrF5YbDv5Xw==,type:str]
        access: ENC[AES256_GCM,data:UWyjO5o=,iv:bZQTOz3IXCK95mx5uUyTxmsAK3lDQ5SIH4ss8UjNcYU=,tag:KyqOkgMrD8uWL51kbc+Aqg==,type:str]
        isDefault: ENC[AES256_GCM,data:NKnaQOM=,iv:k26vS3E2ML1DWWJLPoL48UJcqgT4aE95Yo/UI6ROz60=,tag:P5DHsAX9Dh7C2LQj1xwRtQ==,type:bool]
        editable: ENC[AES256_GCM,data:2geHrjA=,iv:hhpg3dGE6Nbq89pBob4jOxGHZ+oQCTcoOCIm6ZaFwFA=,tag:K2h9Oc7hT8HLRy1fPmTa4w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:/Yh3/w==,iv:s9G/YvkGXsQLYZFECOszIJtCuRMmd39kI/d1/sUv6V8=,tag:lK04I58e15DbzhiLPf1oJw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:77rpci84MEOnBkMWefBZ++9g7NYL9iLD1NL/98X6sGG63P+Rvt2/eETYj6HMz/b5NXHakN/iJ3HfzG8gY0lD8Q==,iv:7IBxIPTFediwTzFmVnU62iSZ4+8U/Xze4Zx4L9SZC24=,tag:/O8olJb+D+ajwFx78WRbKw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:n2bHp9IW0czq/AB+VZswTeHDAK+EJy/aHKmPOSGDiqTORQ+Xp6XtIG23fT1IruqLqsi5zBOm2pi+xHLlEQoDjA==,iv:cZR55XiRLfv/bmWCTSVVRIryOIOASIBayycGX3rLofA=,tag:a2WdSHTiK6UZCRqwZzp3eg==,type:str]
      - name: ENC[AES256_GCM,data:+gfASY0tDfM6fxh8KWn19m+cTna5tiO4dVnjGMataQ==,iv:fiicV5I6wqUmcjaQ+AhC8fUsOX3Gf2U8xpEeaA6CYRw=,tag:SM25C2A4p4Rvi5NhEqvfVw==,type:str]
        type: ENC[AES256_GCM,data:3l1FqN5lXCSJ3YemQicCeyVztZuxDjONQsfvONyjfA==,iv:I134//D4JLFJndHwNOR05l8VahfM/fYSEJ7LEsHtMMk=,tag:A672vfoTSD/d3Rk0fxYS6A==,type:str]
        isDefault: ENC[AES256_GCM,data:PYp6KuI=,iv:4+pEthfU8RUPaeqg/h5PevgS74yj3MYz/m2+ui2Wg1E=,tag:LWnBFzCmAtj3VOFZbA8TUA==,type:bool]
        editable: ENC[AES256_GCM,data:PQyfMA==,iv:KwFH70eyfqLKzGz7gWykkqOotWqc/u5/cdCrroigim0=,tag:JECvslmbQoWqJkX7+TxLzA==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:07Z'
    enc: CiUA4OM7eGLmSoJ66EQEuGr3TsVUK9HXgojlNzFccDV+bvKTf03eEkkAPHlbmdZ5fozs1xYiQ4xC88c1QTeTTZK/fJ+u5TnBXaXOj7gBEViBlREY4m1RBTjODL9y+B5tY4Os2/GIf1nMy5KFosdGasfu
  lastmodified: '2026-04-17T08:24:07Z'
  mac: ENC[AES256_GCM,data:+/5w2a7lLtMZ3v/JMpXykVs1judZznkUKRa4OA3cpJqc14jys8/2pBJ0tZoWla/Q8P8Sl6v1nbzbcc+tvy/+jYpa9I5OjlullDftigA9b1C9zaiDoNe7HUpsNBbkgdWCuX7mVkN4DkhXDohf94fRoB3Kyqcy6DAoC1Or4qbwvFY=,iv:Bv6b+MbzHvquXfbF1GnErmKoDfLNzQkKjfWoE0T5l3w=,tag:mP20/QooFfgHx8SURKS5yA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
