prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:A1XpZ2v59+thbq0oGcbzsvZ/sYl6v9pO1k/YGhsmgNeqq2dALujJtQWfU6db6/jdXloXyLF+86xV4ckOMD6815J6bFR9Nm61O7wqp7WbqlVZbUh102e7xkbQs3PU04YqlVVcBcKi1Z8lgKmNRjXh9TTX78DnjEtyd7bqQzgllbO8BuSJwNwAIuhMRyUN7OIm+VX5k74GM5mCvui3,iv:tpT5gzNk6N/Zx8kpOHjzoakpSyH4WcBGQWt1tNfEGe0=,tag:fsjv8KP9hil6SITXz849Ig==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:cNSjZ+gL8Von4nJTUnsD3hTKXzW6DQvna2tBQKpnQqT9b6IOQKd2r+hp9Gxy6DxL0sMszCNY+y8E7k24hqWO1w==,iv:zU8jBjJHrn+fb5siRWuM1hKMNn6UyKIRgZ4o3/yXQXc=,tag:WW/WghNf2b8ZANA2yDoipA==,type:str]
    password: ENC[AES256_GCM,data:sR24D9+zhiqCEq73fT6z06JrnHPEG9mxNSozFaL4LEevHD4GX6F5Xw/AaeKbkUX3JO5Z1jt5wQRKD5CQpXUGpg==,iv:sahAgtueh0t2dCMCtoa4ceFjHHOgRthD5RAGRgSyYMo=,tag:o+UXNLFvLS5wzj7kJizv2A==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:hPNAt7W71j+IVFKdvA==,iv:yAajaIj1BMruF+l9KJOQ0mUfWy99u+tpeCBv+7GI/A8=,tag:qFnFZQIC4XC0P2hjplokgw==,type:str]
      value: ENC[AES256_GCM,data:tF6YwExDTuNMpMaCDJWlzMesvncMnRQJFPffMruET+NhDMqOeCmgZk16kD+IsloyR/jB+VwF3f1Mf6M9E1oolG9okdnOGgBpClBI0dHdSAQtmE2DxuE2PBwbECclDm8aMNpK48ezI6Qew1rvkMEe/+7U0toL2qDDO0uyA+7cHWkUay896LHZHBLuHEK33WyD8vdKUegU0Yf/JAzOcWmFO1KL/Dta589CqQ/lNZLoInTT8Q==,iv:46N2+ho7X5w8bIvrm9Kq3Uwpm17xDPyTAu86Y2V3E8g=,tag:oEsgpX9wofyKUYigttSWsg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:tUwE+crCD34UX45P08JRkM6vqpgMVcbzaP4wcFXtTvIISLQmOgJAbZgphcRy6vmjS/7ET6LwbW1ySLUScuh0BQ==,iv:MsdhPflMhkf8GHzT+V5I4lKiDJohZVVpOSUNeZCf0WE=,tag:SsbEvSx+2KRsK97cEAfQ3g==,type:str]
        password: ENC[AES256_GCM,data:5l1kZdppY0fmN14UU5ar7jP4wfnWLsDZEN4zZxnwK4UMWPV+zOwXUHGbew4NC2u6jkF+2lcZ6VRGtOhtXZwEug==,iv:ZsHcDO09ZGBMum6IuYxd6qz47c/VciFdw3bxcKLOQgE=,tag:Y3f4D80dXy+DZRzvOgfZPw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        Gm2pjLMUB9cj15epxYJQqLKI8oobQzLLTpSf9yAEyKxzvRNu91C95lE9dtLXd92m: ENC[AES256_GCM,data:P4wEjePVNhjR3sI10Z4lFkcJoGeIMwUcFXARTci6cX2JEIIz/Tbi2oWOTlg+uHf9/BbiistljhYTzPev,iv:U2o4gSjT9krkzswgH38oYsle3/yQf3c9rbfUXN73QOY=,tag:D4WKlkNkOLqwZx9BZPDJPQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:38Z'
    enc: CiUA4OM7eBqlKQDnIiqlzSQd++uNvC5TTgkYEeT4+8Y/KRPL/BUWEkgAPHlbmRXB8tnkPM/au6mzmgEHb5AB2mBgta8azSdun5Lmk3ByAiGsB4Fo1R2Z3PgPiNitN6Rp7oh7lTv5wl013uyrZaTcRO4=
  lastmodified: '2026-04-16T19:32:38Z'
  mac: ENC[AES256_GCM,data:7avhlgXCztoFfLlE9yRRPNDUbJYkm5rSx5QNkeN0euSi1T0Q0kYqNIB0bmdZTzOr9SafsoYrhye5JroanCtakXHsEWwWF2QVHebKhcYGgLLD/OyyFAfd68QX/qt5JAou5pS++zixil7MbfH3dLBhDKc/19qR8tyDXcpUI4rud9M=,iv:rY210e4+BiJNNHAwkg4IIg2MxMTKYV8KHwroB2iR+Sk=,tag:WOd0NEW/c36FMRnf4caElg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
