prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:3Z9ZSGsyIW+15EEHMNrK3QsmDWKPYth0JlMFBgNihqDdSu70y+Duvoh9fYJcnLnqYprS3JslhsgFKvQVGus3jtiA7f7mV3VXyfxOCcwYF/tRlg1Bbea9p1lW9szV6Mw2YQKG6bnwLm5MSMGmox/OWFzu76d1yWkYSczqkbUmPTPe054A/mSr7/w2XvAF80tz5msO8YI1fbnZ5Ng7,iv:IIEzJbmJ3y7yO1A+dihqq2nrLJtk9wy38fFTH3Q7IY8=,tag:VR8G1e+k5eotoitv9/HZtw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:PfyrDYD4KPwXFpynSl/JkX1rDeR+/XeZ5vKE/VfQUSBHdeu18s72og+BJldgQaC677/xE8UOObBvsfoYxMZvXw==,iv:n406xtMB4/t6mySH2x2z6sdbZsCrWAcmZx0zoNsMfeM=,tag:NL12qmgc88+ot8wjtO6mRw==,type:str]
    password: ENC[AES256_GCM,data:0dTnhV/eShrLb1Y0zNT4L+Qxuo4hnmighTbnah1q6VkCDKVATbjnECZZIrNEmB+gorUB92Dn32uKIFqjeMe/lQ==,iv:5YpB55vLmmzwkKr0/0+QfhrUUiHhbzE4CXtSOWp+pEs=,tag:/E626blpg4j1A8F1O/N/iQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:fQ==,iv:VWBcK8UgO8QK2omV/iFA73JWnVYkR+gvOLacFDHIvYY=,tag:r4QfjH4PF6EJhrR9E2gSGQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:UZHLzE4Nj+voEg==,iv:OioiLaN4+NRTzzPwOwx9eksdosWhp2GWAvUbzd9wSqw=,tag:peorUGK+2Lf+ClbBkB/YjQ==,type:str]
        orgId: ENC[AES256_GCM,data:SQ==,iv:U2fOEuP6ftf5C8OLYeohIZPc6JrK4EMG5siz6O9T4s8=,tag:whw4X1u/kMczWFBHDbhnaA==,type:int]
        type: ENC[AES256_GCM,data:YaMuFpQdoUkXdQ==,iv:QghvzC0hzTYOzsCPIOYx0edWvP/3xV6jGk7wLGRz9oA=,tag:5sWkoxeZRWjuZ19t7pbPzQ==,type:str]
        url: ENC[AES256_GCM,data:1DnuVT24plUoPmEjCEMmR/VjCQuM7WnVd3kuBMtt4Iw=,iv:1VEZnt7QfkEmDnjmDQzPeGMhqcJ5c/odOGa3KRuOE64=,tag:CINWC2mAbgMGgJ3DMIXvig==,type:str]
        access: ENC[AES256_GCM,data:+zFWqy4=,iv:h7848zZtgfFNBRs4BFSeRR2/hzzVd20oMAK7QYMIF38=,tag:yGJRTvQwwqAtHxq/m/mIfQ==,type:str]
        isDefault: ENC[AES256_GCM,data:ZqdnX2A=,iv:n2X8Jkf4I4dTFnW2Y4VwW2olqP68LwQHSChTfX9yIyI=,tag:vJCA/IWTERsq79tumhcuiQ==,type:bool]
        editable: ENC[AES256_GCM,data:cpIWVSE=,iv:pYNcTrAQVxvo6XQkYQaGo+7OB0UsF6j4HyGJkdbARz4=,tag:ja1pBD8esHVPxS5fHOO5LQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Lx9qSA==,iv:0ddL2eYASiBD8dERMTOZYCAliRWR3X0NS3FMBV6d4aU=,tag:wR2QyKr3LxfGVwMitG9aSQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:MbebmmN+j1THR+zOKrDTzO1aTCEwTy4DTtV42ITZgkkUXYloZIYnlAmK7I8XIycqXpHpdqH2D280DF12XzyBgA==,iv:MwwntZS0vvTUAPbC6WxJEhDrtz36P6ZL+xUucOoC+8A=,tag:9AeE2tx6AOdSQbUN5TKBew==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:CBlkhBgxVf9Sf8srU56h65ORjPeLgxv9JN9maQiAuPB1SXuuzLTwXYYnzpRZWTmv1902bZCPoDs79UnePLZ2MA==,iv:h045PNGVN7VDiPF9mLBcwzYgYlyF9q0W6xsMRXF9ius=,tag:yLwf2aKgyGtao/u/KLJ+1Q==,type:str]
      - name: ENC[AES256_GCM,data:OM7eG7tU+BsNN7/ckxaav7BXB9XKI/9UZ6St2O6uTA==,iv:OZRFiKLDkXrCHc43bFDq5rxDUuHSwXVRcTO2+BbPHN4=,tag:belZ9qmFdtovkRY+Ms+iqA==,type:str]
        type: ENC[AES256_GCM,data:5W1ORUCjY5hN7zzYPL90GN6t8ttgKSGdqzgr4ifk4A==,iv:RFY8MZgbgP9P7JOEbkZ3ZRQiMqogty8M6OD6PZEZiK0=,tag:KnOkVLOR32xTv2obhIVJKA==,type:str]
        isDefault: ENC[AES256_GCM,data:GluxrAE=,iv:n+ANfCrkFnuDMDilElmvvRmJi8sMClLsyLVZ6LUlN6Y=,tag:53cMJbJgbJHn2lphumQj2g==,type:bool]
        editable: ENC[AES256_GCM,data:38rWGQ==,iv:KSGTjeRWKCPvJPlC2JPtJ63QMEVXC3rQ3fhEyHtpmcU=,tag:KEMRjzS9URjNWmoLu4WoHA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:A9j4cbfaWXfMskd2Dg==,iv:W9fvQ8oWnQM9kIRIl4R+/Aj+l6Hkc1Unn+n44xyrcvI=,tag:Xhn8VRUhv6OZIdDpEFLQqw==,type:str]
      value: ENC[AES256_GCM,data:Lfa107tiq+idZCZoMyEVVu+vbL+SkoCew4ITeLm4XI/1ThuCQkt6VWm9WEwVtpvyq+rW67LnA2yHZt/4/81M/ALvGcJR0utnbUu1hSJ5utthnSy8x8yBR3nbQV0M4Tfyes/3fJHjelHR1UDStphZTBaaS/SJo7Y1DKQTXCoRtlkdTH7SEjrH0kGeCnZG3+MrNpdV1m8l9Da32GMMrymRpkx4S6+0XH23odXMPHI2Sihesg==,iv:i5S3LrSWVGYNh5XoEVE1rNkCUPS+cy7CSq1JRwi5m5Y=,tag:WFDl7I6c+9OfkzB3E0PAZQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:6rMW5g0QGvMbVr6qH/MQHl46ZydlKgWpUGOIR/rxuleGqykUdZu/4/rGGsEC/e5oh8hlgeC5njED2acg/lTz/w==,iv:YRfOzZjxd4DEyQ0TlSJw/+Q5pRr/Yig4iv4yzN7/7AY=,tag:e9pr81AqzOLGv/bQ44nHPQ==,type:str]
        password: ENC[AES256_GCM,data:khEPL/BXrCKJSI8Bg+hv0tqSOvsSIM3ilInUbzdvMSDm8QLb2N/raTl79OkIEGwUeLsUI/2bwTL6vdHQtAocRQ==,iv:JXGveijeynz1ugTVuNhDxRmVHv7gBNyuvsbC9tHIdsQ=,tag:/Zj/bT52ZK0LbAdsyqn/Ww==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hLdo4Vmj7JiHKF7xPBJn1KEBuBx6Fj3iGg3lXZnxuMZ8OoWqQyRL6bA6mWXXne8z: ENC[AES256_GCM,data:5hOzqHK3BKKFNKrjV4GMq/wzeDZHFuzBiwJoLNMxNUOLRspoyM/QucbhvnTAWStn3WgdrKEDU6wXlFNI,iv:/anVHfhAiM6MdYP3Tc+F4OHZsvVlI+DzeNEh85/5gX4=,tag:GWtS5EodED5EvRrM2NYgYQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:22Z'
    enc: CiUA4OM7eATLLHR/I/GWZVx8ZtRDvtJ6sqAqad5CoIpndQnGkkf8EkkAPHlbmbKP+uzgkEQtuz0let+XBQXKFzaZkmMiLXuUHKXCaNbcNI5F38Rrs55lM4zQqWN1mEV5lYW2mbvmhv/DuAwDGahHv+wT
  lastmodified: '2026-04-17T08:25:22Z'
  mac: ENC[AES256_GCM,data:NDHdXV9MEo7gajX8kqU3QBQijVaaCHXPRjBH8lp3tN8q2gzXLQeQ0F1B1S/XirRgu9/mMkYtwlDZAflxpydjtznuoW8p153nM9kTZyR8KDDiHQiG7nncD6hj2b5X0JjvxJPZDXQhPoFGN2BMBvL4z8V5lMJHVZvf5OyvT/2gIMM=,iv:fsCmetRSdICEh+s7XFLEG+QX+Eu4Mcb3HhlZsAtnK7E=,tag:9DWo+OrJ5DYBZ3jljtJqWw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
