prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:ktXJg+ryw3rxF2Obtu1K5RJ0KeCMTyD3pbQkAyNT9Gr0hKOFS3aoJyYGq5jItVOpir5u8g6766JbxpPRINMj61vZTiravtCUnxgxynrhVeaAW0pm+4poLS2y/vwy2gh4J7nx5Ukwo1DeXFBHXyIY2LI8mGck+VG4Z8hRq2V/bXSvRvJwxyLusysHWwm6QswesI6ljJ3amWt/8IyI,iv:kWKQavKHpjq92gU8KECwc1ddmhFNJS8ECcN8SZw+iKw=,tag:eQqEzx5Alxk+XsDasaXYpA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:f7Rjc+lcHrYUr9cUWh2G4/KBFtQym72oLt5Ac/LU7KYSyYWPrVQGwltRUIK4WeyOyNPQAci8188J0v6g4OLChg==,iv:GwmECizuuUpR5Op8myrXBU3pdaYsBvm7FYGgcKoNibk=,tag:Njy4xXREwTQsLw+SYE9LPw==,type:str]
    password: ENC[AES256_GCM,data:Cs2EucljrfanKvqZqhEwDe/54Zp6tt5HApy1TlcQFYl3adY5a8K6U5bSNodHie9iD7fkPhuxGrwz/KOEo659NQ==,iv:6zz5ACqgy2hvN2Lqaeg7Te1EoSbU+Sm+eNO6dXPrtzQ=,tag:9mj06OlWYnyYflhFcx75sQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:XNXui7DMOx5n3J7gwd/w6zQJeTo=,iv:wjY7+ij+owtZSEiOU8fM5wqNqND9IzltB3P8zgb8jF4=,tag:RI9zTxGGhL54+/GUtslBZQ==,type:str]
      client_secret: ENC[AES256_GCM,data:cXgVYdBmmYAH+aoJMYr6edY3u/Y38Xpz2xAxmAFRxHyjPTt3hCy7jA==,iv:k4fy+FZJWe4YIjPeCjtzZKtQqd3caVFbpkJUFeYlHn4=,tag:9bzlBIoP1W9WDdR9sEUnGA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:UHXAcPiNF3UPx3FAHg==,iv:jXXRzwDWTIsGmIQIHB/4fGYXpGbXZ7+xDUrGIbJ++bM=,tag:rnmb4RdbmnrMMuNKKKcNcA==,type:str]
      value: ENC[AES256_GCM,data:svHzJRkankaLfQ6q+TcJHFcKMJE0k71yPJOqGT2pY8+cQkNQTM5/G0UVqTp1HzHXkMaJpR/e19SB09uGDz7regjBqFYsqca4/GXPjHnCWbfIIXg2Hm/u0b91aqX/cP1qFyOHgiLoPzkjOiKxnCKJ22EMtJ8T6GAD6Rehj91kC7qMtzIm6afuxAgKdJSdw1rV8EDyAFzyOO6KkC2tlaU5ZYoLW5Xlvw/+v0y7zvBY0LPLFA==,iv:TD5UT/uPnbEngymIfm5sC676pX6Gnys8dUKsYYh+HwU=,tag:2EWN9M/G9X3quykrPJ8MWg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:NoTu3uAbj0dP2qfKQLQb7kEgR8KySXA19sbda4o4Kwgzbx+cpmsQt1xCxYT803GFW7usRSLNleCxvdAwD5RPFw==,iv:SJUNYheZDeOghA3yQNV+y/0fz/CXptaI2vaZyg497Mo=,tag:BvqMKKOV4M5Gb98glEFTrQ==,type:str]
        password: ENC[AES256_GCM,data:E/WO0M12j4yQgk/ea3/LSZJJfHNx0b3m/b3mhWIoiHVgl0tUE0fjklPXFCqq5Ur7GamiYViMgkZOYpS6oRnV5Q==,iv:NQsJD33b0EUV2VO64akS0qRLBygqzHV2NKgKxsHo7V0=,tag:ZsEp2XyUhvddiTaX33hHOg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        hLdo4Vmj7JiHKF7xPBJn1KEBuBx6Fj3iGg3lXZnxuMZ8OoWqQyRL6bA6mWXXne8z: ENC[AES256_GCM,data:Pwfw9JqQnoJlKYrZqFFmYHu7vddKEBY2FEEDuH3DnhPB/b91bUjxl6qx209gNwRMwrRGa6pH/YrRH65E,iv:9hOQa4jnjHm/y/sHsEwrTbHQPrwEVcSMXELd0iXxqds=,tag:YKh78pECOpxNX9UQt2YKEQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:58Z'
    enc: CiUA4OM7eAj1u3SuMvJBIXVxy+c0602e4AsOLHz0jRRMJIQ7dKcpEkkAPHlbmavtz2Ni41dvC24FWGhVA7YO+OeqR31uz0KH/DK4CF2lZdgF1DV+eTYHqD8QCAQJRHdyFOtKwJ+rxAjaPCkrb54yqUr1
  lastmodified: '2026-04-16T19:34:01Z'
  mac: ENC[AES256_GCM,data:9l4N0TcZFthH03kKAsIhSlTQ/OP2bNkLEfWVs1Rkk1sFRM0Ry5bpAptqRFuzubZ+PNZlasyI7Zyup7yQFYhvrVdAaXHPZyQa7mYxxmgfrSJbgyPiRFW6KvlieEnV6Hg0IAF4Jg1kK4yHrFxN0FmuVxJr2DSz5ygFxjZXwmnEuxY=,iv:mQZ3grok8Su1cZTaK4sdd8kkCB66zyaRgzvGAZCwlh0=,tag:hbwf6eNaBIt+IAn0rMrSKA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
