prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:UBe8JrzpHZhRl13gFBeePp92dUEYofocE0U1Y29rZLALJjvZj+bkPVaFWcMN0RxE6xuTUbZU//CC5pq1d9GU8lHYcAbEyjmfO96R/8V6NCN476RavMAJjwlNy2b1ChQlBV+Cxt7tAk5WqlbT057D0b2yFBDCSqUls7xkiwe1yj61scwmn4iIRTt0Ip1Xxs/L4bW/vcw6yDoRi83l,iv:Vstgc0ad0VMClN75e38tHwHbQ8pNbniI6/Nf8yPVrsQ=,tag:v+hm8zZeyQUa3FMn1a3Rhg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:B/zVvJ8H9q92nKi+wRcoFjv95SvDD1DNCouD/ppQl/jDPa2U4bGXqMqlhn4rX5W8qPnPGmVknwEgzDxUq05Htg==,iv:Ja/MQj6+D3608OcGJ7t+1dbIsYrCWy+iWgxddMTOYe4=,tag:jJ7vIrFPNN9TJiQLuisr/Q==,type:str]
    password: ENC[AES256_GCM,data:ZKoCSl8KtnbRJMWHXH5qoEcVLo1FqyYu6bGQqm3ENnnq+eUP77lma4zxlXltDOb5vQf8fblfS8GexeXxpM54WQ==,iv:UOkP6Ilpt1pW1HHY9CrjQgtbxnF/bUnkkKH/DfVY2ek=,tag:UKfxrqbB1rgkJcsoJEOUvg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:A4piXQ/LvTQSUq6TtwIhqyKsU5Q=,iv:u/rgiaH/h0vq2VAcfrfo98KAQxKozy2IL0lGrVV+8qk=,tag:BkHpaD2oLmLuf2oZYVFatQ==,type:str]
      client_secret: ENC[AES256_GCM,data:SRJ/EkUT/NXKVhTVZRHa5w4A6uE2h8eIPUUuFdTLrB90spjYUeUujQ==,iv:YRWzelNM9Hr5y/xbJRVys7f5wiefa3cRInUV6xTAKC0=,tag:sOLuCDqriqsztxEgVLxmBA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:pSQInXuzLq0nixZGfg==,iv:Pk9VQYwQPjpeM54EqN0zIDrNHUdnvTl8HShrKhk8oW4=,tag:jWyGZbbhoEXe7RZaXwo4zw==,type:str]
      value: ENC[AES256_GCM,data:rFnrZuvwlB5RxWZ03Esw7UKHcfP/ucduOYgQaq29JaCDiTyfm0Wyb3mo7vV4GdTSeQmOnZD3wnLrQvAB9+RP5CrN1QZKfyAjtqezBVMBke1tyqphdtyIZxpRtdgrvCbtrB5SZt8otcmSjVlVrA3r46vVBG7OF2HMEwp7thX/pMxp0G/YBZJ+boXPwTeNu4GLaTZS/Z2dHEmu67cKDVWpQiv8WXnj7VHVPN8N9Jsa5L/kRQ==,iv:hrLR6xizlcRQ+cKEQmHDjQA4JymPGpKadRfN5XgTNbo=,tag:ensLzhsRmLTcbln84LVbFg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:o4fJ0xcfoYQhacH3hl1HM71j19vyA+K+JZECGyZfdBBsCspnrKUxm8MlSCHVQ0RSXIKjK6YDsJyIV3BCmqQcYQ==,iv:DAuhKgjB0lWNrW3gPqz1bAcTi3Vj8dHU1DK+mHY5/vo=,tag:PMlBqb2cQq05I5AvldbE1A==,type:str]
        password: ENC[AES256_GCM,data:Vt54/WWrRcgXHcBbm6hH1wf3pgGmI4FRjP+7WLvQq55ThmnjWURM6Df5o+ufLIetSBRdHDEXQq/94C4mskppFQ==,iv:Lx7HDW95xhibLaTJWfrOD7clJ88/X4dl6ioatLYpMJE=,tag:WADcHoAKEuPxyn2FSlaQ0w==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        1thEnH5ksw6UOJnpFAWabOJfUwReU0czdcYzU7H3tAYtsVA2NDfRZyGWj8YtTsmx: ENC[AES256_GCM,data:FujkHJqy/+y4XzORTjTbhC8TMF2yxTYUclmRHVAMHBVzU0ICXsPfkv/AcNh4V4JsV4BYMqbMq/pEspt7,iv:Z6Oq9aAoXPP/bWygG60mvasIplebbOE4VnNPc4Mvw1M=,tag:L372MWynDy07JscI69y1cw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:11Z'
    enc: CiUA4OM7eAfpfvMuKVsZNJNBta65wamFF7uS/yKfPz8TnupAvV1vEkkAPHlbmTfgQKT9+Hea6keoeDCQ2VjGnoJyyFTpiutAc0n49A/yymoq26daRzC2ZpclbDvcnHZGiLi92B2qscqJNniOONbdSdjE
  lastmodified: '2026-04-16T19:33:11Z'
  mac: ENC[AES256_GCM,data:VTkGzYPykbSIo1Kmn9E0LRg4qmHVj3JRgD7vt16VcVX2mq1BzzcfYfYJiIE0HD/YN/nG+QJtXZgXsuhFp0DQcQUw8sFm0YbIbRCZHicZngImAh8SVaepM+EMeq8V8QdhYsWT+wOA+62kROj4DQjDp9RFN5WvJri6Wvt77XnSncA=,iv:3tFUcXq49InAVp/Q7Xa9t4WtxKwzuawIGPV68afIFdQ=,tag:S1Cw+GanVRP2DpeuuSr11w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
