prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:JbINneoRFV8c209f1FOPxoT5mkf3KczAZIpkZNt4k6UxMuzNOjxTsdQYQwjFFMT7VMltLOFa/4V4BIC2YtPXrV25CFvmxSlRBOCD63tp76vqfBVTyqz06u+5CCTwvpG297dH79BzYP/fb5saaHelUm3XaXAwGeaSgynK2eJZkpl9jPkTMIOfGi6XFDgSskhSbu7i0nXqo7kmo5f4,iv:YZFGKYF4syjfZtCcFQl/z+oCnhf3KKQdIeKXhN9PGfY=,tag:R5iifF8wGyVvXAwwiy5i2Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:zCN3D0FzDoFMpWQmpnW6Ux6kRnCvdK5wv36mpPduHdQPQY/vZ3KudNo6OEaJ4ZKAYpS4U6zkeX+Bv+0n/MCyZg==,iv:AUmcOiT0mOPzDbJ3/T4yMnskMUoXSL2JRYtYTamQE/w=,tag:ZfL9xzSROse0pGFwiHMqoQ==,type:str]
    password: ENC[AES256_GCM,data:JUADO4e6kVTq+OQC6jKws0auAv8xrYix46PTMNQ75HWJl1sIWa0Mu6FQ0cX9XUkl9Wm3c1EUYhE7f6u7Lyx/7w==,iv:InZclbgNPNZcOSPluijeAoOWrOehyzM4cxQBRu6gmG0=,tag:Q2ppf1pt9+YAbezg6B2s0A==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:pw==,iv:YDx7LsNT//dUjN6/O/mmPvbT1MGGkkWmwWW+yC5yWqU=,tag:CQRYzhGiKCLTjfq7ADVEaQ==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:YUB6gkKrse51ow==,iv:JJAjgUvEwdfJJi5Mgj0uLJN7lZxgLobGzX62kxWIlZM=,tag:h/0+kb/ctj4VGETUacF4hg==,type:str]
        orgId: ENC[AES256_GCM,data:Dg==,iv:2/+vJ1BAE6UCRkIcnh9FN5uORsFZ5bx6s9rqOGhx1Xs=,tag:iQqQAv85IZ3oJ02AxE/8Hw==,type:int]
        type: ENC[AES256_GCM,data:MsbTFjZHWe0jgQ==,iv:mwWMSIH4wmj3aAUqmwqfaKU9WdEDVrS+LX0gR1Y8qIM=,tag:H8kbMfFx7ORhW5hSVFQ2VQ==,type:str]
        url: ENC[AES256_GCM,data:3Zznyx7g3ZIhHr1GJNhkyQJgAUOfNtY0Z4Mmd3KxD7U=,iv:BvXaUy+U4RHctq0UyzrzVXKALrjKLL3wnrEXQs+3qXQ=,tag:Cg6Tcfzk4LrPHpq8BoNL6A==,type:str]
        access: ENC[AES256_GCM,data:XP1nWoc=,iv:1PbZbb0lAM0BL60ZCr7m0UeSWfheCCRqfo2L+gniN8o=,tag:3eQ080ZqDIe/gT0/TVc3Lw==,type:str]
        isDefault: ENC[AES256_GCM,data:fa2zet4=,iv:Qp4IynksnEEf3k4r9IOOHBn7BKsUS5ErU/YpRjJoOOs=,tag:Ph28D7NE9KyUwdnf0LCPeg==,type:bool]
        editable: ENC[AES256_GCM,data:yVkltcY=,iv:AGzJVPzuTtMgNUbsZLcc/SQ6dDs4SXN5ob+W63t15pw=,tag:b8AiXf8P6eO7TrEbDmkS6Q==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Lfwa7g==,iv:ImcxFlV76sj8BMPE267rtutphlcDo4wQIIF7LA+xzXw=,tag:VG+S5U/XEjRHl5Ch+xjNfg==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:I0LriBqMmEFLUf0yVpinS3WkGoAhZLiyF3r+tA9GJQyHjHu5Xp286Np0MpQqOYUBAbpMmd9CNJPTdoYNOpYYYQ==,iv:VAc8f3krWL5tTXBRMOJPLVBbo2uWqKlGeLC1mU1Cqro=,tag:cwCPFX/uo8SQclG6hKzpOA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:bPHGGw4nbzwewg1bAH7ylXi8cDkszJ4JcyY3zazvby8iAhSAV3nKX10TGP1ZAy0NaJMTh5DlcBtzriKMYWdUZA==,iv:ZRL0ZmSfSbWun10YVwSqVXLS4khBcC7eWoP/OsgYa6U=,tag:BZgdYCWPzqufzVDDJIihtw==,type:str]
      - name: ENC[AES256_GCM,data:fqbbgqF1Zn9ewnxUm1LuyC/J5CNE1yYIbuHJIkwtdA==,iv:640nSfNkIfsAdhKpPjhbMtuNTU3mQXd8g5fXl/aj+KQ=,tag:iH9n08A+Tdf67S6mEB1bag==,type:str]
        type: ENC[AES256_GCM,data:pY63QKP/HXjO5lUCK0fhdLfDr44SKuNU+REP8icMPA==,iv:vLwZN3XVYDLH7/xfjnULNnFV+wCcw1dkhk4eo3j7X4k=,tag:XF63Ao5UJ4nmT59uzVbtSw==,type:str]
        isDefault: ENC[AES256_GCM,data:uox3b80=,iv:9XETYvYMNSUDkGdskA5M1gm0tRRNQbt/UCywmx5/GgE=,tag:BvIcDsQInJ/ldbg5w9O+Pg==,type:bool]
        editable: ENC[AES256_GCM,data:jyq9Qw==,iv:XRwBAPFfSR4y/fskipJfn/DbaBMpWIecGwih5uGRH1Q=,tag:QTzBqc8wfh9jTTLglPLjWg==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:XwnGbNOzzsZOGLSZ1A==,iv:ISzz3luVjgHhVCdmmj/9/JE5SkQ0UOE5KT5FXtBG5DQ=,tag:FTE/6ff+AjZ9Fpp6vwioDg==,type:str]
      value: ENC[AES256_GCM,data:FmuMKOQ+HclAlo4nA8BBsYXkZsaNfRuL6WJeS2rUdK56OASZqyOZzdTBAmOHXt9e49WSSwBHTEdoTOB6rW5X+ax9ADNdkzLaPShsQzN5A/rXzC2Dl1OCaVhh6kxOZ2sU56jWMHzGZ/klPw7MrYQMkn5vWfmdu6nMTv6SK1fhS4rYUuD5CE3wqrKSv6ur2d+R6dOI3t43TexDswCiL30x5Dq+Q5vGt+rC8slzsZ385YCj4Q==,iv:jSAysmS5rpMhcSuwW7ZDssob23o9vUMvayQmBtxYLF4=,tag:MgejyUOV3ZbVYeIYpQwq1w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:7azIc5foq5aPKMIlcGECLjysjATLtBxh1Dn+8OCdzyHIbnmUtzRL/3rLfOqVWJlABDkC46l8aKiw9aW11aXFrw==,iv:qSeSepfZdDJ71yYI1Z3TunM/dZBT+MxH9ynKr5LB38E=,tag:k7ojAUbVODMhwrPmQAkoIw==,type:str]
        password: ENC[AES256_GCM,data:O9khRP1ZR5rAzewymmgta3xh+cwFXaYHuFk11smgD8SA1daVs8cqN9Ir5Bv8PJMNSWY5oGDs0O1Dk6xS4zK6Dw==,iv:79bA4v3wgRvccmLqsyg4BxkmqN6SbnCeEa2LcIq32vA=,tag:kPDIg/iYpM7PcbiOPd9fqw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        1thEnH5ksw6UOJnpFAWabOJfUwReU0czdcYzU7H3tAYtsVA2NDfRZyGWj8YtTsmx: ENC[AES256_GCM,data:7w71YpYTy5WI6hFijByon9VbMWWHmMMZN204HVwHz4oUv0NvSZCSyvc2ZVgzQeRHVOCQ+hZAcbGgjSCv,iv:2rszbqTD8wV1xxlGo0QK9K4u2OkNGEEb4eT2ousUl1Y=,tag:Rwc12Ae05kuQqpX/y+20xQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:35Z'
    enc: CiUA4OM7ePe2SwYBXSWaQbBuRHBmeuBL/LMgZAYZj6+BBvcQBcdeEkkAPHlbmQkBekq85H0HrZU1E8bfK9S/ii3CS3W5IDn/GYsyIzMwMIHJNynBcRwfdPb9KfJapwnf0nbmCAwSw8R7lwTLKz1QdgJk
  lastmodified: '2026-04-17T08:24:35Z'
  mac: ENC[AES256_GCM,data:w7d4dX5K4OHbxSiKM4g4ivhHzakj5Rnr/hjxZEXg6I6Lrane/t2dAnbYqfBDGlrngnO5s59P32rgUuz8aITQ84CGUvMase2R+9B0T3NgENFTXTLib2/LgAJ/wQYfA0ZQ28XuVMG5cdV+Iflr2VzK2OijLOnKmWCVcKgzjGn/WRA=,iv:ulBZvfDu84CVCYwsa0NL0WXXjDGy97Skxa4L3CEq5Bg=,tag:HBqdpPgM/6oRNyACYVSGYA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
