prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:msw6/MR4WlkP5TgQJYdZhN/4jbcg5CNJwZ6aB7X9413fwf0Lo0CEa0mU40wMWFCYp9N7xZ5zctzCknj/LvH4pxPEdPfFD0g9Ei7bzXN0mFK534MvVJmA3LBhJiTNSSek0TRVl08iMViDOsFxwdWThqU9rDApc6n9ir7D+0aRxtKRvovxouN/XEmkwCc7TIKYQthDczkCpRx9sLaP,iv:9+e6WazLaMTi9ykPJO1OFzby6DFj1qnAMr6N9gH26rI=,tag:DimG7bwJSuiS4ZMQif/Z4g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:qoyAU28KDQhsx+KSkRjuY3M22upYKh82dnDiSr1PBGjGKWyAlSxOmSsYzRJEivBF3Yy0pdUyxLtvOtYxQ/gM9A==,iv:ILgxkXYkvynPHrjmc6iP6nmZQKwvZuigfkH7S/O9S2M=,tag:AjQmgqEEl2IAJioXDBJayQ==,type:str]
    password: ENC[AES256_GCM,data:5aQZywbz/KlPgEhYeIvMJN2dmNrJQY3cawYCVeMzIJwNOfUo6fdehzxFXtpybhrY9y91W5qkCMYHkoZNEiE99Q==,iv:/wA0pT8YbvnExejBx6NvsRKI/YMssyjZ2CytKz5X0Zk=,tag:7HG2CFNsJrDr03Jn6o02qQ==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:IQ==,iv:TKE/qzd9QkOiGxePMbgsDFW1CKhHuDL56FvZHTLQYSQ=,tag:VZek0bNaJq3Wsos9DD2Jug==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:34GVobDN1Y9KEA==,iv:JgJ2uOOaPdBvUaIvqK/n18Q8/ia72HxZuR5zC/75hi4=,tag:f4dDJdmgUunA63OfRGHjxQ==,type:str]
        orgId: ENC[AES256_GCM,data:Dw==,iv:OO35lQmtUnaybT6njfCwTgRCT4Y+SvJTijdwiSQuuEc=,tag:lXwZ2E3/VeqmTLtQZzJ7Yg==,type:int]
        type: ENC[AES256_GCM,data:EKY20P510bfRVg==,iv:jdNmvtiCPWPggcqJ2V9XmYHCN3hn13opDk95FmedVCo=,tag:+lkIjAjZM+rQj5LtKp43cA==,type:str]
        url: ENC[AES256_GCM,data:su8gFMncVUZba5nNofDwiWoqrP7CCUlWjXTFElEERUU=,iv:ANwpEDeMNuGhUIWazd4c405XDz2AlcwezANATXUm+PA=,tag:4mtVgrxyKPjVbZWpOLy5eA==,type:str]
        access: ENC[AES256_GCM,data:MIzwfiA=,iv:mmqqDx1IViXqg9saiRPzmi1EnjfAi3TIi+PR8/cl6ww=,tag:gPLHdMvGChNbIVdXI+EvYA==,type:str]
        isDefault: ENC[AES256_GCM,data:TXXC6xU=,iv:TrdwWnZtDLFjFUhVZHZC8sZj4kNg24My2YWs7Rt0e7I=,tag:+XhsuJC7vLKaePQm4HFKGg==,type:bool]
        editable: ENC[AES256_GCM,data:4Q6YlPU=,iv:o2YYIaSCC2DRPMKaH0XF93YM67TRbh0QEj1Dc6HB5DA=,tag:3SE0zm+mhwwe9x5X5FOPHg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:7xmUkw==,iv:xR1YysAi2Ou/huobc8/PxPzRX3Tt8C9v0syFSpAUOo4=,tag:TTxMYzZg3FX1nbi+Rn0xpA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:5wYJV1YbpHgUA3Mag6Ix29YXTrDieZVJMd1h2+CEaztCH0milxfxt1oGH9oqN2gnL9GKgs4UM5eKIyKEfklLwg==,iv:+g70fqr+H7xgsTt4XyLm6v4YyG/GEg9z6V9Z5mUgnQs=,tag:8f1RPnbP4Sn1vpifXpHp1w==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:zWHKQ8wC8qR8Lez5nMeW8OUZ1bFGZZ/61zzHc7XH8C+YDf6zvYHN0NtuDxY0bb7nLXysx89tFizI4sK+YJQ2lQ==,iv:IjPxV069Ivm1PHCL83wNPVgaIFyqgfIREIj0K+ZsFd8=,tag:rbB2X946pyh9X/098Wzgdg==,type:str]
      - name: ENC[AES256_GCM,data:AdWXjPTeG11nHwc9t+8WRTe+9GrTVJERLw3+6Ygazw==,iv:ptRTkg5BiLlN84v1dKV0wyNBGAUWnCrTz7BB3ewl47Q=,tag:lOrb+yrcI9vfjIsTRzSpGw==,type:str]
        type: ENC[AES256_GCM,data:/LDqozR1gER3ziGMW2veBdEafFzMHXeQTd2FXwIkBw==,iv:5azyN00EQwWXLAk8tLeGRrg0ObA0Hj3eXhLiAzMQQyI=,tag:bDJdaIkm7OTJCdf5kt/4qg==,type:str]
        isDefault: ENC[AES256_GCM,data:GomH1VM=,iv:/yhKl7XDWxHAga/VuftSgEsK4VkYGpZJvcVPOvLZXdc=,tag:+90IcK6frw/z9ttrkmbP2w==,type:bool]
        editable: ENC[AES256_GCM,data:mwns4Q==,iv:d4QQDkU3Nct7tecDF9WaYKqwU39qcfrb1wE25FIOpVQ=,tag:cV7Uh4vtRUY84dPKkYsCpA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:TkNxYnsuU68Xfr6OMQ==,iv:mwVN//BhtIKgZ3BFBGpnvdnUbQpW2XhWy9kSznSVLqA=,tag:0WTk330svL6dMdEYtGg/RA==,type:str]
      value: ENC[AES256_GCM,data:QafUCnc+OcfcFnxMTuvJ0bwckhDwgLxXP45oZ6VIQV7bYlQrb6K+w60r6wLNGiO6u8iOHFuJdZpWeCJxmfvLeoaCpp1hCbIL4QKeHEKDA5mGxuGcimnx2lC9BMfZ5IvNWF/a86y+btDDQyaGnk69P8MzyuH3+7koQtofe2h1J6OWfzY9Ku5avLzwJ9j/FrrvbvheJWcwQ7cKCufW7E9jKsSkLBV3xFSUo/rh1uNEToN5Sw==,iv:67eyzamCbotTv/60rDXSiQFqJfXcawWRUrGat9a+HPU=,tag:aHS2KSBRcUrvIxAvdPU+uQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:iA/vjJ+yMcRhtK32ccN56sIRsSmLirn4k+MGf9H5DbFV0yE/8y9lZeM3GeDVBWooV2mKmWSGx9VvMJNWK1RE/Q==,iv:ViZ3r75glqgIBmA0QkmWXq91M3+KrraeXps2xmg/qSc=,tag:X2eS/XR4uZoI54l3Xpxxfg==,type:str]
        password: ENC[AES256_GCM,data:SHAtDL+sAVthrS0hmFrFCbQ34lxDJ5dsuBGnw0pBOw9J21PC8sA2zFIdqlnUgfBdHBPHDQEvqC6jggUgvipf8A==,iv:iFYJTfTA0oEZoxFG/4Oq2we9OWGzXbOkf+4Jz2dBzoM=,tag:sfdx9p44oaNtqPzRsgOgqw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        J0drkJz8V9PuwBTA1ctEymznzwgDri5BsAdfL2M2YT7zSOgBozmKiPaFHxh11ipU: ENC[AES256_GCM,data:q6wCIS6Iw7Aa198RqZ7artKMDjH5wY6awk7Z/n9NGW9vWKOnrNFMgLb9wINFwKHsXH17Fu/dI1rBeDnA,iv:VPPLGnqMFW3uXFZgyoI0RHPbmao5rqSCypPa/c2btJI=,tag:hXO71NddxFhQlxEhA3iuaw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:59Z'
    enc: CiUA4OM7eNHyeZrbP9iC/JrrngmRSRjj57fSuevMZR71tDf6UVMqEkkAPHlbmassC+OpIp9W14TNlztmZP+gWH9OEYpkicTCnicqCUTUupTQFkCKzIt/2KdXTm8QlwXN2i57oJ7lrbtQ1HOBoQIPnwcz
  lastmodified: '2026-04-17T08:25:00Z'
  mac: ENC[AES256_GCM,data:QYQWy7Aahn6O8aKsOh3dANpamHE09WkV6xgMJKrLoflv3xbb2H3n4/XuZeQ//VcBInekQhxLLCSaWGoaObbkqq5vMQcIzfoUpdKgULgBljoyFXauCll7JwVJmKjIaX9D5NWJcQGWZkFqQn8Sp3RH2x7cXeLdJ8yAtD5eI96I95Y=,iv:/jGQvtCAqQ4NpJFMlt4SnBoGgPw1lgy3xos+n9z3WC0=,tag:y1T3Okailhl+7bUWnRZAhQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
