prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:AP50nNLTvmpD0D/i9qgZv8cnUUGTECCBwsxjsEeqqhFlNbOHXCjX0w0hjOfcTVw8nis4bS4nv1MjQ8C0U/VqMyhR2yZov0ibwwVFJI6YFIoB+WD4pM3nagOEZcghTbxbJKhiLwH4lkSbLMNL1pfGPfXFvV9x6OXtB2XMcVgpkdZUEmfp/6eudBgOk2RmO5Whqr9OJu9OGkb3OY85,iv:2Tn7umxvHuel6dhufnvR1CQYLorfXDIcVCcXjsdKwSY=,tag:3n1dhXcW0TYVBJ1yAqv+Fg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:OG7APEmtZwb4hSRFvApc71q5zsmM9UVhkGnZKT/v4YoCkZ8prpo6Xo6YlLvCNUBxoeuJbv4ZnFKVf/w/pxaCxg==,iv:aH5jO1UUweFxekr3vkdfQpGD8kR595Nxyg61dqt0fk4=,tag:YkgtCDH33emMPsS971Hcvg==,type:str]
    password: ENC[AES256_GCM,data:n4n6HYQcRBLE95Q/XwTsfcrL9b3Mq6CkYNpXGZZf6qmQWvLWo9Bi7SF2sz4FaBOws3HrbWMpVa07xvXDRcJniQ==,iv:iOKHlX6ZpqFvE6WSq53ALLd29eDiwx2AEzxNFCFSt9k=,tag:fW5eWtI67eLgp0T/JQ+TMg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:SU/i9ed3j6eAnb6id83FeaQRQzI=,iv:lGy+TakSaNR6nMVlvbUL/KfWrKgKbPIBhlh5qSy7yOc=,tag:T4j3DDvDgWzds8etA4TUiA==,type:str]
      client_secret: ENC[AES256_GCM,data:JbVvOrgEE/lfULK/yKFsOGnKR9QRhra0Ld4H32oYiistSCdr8G0zRQ==,iv:qH6OMN4SvL7Ts2VXNmcNtTfcHyQ4dvejgkTZPeoss7M=,tag:xZUZcguQT2gblhPpkjp1Cw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:3RHRjkzbP619JhlV/A==,iv:5hROAAAdEr0lhpZLOYHD0f698yJgs/pfFzplLWP/ZUc=,tag:u0vOQU+UcNPksrWqTC7J4Q==,type:str]
      value: ENC[AES256_GCM,data:pqgIlxxQHVSDqf1Gt9ovjzcDRR9ClU/xPESKQN78ZbbMSVuSPp/vBiHP4K7iGgtXOvfF3EFfmCoswRMlLLeIBlSxpw+liFhHbWMO6o4iiCbApfJWcHNZlVkZKuDp1J0y0++HrMiiTb/Tz+2azuhNyQpaAddu8DbzTXynB1/atsn4AYLayscOkqwRXaSMt/Hf9HCtwFIbQk64/Qy8UeT2p2AH+Q23vS1CStTKajY7XjW2BQ==,iv:BZcCHRPGk2wmdan4D+mRJI/BFwCfCwATaorIAiR6HlI=,tag:UN0rhGTsPCSQydqn3m+bZg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:uqaFlguEzS2NCGbs2geNxCRjvphDx7l07oiC51hJ1oPBDO37mj7Q6lxzTC2yYLfTfUkUVrLte0yzVHxbUXaVSg==,iv:TFwKxG13wKeemu8R6MCWuWHt86Of+EX70jFj/CsMCsk=,tag:+qzWhwGIOHmyKkHZjNrg4g==,type:str]
        password: ENC[AES256_GCM,data:jZAyLkonBhj2bHJaV1QjKYSwGAwUXhNoKFZHRfGLKZyDuX8OKIgg9pbANiZR0ZMEZKNfBZnKFGrSRUWgCa4c7g==,iv:13U4o/DVI66YOD8A0i5fX/6+icbRUnnHZ8vWvExD1mY=,tag:c1wTVgKKbjlV+dSp49ixFQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        J0drkJz8V9PuwBTA1ctEymznzwgDri5BsAdfL2M2YT7zSOgBozmKiPaFHxh11ipU: ENC[AES256_GCM,data:YDCVSNF8mMydvN7glvuEQh3NoyPzWhMf4SzHWjp4wXt2iAxEWqKd4YxjPLjOXUEuLFOcTZZOPutVYRWc,iv:/vTCqgItWDhnn+8XYjC54fJGIYDqx4jh7LpAEI/LiTQ=,tag:p1MvQPE3yqSmYdfSzihEoQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:36Z'
    enc: CiUA4OM7ePjcjci69wq+GnShtfVttvkqEsuDFKYHOYaO1t1ZwcViEkkAPHlbmal2p29iSEH39VaA6vsND3KcXrvDnior7p6RVecuz7gDBFtA7bGQiJoztADkp7GVL7vMIG5SN6Ls83kHR3F5Bojy77HB
  lastmodified: '2026-04-16T19:33:36Z'
  mac: ENC[AES256_GCM,data:B3E3GCLFfJMCUG5cYVQCDS+OJHHnBYJanuDvBOsoslULKsVbwZRgzS4uHAJkrkeMMigiTougRXhehf82VOOf+q3WGxapL0JtIMBkmSWpni9gGSCK4zMxdf7O93PmtgT+F/uYbhSlzkc+ezKOYwMMbQzFnav7LQVIN+m48vvvex4=,iv:8mhJFtRG+st2E8hgn0RDPctHn+RzmJzIT06ZXJ6F20U=,tag:uk8W1hh2qQeZztc5r4fHhg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
