prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:pnSyncI2nmYbIPwHk2F2L32nHJCYM+eu4lirGFicQ7yH/4vnjJR3Jt1IUWbpeVfLcb0Vu4EP4q2Yzx9KwGFvLuxD451x8i75Yg21DzQbi7KCdpHDYH/7MGl4svDZuP5vmYh3ERi/VVwRsNC3mwqHnMrhdU6NE+agk+Nx4Tt2+anS2TgaJwm3lgwfCG+3JvmnHrmBi3IKj5kGeRrv,iv:8v+iToHeOb26p2+jpCx0DQZZ3d/kE8gkQJRBPboDy3I=,tag:F8sbegkfyA3APc+3wDq+VQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:6rrzqb4iVG4lfLbsMmd1VuYdzPjSjwnKRlZ6UmvusBvUjxA1fYxt7FjtZp2CIYXE5JIpXvuQgwO8MWugTwhjmw==,iv:z+3LXH6nM1HwLgz8n6lbGNmcjrj3xmxNpOl+L0TgKWI=,tag:6ucj6xbI/pFJGxVQrl5Qww==,type:str]
    password: ENC[AES256_GCM,data:EgTwIRQQwGFE906AA1wmAQB3v5Ars4WGT1V2JLD9RDeRY7mPvQ6cqfqqRDcHieukNo6qNs7jkeRdSwi+BmXhOg==,iv:Iwt51xGFNWphbAI1ffoW7lcEDu59lPYoh9M7ckuTK04=,tag:goVooOce7UpakwQzypKSTw==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:iQ==,iv:dTad88JgrUbuqBalrepiZqiHj7D9r43BebrSaAWR274=,tag:DcGll3cWEPRaRco8LFmf+w==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:u+qOLACcX83zXQ==,iv:eVVxDsy67AFFpWekvJXchdSL0Z9QcmyGZYZDLK8qIAE=,tag:A0fH0Hyeoi/uZt/4G/Pi1g==,type:str]
        orgId: ENC[AES256_GCM,data:GA==,iv:0lrKOPdx3Vr7gpopHqAuXdb3B+2KmPeWT7NX8z4ungQ=,tag:EnrjbtGmAAXtfjP5xqS2BA==,type:int]
        type: ENC[AES256_GCM,data:Zegl+wZJGwf9MA==,iv:ChVby3ztZVyXFodVYlcAhaD6nZPqplnSGOADapk9XWA=,tag:tnZGDZok69YCz8msM2z6Gw==,type:str]
        url: ENC[AES256_GCM,data:F9Uhju1RuQCwLKfy2c8UZACYG21eMA0v0uRLITzqT64=,iv:hBnAiCPgnkrzXEHad0GK4j09o8VUtC1nBsEUnrAQKDo=,tag:ch3mfdRuZjPAMTyThdWASw==,type:str]
        access: ENC[AES256_GCM,data:sejyBoM=,iv:7P3acJYwRrUUGBoGipD6PQRwMWMhhrMGRxLBxE5F4UU=,tag:v7otaZub+65czop7Qw5Slg==,type:str]
        isDefault: ENC[AES256_GCM,data:XpFJBVg=,iv:gByuIyzfQo0rx9xGcZlJc8+QHPEU4VDHBP3Dx/Jildo=,tag:G8IEia/1cRID0d4eX1qPzw==,type:bool]
        editable: ENC[AES256_GCM,data:RhzFfqA=,iv:N31fLaWS5+pCLYsioATRexEyrg1HN5J7hosbwei0dtk=,tag:65iCHe3A4T4lKA0yI4av3w==,type:bool]
        basicAuth: ENC[AES256_GCM,data:qYdF7w==,iv:uIiZlFMJUvdH1LYvY/71hu6MGPdW40dS6w8bCqbPAyw=,tag:BOKDK+VHUkV60+aqbj7TsA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:K2bSwMeJsBIUsZAfE/zkReXpo5g+Tly+E8RexTkPOhi7ftIUT1m2vR2zx5PBzyX6jbfNuv6Z2U8UuSd+Elgp6Q==,iv:sZYrOxEzNx6fDgFfKoo8lnUTZS+P6y3qYhS68SitEgk=,tag:Ckg84MVMe+alamTwEhSyDg==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:12CrOg8vkcCoQKk2phfGGgjQxUGX7CxL3mY4b4IAknfyd2o1+Xq/3Jyv8qkMUPz1sHQuzlMwVlmiptS8ZXam4A==,iv:FlyF3rh/QjyVjEltafFFjJfQPcADCsDiLiW+AhwoDTI=,tag:wXHr7xzZ4foECIEMuaxVyA==,type:str]
      - name: ENC[AES256_GCM,data:Kl1O/pSt+/u1tpApIGLHAtTGHmfTxq37Wiq/rDcY2w==,iv:KaRFvRABSlFGA/ltOqTwkqv+14C0R/NzmdFY/Kmzds8=,tag:7rdArL+OjiNk0LjnGt2HRg==,type:str]
        type: ENC[AES256_GCM,data:dEo2rVuVkC70VcAKTIYvJBIUlKPIWmlB1bUVwmigsQ==,iv:aYazZUdt7agi/c9eIagbConuaKIOzaQirLWscFvBTdU=,tag:2EVGhcQrOEU4mQKf+Xlvyw==,type:str]
        isDefault: ENC[AES256_GCM,data:ab9ZJ3g=,iv:wr7hqejMBqvx4g8V6GuAjCxA9MJhR7OYgtoC6Ic5ZNA=,tag:NFrhVIXSNV11bMAZwzPStQ==,type:bool]
        editable: ENC[AES256_GCM,data:flUUqw==,iv:zzioB+22oS5A1j3czZjZhdmmEMi+0OnBAPAqYLah+y8=,tag:G+QX0HIH4C7aUjpqAunYPQ==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:78xPi/pRDlefQ7QomA==,iv:pDSt7K4+PEOK0uUQZw0/mn9sTgYci+SAvjEmm9C4UUk=,tag:jBD1lrj78MT5TWpaxWWNdA==,type:str]
      value: ENC[AES256_GCM,data:OsPfn532/Mi5A+nE8ntRrzbqoGJ47U7HCWpAFZd42ucyqFdHG/VWlmL0oVUkGYXak8VmZ0ec+oG6yGdkORLNjW2DfhVHLUGzEM4iSA/wZu2B0vyMIUTDCMJLn7jHVJZ1u0koEdxMLf3MoXVSaQAf/Em8Y780lsPK46E8sScDT/sF9TUfL643Epag/AnvBiaP+2/+kMQ3VnbuLQAYSUzcwTmgjuM0OYQM5Wn1b7KKMgl9Og==,iv:/Pgn+JRf0TFQrXWMVkGuG96+HsMzWg8cCKI+qZ6h03U=,tag:Rp6ceFQSCasUTwyLkLTYDw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:X7RP6l8yyT2HqN2CmoEgKqwPlukHQXu3U6ObCmtGxvRMmjF6+t1LwLb23eULpQaMVANZ5BUuEkb+95+eOnMOLQ==,iv:abiZjQ8lj9xk+lPjHVfP1eS0yf+dNr9D4YzrI1gcG9k=,tag:W3H74ts9cByDOvL7+eQFMw==,type:str]
        password: ENC[AES256_GCM,data:iS4ODDPwhdLA7lHnE06xxzxbWa/u0nkPU7okkSRReRvXuiY2wvojjdG/8Qatcu0mfXA6Tdwqpkf3L36cn6JoXA==,iv:q+cRva0lvrK0AvMkODDoErnQvczq3WqtxwR5qc/+OtQ=,tag:W+5q07oROBYL4w/SIrH38g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        IShinge4faiyoch9Cei9yaiweithiecahsahci7aec3Moh0kahgeigh9umuaqu9a: ENC[AES256_GCM,data:p5S/swY2aaOHzQFzDtRrLbi8ZVglr1XMrmyUdDqHAfIQY1BL/RAamj9ew4cyhDd0jVZM+A29vsJ7CZFf,iv:L1Ook93PrAGlapoAtSyiwzOS3PyoEXXEcYPGrD13JxU=,tag:/Vr1lhBIBbgooQuuewO3KQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:32Z'
    enc: CiUA4OM7eCke5c82s5B44DZItVvvaleJQex7tUWZXDTymdu/kPAcEkgAPHlbmQp7ego7G52RJXZGlG9QnxVyXB5n3IspPIiRaQcpnVIp3PUhcTY4WJIpj1BVRy/IVbApZFtojWKhVaCQcskMZGhAIAE=
  lastmodified: '2026-04-17T08:25:33Z'
  mac: ENC[AES256_GCM,data:Rk/0KFx6aHmQR0caMoasVr4YobJ1X2IfysmsM99HubpCGoQhZvL+YzbdeT6ZE8GonjHzt25xhzKSad4tMFA3d78QzQSd7g3YcaRN6n/MvuWKGvIf3QiLUSJk6qk36HHlJtdOAUVvb+JpfetESxf6SIlOtkSs/ipvWjSyj23gryA=,iv:Xgqu+v47qpdXDdQRfQpOj8Jvc8ARO3/z52GRlQC1VFU=,tag:UTSspK+GYmnK267rcDDZoQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
