prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:VFPr1jjV0yW0QaS/VBSlyrRQz8XOoRzrMefjVsMhBlyas693PPPc3lMkh0wReDzfr9G/5bBDnli3PwVjH8K4k7AuISdhlzOo3Cbp8DaWveDS1MB7s29URL/q6CyGFrJftOkbOqYaSCJvY69Dw/Aojuw1+JoxLu28MLe7BBlSyn11kWawVyamgBjuH2KeI8vUeymJEOFmp+AVuPc/,iv:g8XA0rnys16ox5dMMT8+hcX4tAFQgpSsu6DQ5zS+CmU=,tag:IMbolTLFSNcdQDsFPFTE2Q==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:HS3UW4HUSXkhw1jJk/py+wC2PgsHZTswwYGZczhAWiFgKYmC7r1XVywyI7iettHFw7Guk0CxoV4s9V6f8dz+dw==,iv:Vb9k8VcXvAQPm/tZ1dgF2Dq8AS3CX/2CU1u7X2GWsGw=,tag:y3ShTby9BX4WP+9KyTmf0w==,type:str]
    password: ENC[AES256_GCM,data:o7lWTA+DiwiPygJCZJoaTp/QiEBF0+7ME4msUYgZBpG1YK/GOwhsYF+GWcPe/+C5nNmNBRd6GMZsNXa+4SnVgQ==,iv:S0RKjUJ5jOJ5FAcLvXWEi6Y4BJpv/iDX3ytMxDRSkyc=,tag:XziidFAgFO6/ApLfR53bXw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:zxaRqCPlG1GmVwGD0b0u+WLEc7w=,iv:LdHvyZxZ39c6WCKLGFXYzzM6/WdXyWMkteADkutaUK0=,tag:TyMouJhpRY5/GEj3Trxk+w==,type:str]
      client_secret: ENC[AES256_GCM,data:iNqBprcb3nxvy+JEhRq15XouBZ9K+REt4QkqWve0cr9mTzL0LhG5Fg==,iv:HyDHYCY3HyJe40LWqcLCRe857M8Rq+hBYvfIt8MExPQ=,tag:kw9N/AGM5ZPxaVpvwnX86Q==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:4F0bZS+2YcqEUThplA==,iv:eE7Ebpa+SmMc6vUazPrEpXhX76OwLYHnXXsV97oFKpE=,tag:EubuTc7DOSgJhfSu5THgYg==,type:str]
      value: ENC[AES256_GCM,data:ihDtNkMxQVIl6UL4iYF8okpq9pMmy6FLPWS3Ardc5S3om0AU6bCxTueDrWyo8jY9UokrUo/RJkuyRp/SrsBoo1umFkZZzaXSf6dvsHUBEDxulLPPiINi5R0EJoKH6ALNS9sApi3OKDFsbRYkSlwIoejmODJ2i4qs5Egcb8adkpizRm2+0KAPzLvpHTt0Jy37L2hssStwAgda4IjsVzOtmMOziQ2/QYmR+NpFYJ9+uo/PsA==,iv:El5JEDVpC1gEow+zmwvExelfBlUC4UsWRI3MUH7AY74=,tag:NGSheq3iCv+P4Sat0nuauw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:6URMgAKnqWbxsoZuWzlkdPzbqQwNiJH/b3CiO74EEZQ/BbXWl96vVXCHEVGVK5f1p4PGQAg1OIMYYyOkOTYHeA==,iv:q7NNTKYj3jhbd8kVvxxFqyZL2S7OVvSHDUgioMGZQzc=,tag:VX2SnI6pGA8hd7H9zd0wTw==,type:str]
        password: ENC[AES256_GCM,data:p9V1/ElOFGOaTfmX40mLuR8xJx/BAA4MmI4nb2bd9/yUKFpAge8nW9zmlBQn82I9n0bfnT+HeVEuWr2nw/dF6g==,iv:33BemEOiKT2Wlbjy6gN9WV5GMkzSJIg6Io0GmyVTwr8=,tag:jZGO1aLJVo8RIMxGjSxcdQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        IShinge4faiyoch9Cei9yaiweithiecahsahci7aec3Moh0kahgeigh9umuaqu9a: ENC[AES256_GCM,data:2yZAK8V/kjyryizSbj6UDU/urXznDvZkm0dtAYV42fZMqTVpnr454OgXmIQjrcPKY1VPp5ilmfj2KIBR,iv:icLpvo7TtJOCWWh1dCQXVyN8j65eTCZJxDCU+k674fI=,tag:yuD+VE2O3AZ6QuV8PfM0JA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:34:08Z'
    enc: CiUA4OM7eJLu+lk4ySFbC2SLfYBj2Vb2/XWDVgeTl1CwgHpVi6ohEkkAPHlbmVIehJEjGAaxSTC32rdjNThTNSokJxV+WMkvGHRWv4vXXNvCMiPzCvXzXz118N6n69aU+AdJDy98Iy86HaKHodGbLKzp
  lastmodified: '2026-04-16T19:34:08Z'
  mac: ENC[AES256_GCM,data:6n03FVMVOWc0pZIAAIKoJbz7zmkyEcvFfnsRu1gZQBT/fFxp1ObkBA+gLS0WVR9kVRvyRE5+jx0/869zt+jR4itt6Z+cOabuixNv3nb82iWtVHBGPmSZ3t0mc8bNc1MtZ4gOZGhGyKNnNd25ZqhD24rNsoeRDHFObejccPsTIvw=,iv:wZBQQyILmxtlglpD+LyGHRiKDo669LgaDkMsYKj4BDU=,tag:v1uzytr4Jwx+KMPtV5QIoQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
