prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:xZvyqqh15OwFqss1bheyJbrFCOVke+9cg9gTE+HUDotwCWW3GomGkoURb09N29xQE2bz9YCcKzCLsE/47khZYpsDdmBGSa3IwqwlBP9vyepzgXGTY89pN6qyayYFP9OFS3bGZc3uvFKfNhUykUBstMFspR/44B6WUsjlMJBBH+E4D0KKye9w28d+jYxBSCn0A8ZOCazip8i758Kg,iv:tiJf9GS+MdRhs2xpx6oWqqiuSZ4Pw8+EIg1kud7iRxw=,tag:51wEGluhaq3hH57V5q1//A==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:gYgpXHUY14NZOCigadHKaoRd1giHS+5vmxx4ebMN15B5Amca9dnP2Vdbdb/6c9o/tPsIhgzt2ArWu5PcfAuL2g==,iv:TltTf56flOJ1/yFZguY1Y8iXiwLFF/OhQcw25xDEAx4=,tag:uugl18K3LC94AgpV/8FOPQ==,type:str]
    password: ENC[AES256_GCM,data:SUnd4pEDED/SHajm1EDH5MXQvlscVuSuqq3EW8sQsJ+IszzzO4k4oSTET+t1wIF6s8gsUADXGyGDYH4Z2I+9ag==,iv:TzKUiEsIbawCVXwcefoD0l0GbFgAPgHXKWrssVvo4dE=,tag:EfEL5NoQ1Fv2t9BwYfbJVg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:jnjgUrZrX/2NOpPnxA==,iv:dqjuMI293kEQ8VnTwshtIYGcYegaeB8gAenNqUOQaU0=,tag:QR9MnxM/0G21DI+F8gt3jw==,type:str]
      value: ENC[AES256_GCM,data:TjC6EJCwReTUZhGGdZGOkFkB9o4BIgdJWRcDkitJ8AwTVZfJWY6GD0MCq1SrABmNZhXp3L62NpXGZVclAgkV9iboF8wTqGserUPCy34VewbpqfkJCxZLMA/IuMp0Oy4cMMvleVHNFgUcaLne9k55plk/ZsNpPWyo2JXLmsihxG6O5SQMqPylzA8CdRhSL3D3nXyFiilADRfnB1O4xP1KSx2y8WJgSj5aiXwWVmJd30UwHA==,iv:Fyqpiv9TbKmY3VnCJh34H91HcljHcaCmlRWUey8MD0I=,tag:kBC7W60+pmJ72Fzdof5aqw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:STUfVEOo5t9bWSWCXsNil0pg4P5dwpOaoaWhOlnGDrCCcPiqTaz7MAhtzuydoZ4LkYOfAQviYGfVNxeYF1FLZQ==,iv:ToRUH8YN4C4qJB+nR6AZ/2UbUdsYKmazblr3wW9R3+0=,tag:XUqNU/8geG4Xg++6H6Qm6A==,type:str]
        password: ENC[AES256_GCM,data:S6vp9py99Jn8FJhCYYNa6YixGiY+R2nDOjcXWeaRxfqWbmVAQGDP3VNgsMTtvZCqwIrlWWRkjuf30A8FAZP0CQ==,iv:LFkyae5iMTmhOOm9ryM7lTDpuzyT4HtCvWTBtjbAPWU=,tag:HYnVNrT2fHBSgixhEUdsPw==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        W9oHidAdpoHYau9kw6cLcYrzfueKUETjqXuohZEqIM7DPM4FAut4T41Q6fhhoWdZ: ENC[AES256_GCM,data:WqpXuZHBxtDkQY67y4MV81ioVsQbMbevF+onyGU8JjhTnMDA3GK8HTiV5gefzOPJpc1nZ3yEz0OnaCs6,iv:gcsoUBV8yoAxWXBnmuU9jD9HCl3wsA6t0JXmAlrabF0=,tag:E3RxXT+Jgh6zuKWxxGRcpg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:32:34Z'
    enc: CiUA4OM7eFpT1qeO0Jxe1Hctfx4nkhZuKAGbl5KrixrpWRviMZkPEkkAPHlbmQTxHkD7Tsmjx2vgyU+7j+3zAsLMKb6Q4Xfn7CulkqjhD9/c7E9HQDg1uuXZ9ZyMzzVZ1a64IwT1qqekykGPGNg2ATJz
  lastmodified: '2026-04-16T19:32:35Z'
  mac: ENC[AES256_GCM,data:aAC04JVVyJumyg7x0ftVzd4x9wePiZMMJzX3T7lPe3qjA/ARv/3JqepCLuw23PQ03Mdyvv0RqPusqMQa457j15hOSOeVfzvwwAyJBim/AlutpfFyAa+mtxVcg0ffa7vlxazk5HmEhC5Mf4lHHTEV8idi4zYpMYTAbp1LACgfzDs=,iv:SC+/0v3K+ui0zGRc8OfnC4JFqQ2tI2FpqX1W3IUNNhg=,tag:c0eD2UVXBWjJ/NFdDGubeA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
