prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:tMZexCh0FEXYil5cbozGiiQwzQ6NbJ4TOfduDQeOFiYEjqqyHXUlKEUVdDH3LAxiyzOsx+Q7WvZ2pFqo7FDXzkbLxrbmYPdYTB+ne5E90VR/Om2x/9EPoOWunoBY32n2goCQDrpe4SlvhgBHBYgLh6dXCQ03D5J5t0mBaOkYU4VxfJq8n6Qvysmk92mMife1Fi5iVF+UfFJAezW4,iv:42ltnRR7JHvDDLVpvhmGwti1jj1LFjdX3k9oTN6akjc=,tag:hYv2TDzUvHnTSclmFu2Z1A==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:avKUCbO4aT6gTvtMEtnseUjxhgeSul0XF92vyYEybKLQBpSZ/HYlyz7c3/1QHXULxt+SbwPy9uGds6nTrlkvUA==,iv:BcJ1yzIrZzHFmS7q4S4qwBw/sTFfwHxQV4fA53gb32w=,tag:84PD2Byh+IxI446OPvnGMw==,type:str]
    password: ENC[AES256_GCM,data:L77j45tFX3f4y+VsSOTQ/+AAndS25RxE0V/6H698lNfoOwcj325VAYAToGA8E/u8EpwBob4eQGkJFB3UIHEnRA==,iv:mnX2PRvXe+yIFjCQTuy47n6KA+44wh+lDthEXTfxzbU=,tag:7zjfkE+KOy3uM1Vktwtaxg==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:T3U1O6X3tOCb1auUbw==,iv:AKt8EW1IlczLurUawO48JI9fQuJy2WeiuIAerPs1xJE=,tag:xNd8XSDacOtHuZL5URJAYg==,type:str]
      value: ENC[AES256_GCM,data:CWoXpCAaTu8b2RaElCXg2R80iytdJmZkkShsOBijmM3of7CZJ8dpJE5/mci2WEaXD+LYx6w/VPtBfHkjXgtbgiF/3sAIZXq4/+/IbbuKqm16pl5Jnjs3PPLaUfL6o21jGay8oStd2/PLSwGsF9LRAh8ZkhbfDfUhqIkMRMQ1TeaTdQrPmWVTR2QZS65VPQtf7hIdmucPkJMZOPSfduey+zMNEgud6IF3V2+R9bHDaaUhSA==,iv:x8H+ARCbp8uqrtOqKdNeftb3DS+Jal0bEJSGghtBOQs=,tag:XIImcywCb7K8iuDcPWixcg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:F9HSmUqlMSHrRoIwiP9pAitDp5ym/iIrJn2BW9vDXxnubBlfwBfbqKfZkJh6PL3g6pnMh7pvmujwRG7cU7956g==,iv:fqUDeWRCBWxGKhlNPS+/B8Li2gYPRVSIkskEeyoRzWA=,tag:fP31IqNs5DhX7Al7jZT/NA==,type:str]
        password: ENC[AES256_GCM,data:sTqy2f2E63rQwNMM0OE9jW+Vgrhd4hD9/wIzdI9tVdZWosLfX/jQ3IzGpfWPrpEb+QzyfozxrGJX6wT1lO7x9w==,iv:jYO8JRpe5xO95/oQyQbJGEChPUkvgNiByjz2Fj29SiU=,tag:C9ZImsAxF/VOrX7uCWLhnQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        W9oHidAdpoHYau9kw6cLcYrzfueKUETjqXuohZEqIM7DPM4FAut4T41Q6fhhoWdZ: ENC[AES256_GCM,data:xr7MojSDs3SU2W8mjXdYJdV9etbbZHQVQMuZLYzoT9jlbN1Vd89Idcf4dbbZEQ1NgynnFWf7TKDoE62B,iv:AO/QsyONdF9+VzmpaueweupjDwWDS9HYqFMnCrDin1o=,tag:2ZopLAwgtMfyHdr7dl2V2Q==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:eQ==,iv:LBF7cWICxJSgHvK3nG9v06m+EocVl4Stu84Tf3BuOqk=,tag:Nf46kLN4/+g2T5G1dbWL4A==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:gI/V/47UdQlQZw==,iv:vDw9CfmECgWiGf0ATcYx3pQmuq0/71kor5NWYLBDo4Y=,tag:4TFuGJOEzMQSKKaiDuA/pw==,type:str]
        orgId: ENC[AES256_GCM,data:gQ==,iv:ANFgsq2B40K27x9hMNOPOhfTL6PRkxTAGhcx0hzkmwM=,tag:w0q5+QfJ+xMjpPK2LLRy4Q==,type:int]
        type: ENC[AES256_GCM,data:hFICSw03bQG4DQ==,iv:PEr04jkfsBodIkLqG0nbQmZ+va80XIH36YEGoZ522so=,tag:5bMN1Sndd7v6wJHZkiC2QA==,type:str]
        url: ENC[AES256_GCM,data:Yhx27flYKFSUEIK/4hjfTCZpGSOCIgo7m835ubhAOHE=,iv:0WpGnGJp3KVFOKAjTFaCvZnHLLyypZUNVS1EEl6Y2MY=,tag:tnZWuD/Y4maj+NZsyhhJVQ==,type:str]
        access: ENC[AES256_GCM,data:3dBCxe4=,iv:eF22yIN6zoJkR+t6bqnDYhAMBVUieDvAVqR2WtqIaFo=,tag:6K4JKwIDhnbOWIwuYysMVw==,type:str]
        isDefault: ENC[AES256_GCM,data:D6+hCwE=,iv:NWJRdV9PV/d80TaL+aMU3KpStuTUcmpmD57M6RMNsJg=,tag:lBzJkeRf8MZyNNGKPuAusg==,type:bool]
        editable: ENC[AES256_GCM,data:x48aP3U=,iv:0gaDP1GainMp5bvh323KedZxRAOr8AoEQeWnk1v9BlI=,tag:CodJRhD9J4QJogF2cszXrA==,type:bool]
        basicAuth: ENC[AES256_GCM,data:mtCKZg==,iv:GiTfjWKJPdemeZxWgEX+cmLmKHNobboW9bk4zcvN4RA=,tag:J9zcQrJWb28a6Wk8NJ7QEQ==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:dimvBhBZ8hfTd0V4+VnG9Q416W42uqhgj7EK0zeggS4areyv6l4E0pXOS87tNnYOdlVUUztde4vPFhGUTY55/w==,iv:dp09ShZ/Xi4zWVnhnoaEvvB3T9bVmfDpXgdFFt7LRqE=,tag:GshER0CEI6FoDzEbqXWdhA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:9v6/TWr5We0ai32v3EYxyKE7faKIAWwwptIfNZFsrtZ8onvkTK/gknKrEsq2civLoIC4nDT4hJVGiOZrkJnGNw==,iv:Ya2B35hD9P0h+Vi0feWm5klVSY15Id/kN2jLMrD6Bps=,tag:cXSc54dCSht/wRVG25VeSA==,type:str]
      - name: ENC[AES256_GCM,data:h/qJLpCX71+PKvtRNu8wm79tUUGFGtJ47RnMpve49Q==,iv:b+4S6RORKm7WRL+dpbOSGqqW6YvSUjjVLK9ZzD6HhLk=,tag:Kvr36DMUwwdRy8s5IgV/Tw==,type:str]
        type: ENC[AES256_GCM,data:uwb+VfJkjvXlN6OkKMSh+TA3z9DRiiTn8R5lD1Fucg==,iv:+SR72Jai+Y+nZyDP8lY23TcxIkNwNtsR0k16RrNbSLA=,tag:50FuCpSDOYQ5tBzsK2pY0A==,type:str]
        isDefault: ENC[AES256_GCM,data:x+vzPHI=,iv:op55IF5KM9LgzJJdVEpf0piaDoHHBmV7Qq3IdWkdrEQ=,tag:6czVIn3nNLAyb8FSMwJrsA==,type:bool]
        editable: ENC[AES256_GCM,data:3Z8OWg==,iv:nvVhgk2d98LP4go4wh5mA4aDBe8LxXpiw+76069/3rA=,tag:+GZM4qPOxGz9sdTyHz6Epw==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:04Z'
    enc: CiUA4OM7eOon7pc3n93W1AI7uaNHSu/BXVUdw5oQY6lUkC4zXs6JEkkAPHlbmcY7K1gyhSkcmrgTbI54ig9ZxzD/chd/q/6MUu/FLKdd+dxWxAj/Xee8jI/Q9S+OJwVPJJPOInX4cbsnN1Df25PcVkFE
  lastmodified: '2026-04-17T08:24:04Z'
  mac: ENC[AES256_GCM,data:Q7PqAuR2twEmDUre1PVduuiK2M4+Au1RTPw4F3pcDI9CjN5gwimI3krzf1r3X0VgkL5b140eReFPkE0ydbFUOThBp7ztKLiMmsX7hOVRioR3CxN9HBXdSthYyxn8WjD9WdUSTBsZyn/WnqovN+QbNNqq5jAjY69XRhSKdOguhJM=,iv:65oAH+j3laon4KGvXdpCrY5Ysb4C6MHBvi8VbEOlPhI=,tag:89NCQdIM0pEscS4hjsy5IQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
