prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:l9uQPuEhKjf22XTrtzWunpwVVzI7b8tj/HAY99s8c2jX2Yrd/HdjwUWObQrRM5T/M+4K/E1FFuT3UjbXSoNzqlsJ+4LbnmAGqgE4DyqA7SlhvSts+5MEaS84UstlNTj8MuZ3/IDhXBuz1xlhQaBkCaDWYG3YzdWtdE8b6YeRLKu9s9Y++wTqKeeSMwR2Gmuvrte1SM+m1aagDHSD,iv:nedt3SyD0MjcsUAnFnegNaCrzAnSRutBHDc0neXrGTA=,tag:aYnD1531Ueye2MDq7CIfKQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:46nue8pSPrtFFWtSKzrL0lFkmjT1Xh5TfLpOCYPjKNeQNIPnS5jlcctYhSuXKXLUBoWSkpbGG/2OQmJdRZhCWQ==,iv:WVtcqgkbJc5X2UOEwEcqueY23nRXpj7cmtGC75D/dfo=,tag:crxRwTGuywTJO/hmHjkrFw==,type:str]
    password: ENC[AES256_GCM,data:60uUPbK038pJunI6NxAQ6muPqjJKxk0SxuJFHNRH/1PmDhTHy2Kvipc11jzrx55nklWoSsWaHLKDJaSsK+qe6Q==,iv:QeaiUl+zRkY8YsZAxjgeAbs2yAfRU2xG7XVt/qkF9rg=,tag:GOstJnp7w+VTxOqFyJm9Bw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:oZaaH/4tjlKSdpXwjQ==,iv:z2qEGBvy2bPMZk/lw9PKbdFjskCc9BfD9wBqzq4XXdg=,tag:hzG6in8qedkD1qC0YPqrng==,type:str]
      value: ENC[AES256_GCM,data:qwN3r9ZLC71iGBKeYC/r9R72wcHbThAXIk/QDQrW2/9Oc+b+gZLtY1MGLz+XOp5kbtIbJ6WW7305rb2m+zYe65tp0YTaFYiZ61+IHr7bn+rjhPeU/qxXEF7Y5Q3p+EnTH12Xtkr5eRF/0NRzFLF4FluigkvihvBb2uDSvkwx73ErhOndQet/MalJKUE1biQ+/7SFLYHFB//QqikhS5KKAX8zmAF6K5G4TPhdnhDT95+/Bw==,iv:WtC54SSyOkGYm0L+YX+lNwab4OvUTgM3NAAV3kD9E8c=,tag:5H6LMDY+sMP3GvkDik5x+w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:M+ceJxj5HwptDvuCrWXHR5q7FzZNXdyKK1/3iKfvlmlyUFOw/SN/Mo43KeY66R6VhrfYtzqBgVCCdKjvjuVJpw==,iv:2pGjbRtBQ4k2qE83fPYt6P1T0SklZcepHUtNi98Z2X0=,tag:NkTcHnf0Iyb14MDZQp64+g==,type:str]
        password: ENC[AES256_GCM,data:JjuSJIpb7alWxmnxIND2GlDxw42tWZv5lf6PPuKCBC8VqZWrIHJ552EZUPdUMMu1ywfc7vBTEzsCkiw3sj5G0A==,iv:xnL/xGMcMC3TsSIc023C4FSrhONCU5oLwBxqUqgQ9CU=,tag:kASs6rVm1jEWntNfGMTOCQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        YV521IqjWCGCT8ta5qGPYpdK5PAPZmpHBtDICjDG4x6FvqFa3IBdGOq4uyJzzU5G: ENC[AES256_GCM,data:josttkdkOjW/Sk5JnJYXp8yRIaFsirTaSo6SKLxajO4ai+n4h8lFV4du4Y3POWZIkobeaCXRCL/cpjjz,iv:XqJfcmXhYkBK7AbtNHK+p5UTmjX1BoNLVDvDVyQOnDM=,tag:N+T5LfnzUPI58pi814CvQg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:55Z'
    enc: CiUA4OM7eNY8d+5vycYSjcnhVbhNFIRaZ75bbJcNArlBynPQ0X7fEkkAPHlbmTYhzRkvB/MKOKkMHkNKyVBv4+35WGkwSE015BtdEQe+cIJZ28WclaoUCAm+OOpAJRnngAJcRI2hFdoLy2R/o3quwNp4
  lastmodified: '2026-04-16T19:33:56Z'
  mac: ENC[AES256_GCM,data:fSPiUT4E1ZQJMxokgfciNyDwggutcQAe3IzREHiBwt056M6yFyO0xV7QJm9hoN2qn0Jwx9PaWOERMymEF8BZ8vB6BqvrIfK26CpWtSRu++ouejQ0LMXUhBBOw5esEzvw97zCfHjg58vX9PaltcS/xAbacuS5QZ6+wjjuqPdfWP8=,iv:uHw57ovad6D/JPI+VEvQvtFfh0JFFnAELY+Q92u3lAU=,tag:M2y68vseeVmE72YIqatf4w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
