prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:dBY/LAwuioe39j8sp9wknc1gvFV3WJlcgyJm5nviQF6Eh0sEt7RyIwIQJgHMkfX011jeX1KvXlGQ2trrDUkw7ekrXW1QXDHYXjbyxE9YXQlJKlwg2nbbgubQ2qbViQOQ4SJFDv1wti5W1q92x+OMUVCDSSRF1VG6rj8/x3GWRT6RTG4p6cHOlh0U+RZn3+3Fmrx4EhL/jHsLpC5+,iv:Lj5CfTfDAMxzGf0fiFINzp53/7LfWg2YXH2OriNzFyc=,tag:WWKqJSzIjWFjnHY5lx43Rw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:6owxZdPrR4VTkCPweXsNDaBtC3dOXAYhBhO2mvxDaL9H4Xa9Zj57I+oauXLfUHGm7qRJqIHeRVAy36OgNl6aBQ==,iv:uJ20TmMfucObBFLltlI5Z8TcY3f0/PwEj517Y/qcIz0=,tag:FxV9+GLY8Avva/5QY6VPBg==,type:str]
    password: ENC[AES256_GCM,data:u2DHL6k8h9ffhd/SbB/F0xnum1GxEPIFTI0xpyOXrI+Tfi+o+DefOlhmcdaTagvmMMgCVFv4VQ0ReCnHBD8Xuw==,iv:VvTt9x8/FvhN4MHNaxHgAoLOmyZ29iqozivR4EC/aqA=,tag:yXOFquYwnEOEmoS/FbUsLw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:04rBwcE9sxp7hwXITg==,iv:UiPC1BDwcT/nd+ANlSIyP5Xq2lcbKGVilO1mGl2Qa+Y=,tag:21MqbDRzesZRttCMaO4WNA==,type:str]
      value: ENC[AES256_GCM,data:xIAGo+pGAJF8OTcTYTU4ja2MD/BcX2VRvh4IzGHaA5zl8fEBCM2978geM19kVnlCjJeDd0l/HsYDDh8VMYTew28NdzYxDIUC/3CCFFRLReqU0Wuje1WWxWyp/X1mKOUG+rme+dRNELnQ3GySxar7hNgi78j/YS1uXxixBg/ihwLg0AbATGSvLgWxwoTFNwz2Bq7zWddGE1sAbPNlge+PvJav3Ey/+DGQX+Z6rLujzoZUyg==,iv:pAYToG+uNPNyhHETF+lLKaNaonykTdfmlyXd7jOEOoc=,tag:CkTo8rfSuS5f2ZP/mYJbdA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:REZR+0I/zsCMHK1LMfTMTI4ThN8FGc2nE26EoDVrX1qySGpoGuf+cZHMq+73nXmMRTVC+hIBHjHQ8N8dMhnfZQ==,iv:4sEyrNvfbvEdQd5Dg8f5YLWZMXZu+5I5CQtu6iQib/8=,tag:Zzd4QjuC09iibniKkiNdlg==,type:str]
        password: ENC[AES256_GCM,data:kB4pgYX0kRE25E6LUbD3bLmHIwjinnJyzIizsQaVIZ4+SNumNd4ZAsxHpBrAzWY6azdySK/zM3UgV+2Wr14HOA==,iv:CSlMUkw18VHAZqjZb+NeRTHPUblIL8jSZeLcsFPchLQ=,tag:StLSlMmpZ1Ftc3fi315Ztg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        YV521IqjWCGCT8ta5qGPYpdK5PAPZmpHBtDICjDG4x6FvqFa3IBdGOq4uyJzzU5G: ENC[AES256_GCM,data:tEyA7Yd0lpMXKrt1/3xMQ5nq5V/xm+BM+KetsVjvVhUirTUo7GOQJwRR+abHpXugnxRVdpJzfH2Nv1hA,iv:syMnQ5WSNMPR8SVZ62BpKCbqWijbbTRErREFsXOshAk=,tag:d4hupIfuJpF5aAnwxFcb/w==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:dQ==,iv:199f6Q5q/MX03PGSNpcokvWvdNtOWUyI8bofgwRRiU4=,tag:EXGbx7DfqpkPjzKHcXVlqg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:Nw0w9BgrHzY+VQ==,iv:uOUHLyCw0s6WD2lmssu6cHa7A2cexGjU/kRDR8hyLBU=,tag:xg4V7KhMQEVSGeAbsBksDA==,type:str]
        orgId: ENC[AES256_GCM,data:sQ==,iv:wUH85A5QPQsf5qotcwl95zTd4/Y40QpvdHxfKh0TqM8=,tag:MInWXn7MpnjAYgHzlEyXLg==,type:int]
        type: ENC[AES256_GCM,data:htxjnKs/d2sQAQ==,iv:Z22lY9Lq0GzZpbboRQiVD5i+8+3zdgpfDXuF3XRwuX8=,tag:OpKLpmImI51g1NCCXaadcg==,type:str]
        url: ENC[AES256_GCM,data:A7G1cvbjWX2558pF+GC4rGqOhxf/lftjUQyEhOtaLeU=,iv:i38+DimUDVqRphK6iNz60T5hebjMafSXgeqqZZjs4Mg=,tag:SSKcVJj/YuXJDq6vkL6TwA==,type:str]
        access: ENC[AES256_GCM,data:chDrqOQ=,iv:6dMm1io01JahIn+ZarvkYSHFB2GbSh4Rj20dF4bk/GQ=,tag:+1CLc/cnyLp0Y7UDcX4yfA==,type:str]
        isDefault: ENC[AES256_GCM,data:KsEmJiQ=,iv:0rCtew4mXTR6mXjR7N+CBQ7EfnVXZgxyncptRwiH0rE=,tag:9hzzOWBdcWGXazv2C63XWA==,type:bool]
        editable: ENC[AES256_GCM,data:/XMtXPw=,iv:9fzxQtoLzQlbxkss+qrCyUaBjkzTADvK5AtOjAe4ujk=,tag:owwWcJYkVboYyTXTb/xXmQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:BRiKyw==,iv:AxbwYoI5rGz3EXh4Ok0i3bqR0l2ygvA2zqGgTnsORZ8=,tag:U32KLPmHAlPirciAfzxBOA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:s4eI69TPpKKaiHd2CnHoTTgMhpzowI38czOAnoXWJRl24pBH6USMOyZ90bfv72+awY+Js6VSRY12toPW/HSzUA==,iv:F0gRwHMy6517xZXU2612lWSeZWgIufx8c7BwzCp/dMg=,tag:qS4Ep046yr5/y2hdJRgYxw==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:IzYBufH+S+wASBwY6eMXkI1RIeIHgjZh3g6Q+1uS6MOAX6AA9CHjlXxp8y8o+ELOUeFO3D924R+kqW5EzcF7Xw==,iv:CL/Cw1TjcqTXB+l22cfLvmBB2s2plsdtTKAh1zPE5Jo=,tag:RpZ+X9n1BD5FnOuMKcEERA==,type:str]
      - name: ENC[AES256_GCM,data:42kS/ZsPMexUm84gjqaeJpRGWhuenpZBG7MxjIL39w==,iv:UcZYiXbyIt+S9bLnoZgKABYVf+P/Ib8KA12uQmdnDOQ=,tag:6aOPNroai2V9/lHl3oB65Q==,type:str]
        type: ENC[AES256_GCM,data:olC6N6Oc4TO9pezlV3MDOGYaBsmlEM7j22qwaj9ggQ==,iv:HItMpv8UGLtmP3EKnxEmHqLcfwYgCKMeeUxacPnysos=,tag:7cvnj/zvulXEgRB5yCjoCw==,type:str]
        isDefault: ENC[AES256_GCM,data:Zhj7Jmg=,iv:El2ubS/ma/38ZaPJhXy06+Yj3iRdku2cFc1MiB+44YE=,tag:mS80FAlfZKX0pV953LSUgA==,type:bool]
        editable: ENC[AES256_GCM,data:8kXuwA==,iv:5BD2pHo/FKQmklplspVMf1PUAxD+mbNmH9UqnvONHbQ=,tag:0rjeHToN8Fqmypj1t6oUzw==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:18Z'
    enc: CiUA4OM7eLvEdikcfHzweGvxXEzqoXSzO2LdOp4SYOytP/axypy0EkkAPHlbmQp2ZBNTOYjH9AcA+0tEoT05c837qPsyd9xD+c8TSw+4yctpvCGBjm/qATn078HmWQiwdsSuFaocobz21VkFFEksjzA0
  lastmodified: '2026-04-17T08:25:19Z'
  mac: ENC[AES256_GCM,data:TRXLbuOf8g91ugCffe10QM7EUSNmHb8m3O7Zy4QozcTgQjSsbPYuG8y6aFu0CHD118jhjH/ASwwLmxXfGkdtJ21rVXpJvJ5EUYKF8wyWy6aeNoNhCj0Dx/Dn/8YRr0qRuTKZqYuG00XjVCzjHSvXlmJfq0DWXFUe7T6dhBK+w5I=,iv:Vo6x0z7hAlWcMCC5v+UnzspfUoxBdqXv8xDBGIj/lXA=,tag:iaAhWk21p5QoFelh6fpx8g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
