prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:+1A2iHHmYRoenckO5aKrD/sYEwf1wH22RVQ7gzLSBdTL1XOZGcgrBKrjvmaP9Co3f+ksjsVLPKuWxeqKEiBSEaiTxXzFXhDZvCfWgUiPPyysJCJhdiOqY4SqdCgkHwFkRlZ3ArhEqKOviEpo1yYrqz9lR2RGB/2rA2UtFSsCIAL6DctcR2J3Oo7ypwzj9CT/nvciRKDn2k5LhZMM,iv:jK3lyoaDXRiVnf6XFOyp2iF9f/hySDNITXz02nRPkyE=,tag:P1bHlTKzgtNw5J5zIn2AAg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:+UuC2eDgCOi/bdm2mIkLY3cGjGailjUx1CAvPfnf4Jr65EXMJnvtTTsptvU/UMbjPVBkvdp5TD8kDJWdfgzEew==,iv:jSe71wM48SXSj007kQ2VibkZBu3wUfoVmgGR8baFF/0=,tag:rG7yojkZnhExo/7AcMPImg==,type:str]
    password: ENC[AES256_GCM,data:yHMcnFlLIKPydx0XRqSdiMurVUxJzXAeQFyZTO39v72FYYQ+yzexBRqAppEqvOcplld87pqae9MFOAL+R1GpcA==,iv:OHVsG3kGnYT1kvYbd173rCf2FibjD/GG3D+CRK2l68M=,tag:xE8tX0iwM1tbUW1ZNxyb/w==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:oyPT5aI5henMeLKPxA==,iv:3u3gElAvWiwhO5v1IdPxvElHL/B5QBG2NpcBjk0FFrs=,tag:YprmYhIQzkN6EOlMbi3E0A==,type:str]
      value: ENC[AES256_GCM,data:djaS/PvdvT4H3mjV5Pp1cSlVoyfhRgEYnCbHaSHvD2ndmvlXDqJTgPCzMDVWhEmUOy/TMrq8OJDMWQ+GMTrenJ3BVKIwhaVxZCLZDM495e/jOdhe+jGpWqPSbZKBqIIa9/U8VdRJNKK9fwMl36LzKFNDy+jixafxMCWwgM420ed40uBoYEvgF1QtJUwGEq09XgrOHKYmQtNrXjxO9ipxo+RwuKs6/xs0T7zCOn1qg+013g==,iv:Ac6LRsX1lsPsa4BcPv2lM1fJ1UdwTGK4ZoaytmcQ5fQ=,tag:TdqHwYmNWWXuDKHmMnSn+w==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:5W9rQVQG5wc4WgSp4t8xWTZHOq/bxUGsiUviruHahtGhTmmknG/SvBKWjt9sKku3s9S5QtLN81v8iNdQz2Oa6A==,iv:OzAz+N73aLHo92OskEamE1tQkyW1w71ErYbs1LFZvwk=,tag:iTUm1kaoEpSJromrGqZaxg==,type:str]
        password: ENC[AES256_GCM,data:fQfKv8iPMOCqZWOI7SSZEiXqb9SuOQR9zJk4MxBHDT50/3C+647GHUAJJAiUW2F9amlhv50RIIyBNIo0YeC+Dw==,iv:aoeOwff4zZbfEJHADDwROYs0G8owqJWAuFePL7x/f1k=,tag:ijSVGsetqrZHiejsg8H3+A==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        OyFZM2bRc0wzQ5pvRSKRL1ic3DPihHN2ZCt7ttt3bVkGwKvinSRGfpjEVXVh5oZs: ENC[AES256_GCM,data:OyhtVKBsyTSW/Y7aACqdlrk4g1Iqk2zSAqfNyFEWkd1nWGN6KFkdYFJ5V5T1QinPTaCa50pb9TWOANbb,iv:zhflbbblKAT23u1cMVa4FO2GfCUcyT6DXtLBNKl0xrU=,tag:v4UOrKqbyjnSjnMSjG9lMA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:34:02Z'
    enc: CiUA4OM7eHu94/8cHRIe1PgHiu21WuBkJ7C2gmhTgf5WFc6QiWXgEkkAPHlbmRjjq26MuV15qusD890EAGToFLjuy2L2/wIZ53pVw0LgRMwfio8YqvGOupJtJPNzJkLXbRpunQlzwcYKPJ5l5TQXOHY1
  lastmodified: '2026-04-16T19:34:03Z'
  mac: ENC[AES256_GCM,data:26eEm8uSJ2uQUOWKUtnZBjBsHfLF9rOyxdm5a0MmOS3+ACnqKIH94EjYVT1lnZ8sNe0+Jh//+olmhuEVnRk/8M+loyTysy3YLBzsBo4ryrPwxpWD8klAgCzzfnpkS39DR5/HwgLO2dQGTO8KWx4UUo+yBlvJoz34LZYtegMmM7c=,iv:uazMb+V99A9UfK2eo2Z0q43sV10r1/1mRZP8fii3Bks=,tag:Xh3wYKKO6oRH42X6mvpWFg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
