prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:P4VBA9rVS6OX6Hnhd2bskFhMwplkxm3f6QP5c8kK4/sSOlxySBiDWfnNuNIzSO/P8Zw5yaj+mVbFHpbGKoVWjz+8MEfHn2K210a615xIqYqr1IXAuxEzVrZ0UVjJYvFF2C00bd6T16fv68cwSiEvdxXdIdsU9UBWwdc+S9MVe3hM4wTVOjItEQvoHMpCRzGRTBuHsCk957MMqJdw,iv:23m42ekIVJ3CkV6u4XShA7+p+GU1tnktA3MlbYhkSUk=,tag:1a014q/OVe6nN0Oi39zXqA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:BcIWwHRnrY+VABVnDaYoDOZrl0SXBTbWDYTSIMFPrtB2Bvl9mkJKmHXDYKX1DXCGonwfytaHJD6sgXpy37rUzw==,iv:m4YGzpfFlAdhrxTGZizokusyv0cfOme1BPMYgzakwaU=,tag:oXJ4Wh7eAmHT2jv0ZJJZvA==,type:str]
    password: ENC[AES256_GCM,data:HoQtFz8zlGl8zU7rxPRuNVts5QJQjmS/3IzIoyOlJW7tuNqkPkdCg3tzF4iXRigPJdxfpBXSx7NV9GmYuSW5IA==,iv:FcH+HQp5BrZNAFhdQ0mjuLafm7NEPNdAZrCaKvO9/iw=,tag:Do8/xV4f+IiNthW7C3+GcQ==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:84qbev33dFN1n6m+cg==,iv:myEXVmt0+qg52KEQuwcWl65dDQrozj5l7VytE7u1jhg=,tag:DHoilpou3pv4EQK8aV8MfQ==,type:str]
      value: ENC[AES256_GCM,data:7vINU6AhFmNvTk9B3W3040MnxEWLUKghis9ZKSZgt8zj0PswVk81QT/GqXCDSZacZIcafaxPM9t8qEIxX5NXew5F66NriDpKytlxhXg6D3bzffFU/5B4gSbCM03051kTJsusOkGNux8JY6m9ZDLWrLQXBQeb1GXshqw4KxQkrdbI376V5O3ZyQhzKh5tlUZXogeP/SFwB8AwpDicuSAq8aif7cttQj9E/QXXB+1hjQsc2w==,iv:IrU2N/lMgV9JG4RbUu6+eG3rdidvZU2cyG6blbm6RRo=,tag:y9exSG1OIZiqmkdz3p8lJw==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:txSCe7rnpXndJtQynHWdC3GVrrlTeAeabTPI+o8pB5uCg2gx5yIT4ATTVYDEdEiZd2quFkRqxySzJ0PwmIbpSw==,iv:nPS8xSuVhA18ve9TXoL2FL7ChNoDcECb838DDuJMwQk=,tag:mTJrMGMzVHtwpAkzgpw5iQ==,type:str]
        password: ENC[AES256_GCM,data:jHdU4jb8r8R8u+c6CjIhtfFpS+5wT5ScGn8JbTyhQtQgidKP18daVt6XSI+7U+K0GcFLASFP0ej7Yu089vEjtw==,iv:ug2pGXZfLRJyqu9ghuYFu1fHfUza14lq1wmYF5OLx2Q=,tag:a8efVpuATSJpDqyJnAGK/g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        OyFZM2bRc0wzQ5pvRSKRL1ic3DPihHN2ZCt7ttt3bVkGwKvinSRGfpjEVXVh5oZs: ENC[AES256_GCM,data:9LcB83bRgzb58Vam8M02Ff6zC6zR+buesabQQEfWDmfRsKshFDzFuptc9qX6oW4rJjyjo7nlEcETydXq,iv:DPOetY126FwMpRZbMJzEoA0HrFs2c0fDPuEBDGBJ+YU=,tag:brbof7XY5ubcROob9qXc5g==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:EA==,iv:NEA0r8DeBLVX/wHWe8ksjeYScEFeGcAUK1TGx/jayKU=,tag:taPI3LhZL50V8XAoQwG5iA==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:LwmRcKGn+Idfmw==,iv:y06ZrrfXQT3KA/ozaGjswInFwepv9a+XLEo7jSl1r6I=,tag:+blJT1mBZsCAX0OLHb4ODQ==,type:str]
        orgId: ENC[AES256_GCM,data:ow==,iv:kYuNhoVCXGW4gyBvVmT0JJLbdT58FlgZsxmJKX2D8lE=,tag:xMsK09GqHrqAU9WaLG5ErA==,type:int]
        type: ENC[AES256_GCM,data:Wx6BapZtl22y2Q==,iv:xQtGe5VpxPk+69xzDHc2JFbWt50TF875deYykZcDjxc=,tag:JwlUqCaVyn0H0QTjo8tEOQ==,type:str]
        url: ENC[AES256_GCM,data:fU/QU10UaJzplzWNzZ9EruXJZzH4bcoUnk8AO6AFORw=,iv:ir/lCEMQsatjKDrK5G+Y9SMlR5T1E5jNOem+b67V1so=,tag:2VZngRfJx1R1Z2x916QY+g==,type:str]
        access: ENC[AES256_GCM,data:ecR6JE8=,iv:REy8TfC0lHPt26f63kQWIeNiyPC+9NlqA9wfxc9A15E=,tag:lyM91mW8ANNEh2ukPKKKag==,type:str]
        isDefault: ENC[AES256_GCM,data:Dj+OiHU=,iv:J5YfrX3YQFlfpzA+CGvDhMXNLZ1DAFIL971SbbYyJmk=,tag:f1KWSL3Gx0IoxHeLihJewg==,type:bool]
        editable: ENC[AES256_GCM,data:tP4wC8I=,iv:dEI+7HK2ln2xQspCJnuewhB6a1cJUQdxSKzXeK+1+FM=,tag:rWcktxWlm35pjzyTcWkRNQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:OBSKjQ==,iv:twOUHzp8JbdlRdUtHHpoBxOXd1Q5Q20Bh97lfa/1aoU=,tag:3so2YuNoymV7/RUJLDX5xw==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:MiUHkpKsM35jrC46cwYxxNXv2cLfT6IrxYa+qUP6IZtOZBbec8kLoqXTTIPezENGPBw/4nAMP+vP9v6I72+nvQ==,iv:aBlTTxvt0YAHXrvdRB0cz01yOC+GxWDx+z9TegQSTbI=,tag:pu3R9S+qdD6skQQuWlXF+A==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:qvjXL10nYA2ARoxPSETak1MJ5T7c+O2Pz+QDKPZPPGzP1tiSpiHj9GwPjaqvoeAhtO5vUrdrG6BoyCyZ9jjxNg==,iv:qS85J3KR2FNigg504Xt90guNWOnsY68x8hXCFkdDoDc=,tag:TxjfpEhWeE3QAkvBaFPvqw==,type:str]
      - name: ENC[AES256_GCM,data:Jok+QcWpzkewn2EDpchj1RkcnrVMHYcEMxhPO00CkQ==,iv:iO5mPHgrYBKaI3N2xXKNR3JhdGGyN5yWXO+ojVzwY34=,tag:xiWsb10WLuigYDRAqeWREQ==,type:str]
        type: ENC[AES256_GCM,data:o2EM+d4luufhkclj6JUk9zJDSAS7EgQ5C9lyBrifGQ==,iv:XPTedS0JvYt7xXPaIZ6dy6a0HIrOCUHNcLoP4up/ozw=,tag:oLez1/7o89NWsXT6TFoLtg==,type:str]
        isDefault: ENC[AES256_GCM,data:nBf99ZA=,iv:c78PUX+uYbqAYNudzrpsDcQNJhvk4N3Njy/VPSPrDwk=,tag:ntRDtGGK6cJTrYAFcW3eqA==,type:bool]
        editable: ENC[AES256_GCM,data:Zm/HCQ==,iv:JQUgb7H1DwFj38+qRTXBxoPyC+U08wB6AESUKoh4IcY=,tag:hVZz4JAA+luv77PFZnu8ow==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:26Z'
    enc: CiUA4OM7eC+GFA9VAkif/QR0cBTgeOlGJmVNUJMIqd/gxcLTiAK/EkkAPHlbmf90bRYg1/Kv8MloYDFuiOivgCHGT2B2GG8Nz1ffo614xdwWMBhae3Hyv0AaFMCwk3ztplMpwiKrANjHaXEfQLV0SgLX
  lastmodified: '2026-04-17T08:25:27Z'
  mac: ENC[AES256_GCM,data:APLqC9klMnvdG9YjKd/hFC+dUjzLsVf93Qz0qX5YtUYv/KZDzivokIt7yomFRxnuueREY+CuYfiDL6rf7lQ1mt1Y1+fGfAOk+gfdQj6O6sq/xLgXuyMgv56Kp2IsJGh+njwuQnvCEqH5vCatnAMJYKf0NEBcpMqsjL9GejnUURg=,iv:Gj1eet3FNHWH2XiIv/EMQJc2Qz7wxsaQIY49D3MaJsM=,tag:K9RXU+al5SUYiiJ5PoJ2eg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
