prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:NoACPGCNMaAtqn1yu1Z+JBDolPPwaWkCVALARYQ/3EwdUDW1Yv7StKFiER4URkrKPFP38XJhcxvA9QOZs6WrVGtE8NxblaytY06P+Vley5Qf8lfQqDk1Ra2tFn6GbF1cZqzNozaYKQn71l6mnUgc1Vp3ZPTh4BRC4mUWxkfhnpKjRj8J7rxDtbLBPICQ/c9et27IC6lEVfUIkP1l,iv:FZzCXFLzJM9vOJqgcXUSU4YEojauorEEuPylkCqEVEQ=,tag:RqVpJJEiVUnQMJ4JeMTy0w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:wSOAkbsUptCHbHpwS7KDq92Sf93iccSUJb7vNFlPnMhkuRYRrisG8jrbv/eUWgQthlo9TuZpEbKZdxfR52Uv0A==,iv:GyetrXsHNecxBYjEqowzoPVEJ7QpMy/hOggE4XOcxWk=,tag:EqucKhy9WKuLayCwiEwumw==,type:str]
    password: ENC[AES256_GCM,data:MLS8MI3vviqpitkIE3CiSMRGZJny/j2agzFDnL01rUNuqqpkCrIUk6LcMCCZcZEVKZ1vc+zmtZLAi1t/WWPQ0w==,iv:gx/XhlAZzLTsA1rrUPyX71YTFDBOsJvhx+YrS4bH5bA=,tag:S2Pj0WnbdT9wnP/HIsc/VA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:6w==,iv:bYZ4BpZYRKcwRMe4gmBo8hxc3LeEuroBu+IZsP0ut4A=,tag:7qZmFmTn7kpY0+e5eaByww==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:qXOizJ9TyTSoOA==,iv:fn9JuW48ZWSU238BqSzXMbgH3Ta5gheDa/PIWBsgCB4=,tag:sedQ1+AvSZM6qE12gRlaBw==,type:str]
        orgId: ENC[AES256_GCM,data:1Q==,iv:DnbqNsRsOvSUA8FIkxUxnaK32rmax6TcNjyNZegR2vQ=,tag:HEMwxhZDW7IOyXqco+QQ2w==,type:int]
        type: ENC[AES256_GCM,data:IXhYUqFBOLi5SQ==,iv:gIoTdziEtYM5qy9Lp3rVcbS6fNpLNpx9KzgVoGNqx6w=,tag:oXJ7kb6Ar7Hco4whk8F6Kg==,type:str]
        url: ENC[AES256_GCM,data:S9XahxqNrp+Q5kuS8EEh8LZzP/WMFzkQ6+v+2pWjRHs=,iv:NWYm0QAqfLeaqaQI0jm9HhXO2uZGJtw7WxXi5KVKySE=,tag:UbUhwCbQNnCzW3ktp5C34g==,type:str]
        access: ENC[AES256_GCM,data:jNt4ILw=,iv:Fy3AWIyCA/a8N5LWnuzrfCQSHb/f3a/1+WfSj/Z/DrI=,tag:KoTeB+RZv+95ISiwJV/sMA==,type:str]
        isDefault: ENC[AES256_GCM,data:kMTDIu8=,iv:JG5/ianjNemARZB76MgE4reSj83R8RVsRzukYH+aXPg=,tag:gRHjGu6u/XOn3YRrSfUvvA==,type:bool]
        editable: ENC[AES256_GCM,data:zkK1Wjo=,iv:wg74ANmppNQFhSHglNkMmptDIp2eAodz2SeBesa3Ak4=,tag:jmae4c8LQyLH//jnh/nl4g==,type:bool]
        basicAuth: ENC[AES256_GCM,data:Mq2z9Q==,iv:UOqiwXbxwqtEdH1EMJEHtxZqorRdMCZxdWhX3lC8PeU=,tag:NVMzT67toGLZmXhYgb2l2Q==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:WBzQJQdCX5P01thwyMVDzpwroooaMP5TcJWcpef8JVh2FuHPWGDB1fVBp+Jx8544wlVWEI089RMFiDQ67qGC8w==,iv:dL4f6VMtP4dQ/OmcvM6RJXeT11u20ZkQxzGP4MxtW6E=,tag:iavNUahbfAWLOw4YRlThPQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:ivQNpE48USkyNl6ooQNEpDUwp/ZN2y/TJs1Lr1jj5xSeXUS1AKDpQ9+qM/z+OtBj4rRYMO+/a9QbJlFlOL9f6Q==,iv:rs35yu3XOqPTeg1UZdHlqngMlp9FZQyZq08yeb2eKTY=,tag:AbPcp1SDfygqLV7Yh1nF7g==,type:str]
      - name: ENC[AES256_GCM,data:VUZOZqDYQ6kNFtHTQYbaCxc2JD8/ggrl6CG6kTqHhg==,iv:M6cbh5IaEuDPUScvlD4SsB5+b1oSXVaGW1u5W3KUZZ0=,tag:k5PE3gS2BkM7LT+6f6moiw==,type:str]
        type: ENC[AES256_GCM,data:HNVS+JA7WFkZW4C0Q5QugnlkYpKxoEGTXLy2ZhjtLg==,iv:oUF5KOT8+SpHVR5BOb5IRqFAL4tSmzWEfDCMVfkVBXg=,tag:K0latzOnFZOjdM5VOW3hEA==,type:str]
        isDefault: ENC[AES256_GCM,data:Bd47bTU=,iv:jL1whthVDREs0oYtW7lk7t9d+fmVer7GyJW5IfJhDbw=,tag:eLVUs69F40Xu+kjrZoEn+g==,type:bool]
        editable: ENC[AES256_GCM,data:JUyPew==,iv:NUExsW3QnKK9T7iFeazjZSVgKIZ5yR9kmS5SE1GGEWs=,tag:2VOQwlGRAPd+KgiKkO6JWA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:mOuEXhhLd8+PZDMkfw==,iv:dZ1T3J7Xj0/kovpHP2H9zsUnW/eoRBPSlEQSwrWcJh8=,tag:YUonye+psqfRxFxdP1MbNA==,type:str]
      value: ENC[AES256_GCM,data:0WMa6Nz8TD6Vh8xbwfPZLC5Q25sqPrSzoxyBvo6CSZR3oZpbW5jeOgmsHYu0IZBuHsrA5VfaZs8ggPJIZwcJ4y40U0XROvLs0x6PgaUBXpqh6doHkO4iPceovXjoackvay8jqy5KKy2XDAIJXi2yTIyG88nC87fVRO4V7wf51RF2IhG0CFq8P80an36s5oZEsIuwmt2YRc2UU76mn4NvbjF5lDZCsP8LgxlFkfXTmC/aeQ==,iv:88HDA3g8ZiFg+bC1SZjcKQvjCeQYJh+jYnoF3Q+PJrk=,tag:E6qm70rRiByNBThSjsUgUQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:2YocUzpumpFF73DgJQrh2IB1aPp3PAdnADaU5vWgD4ak0wrXYmBvQYYT0+AEJBvvAHzEPNvYwbfK3BITB/OLwg==,iv:vRJx2XhHfHq7tCqeJ8AAqCza1dIlYLoLdQAazUrdeXc=,tag:SuKd+XLlEyHFr04gMzv1cA==,type:str]
        password: ENC[AES256_GCM,data:pD9dBJ76bdXHBA+pAOMBTCPc6BuxXcfD9IakuSLkHCFjrC+i6W7evh5+/mbJvdTpYVih6i/dcZUOM8ytqAbSYQ==,iv:SUO/XB9f0Jnj9zjG806oi0Ko6dN3Ndc6oOCWWwcd67c=,tag:5QspeKALHubfp+bvf7Y6rg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        SEMpzgVnNN2gJo8iT1GUbQZiApa5Yv64sypBVsqD6ozG6H5mjoUcfRLSoSQTqWDD: ENC[AES256_GCM,data:rWYgMHlAgiaoAUMtOQHGgtvp92rYGb1LHO4zulj1frlAMkfQV1Xlk4USp3DG5aJdXm2uFRd/wYtzKBKF,iv:0nCglq5T5TjvPSz5xnmdLFOqL8j2I+1Y89b0x/hugP0=,tag:MTrQmitduoji0DBfqpoB9A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:37Z'
    enc: CiUA4OM7eK6iN+crg5Dtj9xfoz7XJJpW56Ja4gXfNQvqcwTeoQ+1EkkAPHlbmYTkuXKfqY2X3wX9+zZ/eYvocT1O32Lm+LJ1ZpjsoDmvq2Wq1p0Kw5r4VIfU7wa6m0rvrIHERohw6+0e8hW0iJHsdZeM
  lastmodified: '2026-04-17T08:24:38Z'
  mac: ENC[AES256_GCM,data:vMbxjtXlRolbLnkolXH2UyCDqpw6+1KwCgNx25JwHQ/HIJEKgTCXdmjrI/0teZ0zyZnraxOyQYR6y3MfGfrV7bwWar9xlkXF5TPI+5FDHbKCyNnLV7AMZTGo221mjUlVDVOlyfR+8KL1vagIebq9HxCcLn6yT5KEA+oNtzFJvSY=,iv:MgOWOp9aeqBnHR8w42TjHW3sKF49mCIUgq9k7sKjUiU=,tag:B03MdTNImzUpVm8+dPfUPg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
