prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:y1YDg+qjXpA3AOXIrxUKDYoL9HavxmaEobv7xFHnJCMUa5HANf5T2ujjzEr9qKksbSBmt8rz4/y5x3ylea/bx2szJWNhS/d6+F5t0G6G0jZun08OcU1Jl1W1zRB6Eav/Ir6YF8gV3jn39TxyKrYM/hnkRH8vWt6f/iciC7iaRoA+A21JVFsLEuFQMiRb1qWf1ow/7S8+zhz32yNq,iv:AHKjTUFyatkrYcuIUGiJXzD2/g1KfHzAq0CWgD4qkE8=,tag:MSbYLEHs3d14Jcv4WVTOqA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:A3oUgYzdr/7iekE8WlgVojRmJQRjrAIs0Tn+ZciC/OfO6c2ExtzCAQrMM2QTuHCKLliOtsbzL40yVzyK19ykGQ==,iv:GhP1SPKg8Svw0tYIHVj0y7vf7VkGMm35fHjmD30C5hQ=,tag:+pmAhkiIRwluyTN50PTNDg==,type:str]
    password: ENC[AES256_GCM,data:sTCAkcZlstebi6cScyRrsCjwx01NOaB1cSFfsOdiSj3YGtxE5Ea/HXEYQFVunOlnpoBPhjPJnGq9Hm8lztTQRg==,iv:5TwUCpy9zBrvtgdL/HF+159jHK4G/OBK3a6toNoiP3c=,tag:wHC0Jb3qlUSnBoHzrZyCew==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:ngfwr5ksPlAHBrJHYpaaPq7ujJw=,iv:sZxqal5SOEBFb4t7BaewnvgdESwqFXZHZqoutzXYFB8=,tag:We8msTU/DGEjKpVILFtrrg==,type:str]
      client_secret: ENC[AES256_GCM,data:ut0sfhV2DUOcflOj3uwHNWsNCwHeoA6/VcOjUgmj2R7l7CAROubnHA==,iv:oj0Ig43kdxlBmZO0FpuzzfeZr3rLtl8AwYpSp5r5F7I=,tag:DYQtfKjt5VKQaYwAjwJPxA==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:qkauXkwMohFpvDZO3w==,iv:Mlv4eVVlQXg4xAL8nVyChh1GP1ku+4E3bTtCJK2bkrQ=,tag:h9Ku5cdJ5P5p7TBmdmVdbA==,type:str]
      value: ENC[AES256_GCM,data:MavrNtwmD+zX+xE1XETmMFPZswzJDRbk1QhIVDTruHCyk3pIhP4TRWYVvT2b2VPzdzOC+34J+AAAxoOrteLfJO1zSlrTtjwUE/B+3vBc0Mgcsjg/qNOn/UvdGA4d8wSrWPYjZIoUss5hwT1g6TfiaDV1PlAwAl9NxyI2T3EX66QBAEiBMnadO8erYflFsi1LO0MvUsLd8H5+UuBWSaxedlvxBskaxuAKGQPEwqv4mMWQeQ==,iv:F51BatSETHBI132+7NYwe5Zq6LNG8o8NvClldNk78q0=,tag:uOlccbux7EBbOu1iwYRvAg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:Bs6zXv8pr2vTTQ0uLs9IyrQXjKXWuXqEzeUO+LfjDgOMFKcaGUxyRT4nnSgXbSceuYSbKn9nUMCEmW/q9zGZ+g==,iv:DQ+tSrdwHvGWNPu6CDWtkT9yRtBt5EqVW/jipS5xMP0=,tag:Cv6ejEyUk/bNky1Lx50UhA==,type:str]
        password: ENC[AES256_GCM,data:AVEwp7Ix+VTesnY3SCEUIisQn01Kzi/Ndp1dULTusZRefWNBAxvJycyjdHFysxz4TZ2hTRatU2LQtXHR6LqlQQ==,iv:eC/kMhn/Z/8g7TmWwOa8ehKM/wl0qUcKHb2K7rmt5i8=,tag:SK5tfj4bJSp1BHGlIkuVAA==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        SEMpzgVnNN2gJo8iT1GUbQZiApa5Yv64sypBVsqD6ozG6H5mjoUcfRLSoSQTqWDD: ENC[AES256_GCM,data:OiHdNVkdU9ElvD2NH6onDEidCJl/FmDlbDw3ccf812oEBR46ol1v3npGHxRavVbUxmKJhjr1lTdijXxf,iv:7MD/5b0Gno4xOp6IdNedY79PIytjW58T2jKewOi/COM=,tag:1hWRNvCsZ4L0iJChJBeq2g==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:14Z'
    enc: CiUA4OM7eK2PBQugVva6ketgREj8oUUX+FepD/9dFs0tIeFSQ0S0EkkAPHlbmddTaQy9JgUyjB/fc2O+VeNYNY2yVUWm+YR0OdBCY7mOnHcYvkt2WnKnmAZmJnxrL10yAVYH4SLwkXEPvcq4VQKrksvl
  lastmodified: '2026-04-16T19:33:14Z'
  mac: ENC[AES256_GCM,data:PLm5EwwJIqOKepmK2MzGy6N2NRd1iVC1djw3TypoOkLTsmAaT6GrPdD1Vey6iXxHkctb38J0aRtXood2by6m4yGvHLPO8E3kuZZbvBP+v6hIdtcHdWMLTf/5tuXJXQoWlYRA7l/UqmA+PxRLjWIb4wVBR773dRkesau27ZcKwV0=,iv:HsqaapgIZeWaCJkdNF/xmDwWbWPoiigUCEaSsXmPMmw=,tag:s5N1uck7ArUcibhgDhZtuw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
