prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:wfHbD9NGGqKlXd6eMQ==,iv:VGjxBrREYRy7md/0vxqsjynT+HSU1MocjPqUAXKQNNI=,tag:4AH+JrU/nDuHCUytwZfwjA==,type:str]
      value: ENC[AES256_GCM,data:NN/tQLzRTZdSHolLgPuGezC1LpNcwJA5IFInYJLXQ6RwohcwLwyTLmnYnIBpoEKSANyx9NeG9yLbFXPTWDqnO3IXWYijWBJ6qeu5El/EUK91JuOzh4Vk3gh/Jwy3BMEUlyRRWW4czmZmO++xoXx55XaRD4JKi/8IpzCpM02zfcUe6nfly+LIN3lGEeUP6uY21mOUulPLvYO7nSn9ZGBWWtzLqi4KE4dbWKAhMWtS4SB3jw==,iv:/SHlmtjNtn4g3W4IsEfjQQv4eiR/Y2rNiIZhGC8jZ5E=,tag:8muW07oD9ylashmYx245yQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:NoDRKMJ3zLS5TkGhVgWnoFweehS/nGmaHBHESCeu87ISsuNYcvVzzGBby1NzNlI90PnHxOdd0BpvPxAE34zTug==,iv:fi8CMAMMQY7ATXA2shWDZti4oeRrKoUTLLJwRuQ2F7w=,tag:AVtk7JfUriqoe8Khi/gOsQ==,type:str]
        password: ENC[AES256_GCM,data:YVnG3bC4AxF0MMrTIvtP6EToScHuyUFIuX5e6AODnoB9Wo+ORkeBBT5feQZd9c5dah6Sem5TuEIU8BmN7+PhOA==,iv:29VUUFYc9jWsai640NkAEV4AviUGfQ+lqww3U4jgJAU=,tag:hJQTmFWx9NNkb+E85KCt2g==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:pcQCbLExE/0YdC2AHG6BCD/Ihufeegdj3lidUcjtDDa09047skBqgQpamP0l2GamJhlwF7kz58Z9DEZ8,iv:Cyf6uWoxqGtMB9Pz9lbmST4S82dwrCVAOfxY3T3QO6Q=,tag:FMH94LKQOdG2u2r6SFgHeQ==,type:str]
prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:cGKPJzhDIxOwWXVVrecNSx1KJ+XnOHx6U8w1URYD789l8TCaA7F8w4iwgyqnCfYtCuLLRbyxECVtGTKLeydG2A==,iv:IkxGNrab/qsHUGapbLsqN3+M0LUBOZlG1d7PZvMcGs4=,tag:8p67bYR7w3BG4WFRCS6lNw==,type:str]
    password: ENC[AES256_GCM,data:jcXT00FChb/Yj5J8oZgs0NrYFA5MOI6lHM2ukhzGtmreJEKBOFYeo3DStWkXtOXjCOHQlJc4PcJPJNnQMey8CA==,iv:sTQB7vwOEyROnL821jEjKwBuQ4neRxgl4qlp7jEk6Pc=,tag:ouZzQZvTnwojRVZupS7FHg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:15Z'
    enc: CiUA4OM7eKNmo3Um3bLBklca/IZm56sG9KRwdjU/Bl3aa+PWIIyGEkkAZoeZpt22/M8rSH2VaI/eR/HX1LyZcr4hP2gD5zXz23l7VFGmdUw80jByH2iX9BIM3c8pvgkm+sCv0DCkmtuJfFYIJFmD7l16
  lastmodified: '2026-04-16T16:27:22Z'
  mac: ENC[AES256_GCM,data:YPw47DDFtvNeHwAA/F/sd9y2tj5Uy5lkGL2hzZO7PAerjXDd/PhOIjQhV1tLcT5YVF7kXJpoyTtmp3JU7KP0E1g7f16Gl8woEAuSRijjzrZ+J3OqGosYwaUNtaK8/8qGqfAqspWiP5RoFFp1rDxhigQ36KmeSxCepBqLm7TaM4M=,iv:bDmqFYU5tQ447S/OXfj/2WR21NOZ3euifO/F6/bv4cc=,tag:HsDB8Q97v4KZM7EWNNqw/A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
