prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:fIK49Fnc1OxTitkW6Q==,iv:hjGXZICZpB0NzdReDcXzLJgbsm/9OXwKKL//Dy00mAU=,tag:isuflELGRvR8oRhG2Qjt7Q==,type:str]
      value: ENC[AES256_GCM,data:q86xlbhaW66nhv4JdNN73P0JWIoBfgiiw946v02eWWcoXaNLr8vAWJRm9zJs/U8zYc7ehiroYP6OefXyDuIU3n8p8wfZNtARJeyQYqU0YGUh1CzA/hmB7cq8jHp1SB8gAiKOgOADCd4lll4MeyuOqziUxBQQOWloqeSgqskq6BeojKPoKKDrG1JT8Sh8CypF9Zs0+dKekw3URkL5pQ3fQVGKWQkh+9F+nVMUeaKqmL5nhQ==,iv:olBnkSqmboL/d/ly+Q4HV07eRzV5EdMAbbnBWpPMyOk=,tag:eDxGqjN1qprH0hamuWokDA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:eFNr9FGemQVj4goWoU/hEKrEt1rYjtnroSrwhpmQ25Q5R6nnl2eu0LG2PywkG6d1dhVuiKJfO5YsUWkjK3oENA==,iv:zIiRMdrVgmG9korQBte4Ble1oPHYI2PlPbJZFhGAWi8=,tag:cSA7Vb80wmGkUj0dyTh3rw==,type:str]
        password: ENC[AES256_GCM,data:uwYf7YoPaPzxORUbER+N7SdJiFDgdx8Z4VNFRvPN3EifrM1EbvbTWr0BiowzQHVl7Z9y6azglTXImG9U0ChbiQ==,iv:S3+/P7SiiKRj+/y51AZB4XTbu4icbu0BjhA4mT778l8=,tag:LRXwJRLPnBQFqq/TEspjgQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:DeEmXkcGndrmISul5VI3SJT2FwACXQmI9he+Gpf8gX4QhP4WsTMvEBUAyrcL94E3zs1CNXQg+AAj6HId,iv:/iLNtelcYSryVZ4iflj3NaZ0vNo/JkEJ2HazveZH+p4=,tag:DNlzaVhLIfgSohHOWnK0SA==,type:str]
prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:H9y5WDrdbYTw1LZxTbMiERLsgxtykv7oQ/1V+Yn7Szpk+swYmoDPFye9jsP272fxYFJASyItAsY+z9LZme/CYw==,iv:1RZqesfzjqC4XC9OIQ1SRpkIE3pKKxuy8Vs5GSlrOhg=,tag:R64Vc6AyBX60UOwgnyJS9A==,type:str]
    password: ENC[AES256_GCM,data:+j/1usRZbb4Oy1719ccom5aZNgmI81OylJvUFv+5dMl+NDpwnrCY2f/Ei+OAVUu39V+NcNdHv0Z2BRQUAt+BVg==,iv:2d26O5djAyrLziyR8zr2Qxin9Mu7zCcjbTB+plOM90k=,tag:ZtExe/SXn4Wdj3NrC1faiw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:39Z'
    enc: CiUA4OM7eISduCqa5zSn8+Py9qv9vJDrH1rbM5yl/Vnml7MKGZx2EkcAPHlbmWQfZuDpTLXL+81eC80o5RNzsABsKM1o0XzmOhYf30MPZPN4AUIw7tgNeBcow/ZuBUmFdpSAxC/FIm4uDyWGG+0ouA==
  lastmodified: '2026-04-16T19:33:39Z'
  mac: ENC[AES256_GCM,data:8RHAGJTJu+02cceBTpAsYjN+VQX6yqGF4IMBvTWgg2LUmaU1HAwapXNQiu9Tc3IYnWtA0b+eFQxd1wrARkQgPLXSD9ZUscbQ922zRNpS2CI74Bb9bKb44BJIW7m2D5QFRg672OEfIGjyMslTk4Iq7moKn/wCGKe1UEIej89znCY=,iv:7xZogcT8pNrH+TEV/DKRCb2F7ezVKMHTnKqvnSdsFsI=,tag:E7uuuoi4F8WTdiv7XzeMQw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
