prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:kSeuvmrENHIAm7pDXg==,iv:Vt1PZ001jvsDWnjMQCS5bR3xYO68DmJQ4QOyADqFRsw=,tag:gLKG5Fel6x8gX9uS+y/nxg==,type:str]
      value: ENC[AES256_GCM,data:pCWVIbHP9r0UBXivRg1Pie39mqFZ3gbwVXGPlhP6Rxmn14dh4TxKTqXuPoLq47JV1LVjThG0Ojg2hNql7ZmSmKPCdZ2AdXD9zmdUSjQyLaeSuWG5DKJCqpM1Mz0jr9ZFVYgStmpLRfOFropq97CVt0Wk65AYeU9hv64kQ33vp/RHg7GmBstPgoF9q0ZaP0V408Y/5x3PFv4RE0YqLjfgBK/OC3ZHRqTSKIDNI03er13Giw==,iv:I261Q3i65BGJqM5NGqnTVo3aOB9T8EISYtEpLYstv4c=,tag:fA1As5GIWF4p9WNzzVKJQQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:OfpVRvMpIDecoPSZ7ytBfN8zgWwtZcvKG8ZAG6heSMLIvetP0ZkbSRavqTDdZ9zKwBtVpm+CSeZu92fppTICJA==,iv:KnfdKpSeFpimzq9Aj66wW6hp0ATBFmo11eTiu3KwvmI=,tag:iisv3I0pTpdmbzpTMmC7gw==,type:str]
        password: ENC[AES256_GCM,data:pNxM2qREtXx1p1ZODepQ1A235FWI0hYsvlVrz2z4noIoqErKxOCDI3WQDiaNeJ7iDwYq/tGEbMKe7slVLysMvQ==,iv:pTRZy+TGWho8gEWv//i1DYtzuD5Tz6UHEamCGlLj9xs=,tag:U+3EOkSvobRYWY4srtp7HQ==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        HFSmHnxpjKCVdvLjqwD2EmZ4WZpKzb9lQ4bm1N6JArP9lx1zrLjeZx1EWl9QZM5S: ENC[AES256_GCM,data:DT+va8Gi4DEQM/711NpIR311Z9B61vYXQubZsp4tcjQ9H/05jhskxEDtDszf73sE47A1p6iCw5MM8xzl,iv:2nJbNFC2eFNftwIrwaoy0BoiePU37wekHEcP4UWa8C4=,tag:trH35SKKgfHDx8LwCAPH5g==,type:str]
prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:DJK6QWnqLXAKwujX14wXixibolH7wGU1wdjdwbegakrsKL2tJoonw21JQGPPjK4fWcBq+W2QwOPAMmcjTxHYkw==,iv:EQ3bsZH2U9X0qQPOww/rRMJYe/8VfufayPhBp0vDQ/Y=,tag:QxGtAN/68l87PZK+pSNYXg==,type:str]
    password: ENC[AES256_GCM,data:zry2QCXCinOTzkvEUKnBgx/JUTEZrRF2zp0hVJTnid+bsYhA4XMjwWoiR6XuVLvi7BlzeBEvbY4NQRD3cNNDmw==,iv:CyN3dDFK/Pt9ei9NzeX1jnF3td8AvBEMkmmy0KcsecE=,tag:14N7FcVJCNYrIR9kcSvPfg==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Mg==,iv:2ynHRGtzPEJxux5SqXD+tp39JI1HQUH1n3CdHetIR58=,tag:uLg4+V5V93MOgiX3vHSE1w==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:QafsBYgJS9KwSg==,iv:RHntdaeYUQhO60sgKybamQTZwPYv/G2OlcF6RD6p9kI=,tag:8HLLYvOXyIta5kjQo3/Zvg==,type:str]
        orgId: ENC[AES256_GCM,data:ug==,iv:+zKjKcwlziVCrqAhxrYWKGCJ+vxLEHKlwbpvMHYRY00=,tag:NnLhyfYFLPKk69p1dyPO6Q==,type:int]
        type: ENC[AES256_GCM,data:BfDZYhjypMwAbA==,iv:wfdv5xo75TjMnumq+UnZITK8MnKwLtr4fqFpK5rWcOs=,tag:yL8Cidktn3/1sxGjkaGeRg==,type:str]
        url: ENC[AES256_GCM,data:mSCbkNsWAi8Hizg2Ay4FPemP7CYMODa+D+6z83cjjBg=,iv:ndXYnQJ9qVpmF0ICpsttYWCDzO6Rz38tf1PEoYJA8aQ=,tag:zbxXdfvuRSQX+JMRQ/9skA==,type:str]
        access: ENC[AES256_GCM,data:BAGWYyc=,iv:3vA5AN04CB5P1LgFvsYLwN/g0HbvRFBgi3JTXGPx86I=,tag:2v2U1gJfm+QHO+EuIm7V6A==,type:str]
        isDefault: ENC[AES256_GCM,data:eUeDris=,iv:Wx0yoKcJTJdMnqQBzxnZmg6WoXJtpSm2cwWjK2V4FTQ=,tag:lc0T0Ki7U2AyLDAPjdPNyQ==,type:bool]
        editable: ENC[AES256_GCM,data:KPS57Ho=,iv:F3hLSsQzAvCjuOiEMI54Xpl4mq0aQE1Za8FqH8QCx1U=,tag:WgZ39X1/iNsHpQsmFjHutg==,type:bool]
        basicAuth: ENC[AES256_GCM,data:2SkJmQ==,iv:PV1aDWw675wiSpl/etKJSlyuigUAPO5AVJ7dn5EBDc4=,tag:xJyAK50L27f/updjcMUBig==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:NU9hV2tGPBGH/ET8ILcAGmDHypuLKScoHwK0iHY8QTRNJ3yQkAhYtPxxekUMiEmgw3nBK719mmDEmHZ3bVA7Jw==,iv:W/8Kk2gSbso9fnIeU72VtPzAFbZRzLtkPZqLZNV9FaM=,tag:JnCfnJanpKfmirMOy1bnLA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:tqtAKbf3vPYiYULSZNNcwAtL9XcTIVo3gAMcDxcYoFXtBe9rTAZCOkc0QCf3Ivs5L7f5TNoQi/lC2Csu0OKW8g==,iv:y7mmYSJSigxaP+g0Ly+wPzqtG6eW+fjAu1z5ubmzcBE=,tag:9Cln3fzoKBwlQxeeZZEp2Q==,type:str]
      - name: ENC[AES256_GCM,data:qqESsgA39pYoOW8kzlN5wrcgVcQ7fWxUHtB3E5G4mQ==,iv:ymxLPgrTVZ8XP4kcr6CszMTnLkkUUtpXDEyIyBFblIo=,tag:XACqhL4T6TIS8dXgZNYKpQ==,type:str]
        type: ENC[AES256_GCM,data:tqIbCuR/SuIRbeS1tgHD52ig4CnizccFSfYOzouIDg==,iv:gYoq9WRNBSJ/sXBfoba+ryqcxT0hJMne/docNRRi2Wg=,tag:QvKnC3sm/9MMyXwMU5NYyw==,type:str]
        isDefault: ENC[AES256_GCM,data:fe3wsTQ=,iv:S99himFOybvYQeQmw7rMqFmjydzHK+KeWSg99kwqCEc=,tag:zAZOYDBDY6mVy7lSZzJWHg==,type:bool]
        editable: ENC[AES256_GCM,data:WctYTg==,iv:lDTNgjPbJ9DGxAd02QJsf0M2B+lYcQeFXWq848MsuRo=,tag:5C0nm8Vj68CvB3D3LMw1NQ==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:02Z'
    enc: CiUA4OM7eOiA4WkYVCE6TCz9mMPBTwXfT6WCM1M1qRZI+obxPma6EkkAPHlbmUjkesN9cShDtkugHUrnpXv1N85b4tCc464WgoONgq3iyqjvJYIY/zR/hrqqLNmEJHzxolrwuBfHTDi/xhn0DcUh8diG
  lastmodified: '2026-04-17T08:25:03Z'
  mac: ENC[AES256_GCM,data:Eh20qOENcAgH5dzNjBcXLIQ1aQNwno0XYQdZpr0rSPu9zub+enNlE65hTVgjST3RXszEaSPAn901lpm/xuzJ5HbKgVz8Iy3EqHqHZhJXE3IujhjUSvhWj9eNbI6fy3L/I4dtZdZKx6vwpyPAMyWKckiv90YLg8tkLW1TTOGjwXc=,iv:SELvvFzixHgi57+XhX2MIEX+OHcYUePWQziYp03OYCY=,tag:eR7Rfi8mcWcUBPXvlCVrpQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
