prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:k6jONDp3nFRi4GgqZZKbnzRCmZBmtadngYKVymEAhT19rQSbZOi+Iy7YhdeGcLicNGcioUvbCqoy2DV/SGG3e/sO5oUIg8Bdi5KRK4PG1gM+PVkJ3ES8/kArAOKtXUZPnvNU7h7tEwuTrVQu7Sshlyki4ZN+ayg3/1fKVItOKYPbIHXrwvggs3x8n60jJ1UZ9xD6k1ZrqoP7+qju,iv:LLmRHyHLVjJWrdyDEJOM0PaohgHjeSmo/xtks+eH1ac=,tag:qGKMgHzeSuKkCEXc2BfwFw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:EjM/K1DMHUp8FeH3eS1d1RO/unpeBxIp6XHo2ufrWduKf7xT0YERXmYzzp7mh8RZ71+7eyfOOMVcDtjje5wpnQ==,iv:HQHwbs9a+akaN1bAnCPaM1oQAGlUC8fgnwJlhnVRYO4=,tag:QyYyitFChqZNjenNBm5cSQ==,type:str]
    password: ENC[AES256_GCM,data:TXw1eqQZVA7+V1+0X9O7b1J797XsJtCgPAbVdZeDGLI5T2sTqr9w7ENVZeQ8pH4O1i2bAQtaaVCZn7qDLIbrLw==,iv:iQWamw3NvO0aPG/qrg7x/C+ocVAb0N08imKAd0H/ftA=,tag:a4Sw3CrbN84jdIehSDqqPg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:3G7hQ5AAmQZ1UDjFdnKGJPZw3lw=,iv:JYCtSprDdRP2mBfogpHj2wsQqZs6wg+SsxB95e7HUo4=,tag:8CMrpHEbtoBdnlhukamxVA==,type:str]
      client_secret: ENC[AES256_GCM,data:gC+naPRDnW4Hn5eTU0kbBO5dXvxmZUaWNzggO96BfbWnKul3afBXQg==,iv:UOKLR/sifsuVMUFzah6OqtNfaDFgwOWPzOsBemhPTLk=,tag:8f6v5qcUwgQrJRTpcjRz+A==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:mteydPw7kBoSYVg1MA==,iv:PMzOJe2tM8VAyMNVfka8PupvYG6BcBKlin7kyD86PQw=,tag:W6qYM2dOyF4PH1mCdCjEnA==,type:str]
      value: ENC[AES256_GCM,data:kgTuDzQNX8jLuij8T5VOOZwsQ9XZEIoPi0hut6GGNelePPelzcd5rRExY1SG2VQqO+DHG/aRTBB5MdrYMXgGiFCKJfv+/WTnxucgfxHzJOr/g+ut108wKPA4nymQ77JYbmvX3LiwIgpyPdw3MxcoNycGErEJsil0AQpxQXB55N9ngz9zp00hdSU8quRlGQOht7X4N1lbB7SqBpLrGtRe6LiQMUOwJ2B2pywkNyLr8tZ8lQ==,iv:HK2vgl8ujP3ufiYbC60BXOmQAb9pVzcropDwVlh4V9g=,tag:HYTQeBudK5EKbLDspBT0dQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:pNCkX8g6hbSbJYHgTSBysSg9yZ8FC12XYAVBcwBc2CqxNGga93Agsmn9Feps1JTHEjquRvhsOxpeuGtT4PpQFw==,iv:tu4joehqjFcDsSaHjneb65MpeaY0Ueu939N9zH5qU84=,tag:eNs31B4Effo3QdkBtWlhUA==,type:str]
        password: ENC[AES256_GCM,data:gm+C3BFAmCY0b3hixKpviAhxsezilrpRglHycEzR8GH7wO4iu7+3u8IW2HqZAtFLjXScZRIvy2mx7mtFDTo+Dg==,iv:JlFNeZT+iDL9HhY5l8vnlgkFuGRdmuKDKL4EO5CgEFo=,tag:6IjJHapWOPddmmTSzMCLHg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        f1ODYMS2Ep9Jt9vlJjao5BnkX02rlTsW4JfQ1h14gFTLZbuESOuPOW5Qbo0N0KyU: ENC[AES256_GCM,data:KsG+++sLRvV09krLyuSRJYptdnc3DU7mMSMR/TdROCIAIu1exJLIX1fx1bit/1wqM8lyb9rL5lm9Pc9t,iv:awJhS/UiwHpO3agRdMVTSXRRYtBji4j4xvOVlBOp2n4=,tag:2YG7TdT5/4B9yJVAI3wqSg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:45Z'
    enc: CiUA4OM7eLE9MEV6zdFHTzLfVKb6FZVh5A61k4TrUD1W/OzdUj1WEkkAPHlbma2HIk3EPtPEViDCVlB5AY3T4Jm+/WhJ0f4/YeKFPaml+YouHB4whm7oh7goGtWxItqP7qnXuEFGhvLS7PSVN/dI0dJE
  lastmodified: '2026-04-16T19:33:45Z'
  mac: ENC[AES256_GCM,data:Hdp3mAtCmjsVx1DmApPIRGk8niN9VNdJSGuuXMs0J9no4HbapRDxt0VcjPFu6eQa3w41oOD2gj5pMqD1uYLBQux2AJjEr2OGsPJRhKPyWaFRkSVrycue/15F1+f1BwBUWROv7c3EwwAQkvWvBbuM6v+9mFxC7sMx0Oj9tbrDn7s=,iv:VfBJN7tu18aTPXMS/T4dpt6wmfb6p3oBp789wgxZ35c=,tag:9pALCfS/wcjTFwzIY7vpdw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
