prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:AjldhGBB1y8L2neUFp6SM8KsXt8BwHr14Jw60QB2L9bRuGkjZAKZ1Wrn+P+2VQzRupVr51JijQJGpI2w+6WyHnIAfsHmfDLS8XXoww72XiQAlANCKtbEGoByViPX62Xl/8hRm67cgZ/rUXq34nj2YjFsNPV5jVk/mIKJmczIvz6S6HjbPlW0HkFeHdyffUUuwdzW6sPIH3FIroEs,iv:Y1mgshztM9jbLUUrDgzOvoDZbHluXStRVVYJ6mOT18A=,tag:ewNDiFYRP7WUv3JA/w5TZA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:4Bwpvic/uCRYKogaP1M0DA6cmu9zjBSbsuDE9eGRzD8MjexEGwnIsfcVNmayEhlO9a3gSFFjbe0WXQ7BBq4CEg==,iv:MbTdkOFB75wubE+kGHGI5aBRUa2+FbDna2ldXgZJWpw=,tag:fArCUzW5JkXr8+o/n8IVIw==,type:str]
    password: ENC[AES256_GCM,data:Uvkes9xE76qO3RxK9fZJLjlQLJf1BMaEDViOyp83BtP4tpASQwa9hNmKvV+cYXts7XVkcwx5IpT0ioAeIFmz3Q==,iv:8u8/T5Zl4thlxc3u1AHiVQMJUwn7UhvYlpJcMTHQJN4=,tag:mlHmMpt3tWkv+I/f1NLYUA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:XA==,iv:IyCVtifr6AHrt8YJLz6Vq3DdGVSB45SsItNjtobUoxU=,tag:v9rWO9jbAUz2VYR/R2U+Pg==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:HxJy3PFWUbhfeg==,iv:2HjzF2tbQHJYyY05DfYY+oxzF5Cgds+nYjMOl8nXbWg=,tag:t9gNwlqfcJvF/0VsOyV1EA==,type:str]
        orgId: ENC[AES256_GCM,data:hQ==,iv:wDypFYGfBRdI7x9+5DPe0+xIV0/0gthJVCXLBbzRF5Y=,tag:0CGj0FdbFIjNquEC7eZPvQ==,type:int]
        type: ENC[AES256_GCM,data:QcmFh1e1OTG2XQ==,iv:0lnbcC4658tQd2EDJxOD1R/QGYcrteg9RD03OkQcL48=,tag:8FKCAjW6OvrDUV8+5E+sQA==,type:str]
        url: ENC[AES256_GCM,data:1TkYZa2evn+B4/INNiR3RMRVNAMGhC4Ybaj0g/IMYDA=,iv:2RFx0XwM/nlc77QIK6b4Tiv4qMCpKnSNCLM9Cr7xAMg=,tag:V517OiswgKF/hzBHutbYvg==,type:str]
        access: ENC[AES256_GCM,data:fLWwmWY=,iv:gl7p7HfDZV5uJ3V3eH0iGL8uZjKKQKVR0i4FrQ0ezy4=,tag:DdhI7nxzrp9R+5xeR9lyaQ==,type:str]
        isDefault: ENC[AES256_GCM,data:G7GvAbM=,iv:H4ANVRhL0+YDAbeI+WahOWf523T81Dazx0AlCQeCyf4=,tag:2X12IjA3/wFn1J9t3oLm8A==,type:bool]
        editable: ENC[AES256_GCM,data:YsbOQ1Y=,iv:L+PG2nvYuCPX9NPd4eCyJlZAxfVP+igryIwn2aAV80I=,tag:QXlinufGdQaNChD8dnP1Yw==,type:bool]
        basicAuth: ENC[AES256_GCM,data:WaORgA==,iv:6SrW3YO75poYKjC8TLyUHus5ff4ThlzUa97CFEXGCKc=,tag:7guyuy4evoOgelh+ribNbA==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:3+HlnMDeo9LiUrzpeFuZK+Qqsqs7QFrfvnqMmu6MDD7Y+5UeaSMvuVJ2greWZ6srsi2FwIr+DnKOfFhJL1/IdA==,iv:Qji5fYosVlHJnJ1FNImg09foQfAmGy+V6LP/cVjbg9g=,tag:2NqJ+iflOjEU48MYRyGdbQ==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:y8EjntLUuiHjHloD1YxaeexVIMlvUnYcF6ce1zXLfNQfUzsIv8keIKuYkPxNHKOBR36SINc7/pnvjirH7uky4g==,iv:K+l3fv4wRavSKII7oMwmQz4TzUKzlzoUgwWtS/IvXsM=,tag:FZN/fTaVdONzRCleuGJQ3A==,type:str]
      - name: ENC[AES256_GCM,data:4/5BJnWsnH9/L4p3ALQNxy1khJYr2/xoaFqWJIPnww==,iv:oA0XEFc2WFAwGzG+pfoCPsdpQzKWO577X+9bxO/N2bQ=,tag:SElpkQHbkYToCd4lxJoSLw==,type:str]
        type: ENC[AES256_GCM,data:iJArl+BXjpIJDdhTJ5DDAjv/nTP5xbGJ9UYPywhuVA==,iv:0R/kBm7FMJrQTseYztZ5UE0ygJFo3VjhikxqS+IVU3Y=,tag:dpY4ffYLOfCnmfl86E27pg==,type:str]
        isDefault: ENC[AES256_GCM,data:wx1nnTo=,iv:IaILwtvmVmeMSRoXy0ERnqYpYqzYGaGczuV1Ins19cw=,tag:wDPVUgdLkxuH5zp0JoewTA==,type:bool]
        editable: ENC[AES256_GCM,data:oku/hA==,iv:bdDYJFc9EFKE9MLDF+XTowOMxjlQZM1BimXWd0HL0Nk=,tag:JIHsMnQm4eGpT9EbFbZNpA==,type:bool]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:orJMDFqJgqikk4cC+A==,iv:hQ4iZyJQ7ADFKbshYNh+bo32QUCdW1HRNEanQ9Jxmwk=,tag:ytniedcKv8FOy+7ctd+P4g==,type:str]
      value: ENC[AES256_GCM,data:dkk6Dk4pIrLZAWhF7UVCj4XuyqoK4Ka54z+MnyGAEyEk5hK28xflYjYdUvVh5t6wFRcbzv37jY6xZvqtm438b4AUMkS91bO6N3bSsjen1c/juKlstGgHp2+gukXoAyGgz5wdVOfMa5JWZYnMLQu+4je7bJO9Btgq34CP3ZiBgtbNhC+y9fxEPUYDO9lMZSTec4yl3BxBMAF584UQN6Mg5f2V+hsEcKz8SNtc21yZITxhVg==,iv:KZjsdjs1xt18F1mURAX5/YBeujq9Ofu8OxDTk8jeuYU=,tag:0G+ELSZZU0iDSBJs7z8oYg==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:K5c9Plz435ePW9gfaelQfJxKwxS5JSuHszF6t+XWSxww6SaY8Jn3ASqCaeA9SYihZWBYITdYDreaAbDVW4mddw==,iv:JcwE98CPiKyWgrz8P8syiWji8oqR2JJBqejZXErY5Ts=,tag:FHfkeGJusFLaGlJGqLU3ww==,type:str]
        password: ENC[AES256_GCM,data:kbX7bZpc5OugYv65gwaG9Mm87XIMWXEtPuoX6LKceAKonIYmIwAFGcWVTNHqff/cm6xiEQ85iVrhbP2sI+wbMQ==,iv:NLt9wMGWWgxmWSN9jl+DgY4Dc/sCrevcG6t+/aIqCy8=,tag:/SgPfjNz2GXzbt7xc6Rbsg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        f1ODYMS2Ep9Jt9vlJjao5BnkX02rlTsW4JfQ1h14gFTLZbuESOuPOW5Qbo0N0KyU: ENC[AES256_GCM,data:dV/9TufTgC9NISD32yACIOJzqmDny8ONW+VWb0cIK2kTQ+XEQPnEcbhhJSBocXC4+C0AuEF+tkvPG1XJ,iv:Vr5OY5YqnrGuXjR7Z5NjyvnK4L99d34fVpp0M2aUQlc=,tag:2NLJulJ3JJ8wUwzAiiSWnA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:25:08Z'
    enc: CiUA4OM7eOw3b/0TkyNa1jIULahlcHbGqXjGT1HvCwZk7/pPq2jpEkkAPHlbmZ/jXFRAj/gKJhbzLDW4BzkaCNq78B3x2HOmZvLWREnBkz+/paOkK6w+XQSCJnLDucCxca7XiN26uyoVu6biSjUAIovr
  lastmodified: '2026-04-17T08:25:08Z'
  mac: ENC[AES256_GCM,data:umPJNOD2LPW8hmSkys6ZomBKhFT63mdsrr5r3nhhv+F3tL56sypLGZ/7ccrQ/H/NsfExBxZRBPA6nlpW61cas0G+o446nWs3Ix/2RH+v75ytuc0pv4cVkWF0LQqvk50pdZIsM2rpgRT2UCTF+n7glEP+KIgkSW/55YTWisrCY+k=,iv:pDZXZbHClCUi1akVbRE30kmSNHcINgwJAj7Mu9Jkqls=,tag:KSqg/He1Zt5lhY0n4vi4MQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
