prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:cwEYEDwaARA6q83jRpQwn658dtDx9WKchEpP5zzExVxuu+Q+YoP3Uh/W5JThKfmS1Yk7+ZnEYY93AgfKZ4Lnm4DZa7nHjA6OJUMbSlGUG71/NjydyniiFop3B7dAgOpjuOSHfBPevxswpE8bNp1NUHcmyDvXtqeKv1I2qMayxPd/JTiwJVTD+EszZl6Fd90SfB19fKAyECTbDgdB,iv:BekNjN6I/d+BNPHvN7apCJ0BXdMRLFusPhWi5oPDw14=,tag:uaqtQzUZIuYp/EC5pwZzhQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:BmMtJ0IKmTyRqo88RgR74rRrx3kKvdbbjQhn6kF9jQe5+Q7IdzM/KuB6zAMkUVbdbI79pgz+7nHS2uHA2qyJCQ==,iv:2oRmP3CqL1eiboAft8YV/RD4zlJsKO+6F7PH+7h5ygM=,tag:M+IfLagqxexqgU/J3fy9Pg==,type:str]
    password: ENC[AES256_GCM,data:Ii44aEFaRRlSdXVrS3QcEjpfRDLMirozCaG8dzHb6j4tOh/Gdzh7aYRYVv2+db679Zb2bKAfIsxmrWcMBc4yNw==,iv:AmFjQGGtdPE8EC0wSKXdakdSStablVvgpZi0fr8ns+s=,tag:0OYkqFomUjhkVYAVVEbm2Q==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:dJkybT1J6Eno98QsWg==,iv:CIr111BUFjg9SILclK8NuCiL1qO5YYTCPv6rjOorZW8=,tag:gzTmnfsv0G9g2INlNzwzTg==,type:str]
      value: ENC[AES256_GCM,data:C1EqijcBY3gy4Eto2vmLdyKCJPbyNZqyolGkE9YgWaUEDHskkvD/W38F+ZLnqdU02YKPqXf98gnCM+D8KfNzVXFUhao1EOgkJTDvNiUwMs6PzmtctF3pY7uGxRB1fRx2umpuj2XsXVfpBc5m44aHf/c7B/mz8zWVyfHSD8QBCXlRfAetJyZKGdAtu2GXZ3WI6IMd4sh9sGVlAdw5cyhGdjQqbt8v0o6p6abV+RfGZs3gMg==,iv:LOA/LYnsVQ4AJIFru5usWW4BiKNztaTIp+Ygc5Mxyf8=,tag:aPnZ5l3x8zW/LUalP8KTVQ==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:BfZDcMWktp1iwKSt3W7FhCJ9J76EVahs052eXm2Tw7ye2TyGt18T+HmrnS29swfFn8EwiNXhKXpQgSFQw5V93A==,iv:muhCanPiTdW2KESXUCLoUvJ411p4xne1ZdPSKxN4yJk=,tag:wnaVBMsC1E4Dx54lVJbWxQ==,type:str]
        password: ENC[AES256_GCM,data:5M6zRPV/FVyOXiN2z5L9LoRWTwrpk4fr54lM9q6glrflRAtM3l6eepQ+4ZYjTAhKvpIyAdmMPN7tarqirU85Wg==,iv:hz2QljMJmRMmzbYLwFwn3gTxNmZxYfT/Z7j+UufzZZg=,tag:/dvoovOiMqemwU4mj0r0Lg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        nujsn2Khn099xNWfnILHcIKwR53lYDtMiojwCbKR54t91KqNmJQoi5YQW56sKHf1: ENC[AES256_GCM,data:EVhEWhvJXachU8/sEQJWFvj5FxudZRWSC+SLUCC8Il/obm3zzgQ0L65xTdvgFZjsElo3cCYTZ7GZrhhv,iv:Ot7tirZW26kAdXv7WEFIyaOV+xOAgGhFxezsKZr+eNs=,tag:NFY4ZAZYxy2eLLEE0F0maA==,type:str]
grafana:
  datasources:
    datasources.yaml:
      apiVersion: ENC[AES256_GCM,data:Dw==,iv:m69Do7ycogUHF/aRvc5v7gI62graUqR3OattUyoL0aU=,tag:jIvG2KNwyn7FkM+iD2Ja7w==,type:int]
      datasources:
      - name: ENC[AES256_GCM,data:caZr7eUFXG7hwg==,iv:aF66EUxAnVQB5uXeUI4pJaoGfKnRv6WkwVcJBe0sTG4=,tag:4H61nk8xpDX8X2ReJUl/bw==,type:str]
        orgId: ENC[AES256_GCM,data:ag==,iv:OoFTIvJQf1sDIGgvvoqWQKw49aEUgqQaBBmdDV4BzUY=,tag:WIfe+9iu6I3VWTqTXfGY6w==,type:int]
        type: ENC[AES256_GCM,data:gf8Hmfwkb6bnhQ==,iv:ptU9JOKGKT9NTUqpbV/DCr60BUsrSK8gVngiWjLbyFU=,tag:QToBuFkHol+tp+A4c+iJng==,type:str]
        url: ENC[AES256_GCM,data:I1LHeAe7avyZIOAIjNb+QYz+CSXaFXiKbYgQhp6JZK0=,iv:y+BgEiOre4CHPg5qADcqXgGsI9Aj8q16L5eazX1++sI=,tag:cIOATOG3qqzDeKVOqaQewQ==,type:str]
        access: ENC[AES256_GCM,data:4Fy11JE=,iv:o4u1h8dDg1qEwge7djqjaqny46Qx0Sob7GRH2bJ5X5E=,tag:dEjSkSjGyFcKGGmYlOt+IQ==,type:str]
        isDefault: ENC[AES256_GCM,data:eQDv2G0=,iv:N2hgnzlb+/hx9AkcslehHR51SSm1y9HZAQs3wFZw3Kc=,tag:f8w8zbSPATU0eR6XBQELJg==,type:bool]
        editable: ENC[AES256_GCM,data:bFVFJb4=,iv:b/2C3bl7LlywmLBvzzLoWj+ch7epJS/KvgIZEDtJBp4=,tag:LBjF4rWhk3xItRHGbwJ2PQ==,type:bool]
        basicAuth: ENC[AES256_GCM,data:FnlvyA==,iv:VnipEacZki+GAk30jMLa+89z3fHqQKy2jk8rgGd+O/0=,tag:S9TbOi/wgKK8UkINByD6Ig==,type:bool]
        basicAuthUser: ENC[AES256_GCM,data:C0jXD/ymlJnM7ioPb+XOTCNDOWCuYQfiTmzjBwV72tWg85xe0CARQIhRQMaX+CIaxVtDXUpe2dGIBGoVVsfa5g==,iv:cyNDxttEQSEOJDGWJYY0xoySiOrf8oK724G/4bPnJgs=,tag:jXASXOZZ2K9vbSqx8JrPFA==,type:str]
        secureJsonData:
          basicAuthPassword: ENC[AES256_GCM,data:sbkCCy3I7S3pk5YWOjTJREMCFyesbKFK3f/Dzt+v+7I12WMACj2ifdEtCy5ydJqAAnxYPB87cmglzqpRa137yg==,iv:lzok6PUpIshgI+ExGOqzNU0eGedG0ZVsRNJEw6SePRM=,tag:Jd52TSDo5QKqyD0+esMxzQ==,type:str]
      - name: ENC[AES256_GCM,data:+ARDgJscpqQkGjKeWO4OK6ZLAsRO4U3mjawG/MpiMg==,iv:sqsQDXp6PBxal2fFDJB1YAI03m2SZDbvYASxYg80VY8=,tag:7FfUufYNul3TbnKNrzNd+w==,type:str]
        type: ENC[AES256_GCM,data:2yVsl8UA1mB3+/uXlsHRBLLWFdBDSvOMQGFgTRJ7nw==,iv:X5+l2QrLfwV/sHOiAexJmqSMwOTcfZzS4NTCZGTdsVs=,tag:vNcLqSSpcGexTetiR/Zrfg==,type:str]
        isDefault: ENC[AES256_GCM,data:oUUPigI=,iv:9Gk6lZqYqzEJCLwKdFDNFaF8xxUWwtUMlEUT4PnClvE=,tag:TDpcri8N3WXDYJMXgnZl2w==,type:bool]
        editable: ENC[AES256_GCM,data:ym8Lwg==,iv:hca0nWeHjq3iMu/oLRq3Rf+7WPP9zRXI0R4/MR0gedU=,tag:irSI+kGvZmTYJ8cKezymYQ==,type:bool]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-17T08:24:53Z'
    enc: CiUA4OM7eJlq9kj0AwnVMKD6zJyg8YWKi3TFFeIm+/BZdj3UYXJdEkkAPHlbmUm0a8yvQ9sGTFVKqCsHopq41LLid3zp4kVRBzmJ8s28qRIoB1sn8WTYa/DwlhKvxR5uVi9xSS0bij7xI9dzZ+LdpCLz
  lastmodified: '2026-04-17T08:24:53Z'
  mac: ENC[AES256_GCM,data:/Moekt03cp2FKIR3GdaVovJ/DJ6re5cLnFYUxeiqy03BLoiQzA+IntZZPp+I2wY0DSm4omxXspqhcIZiXkvdzQZjxqgrFbW5J09wr151O+BJsUCi1my/D+T7ze9G4Y4bHZp69Y3Jwv1fmND8drAp7MN0EChoY1ilmYgE38Gzakg=,iv:VZA9rxpA4fphiIxDER/sZMU0+kICrdG0nJiUW6iMrXU=,tag:BscdvUNqI3Gy9Xt/69XQBA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
