prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:5BWXDn3S+qQpeh4TKntxS/kgpCygUBbmblmz5QmrYKRSEG0PjrsiNo2Iy86Ut8nndA6T48qeNukxaodf2uQUJMqtCpBdq0B6xTCYrm1qYpwGLCO/jZ0HWldpqM1kDYeCZWiAu6R0VCRI8LRw0PVfjcvV9tgsWjwnth+42SFjDKi2d3gXQlsRDL156DtxB0cH8owguDav6IEQo3rT,iv:gPflIz115i5QNJidOraT0TacrZPSXv4OjJYcpLbt7Es=,tag:pvwbSDkOlouH4ek+Cp++bw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:OvuqL4Zd83z9UNMUK5Gon/BMT9xa/pgpNy3uXAcRlMLgjCRa8UEVBp0WCv8NjsgQPwCwf5q5CWbLlR98Nxznrw==,iv:jpHk+hPmxArXhpaU6Phz0eGwwjWMdXXR7Rf9qDb5TDM=,tag:1x6fhOPpZiIx1t4CD0ePVg==,type:str]
    password: ENC[AES256_GCM,data:6ev28XostCHVufGyz1wFp3lY8Bj7HQhL6bjFtJUWjWe5zucQJATJBd6vD9mRwPs+8YntT6CYe3cgGAYV9UTwQw==,iv:/DLly40nRlXJmJVDPCCfjDAcw/o8thM8+a65GWqzZDE=,tag:zdq7CyEAWCqMLRVFU4ADHw==,type:str]
prometheus:
  server:
    probeHeaders:
    - name: ENC[AES256_GCM,data:jm3HxC/GGx0IhxSrvA==,iv:FUswduIG4NcEL7L9DlFPnHPofgcf5XHBHT+4FS/j7Vw=,tag:NXAMsyWDiHHRnuKzb10isw==,type:str]
      value: ENC[AES256_GCM,data:vAmXQjuFa7WMIFDPwo5KxhJUX8WbPdQejY8fLd5gOw/5GfGhwMISVgdx3bv07/lciozpcWF4Ay0iSYeYUqwpYvByzCDP8t6ZP6wA+nqGZW4/vDxV096aFw2njnavG+EJUvuqEzgUhSolbULEZPwt7famJqHi1X6hNLTeeLZ5jEXajf6zqwbmmCQ1Ql1Xm3JzXIkqx6Bby61blKshapGj0Cyss6uPG7BiAJ2eBo7F1MeHPQ==,iv:gsQxppuKZ+gCEV0cq3vduHhsDXAkkk13suSaDfLNImk=,tag:pUAIjmDZyu0TeppWhq9FwA==,type:str]
    configmapReload:
      prometheus:
        username: ENC[AES256_GCM,data:rs2esZN1mdjwdFOzvwaq7LrztFSqTKk/Vnpv3RhDBVQn/tV4zT28G2s78etrOT3QraRJKFyBQ3X46jE6G/LXtQ==,iv:UQq5+v/EwrFwlb1OSdv4QpgFK3RC170YXtuLnSi8BRM=,tag:0npvyG1CCU9ggwVQ5Aj0WQ==,type:str]
        password: ENC[AES256_GCM,data:Oa0EuWOMgAs4dpY920Uf2rZddea3s/NB878F5551+wJn/9u+VJHNIuGxdjnKoYJiebg+PFN++9guXxZ8Fpbx9Q==,iv:10XpoN1CFoPffz7wkbezp1Tf8SpJG3gatJkUVALCAOI=,tag:W365pkVavy3odvvQ++xEOg==,type:str]
  serverFiles:
    web.yml:
      basic_auth_users:
        nujsn2Khn099xNWfnILHcIKwR53lYDtMiojwCbKR54t91KqNmJQoi5YQW56sKHf1: ENC[AES256_GCM,data:Mnfos3TGdG7xkRx62bHV9DHB+Ll0uL8EUPkBaQmi97L+Jo7QCTBfSdSzOdbCf/ZrE+o+s/o8R3ixY/w+,iv:ValjCurR+MVeLsHJHDzB5YBTPceOnH+Ir2AHtAgFz9g=,tag:vcDlUxSYlO9ZCVXbKQ+QKw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-04-16T19:33:29Z'
    enc: CiUA4OM7eONpXqqIQa+KZMVtSiq7zjdVvCbh2Ckxx7mnxzX/E7lbEkkAPHlbmTVr/TwmTYA/nHRRYgWk6PbZtY8pGJb6XKC6FkUQowX7AfBkLNvQBQITMwtulAAnfmddweJ5IHb7Bi6N3W6xrpHbvGB1
  lastmodified: '2026-04-16T19:33:29Z'
  mac: ENC[AES256_GCM,data:EhlczMoGWwBV4xs3zNb9pde9j+VcDhxDrmv5OcSBqM9J/hsDjc9bFN/S7XuKbhzPgoCy4xnIqW09JUrYFW/NUymsgbW44H+dL4a2NpowIJT2PI9sYik0gRWQnOfyUuG63BEEsovcRPiUd8nfPhQogQ8slVErtspoaqaktBmDgQY=,iv:Q2NMOOXLIqN+rVEzfJqzgYO1hxluCTZOV557tikdQWY=,tag:xrgm0C5SJLJM5EaeAIhA9w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
